import type { ModuleContent } from '../../types/content';

export const module9: ModuleContent = {
  id: 'cqa-m9',
  sectionId: 'cqa',
  moduleNumber: 9,
  eyebrow: 'CQA 10',
  title: 'Worked Example — Afucosylated Anti-CD20 IgG1',
  lead: 'A comprehensive end-to-end CQA assessment for a hypothetical ADCC-dependent anti-CD20 IgG1 monoclonal antibody — from QTPP through pCQA identification, risk scoring, specification setting, to the complete control strategy and analytical panel.',
  tags: [
    { label: 'Anti-CD20', color: 'red' },
    { label: 'ADCC-Dependent', color: 'amber' },
    { label: 'IgG1', color: 'blue' },
    { label: 'End-to-End', color: 'green' },
  ],
  stats: [
    { label: 'Molecule', value: 'Anti-CD20 IgG1' },
    { label: 'Primary MoA', value: 'ADCC' },
    { label: 'pCQAs Assessed', value: '18' },
    { label: 'CQAs Designated', value: '12' },
  ],
  sections: [
    {
      type: 'card',
      title: 'Case Overview — The Molecule',
      color: 'blue',
      content:
        'This worked example follows the CQA assessment for "mAb-X," a hypothetical afucosylated anti-CD20 IgG1 monoclonal antibody developed for the treatment of B-cell non-Hodgkin lymphoma (NHL). The molecule targets CD20 on B-cell surfaces and its primary mechanism of action is antibody-dependent cellular cytotoxicity (ADCC), mediated through binding of the afucosylated Fc to FcgammaRIIIa (CD16a) on NK cells. Secondary mechanisms include complement-dependent cytotoxicity (CDC) via C1q binding, antibody-dependent cellular phagocytosis (ADCP) via FcgammaRIIa/FcgammaRI, and direct apoptosis signalling through CD20 cross-linking. The molecule is produced in a FUT8-knockout CHO-K1 cell line, yielding >90% afucosylated glycans at Asn297. Drug substance is formulated at 30 mg/mL in 20 mM histidine-HCl, 240 mM trehalose, 0.02% PS80, pH 6.0, and filled into 20 mL Type I glass vials (400 mg/vial) for IV administration at 375 mg/m2 (typical dose ~700 mg). The target shelf life is 24 months at 2-8C. This example demonstrates how the mechanism of action, molecular format, and formulation drive every CQA classification decision.',
    },
    {
      type: 'card',
      title: 'QTPP — Quality Target Product Profile',
      color: 'teal',
      content:
        'The QTPP for mAb-X was defined during the target product profile (TPP) stage, before cell line development: Dosage Form: sterile, preservative-free solution for IV infusion. Route of Administration: intravenous, diluted in 250 mL 0.9% NaCl. Strength: 30 mg/mL, 400 mg per 20 mL vial. Purity: >=95% monomer by SEC; <=2% HMW aggregate. Potency: 80-125% ADCC relative potency vs. reference standard. Identity: peptide map consistent with expected mAb-X sequence; iCIEF pI consistent with reference. Afucosylation: >=85% afucosylated glycans (critical for MoA — this is unique to glycoengineered products). Stability: >=24 months at 2-8C with no more than 5% aggregate increase and potency maintained >=80%. Container Closure: Type I borosilicate glass vial with FluroTec-coated chlorobutyl stopper. Sterility: sterile per USP <71>; endotoxin <0.25 EU/mL per USP <85>. Appearance: clear to slightly opalescent, colourless to pale yellow. pH: 6.0 +-0.3. Osmolality: 270-330 mOsm/kg.',
    },
    {
      type: 'table',
      title: 'Complete pCQA Risk Assessment — Alt et al. Scoring',
      headers: ['pCQA', 'BioActivity (2-20)', 'PK/PD (2-20)', 'Immunogenicity (2-20)', 'Safety (2-20)', 'max(I)', 'Uncert. (1-7)', 'Risk Score', 'Classification'],
      rows: [
        ['Afucosylation', '20', '4', '2', '4', '20', '2', '40', 'CQA (Medium)'],
        ['Galactosylation', '8', '4', '2', '2', '8', '4', '32', 'CQA (Medium)'],
        ['High-Mannose', '4', '12', '2', '2', '12', '3', '36', 'CQA (Medium)'],
        ['Sialylation', '4', '4', '2', '2', '4', '5', '20', 'Non-CQA (Low)'],
        ['Aggregates (soluble)', '4', '8', '16', '12', '16', '2', '32', 'CQA (Medium)'],
        ['Fragments', '8', '8', '4', '4', '8', '3', '24', 'Non-CQA (Low)'],
        ['Subvisible Particles', '2', '4', '16', '8', '16', '3', '48', 'CQA (Medium)'],
        ['Charge Variants (%Acidic)', '12', '4', '2', '2', '12', '3', '36', 'CQA (Medium)'],
        ['Deamidation (HC CDR2 Asn55)', '16', '4', '2', '2', '16', '2', '32', 'CQA (Medium)'],
        ['Met252 Oxidation', '4', '12', '2', '2', '12', '2', '24', 'Non-CQA (Low)'],
        ['CDR Trp Oxidation', '12', '4', '2', '2', '12', '4', '48', 'CQA (Medium)'],
        ['HCP (total)', '2', '2', '12', '16', '16', '2', '32', 'CQA (Medium)'],
        ['HCP (PLBL2 specific)', '2', '2', '4', '8', '8', '3', '24', 'Non-CQA (Low)'],
        ['Residual DNA', '2', '2', '4', '8', '8', '2', '16', 'Non-CQA (Low)'],
        ['Residual Protein A', '2', '2', '8', '12', '12', '2', '24', 'Non-CQA (Low)'],
        ['C-terminal Lys', '2', '2', '2', '2', '2', '1', '2', 'Non-CQA (Low)'],
        ['N-terminal pyroGlu', '2', '2', '2', '2', '2', '1', '2', 'Non-CQA (Low)'],
        ['Potency (ADCC)', '20', '8', '2', '4', '20', '1', '20', 'CQA — by definition'],
      ],
      sortable: true,
    },
    {
      type: 'callout',
      title: 'Risk Score Interpretation — Key Decisions',
      variant: 'info',
      content:
        'Several scoring decisions merit detailed justification: (1) Afucosylation scores BioActivity 20 because mAb-X is produced in a FUT8-knockout line specifically to maximise ADCC — afucosylation IS the mechanism. Uncertainty is 2 (not 1) because while the afucosylation-ADCC relationship is well established for IgG1, the specific dose-response relationship for mAb-X has not yet been confirmed clinically. (2) Fragments score Risk = 24 (Non-CQA) despite being a degradation product because: the primary MoA is ADCC (requiring intact Fc + Fab), and fragments are a minor component (<3%) that does not accumulate significantly at 2-8C. However, fragments ARE monitored on stability (Tier 2) because a sudden increase would indicate a process or stability change. (3) Met252 Oxidation scores Risk = 24 (Non-CQA) — this is notable because Met252 oxidation directly affects PK (score 12) and is a CQA for many mAbs. However, mAb-X is dosed by body surface area with flat dosing (not exposure-dependent), and the formulation includes 10 mM methionine that limits Met252 oxidation to <5% over shelf life. The low uncertainty (2) reflects robust FcRn binding data from forced-oxidized lots confirming the magnitude of the PK effect. (4) Potency is classified as CQA "by definition" — regardless of risk score, the ability of the product to achieve its intended pharmacological effect must always be controlled.',
    },
    {
      type: 'table',
      title: 'Resulting Drug Substance Specifications',
      headers: ['Test', 'Method', 'Acceptance Criterion', 'CQA Tier', 'Justification'],
      rows: [
        ['Appearance', 'Visual inspection', 'Clear to slightly opalescent, colourless to pale yellow', 'Non-CQA', 'Compendial requirement; opalescence limit 18 NTU'],
        ['pH', 'Potentiometry', '5.7-6.3', 'Non-CQA', 'Formulation stability optimum'],
        ['Protein concentration', 'UV A280 (e = 1.5 mL/mg/cm)', '30 +/- 3 mg/mL', 'Non-CQA', 'Dose accuracy'],
        ['Identity', 'Peptide map + iCIEF pI', 'Consistent with reference; pI 8.2-8.6', 'Non-CQA', 'Identity confirmation per ICH Q6B'],
        ['Purity by SEC', 'SEC-HPLC', '>=95.0% monomer; <=2.0% HMW; <=3.0% LMW', 'CQA (Tier 1)', 'Clinical lot range 96.5-98.2%; 3-sigma from mean'],
        ['Purity by CE-SDS (NR)', 'CE-SDS non-reducing', '>=90.0% intact IgG', 'CQA (Tier 1)', 'Clinical lot range 93.2-96.8%'],
        ['Charge variants', 'iCIEF', '%Acidic <=35; %Main >=50; %Basic <=20', 'CQA (Tier 1)', 'Clinical lot range: Acidic 20-30%, Main 58-68%, Basic 8-15%'],
        ['Glycan profile — afucosylation', 'HILIC-FLR', '>=85% afucosylated', 'CQA (Tier 1)', 'MoA-critical; FUT8-KO process delivers 90-95%; clinical lots all >=88%'],
        ['Glycan profile — high-mannose', 'HILIC-FLR', '<=8%', 'CQA (Tier 1)', 'PK impact at >10%; process range 2-6%'],
        ['Glycan profile — galactosylation', 'HILIC-FLR', 'Report result (30-70%)', 'CQA (Tier 1)', 'Wide range acceptable; CDC is secondary mechanism'],
        ['Potency', 'ADCC reporter bioassay', '80-125% relative potency', 'CQA (Tier 1)', 'ICH Q6B requirement; 4PL dose-response against reference standard'],
        ['HCP', 'Generic CHO HCP ELISA', '<=100 ppm (ng/mg)', 'CQA (Tier 1)', 'Safety/immunogenicity; process clears to <30 ppm typically'],
        ['Residual DNA', 'qPCR (CHO-specific)', '<=10 ng/dose', 'Non-CQA (Tier 1)*', 'WHO guideline; regulatory expectation despite low actual risk'],
        ['Residual Protein A', 'Protein A ELISA', '<=10 ppm', 'Non-CQA (Tier 1)*', 'Immunogenicity precaution; process clears to <2 ppm typically'],
        ['Endotoxin', 'Kinetic LAL', '<0.25 EU/mL', 'Non-CQA', 'Compendial requirement (USP <85>)'],
        ['Subvisible particles', 'HIAC / MFI', '<=6000/container >=10um; <=600/container >=25um', 'CQA (Tier 1)', 'USP <787>; immunogenicity risk'],
        ['Visible particles', 'Visual inspection', 'Essentially free of visible particulates', 'Non-CQA', 'USP <790>; compendial requirement'],
        ['Osmolality', 'Vapour pressure osmometry', '270-330 mOsm/kg', 'Non-CQA', 'Physiological tonicity for IV'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'Control Strategy — Multi-Tier Integration for mAb-X',
      color: 'green',
      content:
        'The control strategy for mAb-X integrates all four tiers for each CQA. Afucosylation example: Tier 1 — HILIC-FLR release testing with acceptance criterion >=85% afucosylated. Tier 2 — At-line Raman spectroscopy in the bioreactor for real-time glycan monitoring (PAT), providing early warning if glycan profile deviates during production. Tier 3 — Cell culture CPP control: pH 6.9-7.1, DO >=30%, temperature 33+-1C in production phase (the FUT8-KO cell line provides the primary control, but Golgi processing efficiency still depends on culture conditions). Tier 4 — Media raw material control: manganese supplementation (0.04-0.4 uM for GnT-I activity), absence of fucose in media (inadvertent fucose addition could partially restore fucosylation via the salvage pathway). Aggregate control example: Tier 1 — SEC >=95% monomer, HIAC USP <787>. Tier 2 — At-line SEC after UF/DF (reject if >3% aggregate before formulation); visual inspection at 100% during fill. Tier 3 — UF/DF TMP 10-20 psi (DOE-established range preventing membrane-surface aggregation); low-pH hold <=2 hours (minimises acid-induced aggregation); fill speed <=10 mL/min (minimises shear). Tier 4 — PS80 lot testing for peroxide value <10 mEq/kg; sucrose or trehalose purity >99.5%.',
    },
    {
      type: 'table',
      title: 'Complete Analytical Panel — Release, Stability, and Characterisation',
      headers: ['Method', 'Attribute(s)', 'Release', 'Stability', 'Characterisation', 'Comparability'],
      rows: [
        ['SEC-HPLC', 'Monomer %, HMW, LMW', 'Yes', 'Yes (all timepoints)', 'Yes', 'Yes'],
        ['CE-SDS (NR + R)', 'Intact IgG, HC/LC, fragments', 'Yes', 'Yes', 'Yes', 'Yes'],
        ['iCIEF', 'Charge variants, pI', 'Yes', 'Yes', 'Yes', 'Yes'],
        ['HILIC-FLR', 'Glycan profile', 'Yes', 'Selected timepoints', 'Yes', 'Yes'],
        ['ADCC reporter bioassay', 'ADCC potency', 'Yes', 'Yes', 'Yes', 'Yes'],
        ['Target-binding ELISA', 'CD20 binding', 'Yes', 'Yes', 'Yes', 'Yes'],
        ['Peptide mapping LC-MS/MS', 'Identity, PTMs (deamidation, oxidation)', 'Yes (identity)', 'Yes (6M, 12M, EOS)', 'Yes (full)', 'Yes (full)'],
        ['Intact/subunit MS', 'MW, glycoform mass', 'No', 'No', 'Yes', 'Yes'],
        ['HIC', 'Oxidation variants', 'No', 'Yes (selected)', 'Yes', 'Yes'],
        ['SPR (CD20, FcgRIIIa, FcRn)', 'Binding kinetics', 'No', 'No', 'Yes', 'Yes'],
        ['DSC / nanoDSF', 'Thermal stability (Tm, Tonset)', 'No', 'No', 'Yes', 'Yes'],
        ['AUC-SV', 'Sedimentation coefficient, oligomers', 'No', 'No', 'Yes', 'Yes'],
        ['DLS', 'Rh, polydispersity', 'No', 'Selected timepoints', 'Yes', 'Yes'],
        ['MFI', 'Subvisible particles (morphology)', 'Yes', 'Yes', 'Yes', 'Yes'],
        ['HIAC', 'Subvisible particles (count)', 'Yes', 'Yes', 'No', 'Yes'],
        ['CDC assay', 'Complement-dependent cytotoxicity', 'No', 'No', 'Yes', 'Yes'],
        ['HDX-MS', 'Conformational dynamics', 'No', 'No', 'Yes', 'Yes (biosimilar)'],
        ['HCP ELISA', 'Total HCP', 'Yes', 'No', 'No', 'Yes'],
        ['HCP LC-MS/MS', 'Individual HCP identification', 'No', 'No', 'Yes', 'Yes'],
        ['qPCR', 'Residual DNA', 'Yes', 'No', 'No', 'No'],
        ['Protein A ELISA', 'Residual Protein A', 'Yes', 'No', 'No', 'No'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'Stability Programme Design',
      color: 'amber',
      content:
        'The stability programme for mAb-X follows ICH Q5C (Quality of Biotechnological Products: Stability Testing) with the following design: Long-term: 2-8C (target storage), tested at 0, 3, 6, 9, 12, 18, 24, 36 months using the full stability panel (SEC, CE-SDS, iCIEF, HILIC-FLR, potency, peptide mapping [selected timepoints], pH, appearance, subvisible particles). Accelerated: 25C/60% RH, tested at 0, 1, 3, 6 months — this condition accelerates deamidation, aggregation, and fragmentation and confirms the degradation pathways identified during forced degradation. Stress: 40C/75% RH, tested at 0, 2 weeks, 1 month — demonstrates the molecule is sufficiently stable to survive temperature excursions during shipping and handling. Photostability: ICH Q1B Option 2 (1.2M lux-hours visible + 200 W-hr/m2 UV-A) — demonstrates packaging protects against light-induced Trp oxidation and aggregation. In-use: simulate clinical preparation (dilution in 0.9% NaCl infusion bag, stored at room temperature for 24 hours) — confirms stability under in-use conditions. Three batches minimum at each condition (PPQ batches for initial filing, annual stability batches for ongoing verification). The stability data support the 24-month shelf life claim and provide the trending data for the continuous process verification programme.',
    },
    {
      type: 'callout',
      title: 'Decision Framework — When to Re-Assess CQA Classification',
      variant: 'warning',
      content:
        'The CQA assessment for mAb-X is a living document that must be updated at key milestones: (1) End of Phase I — first clinical exposure data; re-evaluate immunogenicity risk scores based on ADA incidence. If unexpectedly high ADA rates are observed, increase immunogenicity impact scores for aggregates and subvisible particles. (2) End of Phase II — dose-response data; re-evaluate potency and PK impact scores. If a dose-exposure-response relationship is established, PK-impacting CQAs (high-mannose, Met252 oxidation) may warrant tighter specifications. (3) BLA submission — full clinical dataset; finalise CQA classifications with clinical evidence. Met252 oxidation may be upgraded from non-CQA to CQA if PK data show clinical significance. Fragments may be upgraded if stability data show unexpected accumulation. (4) Post-approval — any manufacturing change triggering a comparability assessment requires CQA re-evaluation. Site transfer from Site A (2000 L) to Site B (12000 L) may change the glycan profile (scale-dependent Golgi processing), requiring re-assessment of glycan CQA ranges. (5) Label expansion — if mAb-X is developed for a second indication (e.g., CLL) where CDC is the primary mechanism, galactosylation CQA status must be upgraded because it directly modulates C1q binding.',
    },
    {
      type: 'callout',
      title: 'Lessons from the Anti-CD20 Class — Real-World Precedents',
      variant: 'success',
      content:
        'The anti-CD20 class provides rich real-world precedents for CQA decisions: Rituximab (MabThera/Rituxan, first-generation, CHO, normally fucosylated) — ADCC is a secondary mechanism; afucosylation specifications were originally broad. The rituximab biosimilar experience (2015-2020) demonstrated that small glycan differences (5-10% fucosylation variation) could be bridged with ADCC functional data. Obinutuzumab (Gazyva, GlycoMAb technology, afucosylated) — ADCC is the primary differentiator from rituximab; afucosylation is the defining CQA with tight specifications (>90%). The clinical superiority of obinutuzumab over rituximab in CLL (GALLIUM trial) was attributed to enhanced ADCC from afucosylation, providing the clinical evidence that afucosylation directly translates to efficacy. Ofatumumab (Arzerra, fully human anti-CD20, targets a different CD20 epitope) — CDC is the primary mechanism rather than ADCC; galactosylation becomes a more important CQA, and afucosylation is less critical. These examples demonstrate that even within the same target (CD20), the CQA classification varies based on the specific MoA.',
    },
  ],
  mentorQuestions: [
    'In the mAb-X risk assessment, fragments were classified as non-CQA (Risk = 24) while charge variants were classified as CQA (Risk = 36). A regulatory reviewer asks why both degradation products are not treated equally. How do you defend the different classifications using the Alt et al. framework and mAb-X-specific data?',
    'You are planning a post-approval manufacturing site transfer for mAb-X from a 2000 L single-use bioreactor to a 12000 L stainless steel bioreactor. Which CQAs are most at risk of changing due to this scale-up, and what is your comparability study design?',
    'mAb-X is being developed for a second indication in rheumatoid arthritis where the MoA is primarily B-cell depletion through ADCC and ADCP, but the dosing regimen is much lower (1000 mg every 6 months vs. 375 mg/m2 weekly x4 in NHL). How does the different dosing regimen affect your CQA risk scores, particularly for PK-impacting attributes?',
  ],
};
