import type { ModuleContent } from '../../types/content';

export const module7: ModuleContent = {
  id: 'effector-m7',
  sectionId: 'effector',
  moduleNumber: 7,
  eyebrow: 'EFFECTOR 08',
  title: 'Effector Function Summary',
  lead: 'This capstone module integrates all Fc effector functions — ADCC, ADCP, CDC, FcRn recycling, and Protein A binding — into a unified reference framework. Use this as the decision-making guide for selecting the optimal Fc effector profile based on mechanism of action, target biology, and CMC strategy.',
  tags: [
    { label: 'Integration', color: 'amber' },
    { label: 'Decision Framework', color: 'green' },
    { label: 'Subclass Selection', color: 'blue' },
    { label: 'CMC Strategy', color: 'purple' },
  ],
  stats: [
    { label: 'Effector Functions', value: '5 major' },
    { label: 'IgG Subclasses', value: '4 (IgG1–IgG4)' },
    { label: 'Key CH2 Residues', value: '~25' },
    { label: 'Engineering Platforms', value: '12+' },
  ],
  sections: [
    {
      type: 'table',
      title: 'Master Effector Function Integration Table',
      headers: ['Effector Function', 'Molecular Requirements', 'Glycan Dependencies', 'Key CH2/CH3 Residues (EU)', 'Fc Engineering Options', 'IgG Subclass Ranking', 'Clinical Application'],
      rows: [
        [
          'ADCC',
          'FcγRIIIa (CD16a) crosslinking on NK cells → ITAM → Syk → perforin/granzyme',
          'Core fucose: steric clash with FcγRIIIa Asn162 glycan → afucosylation enhances 10–50×. Bisecting GlcNAc: modest enhancement (~2×).',
          'L234, L235, G236 (lower hinge); D265, Y296, S298, A327, L328, I332 (CH2 body); N297 (glycan)',
          'Afucosylation (GlycoMAb, Potelligent); S239D/I332E (DE); GASDALIE; F243L/R292P/Y300L/V305I/P396L',
          'IgG1 > IgG3 >> IgG4 > IgG2',
          'Tumour killing: obinutuzumab, margetuximab, mogamulizumab. ADCC is dominant for haematological targets with high NK cell access.',
        ],
        [
          'ADCP',
          'FcγRIIa (CD32a) + FcγRI (CD64) on macrophages → ITAM → Syk → phagocytic cup → phagolysosome',
          'Minimal glycan dependence: FcγRIIa binding not significantly affected by core fucose (Asn162 not at interface). Galactose: neutral to modest effect.',
          'L234, L235 (lower hinge); D265, A327, P329, I332 (CH2); FcγRI additionally contacts D3 domain',
          'S239D/I332E (modest ADCP enhancement); G236A; anti-CD47 combination to block SIRPα checkpoint',
          'IgG1 ≈ IgG3 > IgG4 > IgG2',
          'Solid tumour settings with tissue-resident macrophages. Cross-presentation to CD8⁺ T cells bridges innate and adaptive immunity.',
        ],
        [
          'CDC',
          'C1q hexamer (6 gC1q heads) binding to clustered Fc (IgG hexamer model) → C1r/C1s → C4b2a → C3 amplification → MAC (C5b-9)',
          'Terminal galactose (G1F/G2F): enhances 1.5–2× via CH2 conformation. High mannose (Man5): reduces ~50%. Core fucose: no significant effect.',
          'D270, K322, K326, P329, P331, E333 (CH2 C1q face); E345, E430, S440 (CH3 Fc-Fc hexamer contacts)',
          'E345R/E430G (HexaBody); K326W/E333S; IgG1/IgG3 chimeric CH2; CDC silencing: K322A, P329G, LALA-PG',
          'IgG3 > IgG1 >> IgG2 > IgG4 (negligible)',
          'B-cell depletion: rituximab, ofatumumab, obinutuzumab. High antigen density required for Fc hexamerisation and C1q recruitment.',
        ],
        [
          'FcRn Recycling',
          'pH-dependent binding: His310/His433/His435 protonated at endosomal pH 6.0 → salt bridges to FcRn acidic patch. Release at pH 7.4 upon deprotonation. 2:1 FcRn:IgG stoichiometry.',
          'No direct glycan involvement: FcRn contacts the CH2–CH3 elbow, distal from N297 glycan. Glycan indirectly affects CH2 conformation.',
          'I253, H310, H433, N434, H435, Y436 (CH2–CH3 elbow); M252, S254, T256 (YTE site); M428 (LS site)',
          'YTE (M252Y/S254T/T256E): ~4× half-life; LS/XTEND (M428L/N434S): ~3× half-life; Abdeg (H435A): accelerated clearance',
          'IgG1 ≈ IgG2 ≈ IgG4 (~21 d) > IgG3 (~7 d, R435)',
          'All therapeutic mAbs depend on FcRn for half-life. Extended: ravulizumab (YTE), nirsevimab (LS). Reduced: efgartigimod (Abdeg) for autoimmune IgG depletion.',
        ],
        [
          'Protein A Binding',
          'Protein A SpA domains bind CH2–CH3 interface (overlapping with FcRn site). pH-dependent elution (pH 3.0–3.5) used in manufacturing.',
          'No direct glycan involvement: Protein A contacts protein surface at CH2–CH3 elbow.',
          'I253, H310, H433, N434, H435, Y436 (overlapping with FcRn site); Q311, D376, L432 (additional SpA contacts)',
          'Most FcRn mutations preserve Protein A binding. YTE: slightly reduced. H435R (IgG3): reduced Protein A binding (use Protein G).',
          'IgG1 ≈ IgG2 ≈ IgG4 > IgG3 (allotype-dependent)',
          'Universal manufacturing: Protein A chromatography is the platform capture step. Binding affinity affects dynamic binding capacity and process economics.',
        ],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'IgG Subclass Selection — Decision Criteria',
      color: 'blue',
      content:
        'IgG subclass selection is the first and most consequential Fc engineering decision, as it sets the baseline effector function profile before any mutations are introduced. IgG1: the default therapeutic subclass (>80% of approved mAbs), providing strong ADCC, ADCP, and CDC, plus robust FcRn recycling and Protein A binding. Selected when one or more effector functions contribute to the mechanism of action (tumour killing, B-cell depletion, pathogen neutralisation with effector clearance). IgG2: selected when all effector functions must be minimised (immune checkpoint agonists like anti-CTLA-4, receptor-blocking mAbs where effector killing is undesirable). IgG2 has a rigid 12-residue hinge with 4 inter-chain disulphides, reducing Fc flexibility and FcγR/C1q engagement. Retains full FcRn binding and Protein A binding. IgG3: rarely used therapeutically despite having the strongest ADCC and CDC, because its 62-residue hinge is protease-sensitive, it has a shortened half-life (~7 days due to R435), and extensive allotypic polymorphisms complicate immunogenicity assessment. IgG4: selected for blocking/neutralising mAbs where all effector functions must be silenced (pembrolizumab, nivolumab, dupilumab). P331S eliminates CDC; reduced FcγR binding minimises ADCC/ADCP. The S228P hinge mutation prevents Fab-arm exchange. Retains full FcRn binding.',
    },
    {
      type: 'table',
      title: 'IgG Subclass Effector Function Profile',
      headers: ['Property', 'IgG1', 'IgG2', 'IgG3', 'IgG4'],
      rows: [
        ['ADCC', '+++', '+/−', '+++', '+/−'],
        ['ADCP', '+++', '+', '+++', '+'],
        ['CDC', '++', '+', '+++', '−'],
        ['FcRn half-life', '~21 d', '~21 d', '~7 d (R435)', '~21 d'],
        ['Protein A binding', '+++', '+++', '+ (allotype-dependent)', '+++'],
        ['Hinge length', '15 residues', '12 residues (rigid)', '62 residues (flexible)', '12 residues'],
        ['Inter-chain disulphides', '2', '4', '11', '2'],
        ['Fab-arm exchange', 'No', 'No', 'No', 'Yes (prevented by S228P)'],
        ['Approved mAb examples', 'Trastuzumab, rituximab, adalimumab', 'Panitumumab, denosumab', 'None currently', 'Pembrolizumab, nivolumab, dupilumab'],
        ['Typical MoA', 'Tumour killing, B-cell depletion, ADCC/CDC-dependent', 'Receptor blocking, ligand neutralisation (minimal effector)', 'Research tool (rarely therapeutic)', 'Checkpoint blocking, cytokine neutralisation (effector-silent)'],
      ],
      sortable: false,
    },
    {
      type: 'card',
      title: 'Decision Framework — Choosing the Effector Profile by MoA',
      color: 'green',
      content:
        'Step 1 — Define the mechanism of action: Does target cell killing contribute to efficacy? If yes → effector-active Fc (IgG1 or enhanced). If no → effector-silent Fc (IgG4 or silenced IgG1). Step 2 — Identify the dominant effector mechanism: For haematological malignancies with high NK cell access → ADCC-optimised (afucosylation, DE mutations). For solid tumours with tissue macrophage dependence → ADCP-optimised (Fc mutations + anti-CD47 combination). For B-cell targets with high antigen density (>100,000 copies) → CDC contribution likely (IgG1, galactosylation control). Step 3 — Consider half-life requirements: Chronic dosing (monthly or less frequent) → FcRn-enhanced (YTE or LS). Standard biweekly/monthly IV → wild-type IgG1. Autoimmune IgG depletion → Abdeg approach. Step 4 — Evaluate safety constraints: If the target is expressed on healthy tissues → minimise effector function to avoid on-target/off-tumour toxicity (IgG4 or effector-silent IgG1). If complement activation poses infusion reaction risk → silence CDC (K322A or IgG4). Step 5 — Apply CMC feasibility: Verify Protein A binding (manufacturing platform compatibility), thermal stability (formulation robustness), and glycan control requirements (afucosylation adds manufacturing complexity).',
    },
    {
      type: 'code',
      title: 'Fc Engineering Decision Tree',
      language: 'text',
      code: [
        '═══ START: What is the primary mechanism of action? ═══',
        '',
        '┌─ Target cell killing required?',
        '│  ├─ YES → Effector-ACTIVE Fc',
        '│  │  ├─ NK cell access (blood/lymphoid)?',
        '│  │  │  ├─ YES → Optimise ADCC',
        '│  │  │  │  ├─ Afucosylation (GlycoMAb/Potelligent)',
        '│  │  │  │  ├─ OR S239D/I332E (DE mutations)',
        '│  │  │  │  └─ OR GASDALIE (research stage)',
        '│  │  │  └─ NO (solid tumour, tissue) → Optimise ADCP',
        '│  │  │     ├─ IgG1 wild-type + anti-CD47 combination',
        '│  │  │     └─ OR G236A / S239D (modest ADCP boost)',
        '│  │  ├─ High antigen density (>50,000/cell)?',
        '│  │  │  ├─ YES → CDC may contribute',
        '│  │  │  │  ├─ Control galactosylation (G1F/G2F)',
        '│  │  │  │  └─ Consider E345R (HexaBody, research)',
        '│  │  │  └─ NO → CDC unlikely; focus ADCC/ADCP',
        '│  │  └─ Extended half-life needed?',
        '│  │     ├─ YES → Add YTE or LS mutations',
        '│  │     └─ NO → Wild-type Fc half-life sufficient',
        '│  └─ NO → Effector-SILENT Fc',
        '│     ├─ IgG4 (S228P) → natural effector silence',
        '│     ├─ OR IgG1-LALA (L234A/L235A) → silenced ADCC/ADCP',
        '│     ├─ OR IgG1-LALA-PG (+ P329G) → silenced ADCC/ADCP/CDC',
        '│     └─ OR IgG1-N297A/Q (aglycosyl) → all effector functions eliminated',
        '',
        '═══ CMC CHECKPOINT ═══',
        '• Verify Protein A binding (manufacturing platform)',
        '• Check thermal stability (Tm by DSC)',
        '• Assess aggregation propensity (SE-HPLC under stress)',
        '• Confirm FcRn binding (pH 6.0 AND pH 7.4 if engineered)',
        '• Validate glycan specifications match effector requirements',
      ].join('\n'),
    },
    {
      type: 'table',
      title: 'Fc Engineering Platforms — Clinical and CMC Summary',
      headers: ['Platform', 'Mutations / Approach', 'Target Function', 'Enhancement', 'CMC Impact', 'Clinical Stage'],
      rows: [
        ['GlycoMAb (Roche)', 'FUT8 KO in CHO → afucosylation', 'ADCC ↑↑↑', '~50× FcγRIIIa', 'Engineered cell line; glycan lot-release testing', 'Approved (obinutuzumab)'],
        ['Potelligent (BioWa)', 'FUT8 KO + GnTIII overexpression', 'ADCC ↑↑↑', '~50× FcγRIIIa', 'Engineered cell line; glycan specifications', 'Approved (mogamulizumab, benralizumab)'],
        ['DE (Xencor)', 'S239D/I332E', 'ADCC ↑↑', '~7× FcγRIIIa', 'Standard CHO; mutations verified by peptide mapping', 'Phase II/III'],
        ['GASDALIE', 'G236A/S239D/A330L/I332E', 'ADCC ↑↑↑', '~100× FcγRIIIa', 'Standard CHO; 4 mutations', 'Research stage'],
        ['Margetuximab Fc', 'F243L/R292P/Y300L/V305I/P396L', 'ADCC ↑↑', '~10× FcγRIIIa', 'Standard CHO; 5 mutations; peptide map verification', 'Approved (margetuximab)'],
        ['HexaBody (Genmab)', 'E345R or E430G', 'CDC ↑↑↑', '>100× C1q', 'Standard CHO; hexamer formation CQA', 'Phase I/II'],
        ['LALA', 'L234A/L235A', 'ADCC/ADCP ↓↓', 'Silences FcγR binding', 'Standard CHO; hinge mutations verified', 'Approved in bispecifics'],
        ['LALA-PG', 'L234A/L235A/P329G', 'ADCC/ADCP/CDC ↓↓↓', 'Silences all effector functions', 'Standard CHO; 3 mutations', 'Approved (atezolizumab)'],
        ['YTE (MedImmune)', 'M252Y/S254T/T256E', 'FcRn ↑↑', '~10× FcRn at pH 6.0', 'Protein A: slightly reduced; Tm: −2°C', 'Approved (ravulizumab)'],
        ['LS/XTEND (Xencor)', 'M428L/N434S', 'FcRn ↑↑', '~11× FcRn at pH 6.0', 'Protein A: normal; Tm: −1°C', 'Approved (nirsevimab, sotrovimab)'],
        ['Abdeg (argenx)', 'M252Y/S254T/T256E/H433K/N434F', 'IgG depletion', 'Competes for FcRn; depletes endogenous IgG', 'Fc fragment product; unique PK', 'Approved (efgartigimod)'],
        ['Aglycosyl (N297A/Q)', 'N297A or N297Q', 'All effector ↓↓↓', 'Eliminates glycan; full effector silence', 'No glycan CQA; simplified analytics; possible aggregation risk', 'Multiple clinical programmes'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'Overlapping and Competing Residue Networks',
      color: 'red',
      content:
        'A critical challenge in Fc engineering is that the effector function contact sites overlap and compete. The lower hinge (L234/L235) is the primary contact for all FcγRs — LALA mutations that silence ADCC also silence ADCP. The CH2–CH3 elbow (I253/H310/H435) is shared by FcRn and Protein A — some FcRn-enhancing mutations (YTE) modestly reduce Protein A binding. The CH2 body around P329/P331 is the C1q contact face, adjacent to FcγR contacts at D265/I332 — engineering one can affect the other. The N297 glycan maintains CH2 conformation required by all Fc receptors — removing it (N297A) abolishes ADCC, ADCP, and CDC simultaneously but also risks CH2 destabilisation and aggregation. Understanding this interconnected residue network is essential for predicting off-target effects of any Fc modification. Every Fc mutation should be characterised against the full panel: FcγRI, FcγRIIa (H131/R131), FcγRIIb, FcγRIIIa (V158/F158), FcγRIIIb, C1q, FcRn (pH 6.0 and 7.4), and Protein A. Omitting any receptor from the panel creates blind spots.',
    },
    {
      type: 'bullets',
      title: 'CMC Characterisation Checklist for Fc-Engineered mAbs',
      items: [
        'FcγR binding panel (SPR): FcγRI, FcγRIIa-H131, FcγRIIa-R131, FcγRIIb, FcγRIIIa-V158, FcγRIIIa-F158, FcγRIIIb. Report KD, ka, kd for each. Compare to wild-type IgG1 reference standard.',
        'C1q binding (ELISA or SPR): quantify C1q engagement. For CDC-dependent mAbs, C1q binding is lot-release. For effector-silent mAbs, confirm C1q binding is abolished.',
        'FcRn binding (SPR at pH 6.0 and pH 7.4): KD at pH 6.0 for recycling capacity; KD at pH 7.4 to confirm release. For YTE/LS variants, dual-pH assay is lot-release.',
        'Protein A binding (SPR or ITC): confirm dynamic binding capacity is compatible with manufacturing platform. Particularly important for YTE variants where M252Y can reduce Protein A affinity.',
        'ADCC assay (reporter bioassay + primary NK cells): reporter bioassay for lot-release potency; primary NK assay for extended characterisation. Specify FcγRIIIa genotype of cell line.',
        'ADCP assay (MDM-based or THP-1 reporter): for mAbs where ADCP is MoA. Report donor FcγRIIa genotype. THP-1 reporter for reproducibility.',
        'CDC assay (complement-dependent lysis): for mAbs where CDC is MoA. Standardise serum lot (CH50 qualification) and target cell CD55/CD59 expression.',
        'Glycan profiling (HILIC-UPLC, CE-LIF, LC-MS): quantify core fucosylation, galactosylation, high-mannose species, bisecting GlcNAc. Set specifications linked to effector function requirements.',
        'Thermal stability (DSC): report Tm for CH2, CH3, and Fab domains. Compare to wild-type to assess destabilisation from Fc mutations.',
        'Aggregation propensity (SE-HPLC, DLS under stress): critical for any Fc variant, particularly aglycosyl and FcRn-enhanced variants that may alter CH2 stability.',
      ],
    },
    {
      type: 'callout',
      title: 'Industry Perspective — The Modern Fc Engineering Toolkit',
      variant: 'success',
      content:
        'The therapeutic antibody field has evolved from using natural IgG subclasses as-is to precision engineering of the Fc region as a modular platform. The modern Fc toolkit enables: (1) enhanced ADCC (afucosylation, DE, GASDALIE) for tumour-killing mAbs; (2) enhanced CDC (HexaBody) for complement-dependent targets; (3) effector silencing (LALA-PG, IgG4-S228P, N297A) for blocking and agonist mAbs; (4) half-life extension (YTE, LS) for reduced dosing frequency; (5) IgG depletion (Abdeg) for autoimmune disease. These tools can be combined — for example, afucosylation + LS provides enhanced ADCC with extended half-life. The CMC scientist must understand the interplay of these modifications to design appropriate characterisation programmes, set meaningful specifications, and ensure that engineering mutations do not introduce unintended liabilities in manufacturing, stability, or immunogenicity.',
    },
    {
      type: 'callout',
      title: 'Regulatory Expectation — Comprehensive Fc Characterisation',
      variant: 'warning',
      content:
        'For any Fc-engineered therapeutic mAb, regulatory agencies (FDA, EMA, PMDA) expect the BLA/MAA dossier to include: (1) a rationale for the Fc engineering approach with structural data (crystallography, computational modelling, or extensive mutagenesis data) supporting the design; (2) a comprehensive Fc receptor binding panel (FcγRI through FcγRIIIb, C1q, FcRn at dual pH) demonstrating the intended modification and confirming no unintended off-target receptor effects; (3) cell-based functional assays (ADCC, ADCP, CDC as relevant) demonstrating the expected functional consequence; (4) PK/PD data showing the engineered half-life or effector profile translates to the intended clinical benefit; (5) immunogenicity risk assessment addressing whether the mutations introduce new T-cell epitopes. ICH S6(R1) applies to all engineered antibody Fc domains. Failure to provide comprehensive Fc characterisation is a common deficiency in BLA review.',
    },
  ],
  mentorQuestions: [
    'You are designing a new anti-EGFR mAb for colorectal cancer. EGFR is expressed at ~50,000 copies per tumour cell and also at ~10,000 copies on normal intestinal and skin epithelium. Walk through your Fc subclass and engineering decision: which effector functions do you want, which do you want to avoid, and what are the CMC characterisation requirements for your chosen Fc variant?',
    'Compare the LALA-PG (L234A/L235A/P329G) and IgG4-S228P approaches for creating an effector-silent mAb. What are the advantages, disadvantages, and residual effector activity of each? Under what circumstances would you choose one over the other?',
    'A bispecific antibody programme uses a heterodimeric Fc (knobs-into-holes) with one chain carrying the LS mutations and the other chain unmodified. Predict how this asymmetric Fc would affect: (a) FcRn recycling (considering 2:1 stoichiometry), (b) FcγRIIIa binding (considering asymmetric Fc engagement), and (c) Protein A purification. What characterisation experiments would you design to evaluate each?',
  ],
};
