import type { ModuleContent } from '../../types/content';

export const module3: ModuleContent = {
  id: 'effector-m3',
  sectionId: 'effector',
  moduleNumber: 3,
  eyebrow: 'EFFECTOR 04',
  title: 'CDC Classical Pathway',
  lead: 'Complement-dependent cytotoxicity through the classical pathway requires C1q binding to clustered Fc regions, triggering an enzymatic cascade that assembles the membrane attack complex. This module traces every molecular step from C1q hexamer recognition to MAC pore formation, including the glycan and engineering determinants that control CDC potency.',
  tags: [
    { label: 'CDC', color: 'red' },
    { label: 'C1q', color: 'blue' },
    { label: 'MAC', color: 'purple' },
    { label: 'IgG Hexamer', color: 'amber' },
  ],
  stats: [
    { label: 'C1q Globular Heads', value: '6 (gC1q)' },
    { label: 'MAC Pore Diameter', value: '~10 nm' },
    { label: 'Key CH2 Face', value: 'P329 / P331' },
    { label: 'Hexamer Model', value: 'Diebolder 2014' },
  ],
  sections: [
    {
      type: 'card',
      title: 'C1q Structure — The Hexameric Complement Sensor',
      color: 'blue',
      content:
        'C1q is a 460 kDa soluble glycoprotein that initiates the classical complement pathway. It is composed of 18 polypeptide chains — six copies each of the A, B, and C chains — assembled into a "bouquet of tulips" architecture. Each A-B-C heterotrimer forms a collagen-like triple helix stalk (~75 nm) terminating in a C-terminal globular head domain (gC1q, ~47 kDa per trimer). The six stalks converge at their N-termini into a central fibrillar hub. The six gC1q heads are the IgG Fc-binding modules, each recognising a distinct Fc region. The gC1q head engages the CH2 domain face of IgG at a site centred on P329 and P331 (EU numbering), with additional contacts at D270, K322, P329, and K326. Critical requirement: a single monomeric IgG binds C1q with Ka ~10⁴ M⁻¹ — far too weak for stable engagement at physiological C1q concentrations (~70 µg/mL in serum). Activation requires at least two gC1q heads to simultaneously engage adjacent Fc regions, providing avidity (apparent Ka ~10⁷ M⁻¹). This multivalent requirement ensures that C1q activates only when IgG is clustered on a target surface.',
    },
    {
      type: 'card',
      title: 'The IgG Hexamer Model — Optimal C1q Platform',
      color: 'amber',
      content:
        'Diebolder et al. (Science 343:1260, 2014) demonstrated that IgG1 molecules can form ordered hexameric rings on cell surfaces through non-covalent Fc–Fc contacts at the CH2–CH3 elbow interface. The hexamer places six Fc regions in a planar arrangement matching the spatial geometry of the six gC1q heads perfectly. The Fc–Fc interface involves residues E345, E430, S440, and K439 at the CH3 domain, with E345 making the critical intermolecular contact. Mutation E345R dramatically stabilises IgG hexamerisation on target cell surfaces, increasing CDC potency by >100-fold for antibodies that normally show weak CDC. Similarly, E430G reduces the electrostatic repulsion between adjacent Fc regions, promoting hexamer formation. The hexamer model explains several longstanding observations: (1) why high antigen density enhances CDC — more antigen sites allow more IgG binding, increasing the probability of hexamer formation; (2) why IgG3 has the strongest CDC — its extended 62-residue hinge gives the Fab arms greater reach to bind antigen while allowing Fc regions to assemble into hexameric platforms; (3) why IgG4 has negligible CDC — the CH3 interface residues differ and Fab-arm exchange disrupts stable hexamerisation.',
    },
    {
      type: 'code',
      title: 'Classical Pathway Cascade — Step-by-Step (EU Numbering)',
      language: 'text',
      code: [
        '═══ STEP 1: RECOGNITION ═══',
        'C1q gC1q heads bind clustered IgG Fc at CH2 face (P329/P331/D270/K322/K326)',
        '  → Minimum: 2 adjacent Fc regions; optimal: IgG hexamer (6 Fc)',
        '  → C1q conformational change transmitted through collagen stalks',
        '',
        '═══ STEP 2: C1 COMPLEX ACTIVATION ═══',
        'C1r₂C1s₂ tetramer bound within C1q collagen stalks',
        '  → C1q conformational change → C1r autoactivation (serine protease)',
        '  → Activated C1r cleaves C1s → active C1s serine protease',
        '',
        '═══ STEP 3: C4 CLEAVAGE ═══',
        'Active C1s cleaves C4 → C4a (anaphylatoxin, released) + C4b',
        '  → C4b exposes internal thioester bond (Cys-Gln)',
        '  → Thioester reacts with hydroxyl/amine on target surface → covalent attachment',
        '  → ~5% of C4b binds surface; rest hydrolysed (C4b(H₂O)) = inefficient step',
        '',
        '═══ STEP 4: C2 CLEAVAGE ═══',
        'C4b binds C2 → C1s cleaves C4b-bound C2 → C2a (catalytic) + C2b (released)',
        '  → C4b2a = C3 convertase of classical pathway (surface-bound enzyme)',
        '',
        '═══ STEP 5: C3 AMPLIFICATION ═══',
        'C3 convertase (C4b2a) cleaves C3 → C3a (anaphylatoxin) + C3b',
        '  → C3b thioester covalently binds target surface (opsonisation)',
        '  → AMPLIFICATION: each C3 convertase generates ~200 C3b molecules',
        '  → C3b also feeds alternative pathway amplification loop (Factor B/D)',
        '',
        '═══ STEP 6: C5 CONVERTASE ═══',
        'C3b binds to C4b2a → C4b2a3b = C5 convertase',
        '  → C5 convertase cleaves C5 → C5a (potent anaphylatoxin) + C5b',
        '',
        '═══ STEP 7: MAC ASSEMBLY ═══',
        'C5b sequentially recruits: C6 → C7 → C5b67 inserts into lipid bilayer',
        '  → C8 binds C5b67 → C8 partially penetrates membrane',
        '  → 10–18 copies of C9 polymerise around C8 → forms transmembrane pore',
        '  → MAC (C5b-9): ~10 nm internal diameter pore',
        '  → Ion/water influx → osmotic lysis of target cell',
      ].join('\n'),
    },
    {
      type: 'card',
      title: 'C3 Amplification Loop — The Cascade Multiplier',
      color: 'green',
      content:
        'The C3 amplification step is the pivotal point of the complement cascade. Each C3 convertase (C4b2a) cleaves approximately 200 C3 molecules in its ~60-second half-life before it is inactivated. C3b fragments covalently attach to the target cell surface via their exposed thioester bond, serving dual functions: (1) opsonisation — surface-bound C3b is recognised by complement receptors CR1 (CD35) and CR3 (CD11b/CD18) on phagocytes, promoting complement-dependent phagocytosis; (2) C5 convertase formation — C3b associates with existing C4b2a to form C4b2a3b (C5 convertase). Additionally, surface-bound C3b feeds the alternative pathway amplification loop: Factor B binds C3b, is cleaved by Factor D to form C3bBb (alternative pathway C3 convertase), which generates additional C3b. This positive feedback loop can deposit thousands of C3b molecules on a target within minutes. The amplification loop explains why even modest classical pathway initiation (a few C1q binding events) can produce massive C3b opsonisation and ultimately efficient MAC formation.',
    },
    {
      type: 'card',
      title: 'Complement Regulatory Proteins — CD55 and CD59',
      color: 'red',
      content:
        'Host cells protect themselves from complement-mediated damage through membrane-bound complement regulatory proteins (mCRPs). CD55 (decay-accelerating factor, DAF) is a GPI-anchored protein that accelerates the decay of both classical (C4b2a) and alternative (C3bBb) C3/C5 convertases by displacing C2a and Bb from the enzymatic complex. CD59 (protectin, membrane inhibitor of reactive lysis) blocks the final step of MAC assembly by binding C8 and preventing C9 polymerisation. Tumour cells frequently overexpress CD55 and CD59 as immune evasion mechanisms, directly reducing CDC efficacy of therapeutic mAbs. CD55 expression is upregulated 2–5-fold in many B-cell lymphomas and solid tumours, and CD59 expression correlates with resistance to rituximab-mediated CDC. Therapeutic strategies to overcome mCRP-mediated resistance include: (1) bispecific antibodies targeting both the tumour antigen and CD55/CD59; (2) siRNA silencing of CD55/CD59; (3) use of IgG hexamerisation-enhancing mutations (E345R/E430G) to generate sufficiently overwhelming complement activation to saturate mCRP capacity; (4) combination with neutralising anti-CD59 antibodies. In CMC characterisation, target cell CD55/CD59 expression must be monitored as a critical assay variable.',
    },
    {
      type: 'table',
      title: 'IgG Subclass and Glycan Effects on CDC',
      headers: ['Variable', 'CDC Potency', 'Mechanism', 'CMC Relevance'],
      rows: [
        ['IgG3', 'Strongest', '62-residue hinge → maximal Fab reach with Fc hexamer assembly; most efficient C1q recruitment', 'Rarely used therapeutically (short half-life, Protein A binding issues); allotypic polymorphisms'],
        ['IgG1', 'Strong', 'Standard 15-residue hinge; efficient hexamerisation on high-density targets', 'Default therapeutic subclass; CDC characterised in Q6B extended panel'],
        ['IgG2', 'Weak', 'Rigid 12-residue hinge with 4 disulphides; poor Fc clustering; weak C1q contacts', 'Selected for mAbs where CDC is undesirable (e.g., immune checkpoint agonists)'],
        ['IgG4', 'Negligible', 'Fab-arm exchange disrupts hexamer; CH2 residues differ at C1q contact site (P331S)', 'Selected for blocking-only mAbs (e.g., pembrolizumab, nivolumab)'],
        ['High galactose (G2F)', 'Enhanced 1.5–2×', 'Terminal galactose improves CH2 conformation for C1q contact', 'Galactosylation is CQA for CDC-dependent mAbs; cell culture conditions (galactose feed) modulate'],
        ['High mannose (Man5)', 'Reduced ~50%', 'Altered CH2 conformation reduces C1q binding; faster serum clearance', 'Man5 >10% triggers CMC concern; high mannose specification set in lot-release'],
        ['Afucosylation', 'No significant change', 'Core fucose does not contact C1q binding face (P329/P331 distal from Asn162 site)', 'Afucosylation selectively enhances ADCC without altering CDC — important for MoA dissection'],
        ['E345R hexamer mutation', '>100× enhancement', 'Stabilises Fc-Fc hexameric ring matching C1q geometry', 'Research/clinical stage; not yet in approved products'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'CDC Assay Design for CMC',
      color: 'purple',
      content:
        'The standard CDC assay incubates antibody-opsonised target cells with human serum (or purified complement) and measures target cell lysis. Target cells: Raji or Daudi cells (anti-CD20), WIL2-S cells (high CD20 density, preferred for rituximab biosimilars), or Wien 133 cells (anti-CD38, daratumumab). Complement source: pooled normal human serum (NHS) from ≥10 donors or commercially sourced complement-preserved serum; heat-inactivated serum (56°C, 30 min) serves as negative control. Readout: 51Cr release (historical gold standard), calcein AM release (fluorescence), ATP-based viability (CellTiter-Glo), or propidium iodide uptake (flow cytometry). Incubation: 1–2 hours at 37°C. Key variables that must be standardised: (1) serum lot — complement activity varies ≥3-fold between commercial lots; CH50 titration should be performed on each lot; (2) target cell CD20/antigen density — passage number affects expression; (3) target cell CD55/CD59 expression — must be monitored as mCRP upregulation causes assay drift; (4) serum concentration — typically 10–25% v/v final; higher concentrations paradoxically reduce CDC due to complement regulatory factor excess.',
    },
    {
      type: 'table',
      title: 'CH2 Residues Critical for C1q Binding (EU Numbering)',
      headers: ['Residue', 'Amino Acid', 'Role in C1q Contact', 'Effect of Mutation'],
      rows: [
        ['D270', 'Asp', 'Electrostatic contact with gC1q B-chain', 'D270A: ~70% reduction in CDC'],
        ['K322', 'Lys', 'Salt bridge to gC1q acidic residue; critical for recognition', 'K322A: near-complete loss of CDC'],
        ['P329', 'Pro', 'Hydrophobic packing in "Pro sandwich" with gC1q Trp', 'P329A: >90% reduction in C1q binding'],
        ['P331', 'Pro', 'Adjacent proline completing the sandwich motif', 'P331S (as in IgG4): major CDC reduction'],
        ['K326', 'Lys', 'Electrostatic contact with gC1q', 'K326W: enhanced CDC (~2×); K326A: reduced CDC'],
        ['E333', 'Glu', 'Peripheral contact; modulates C1q approach angle', 'E333S: modest reduction in CDC'],
      ],
      sortable: false,
    },
    {
      type: 'card',
      title: 'The Galactosylation–CDC Connection',
      color: 'teal',
      content:
        'Terminal galactose residues on the Fc N-glycan (G1F, G2F species) enhance CDC by 1.5–2-fold compared to agalactosylated (G0F) glycoforms. The mechanism involves indirect conformational effects: galactose residues extend the glycan branches, creating additional non-covalent contacts with the CH2 protein backbone (particularly at the Phe241 and Asp265 region). These contacts stabilise a slightly more "open" CH2 conformation that optimises the spatial presentation of the P329/P331 C1q-binding face. Hodoniczky et al. (Biotechnol. Prog. 21:1644, 2005) and Raju (Curr. Opin. Immunol. 20:471, 2008) demonstrated that in vitro galactosylation of agalactosylated IgG1 using recombinant β-1,4-galactosyltransferase (B4GALT1) restores CDC activity to levels equivalent to naturally galactosylated antibody. In CHO cell culture, galactosylation can be controlled by: (1) galactose supplementation in the feed medium (1–10 mM); (2) uridine/manganese co-supplementation to enhance UDP-Gal donor availability; (3) culture temperature shift to 33°C during production phase. For CDC-dependent mAbs, terminal galactosylation (%G1F + %G2F) is classified as a CQA with manufacturing specifications.',
    },
    {
      type: 'bullets',
      title: 'Fc Engineering Strategies for CDC Modulation',
      items: [
        'Hexamerisation-enhancing mutations (E345R, E430G, S440Y): stabilise Fc–Fc contacts to promote ordered hexameric IgG platforms that optimally engage all six C1q gC1q heads. E345R alone increases CDC >100-fold for poorly CDC-active antibodies. These are being explored in HexaBody technology (Genmab).',
        'K326W/E333S double mutation: enhances direct C1q binding affinity ~5-fold by improving hydrophobic packing (K326W) and reducing charge repulsion (E333S) at the gC1q interface.',
        'IgG1/IgG3 chimeric Fc: grafting the IgG3 CH2 domain (superior C1q binding) onto an IgG1 CH3 backbone (retaining Protein A binding and normal half-life) creates a CDC-enhanced hybrid.',
        'CDC-silencing for safety: when CDC is undesirable (checkpoint mAbs, receptor agonists), IgG4 backbone (P331S natural) or IgG1 with K322A/P329G mutations eliminates C1q recruitment. The LALA-PG mutations (L234A/L235A/P329G) silence both FcγR and C1q.',
        'Complement pathway inhibition: for mAbs where CDC causes on-target toxicity (e.g., anti-GPI-anchored antigen mAbs causing haemolysis), selective CDC silencing preserves ADCC/ADCP while eliminating complement-mediated tissue damage.',
      ],
    },
    {
      type: 'callout',
      title: 'Industry Practice — CDC in the CMC Toolkit',
      variant: 'info',
      content:
        'For mAbs where CDC is part of the mechanism of action (rituximab, ofatumumab, daratumumab), CDC potency is a critical quality attribute measured by complement-dependent lysis assays and C1q binding by SPR/ELISA. The assay is included in the extended characterisation panel (ICH Q6B) and increasingly in lot-release panels for originator and biosimilar products. Key variables to control: serum lot qualification (CH50 >95% of reference), target cell CD20 and CD55/CD59 expression monitoring, and relative potency calculation against a qualified reference standard. For biosimilar development, FDA classifies CDC as a Tier 1 functional attribute requiring the most rigorous analytical similarity demonstration when CDC is a mechanism of action for the reference product.',
    },
    {
      type: 'callout',
      title: 'Clinical Relevance — Complement in Therapeutic Resistance',
      variant: 'danger',
      content:
        'Complement regulatory protein (mCRP) overexpression is a documented mechanism of resistance to CDC-dependent mAbs. Treon et al. (Blood 104:3644, 2004) showed that rituximab-resistant lymphoma cells upregulate CD55 and CD59 by 3–5-fold compared to sensitive cells. In CLL, baseline CD59 expression inversely correlates with rituximab CDC efficacy. Ofatumumab, a type I anti-CD20 mAb that binds a membrane-proximal epitope closer to the cell surface, was specifically developed to achieve more potent CDC than rituximab on mCRP-high tumour cells. The membrane proximity of its epitope allows more efficient Fc hexamerisation and C1q recruitment. Understanding the balance between antigen density, Fc hexamerisation propensity, mCRP expression, and complement consumption at the tumour site is essential for predicting CDC contribution to clinical efficacy.',
    },
  ],
  mentorQuestions: [
    'Walk through the full classical complement cascade from C1q binding to MAC pore insertion. At which step does the largest amplification occur, and why is this relevant to the dose-response relationship of CDC-dependent mAbs?',
    'The Diebolder IgG hexamer model explains why high antigen density enhances CDC. If you were developing a mAb against a low-density tumour antigen (~5,000 copies/cell), what Fc engineering strategies could you employ to rescue CDC activity, and what off-target complement activation risks would you need to evaluate?',
    'Your rituximab biosimilar shows equivalent FcγR binding and ADCC but 30% lower CDC potency. Glycan analysis reveals a shift from 45% G1F/G2F to 30% G1F/G2F with a corresponding increase in G0F. How would you address this in your CMC strategy and regulatory filing?',
  ],
};
