import type { QuizQuestion } from '../types/content';

export const quizQuestions: QuizQuestion[] = [
  // ═══ STRUCTURE (10 questions) ═══
  {
    id: 'q-str-1',
    sectionId: 'structure',
    question: 'Which domain of IgG1 has the lowest thermal stability (Tm) and serves as the primary nucleation site for aggregation?',
    options: [
      'CH2 domain (~60-65°C) — lacks stabilising inter-domain contacts and depends on glycan support',
      'CH3 domain (~82-85°C) — exposed to solvent at the Fc terminus',
      'VH domain (~65-80°C) — contains the most diverse CDR loops',
      'CH1 domain (~70°C) — does not form stable inter-chain contacts until LC pairing',
    ],
    correctIndex: 0,
    explanation: 'The CH2 domain has the lowest Tm (~60-65°C) among IgG domains because it lacks a stabilising CH2-CH2 protein-protein interface — the two CH2 domains are held apart solely by the Asn297 glycans acting as structural struts. When CH2 unfolds first under thermal stress, it exposes hydrophobic patches that nucleate aggregation. This is why DSC thermograms of mAbs typically show CH2 as the first endotherm, and why formulation strategies must prioritise CH2 stabilisation.',
    difficulty: 'medium',
  },
  {
    id: 'q-str-2',
    sectionId: 'structure',
    question: 'The LALA-PG mutation adds P329G to the LALA backbone. What is the specific molecular mechanism by which P329G abolishes CDC?',
    options: [
      'P329G disrupts the proline sandwich between P329 and two Trp residues in C1q, preventing complement activation',
      'P329G prevents C3 convertase assembly on the cell surface by altering CH2 conformation',
      'P329G causes CH2 domain misfolding that sterically blocks C1q binding',
      'P329G alters the glycan orientation at Asn297 making it incompatible with C1q recognition',
    ],
    correctIndex: 0,
    explanation: 'Pro329 in wild-type IgG1 forms a characteristic "proline sandwich" where it is wedged between two tryptophan residues (Trp163 and Trp100) in the C1q globular head domain. This Pro-Trp-Trp stacking interaction is essential for C1q binding to the CH2 domain. The P329G mutation replaces the rigid proline ring with flexible glycine, which cannot maintain the sandwich geometry. This specifically abolishes C1q binding and CDC, while the LALA mutations (L234A/L235A) separately abolish FcγR binding. Together, LALA-PG creates a fully silenced Fc.',
    difficulty: 'hard',
  },
  {
    id: 'q-str-3',
    sectionId: 'structure',
    question: 'In knobs-into-holes (KiH) bispecific engineering, which CH3 mutations create the "hole" chain?',
    options: [
      'T366S, L368A, Y407V — creating a cavity to accommodate the T366W knob',
      'T366W — a single large tryptophan residue that fills the interface',
      'L351D, T366R — introducing charged residues for electrostatic steering',
      'K409A, F405L — removing side chains at the dimer interface',
    ],
    correctIndex: 0,
    explanation: 'The KiH approach (Ridgway et al. 1996, Atwell et al. 1997) engineers one CH3 chain with a "knob" mutation T366W (replacing small threonine with bulky tryptophan) and the partner chain with three "hole" mutations T366S, L368A, Y407V that create a complementary cavity. The hole mutations replace medium-sized residues with smaller ones (Thr→Ser, Leu→Ala, Tyr→Val) to accommodate the large tryptophan knob. This drives heterodimerisation with ~95% efficiency and is the foundation of many approved bispecific antibodies.',
    difficulty: 'hard',
  },
  {
    id: 'q-str-4',
    sectionId: 'structure',
    question: 'Why does IgG3 bind poorly to Protein A compared to IgG1, IgG2, and IgG4?',
    options: [
      'IgG3 has Arg435 instead of His435 at the Protein A binding site in CH3',
      'IgG3 has an extended 62-residue hinge that sterically blocks the Protein A binding site',
      'IgG3 lacks the CH3-CH3 dimer interface required for Protein A engagement',
      'IgG3 glycosylation at additional sites in the hinge shields the Protein A contact surface',
    ],
    correctIndex: 0,
    explanation: 'The Protein A binding site on CH3 involves residues H433, H435, and Y436. IgG1, IgG2, and IgG4 all have His435, which makes critical contacts with Protein A. IgG3, however, has Arg435 — the larger, positively charged arginine side chain disrupts the binding pocket geometry and electrostatic complementarity required for Protein A interaction. This is why IgG3 antibodies require alternative purification strategies such as Protein G chromatography or engineered Protein A resins. Some IgG3 allotypes with His435 (common in certain populations) do bind Protein A.',
    difficulty: 'hard',
  },
  {
    id: 'q-str-5',
    sectionId: 'structure',
    question: 'An Asn-Gly (NG) motif at HCDR2 position 54-55 represents what level of CMC risk, and what is the approximate deamidation half-life?',
    options: [
      'Very high risk — t½ of 1-14 days depending on conformation, directly impacts potency if in the paratope',
      'Medium risk — t½ of weeks to months, usually clinically insignificant',
      'Low risk — NG motifs in CDRs are conformationally protected from deamidation',
      'High risk for charge heterogeneity but t½ > 30 days at physiological pH',
    ],
    correctIndex: 0,
    explanation: 'An NG motif is the fastest-deamidating dipeptide sequence, with half-lives as short as 1 day in unstructured peptides and 1-14 days in folded proteins depending on local conformation and solvent accessibility. When located in HCDR2 at positions 54-55, deamidation converts Asn to Asp/isoAsp, introducing a negative charge and potential backbone isomerisation that can reduce antigen binding by 10-100×. This generates charge heterogeneity detectable by CEX and iCIEF. It is one of the highest-risk CDR liabilities in CMC development and may require engineering intervention or wider specifications.',
    difficulty: 'expert',
  },
  {
    id: 'q-str-6',
    sectionId: 'structure',
    question: 'What is the role of BiP (GRP78/HSPA5) in antibody biosynthesis in CHO cells?',
    options: [
      'BiP binds CH1 and retains the heavy chain in the ER until light chain pairing occurs, preventing premature HC aggregation',
      'BiP catalyses the formation of inter-chain disulfide bonds between HC and LC',
      'BiP acts as the primary glycosyltransferase for N-linked glycan attachment at Asn297',
      'BiP escorts folded antibodies from the ER to the Golgi for secretion',
    ],
    correctIndex: 0,
    explanation: 'BiP (immunoglobulin heavy chain binding protein, also known as GRP78 or HSPA5) is an ER-resident Hsp70 family chaperone that specifically binds the CH1 domain of free heavy chains. This binding serves two critical functions: (1) it prevents premature HC-HC aggregation in the ER, and (2) it retains unpaired HC in the ER via the KDEL retrieval pathway until a light chain becomes available for pairing. Only when LC binds to CH1 does BiP release, allowing the assembled H2L2 to proceed through quality control and secretion. This is why LC:HC ratio (ideally 1.2-1.5:1 LC excess) is critical in cell line development.',
    difficulty: 'medium',
  },
  {
    id: 'q-str-7',
    sectionId: 'structure',
    question: 'The IgG4 hinge sequence contains CPSC. Why does changing S228 to P228 prevent Fab-arm exchange?',
    options: [
      'Proline rigidifies the hinge backbone, preventing the conformational flexibility needed for inter-molecular disulfide shuffling between half-antibodies',
      'P228 creates a new inter-chain disulfide bond that locks the two heavy chains together',
      'P228 eliminates a protease cleavage site that initiates Fab-arm exchange',
      'P228 changes the hinge from a flexible linker to a rigid rod, preventing any Fc movement',
    ],
    correctIndex: 0,
    explanation: 'Wild-type IgG4 has a CPSC hinge motif that allows the two inter-heavy chain disulfide bonds (C226-C226\' and C229-C229\') to exist in equilibrium between inter-chain and intra-chain configurations. When disulfides form intra-chain, the half-antibody (HL) can dissociate and re-associate with a different HL — this is Fab-arm exchange. S228P converts CPSC to CPPC (matching IgG1\'s hinge motif), where the rigid proline constrains the backbone geometry to strongly favour the inter-chain disulfide configuration, preventing dissociation. This was first described by Angal et al. (1993) and is now mandatory for all therapeutic IgG4 mAbs.',
    difficulty: 'hard',
  },
  {
    id: 'q-str-8',
    sectionId: 'structure',
    question: 'In EU numbering, which pair of residues forms the conserved intra-domain disulfide bond in the CH2 domain?',
    options: [
      'C261-C321',
      'C226-C229',
      'C220-C214',
      'C367-C425',
    ],
    correctIndex: 0,
    explanation: 'Each CH2 domain contains a conserved intra-domain disulfide bond between C261 and C321 (EU numbering). This bond stabilises the immunoglobulin fold of CH2 and is essential for maintaining domain integrity. C226 and C229 are inter-heavy chain disulfides in the hinge region. C220(HC)-C214(LC) is the inter-chain disulfide between heavy and light chains. C367-C425 is the intra-domain disulfide of CH3. In a complete IgG1 molecule, there are 12 intra-domain disulfides (one per domain) and 4 inter-chain disulfides.',
    difficulty: 'medium',
  },
  {
    id: 'q-str-9',
    sectionId: 'structure',
    question: 'Which numbering scheme is used for variable region CDR positions in industry CMC documentation?',
    options: [
      'Kabat numbering — based on sequence variability analysis',
      'EU numbering — based on the Eu myeloma protein',
      'IMGT numbering — standardised 128 positions per domain',
      'Chothia numbering — based on structural loop conformations',
    ],
    correctIndex: 0,
    explanation: 'Industry convention uses Kabat numbering (Wu & Kabat 1970, updated 1991) for variable region and CDR positions, and EU numbering for constant region/Fc positions. Kabat numbering defines CDRs based on sequence variability peaks and uses letter suffixes for insertions (e.g., H52A, H52B). IMGT is used for germline gene assignment. Chothia defines CDRs based on structural loop conformations. In CMC documentation, regulatory submissions, and patent filings, you must always specify which numbering scheme is being used, and the convention is Kabat for variable + EU for constant.',
    difficulty: 'medium',
  },
  {
    id: 'q-str-10',
    sectionId: 'structure',
    question: 'What is the Vernier zone and why is it critical during antibody humanisation?',
    options: [
      'Framework residues that support CDR loop conformations without contacting antigen — back-mutating these to donor sequence rescues binding after CDR grafting',
      'The antigen-contact residues within CDR loops that must be preserved during humanisation',
      'The CH1-CL interface residues that determine light chain pairing specificity',
      'Solvent-exposed framework residues that drive immunogenicity of the humanised antibody',
    ],
    correctIndex: 0,
    explanation: 'The Vernier zone, defined by Foote & Winter (1992), consists of ~20 framework residues in VH and VL that do not directly contact antigen but structurally support the positioning and conformation of CDR loops. Key VH Vernier residues include positions 2, 4, 27-30, 47-49, 67, 69, 71, 73, 78, 93, 94 (Kabat numbering). During humanisation by CDR grafting, these residues in the human acceptor framework may differ from the donor (e.g., mouse) framework, causing CDR loops to adopt suboptimal conformations and reducing binding affinity. Back-mutating specific Vernier residues to the donor sequence is the primary rescue strategy.',
    difficulty: 'hard',
  },

  // ═══ GLYCOSYLATION (12 questions) ═══
  {
    id: 'q-glyc-1',
    sectionId: 'glycosylation',
    question: 'What is the primary molecular mechanism by which removal of core fucose enhances ADCC by up to 50-fold?',
    options: [
      'Removing Fc core fucose eliminates steric clash with the FcγRIIIa Asn162 glycan, allowing tighter receptor binding',
      'Afucosylation exposes a new binding epitope on CH2 that FcγRIIIa recognises',
      'Core fucose blocks the C1q binding site, so removing it enhances complement-mediated killing',
      'Without fucose, the Fc glycan adopts an extended conformation that bridges two FcγRIIIa receptors simultaneously',
    ],
    correctIndex: 0,
    explanation: 'Crystal structures (PDB 3SGJ) reveal that FcγRIIIa carries its own N-glycan at Asn162. When the mAb Fc has core α1,6-fucose at Asn297, this fucose residue sterically clashes with the receptor\'s Asn162 glycan, specifically involving aromatic residues Tyr158 and Phe176 on FcγRIIIa. This steric clash reduces Fc-receptor binding affinity by 10-50×. Removing core fucose eliminates this clash, allowing optimal glycan-glycan contacts and dramatically enhanced FcγRIIIa binding. This mechanism was elucidated through the work of Shields (2002), Shinkawa (2003), and structural studies by Ferrara (2006).',
    difficulty: 'hard',
  },
  {
    id: 'q-glyc-2',
    sectionId: 'glycosylation',
    question: 'In the Golgi enzyme cascade, which enzyme adds core α1,6-fucose to the reducing-end GlcNAc, and what is its gene name?',
    options: [
      'FUT8 (α1,6-fucosyltransferase) — uses GDP-fucose as the sugar donor',
      'B4GalT1 (β1,4-galactosyltransferase) — uses UDP-galactose as the sugar donor',
      'MGAT3 (GnTIII) — adds bisecting GlcNAc which is then converted to fucose',
      'ST6GAL1 (α2,6-sialyltransferase) — adds fucose via a sialylation-dependent pathway',
    ],
    correctIndex: 0,
    explanation: 'FUT8 (α1,6-fucosyltransferase, gene: FUT8) is the sole enzyme responsible for adding core fucose via an α1,6 linkage to the innermost (reducing-end) GlcNAc residue of N-glycans. It operates in the medial-to-trans Golgi compartment and requires GDP-fucose as the nucleotide sugar donor. GDP-fucose is synthesised via two pathways: the de novo pathway (from GDP-mannose via GMD and FX) and the salvage pathway (from free fucose via FUK and FPGT). The competitive inhibitor 2-fluorofucose blocks the de novo pathway and is used as a media additive for controlled afucosylation.',
    difficulty: 'medium',
  },
  {
    id: 'q-glyc-3',
    sectionId: 'glycosylation',
    question: 'Why are high-mannose glycoforms (Man5-Man9) classified as "always CQA" regardless of the antibody\'s mechanism of action?',
    options: [
      'Terminal mannose residues are recognised by CD206 (mannose receptor) on macrophages and hepatic endothelium, causing accelerated clearance that affects PK regardless of MoA',
      'High-mannose species aggregate more readily due to increased hydrophilicity at the Fc surface',
      'Man5-9 glycans cannot support FcγR binding, eliminating all effector functions',
      'High-mannose is immunogenic in humans because it resembles pathogen-associated glycans',
    ],
    correctIndex: 0,
    explanation: 'High-mannose glycoforms expose terminal α1,2-linked mannose residues that are normally associated with pathogens (yeast, bacteria). The mannose receptor (CD206/MRC1), expressed on macrophages, dendritic cells, and hepatic sinusoidal endothelial cells, recognises these terminal mannose residues and mediates receptor-mediated endocytosis and clearance. Goetze et al. (2011, Glycobiology) provided the first human clinical evidence: radiolabeled high-mannose IgG1 cleared ~2× faster than complex-type glycoforms. Because this PK impact is independent of the antibody\'s therapeutic mechanism, high-mannose is always classified as a CQA requiring process control (typically NMT 5-10%).',
    difficulty: 'hard',
  },
  {
    id: 'q-glyc-4',
    sectionId: 'glycosylation',
    question: 'What landmark 2008 Science paper discovered that sialylated IgG Fc mediates the anti-inflammatory activity of IVIG, and through which receptor?',
    options: [
      'Anthony et al. — sialylated Fc binds DC-SIGN (CD209) on dendritic cells, upregulating inhibitory FcγRIIb on effector macrophages',
      'Shields et al. — sialylated Fc binds FcγRIIIa with enhanced affinity, suppressing NK cell activation',
      'Nimmerjahn et al. — sialylated Fc activates the classical complement pathway at sub-lytic levels for immune modulation',
      'Kaneko et al. — sialylated Fc binds FcRn with enhanced affinity at pH 7.4, extending half-life and diluting inflammatory IgG',
    ],
    correctIndex: 0,
    explanation: 'Anthony et al. (2008, Science 320:373-376) demonstrated that α2,6-sialylated IgG Fc is the active anti-inflammatory component of intravenous immunoglobulin (IVIG). The proposed mechanism involves sialylated Fc binding to DC-SIGN (CD209, also known as SIGN-R1 in mice) on dendritic cells, which triggers a signalling cascade leading to upregulation of the inhibitory receptor FcγRIIb on effector macrophages. This raises the activation threshold for inflammatory immune complexes, producing an anti-inflammatory effect. Importantly, only α2,6-linked sialic acid (produced by ST6GAL1) engages this pathway — CHO cells primarily produce α2,3-linked sialic acid (via ST3GAL4/6), which has different receptor specificity.',
    difficulty: 'expert',
  },
  {
    id: 'q-glyc-5',
    sectionId: 'glycosylation',
    question: 'Which upstream cell culture parameter most directly controls galactosylation levels, and what is the mechanistic basis?',
    options: [
      'Mn²⁺ supplementation — Mn²⁺ is the essential divalent cation cofactor for B4GalT1 (β1,4-galactosyltransferase) activity in the trans-Golgi',
      'Dissolved oxygen — high DO inhibits UDP-galactose transporter activity in the Golgi membrane',
      'Culture pH — galactosyltransferase has a sharp pH optimum at exactly pH 7.0',
      'Glucose concentration — glucose competes with galactose for UDP-sugar synthesis enzymes',
    ],
    correctIndex: 0,
    explanation: 'B4GalT1 (β1,4-galactosyltransferase 1, gene: B4GALT1) requires Mn²⁺ as an essential divalent cation cofactor for catalytic activity. In standard CHO media, Mn²⁺ is often present at sub-optimal levels. Supplementation with 0.02-0.05 mM MnCl₂ can significantly increase galactosylation from G0F-dominant to G1F/G2F-enriched profiles. The mechanism involves Mn²⁺ binding at the catalytic site, positioning the UDP-galactose donor for optimal transfer to the terminal GlcNAc on each antenna. Temperature reduction (32-33°C) also increases galactosylation by increasing Golgi residence time, and pH affects it indirectly by altering enzyme activity and Golgi compartment function.',
    difficulty: 'hard',
  },
  {
    id: 'q-glyc-6',
    sectionId: 'glycosylation',
    question: 'In HILIC-UPLC glycan analysis, what is the standard fluorescent label, and what is the typical elution order?',
    options: [
      '2-AB (2-aminobenzamide) label; elution order: Man5 < G0 < G0F < G1F < G1F\' < G2F < G2FS1',
      'APTS (8-aminopyrene-1,3,6-trisulfonate) label; elution order: G2FS1 < G2F < G1F < G0F < Man5',
      'InstantPC label; elution order: Man5 < G0F < G0 < G2F < G1F < G2FS1',
      'procainamide label; elution order: G0F < Man5 < G1F < G2F < G2FS1',
    ],
    correctIndex: 0,
    explanation: '2-AB (2-aminobenzamide) is the most widely used fluorescent label for released N-glycan analysis by HILIC-UPLC. After PNGaseF release of glycans, reductive amination with 2-AB provides fluorescent detection (excitation 330 nm, emission 420 nm). On a Waters BEH Glycan column (1.7 µm, 130Å), the elution order follows increasing hydrophilicity: smaller/less branched glycans elute first (Man5), followed by core structures (G0, G0F), then galactosylated species (G1F isomers, G2F), and finally sialylated species (G2FS1, G2FS2). GU (glucose unit) values calibrated against a dextran ladder enable peak assignment. APTS is used in CE-LIF, and procainamide provides enhanced MS sensitivity but is less standardised.',
    difficulty: 'expert',
  },
  {
    id: 'q-glyc-7',
    sectionId: 'glycosylation',
    question: 'What distinguishes the GlycoMAb platform (Roche/Glycart) from the POTELLIGENT platform (BioWa/Kyowa Kirin)?',
    options: [
      'GlycoMAb overexpresses GnTIII (MGAT3) to produce bisected afucosylated glycans; POTELLIGENT uses FUT8 knockout for purely afucosylated glycans without bisecting GlcNAc',
      'GlycoMAb uses FUT8 knockout while POTELLIGENT uses GnTIII overexpression',
      'GlycoMAb uses 2-fluorofucose media additive while POTELLIGENT uses kifunensine',
      'Both platforms use the same FUT8 knockout approach but different CHO host cell lines',
    ],
    correctIndex: 0,
    explanation: 'GlycoMAb (Roche/Glycart, now Roche Glycart AG) overexpresses GnTIII (MGAT3) with a Golgi localisation signal in CHO cells. GnTIII adds bisecting β1,4-GlcNAc to the core mannose, which sterically blocks FUT8 access, resulting in bisected, predominantly afucosylated glycans. This was used to produce obinutuzumab (Gazyva). POTELLIGENT (BioWa, subsidiary of Kyowa Kirin) achieves afucosylation through complete FUT8 gene knockout (originally using lectin selection, later ZFN/CRISPR), producing purely afucosylated glycans without bisecting GlcNAc. This was used for mogamulizumab (Poteligeo). Both enhance ADCC via the same core mechanism (removing fucose-Asn162 steric clash), but GlycoMAb produces more analytically complex glycan profiles.',
    difficulty: 'expert',
  },
  {
    id: 'q-glyc-8',
    sectionId: 'glycosylation',
    question: 'What is Neu5Gc, and why is it a concern for therapeutic mAbs produced in CHO cells?',
    options: [
      'N-glycolylneuraminic acid — a non-human sialic acid that CHO cells can incorporate from bovine-derived media components, against which most humans have pre-existing antibodies',
      'A novel glycan structure unique to CHO cells that enhances ADCC beyond what is therapeutically desirable',
      'A degradation product of Neu5Ac (NANA) that forms during low-pH viral inactivation',
      'A CHO-specific core fucose variant that binds FcγRIIb and causes immunosuppression',
    ],
    correctIndex: 0,
    explanation: 'Neu5Gc (N-glycolylneuraminic acid) is a sialic acid variant produced by the CMAH (CMP-Neu5Ac hydroxylase) enzyme. Humans lost CMAH function ~2-3 million years ago due to an Alu-mediated gene deletion and cannot synthesise Neu5Gc. However, CHO cells express CMAH and can produce Neu5Gc, or incorporate it from bovine-derived media components (serum, hydrolysates). Most humans have circulating anti-Neu5Gc antibodies (from dietary exposure to red meat), which can bind Neu5Gc on therapeutic mAbs and potentially trigger immune-mediated clearance or adverse reactions. This is why chemically defined, animal component-free media is preferred, and Neu5Gc is monitored as a potential immunogenicity-related CQA.',
    difficulty: 'hard',
  },
  {
    id: 'q-glyc-9',
    sectionId: 'glycosylation',
    question: 'What is the OST glycosylation efficiency at Asn297, and what species results when it misses?',
    options: [
      '~97-99% efficiency; missed glycosylation produces non-glycosylated heavy chain (NGHC) with destabilised CH2, detectable by HILIC and intact MS',
      '100% efficiency; non-glycosylated species arise only from enzymatic cleavage by PNGaseF during processing',
      '~90% efficiency; the 10% unglycosylated fraction is the main source of acidic charge variants',
      '~99.9% efficiency; NGHC is never observed in properly controlled CHO processes',
    ],
    correctIndex: 0,
    explanation: 'The OST complex (primarily STT3A subunit for co-translational glycosylation) achieves ~97-99% efficiency at the Asn297 NLT sequon. The 1-3% of heavy chains that escape glycosylation produce non-glycosylated heavy chain (NGHC) species. When one HC is glycosylated and the other is not, a hemi-glycosylated mAb results (Ha et al. 2011), with asymmetric Fc properties. NGHC is detectable as an ~1.4 kDa mass difference by intact/subunit MS, and by the absence of glycan peaks in HILIC analysis. The specification for NGHC is typically NMT 1% for innovator products. NGHC can increase under nutrient limitation or when OST cofactors are depleted.',
    difficulty: 'hard',
  },
  {
    id: 'q-glyc-10',
    sectionId: 'glycosylation',
    question: 'Which upstream process parameter primarily drives elevated high-mannose (Man5) levels in CHO cell culture?',
    options: [
      'Low dissolved oxygen and nutrient limitation (glucose/glutamine depletion) — both impair Golgi processing enzyme activity',
      'High Mn²⁺ concentration — manganese inhibits α-mannosidase I activity',
      'Low culture temperature (32°C) — cold stress arrests glycan processing at the Man5 stage',
      'Elevated ammonia — ammonia directly inhibits the OST complex, causing incomplete glycosylation',
    ],
    correctIndex: 0,
    explanation: 'Elevated Man5 (high-mannose) levels result from incomplete Golgi processing, where the glycan fails to progress past the Man5GlcNAc2 intermediate. Low dissolved oxygen impairs Golgi enzyme function and UDP-sugar nucleotide synthesis. Glucose/glutamine depletion reduces the supply of UDP-GlcNAc and other nucleotide sugar donors needed by GnTI (MGAT1, the enzyme that converts Man5 to the first complex-type intermediate). Extended culture duration with declining viability also increases Man5 as dying cells release glycosidases that trim complex glycans back to high-mannose forms. Monitoring DO, glucose, and viability are key process controls for Man5.',
    difficulty: 'medium',
  },
  {
    id: 'q-glyc-11',
    sectionId: 'glycosylation',
    question: 'In the three-input framework for glycan CQA specifications, what are the three inputs?',
    options: [
      'Functional biology (glycan impact on MoA), process capability (what the process can deliver consistently), and clinical data (range in pivotal trial material)',
      'Analytical method precision, lot-to-lot variability, and regulatory precedent from similar products',
      'In vitro potency data, in vivo PK data, and manufacturing cost impact',
      'ICH Q6B requirements, comparator product data, and statistical process control limits',
    ],
    correctIndex: 0,
    explanation: 'Setting defensible glycan specifications requires integrating three independent inputs: (1) Functional biology — what is the glycan species\' impact on the mechanism of action, PK, immunogenicity, and safety? This determines which glycans are CQAs vs non-critical. (2) Process capability — what glycan range can the validated manufacturing process consistently deliver with adequate Cpk (target >1.33)? Specifications must be achievable. (3) Clinical data — what glycan range was present in the material used in pivotal clinical trials that demonstrated safety and efficacy? Specifications should encompass this clinically qualified range. The tightest of these three inputs typically sets the final specification limits.',
    difficulty: 'medium',
  },
  {
    id: 'q-glyc-12',
    sectionId: 'glycosylation',
    question: 'What are the key oxonium ion m/z values that serve as diagnostic markers for glycopeptides in LC-MS/MS analysis?',
    options: [
      'm/z 204.09 (HexNAc⁺), 292.10 (Neu5Ac⁺), and 366.14 (HexHexNAc⁺) — generated by CID/HCD fragmentation',
      'm/z 162.05 (Hex⁺), 203.08 (HexNAc⁺), and 291.10 (Neu5Ac⁺) — generated by ETD fragmentation',
      'm/z 138.06 (GlcNAc fragment), 274.09 (Fuc-GlcNAc⁺), and 454.16 (Man3⁺)',
      'm/z 180.06 (Glc⁺), 342.12 (Lac⁺), and 504.17 (Mal3⁺) — standard sugar markers',
    ],
    correctIndex: 0,
    explanation: 'In glycopeptide LC-MS/MS analysis, collision-induced dissociation (CID) or higher-energy collisional dissociation (HCD) generates characteristic oxonium ions from glycan fragmentation: m/z 204.087 (HexNAc⁺, N-acetylhexosamine), m/z 292.103 (Neu5Ac⁺, N-acetylneuraminic acid), and m/z 366.140 (HexHexNAc⁺, hexose-N-acetylhexosamine disaccharide). These ions are diagnostic for glycopeptides and are used as triggers in data-dependent acquisition methods (oxonium ion-triggered MS/MS). Y-ions (peptide backbone retaining partial glycan) provide glycan composition, while b/y peptide ions confirm the glycosylation site. This is the gold standard for site-specific glycan quantification.',
    difficulty: 'expert',
  },

  // ═══ MOA (8 questions) ═══
  {
    id: 'q-moa-1',
    sectionId: 'moa',
    question: 'In the ADCC cascade, what happens after FcγRIIIa crosslinking on the NK cell surface?',
    options: [
      'ITAM phosphorylation on CD3ζ/FcεRIγ adaptors → ZAP-70/Syk recruitment → PLCγ activation → Ca²⁺ flux → perforin/granzyme degranulation',
      'Direct perforin insertion into the target cell membrane without signalling intermediates',
      'C1q recruitment to the NK cell-target cell interface for complement-assisted killing',
      'FcγRIIIa internalisation with the target antigen, leading to lysosomal degradation',
    ],
    correctIndex: 0,
    explanation: 'After antibody-opsonised target cells are engaged by FcγRIIIa (CD16a) on NK cells, receptor crosslinking triggers ITAM (immunoreceptor tyrosine-based activation motif) phosphorylation on the associated CD3ζ and FcεRIγ adaptor chains by Src family kinases. This recruits ZAP-70 and Syk tyrosine kinases, which activate PLCγ (phospholipase C gamma). PLCγ cleaves PIP2 into IP3 (triggering Ca²⁺ release from ER stores) and DAG (activating PKC). The Ca²⁺ flux triggers polarised degranulation — directed release of lytic granules containing perforin and granzyme B toward the target cell. Perforin forms pores in the target membrane through which granzyme B enters and activates the caspase cascade (caspase-3, caspase-8, Bid cleavage) leading to apoptosis.',
    difficulty: 'hard',
  },
  {
    id: 'q-moa-2',
    sectionId: 'moa',
    question: 'What is the "bystander effect" in ADC biology, and which payload/linker combinations exhibit it?',
    options: [
      'Cell-permeable free payload released from dead target cells diffuses and kills antigen-negative neighbouring cells; MMAE with cleavable linkers exhibits this, DM1-SMCC does not',
      'ADC binding to target cells triggers FcγR-mediated uptake by neighbouring macrophages; all ADCs exhibit this',
      'Payload accumulation in the tumour microenvironment from ADC metabolism; only SN-38 payloads show this',
      'Antibody-dependent complement activation creates a cytotoxic zone around the target cell; only DXd exhibits this',
    ],
    correctIndex: 0,
    explanation: 'The bystander effect occurs when free payload released from killed target cells is sufficiently membrane-permeable to diffuse into and kill neighbouring antigen-negative tumour cells. MMAE (monomethyl auristatin E), released from cleavable valine-citrulline linkers by cathepsin B in lysosomes, is highly cell-permeable and exhibits strong bystander killing — this is therapeutically advantageous in heterogeneous tumours. DM1 (maytansinoid) conjugated via non-cleavable SMCC linker requires complete lysosomal degradation of the antibody, releasing charged Lys-SMCC-DM1 metabolites that are not cell-permeable, so no bystander effect occurs. DXd (deruxtecan topoisomerase I inhibitor, DAR ~8) also exhibits bystander activity, contributing to the clinical efficacy of trastuzumab deruxtecan in HER2-low tumours.',
    difficulty: 'hard',
  },
  {
    id: 'q-moa-3',
    sectionId: 'moa',
    question: 'How does a BiTE (bispecific T cell engager) achieve MHC-independent killing of tumour cells?',
    options: [
      'One arm binds a tumour antigen and the other binds CD3ε on T cells, forming an immunological synapse that bypasses the normal TCR-MHC requirement for T cell activation',
      'The BiTE activates complement independently of MHC, creating pores in the tumour cell membrane',
      'BiTEs block MHC class I expression on tumour cells, making them targets for NK cell "missing self" recognition',
      'BiTEs deliver a cytotoxic payload to tumour cells through receptor-mediated endocytosis',
    ],
    correctIndex: 0,
    explanation: 'BiTE molecules (e.g., blinatumomab: anti-CD19×anti-CD3) are tandem scFv bispecifics (~55 kDa) that physically bridge a tumour cell (via one scFv targeting a tumour antigen like CD19) to a T cell (via the other scFv targeting CD3ε). This proximity-driven crosslinking of CD3 on the T cell surface triggers the TCR signalling cascade independently of peptide-MHC presentation — the T cell does not need to recognise a specific peptide antigen. The resulting immunological synapse formation leads to perforin/granzyme-mediated killing of the bridged tumour cell. A single T cell can serially kill multiple target cells. Because this mechanism bypasses MHC, it is effective against tumours that have downregulated MHC class I as an immune escape mechanism.',
    difficulty: 'medium',
  },
  {
    id: 'q-moa-4',
    sectionId: 'moa',
    question: 'In the CDC classical pathway, what is the minimum number of IgG molecules required to activate C1q on a cell surface?',
    options: [
      'At least 2 IgG molecules in close proximity (hexagonal array model suggests 6 IgG form optimal hexameric ring for C1q binding)',
      'A single IgG molecule is sufficient if it has G2F glycosylation',
      'At least 10 IgG molecules are needed to overcome the activation threshold',
      'Any number of IgG — the stoichiometry depends solely on C1q concentration',
    ],
    correctIndex: 0,
    explanation: 'C1q is a hexameric molecule with 6 globular heads, each capable of binding one IgG Fc. Activation requires multivalent engagement — a minimum of 2 closely spaced IgG molecules are needed, but optimal activation occurs when IgG forms hexameric rings on the cell surface (Diebolder et al. 2014, Science). In this model, 6 IgG molecules arrange in a hexagonal platform with their Fc regions pointing upward, providing optimal geometry for all 6 C1q heads to bind simultaneously. The density of target antigen on the cell surface determines how readily these IgG clusters form, which is why CDC efficacy correlates strongly with target antigen density. This model explains why some targets with low expression are poor CDC targets despite adequate antibody binding.',
    difficulty: 'hard',
  },
  {
    id: 'q-moa-5',
    sectionId: 'moa',
    question: 'Why do TNFR superfamily agonist antibodies (e.g., anti-4-1BB, anti-OX40) require FcγR-mediated crosslinking for activity?',
    options: [
      'TNFR superfamily members signal through receptor trimerisation; bivalent IgG alone cannot achieve sufficient clustering, but FcγRIIb on neighbouring cells scaffolds multiple IgG-receptor complexes into higher-order arrays',
      'Agonist antibodies must internalise via FcγR to activate intracellular TNFR signalling domains',
      'FcγR binding converts the antibody from an antagonist to an agonist conformation',
      'Without FcγR crosslinking, agonist antibodies are rapidly cleared by the mannose receptor',
    ],
    correctIndex: 0,
    explanation: 'TNFR superfamily receptors (4-1BB/CD137, OX40/CD134, CD40, GITR) naturally signal through ligand-induced receptor trimerisation and higher-order clustering via CRD (cysteine-rich domain) pre-assembly. Bivalent IgG can only crosslink 2 receptor molecules — insufficient for productive signalling. FcγRIIb (the inhibitory Fc receptor, expressed on many immune cell types) acts as a scaffold: when FcγRIIb on a neighbouring cell binds the Fc of the agonist antibody, it effectively clusters multiple antibody-receptor complexes into supramolecular arrays. This IgG2 subclass is uniquely interesting for agonist applications because its rigid hinge allows a degree of Fc-Fc self-crosslinking without requiring trans-cellular FcγRIIb, though this remains an area of active investigation.',
    difficulty: 'expert',
  },
  {
    id: 'q-moa-6',
    sectionId: 'moa',
    question: 'What is the primary CMC challenge unique to bispecific antibodies manufactured using the knobs-into-holes approach?',
    options: [
      'Homodimer contamination (~5% knob-knob or hole-hole species) that must be separated from heterodimer and detected by native MS, HIC, or SEC-MALS',
      'Complete loss of Fc effector function due to the CH3 mutations',
      'Inability to bind Protein A, requiring alternative purification strategies',
      'Rapid aggregation during formulation due to asymmetric thermal stability',
    ],
    correctIndex: 0,
    explanation: 'KiH heterodimerisation achieves ~95% heterodimer efficiency, meaning ~5% homodimer contaminants (knob-knob and hole-hole species) co-produce. These homodimers have identical molecular weights to the heterodimer in some formats, making them analytically challenging to detect and remove. Key analytical methods include: native MS (resolves heterodimer from homodimers by mass difference if arms differ), hydrophobic interaction chromatography (HIC, exploits surface hydrophobicity differences), and SEC-MALS (if size differences exist). Process solutions include differential Protein A binding (engineering one arm to not bind Protein A), ion exchange chromatography exploiting pI differences between the two arms, and mixed-mode chromatography.',
    difficulty: 'hard',
  },
  {
    id: 'q-moa-7',
    sectionId: 'moa',
    question: 'For an anti-PD-L1 antibody, why might the Fc be engineered to abolish effector functions (e.g., using LALA mutations)?',
    options: [
      'PD-L1 is expressed on activated T cells — an effector-competent Fc would kill the very T cells needed for anti-tumour immunity via ADCC',
      'Anti-PD-L1 antibodies do not need to bind target cells, so Fc function is irrelevant',
      'LALA mutations improve binding affinity to PD-L1 by altering the Fab conformation',
      'Effector function would cause complement activation leading to systemic toxicity',
    ],
    correctIndex: 0,
    explanation: 'PD-L1 (B7-H1/CD274) is expressed not only on tumour cells but also on activated T cells, dendritic cells, and macrophages in the tumour microenvironment. An anti-PD-L1 antibody with intact effector functions would trigger ADCC and ADCP against PD-L1-expressing activated T cells, depleting the very effector cells needed for anti-tumour immunity. This is why atezolizumab (Tecentriq, anti-PD-L1) was engineered with an Fc containing N297A (aglycosylation) or LALA-type mutations to abolish FcγR binding and effector functions. In contrast, anti-PD-1 antibodies (pembrolizumab, nivolumab) use IgG4 with S228P, which naturally has low effector function. The choice of Fc engineering for checkpoint inhibitors directly depends on the expression pattern of the target.',
    difficulty: 'hard',
  },
  {
    id: 'q-moa-8',
    sectionId: 'moa',
    question: 'What is cytokine release syndrome (CRS) and why is it particularly associated with T cell-engaging bispecifics?',
    options: [
      'Massive T cell activation by CD3 crosslinking causes supraphysiological release of IL-6, TNF-α, and IFN-γ, producing systemic inflammation — mitigated by step-up dosing',
      'Bispecific antibodies directly activate complement leading to anaphylatoxin release',
      'CRS is caused by aggregated bispecific species triggering FcγR crosslinking on macrophages',
      'T cell engaging bispecifics cause tumour lysis syndrome which is misidentified as CRS',
    ],
    correctIndex: 0,
    explanation: 'T cell-engaging bispecifics (BiTEs, CD3-targeting bispecifics) polyclonally activate T cells through CD3ε crosslinking. Unlike natural T cell activation which is controlled by co-stimulatory signals and antigen-specific TCR engagement, bispecific-mediated CD3 activation occurs simultaneously across many T cells. This massive, rapid T cell activation causes supraphysiological release of pro-inflammatory cytokines: IL-6, TNF-α, IFN-γ, IL-2, IL-10. The resulting cytokine storm manifests clinically as fever, hypotension, hypoxia, and organ dysfunction (CRS). Step-up dosing protocols (starting at low doses and escalating) allow gradual T cell activation and cytokine release, reducing CRS severity. Tocilizumab (anti-IL-6R) is the standard treatment for severe CRS.',
    difficulty: 'medium',
  },

  // ═══ EFFECTOR (7 questions) ═══
  {
    id: 'q-eff-1',
    sectionId: 'effector',
    question: 'FcγRIIIa (CD16a) has a clinically significant polymorphism at position 158. What are the two alleles and their clinical impact?',
    options: [
      'V158 (high affinity, ~15% homozygous) and F158 (low affinity, ~45% homozygous) — V/V patients respond better to ADCC-dependent mAbs like rituximab (Cartron 2002)',
      'V158 (low affinity) and F158 (high affinity) — F/F patients are resistant to therapeutic antibodies',
      'R158 (activating) and H158 (inhibitory) — determines whether FcγRIIIa signals through ITAM or ITIM',
      'G158 (glycosylated) and A158 (aglycosylated) — affects FcγRIIIa surface expression levels on NK cells',
    ],
    correctIndex: 0,
    explanation: 'FcγRIIIa position 158 has two common alleles: V158 (valine, higher affinity for IgG Fc) and F158 (phenylalanine, lower affinity). Approximately 15% of Caucasians are V/V homozygous, 40% V/F heterozygous, and 45% F/F homozygous. Cartron et al. (2002, Blood) demonstrated that patients with non-Hodgkin lymphoma who were V/V homozygous had significantly better clinical responses to rituximab (anti-CD20, ADCC-dependent MoA). The V158 allele has ~5× higher affinity for IgG1 Fc, resulting in more efficient NK cell activation and ADCC. Afucosylated antibodies (e.g., obinutuzumab) partially overcome the F158 disadvantage by enhancing Fc-FcγRIIIa binding regardless of polymorphism.',
    difficulty: 'hard',
  },
  {
    id: 'q-eff-2',
    sectionId: 'effector',
    question: 'What is the molecular basis of pH-dependent FcRn binding that enables the 21-day IgG half-life?',
    options: [
      'His310 and His435 in CH2/CH3 have pKa ~6.5; at endosomal pH 6.0 they protonate (positive charge) and bind FcRn acidic patch; at blood pH 7.4 they deprotonate and release',
      'FcRn undergoes a conformational change at pH 6.0 that exposes a new IgG binding site',
      'At pH 6.0, the Fc glycan becomes protonated and mediates direct sugar-lectin contacts with FcRn',
      'Low pH causes IgG aggregation in the endosome, which concentrates Fc domains for FcRn multivalent binding',
    ],
    correctIndex: 0,
    explanation: 'The pH-dependent FcRn recycling mechanism is based on histidine residues at the Fc-FcRn interface. His310 (CH2) and His435 (CH3) have pKa values of approximately 6.5. At the acidic pH of early endosomes (~6.0), these histidines become protonated, gaining a positive charge that creates electrostatic interactions with acidic residues (Glu115, Asp130, Glu133) on the FcRn α-chain. At blood pH (7.4), histidines deprotonate and lose these electrostatic contacts, causing Fc release. I253, N434, and Y436 provide additional pH-independent hydrophobic/hydrogen bond contacts. The FcRn molecule consists of an MHC class I-like α-chain non-covalently associated with β2-microglobulin, and binds IgG in a 2:1 FcRn:IgG stoichiometry.',
    difficulty: 'hard',
  },
  {
    id: 'q-eff-3',
    sectionId: 'effector',
    question: 'Which is the only inhibitory receptor in the FcγR family, and on which cells is it primarily expressed?',
    options: [
      'FcγRIIb (CD32b) — expressed on B cells, basophils, and dendritic cells; contains an ITIM that recruits SHIP phosphatase to dampen activation',
      'FcγRIIIb (CD16b) — expressed on neutrophils; GPI-anchored with no signalling capacity',
      'FcγRI (CD64) — expressed on monocytes; its high affinity prevents excessive activation',
      'FcγRIIa (CD32a) — expressed on platelets; the H131R polymorphism determines inhibitory vs activating function',
    ],
    correctIndex: 0,
    explanation: 'FcγRIIb (CD32b) is the sole inhibitory Fc gamma receptor. It contains an ITIM (immunoreceptor tyrosine-based inhibitory motif) in its cytoplasmic tail, which upon phosphorylation recruits the SHIP (SH2 domain-containing inositol phosphatase) phosphatase. SHIP dephosphorylates PIP3, counteracting the PI3K signalling triggered by activating FcγRs. FcγRIIb is expressed on B cells (where it negatively regulates B cell activation and antibody production), basophils, mast cells, and dendritic cells. It is also relevant to agonist antibody biology — FcγRIIb on neighbouring cells serves as a scaffold for crosslinking TNFR superfamily agonist antibodies. All other FcγRs are activating: FcγRI (ITAM), FcγRIIa (ITAM), FcγRIIIa (ITAM via CD3ζ/FcεRIγ adaptors).',
    difficulty: 'medium',
  },
  {
    id: 'q-eff-4',
    sectionId: 'effector',
    question: 'Why do IgG aggregates clear faster than monomeric IgG from the circulation?',
    options: [
      'Aggregates present multiple Fc regions that crosslink activating FcγRs on macrophages, triggering phagocytic clearance that bypasses FcRn recycling',
      'Aggregates are too large to be pinocytosed into endosomes where FcRn binding occurs',
      'Aggregates expose Fab regions that are recognised as foreign by the adaptive immune system',
      'The glycans on aggregated IgG are enzymatically trimmed by blood-borne glycosidases',
    ],
    correctIndex: 0,
    explanation: 'Monomeric IgG is pinocytosed non-specifically into endothelial cells, where FcRn binding at pH 6.0 rescues it from lysosomal degradation by recycling it back to the cell surface (21-day half-life mechanism). IgG aggregates, however, present multiple Fc regions in close proximity. When these contact macrophages, they crosslink activating FcγRs (particularly FcγRI and FcγRIIa), triggering receptor-mediated phagocytosis. Once inside macrophage phagolysosomes, aggregated IgG is degraded rather than recycled. Additionally, aggregates can activate the classical complement pathway (C1q binds clustered Fc), tagging them with C3b for complement receptor-mediated clearance. This is why aggregate levels are a critical CQA — aggregates are cleared faster, reducing efficacy, and can also trigger immunogenicity through enhanced antigen presentation.',
    difficulty: 'hard',
  },
  {
    id: 'q-eff-5',
    sectionId: 'effector',
    question: 'What is the stoichiometry of IgG binding to FcRn, and which Fc domain surfaces are involved?',
    options: [
      '2:1 (two FcRn molecules bind one IgG) — FcRn contacts the CH2-CH3 junction at residues I253/H310 (CH2) and H433/N434/H435/Y436 (CH3)',
      '1:1 (one FcRn per IgG) — FcRn binds only the CH3 domain dimer interface',
      '1:2 (one FcRn binds the Fc of two different IgG molecules simultaneously)',
      '6:1 (six FcRn molecules form a hexameric ring around one IgG Fc, similar to C1q)',
    ],
    correctIndex: 0,
    explanation: 'IgG binds FcRn in a 2:1 stoichiometry — two FcRn heterodimers (each consisting of an MHC class I-like α-chain and β2-microglobulin) bind symmetrically to the two CH2-CH3 hinge regions of one IgG Fc. The binding interface spans the CH2-CH3 domain junction, involving I253 and H310 from CH2 and H433, N434, H435, and Y436 from CH3. This interface partially overlaps with the Protein A binding site (H433, H435, Y436), which is why some FcRn-enhancing mutations can affect Protein A purification. The 2:1 stoichiometry has been confirmed by analytical ultracentrifugation and X-ray crystallography (Martin et al. 2001, Molecular Cell).',
    difficulty: 'expert',
  },
  {
    id: 'q-eff-6',
    sectionId: 'effector',
    question: 'In ADCP, what is the role of the SIRPα-CD47 axis, and which therapeutic targets it?',
    options: [
      'CD47 on tumour cells sends a "don\'t eat me" signal through SIRPα on macrophages; magrolimab blocks CD47 to enhance phagocytic clearance',
      'SIRPα activates the phagocytic machinery when it binds CD47; anti-SIRPα antibodies enhance ADCP',
      'CD47 is a complement regulatory protein; blocking it activates CDC rather than ADCP',
      'The SIRPα-CD47 interaction promotes tumour cell invasion; blocking it has anti-metastatic rather than immune effects',
    ],
    correctIndex: 0,
    explanation: 'CD47 is a ubiquitously expressed transmembrane protein that acts as a "don\'t eat me" signal. When CD47 on a target cell engages SIRPα (signal regulatory protein alpha, CD172a) on macrophages, the ITIM domains of SIRPα recruit SHP-1/SHP-2 phosphatases that dephosphorylate myosin IIA, inhibiting phagocytic cup formation and engulfment. Many tumour cells upregulate CD47 to evade macrophage-mediated phagocytosis. Magrolimab (anti-CD47) and other CD47-targeting agents block this inhibitory signal, enabling macrophages to phagocytose opsonised tumour cells via their activating FcγRs (FcγRI, FcγRIIa). This works synergistically with tumour-targeting antibodies like rituximab — the anti-CD20 provides the "eat me" signal via Fc-FcγR interaction, while CD47 blockade removes the "don\'t eat me" brake.',
    difficulty: 'hard',
  },
  {
    id: 'q-eff-7',
    sectionId: 'effector',
    question: 'What is the IgG subclass ranking for CDC potency, and why?',
    options: [
      'IgG3 > IgG1 >> IgG2 > IgG4 — IgG3 has the most flexible and longest hinge allowing optimal C1q hexameric array formation, while IgG4 has very weak C1q binding',
      'IgG1 > IgG3 > IgG4 > IgG2 — based on total serum concentration',
      'IgG2 > IgG1 > IgG3 > IgG4 — IgG2 rigid hinge provides best C1q geometry',
      'All four subclasses have equal CDC potency when matched for antigen binding affinity',
    ],
    correctIndex: 0,
    explanation: 'The CDC potency ranking is IgG3 > IgG1 >> IgG2 > IgG4. IgG3 has the most potent CDC activity due to its extended 62-amino acid hinge region (vs 15 residues for IgG1), which provides exceptional flexibility for forming optimal hexameric IgG arrays on the cell surface — the geometry required for efficient C1q engagement. IgG1 is the most commonly used therapeutic subclass and has robust CDC. IgG2 has weak CDC due to its rigid, short hinge with 4 inter-chain disulfides limiting Fab arm flexibility. IgG4 has very weak to negligible CDC because of poor C1q binding. The C1q binding face on CH2 (P329/P331) is present in all subclasses, but the ability to form productive hexameric arrays differs dramatically based on hinge flexibility.',
    difficulty: 'medium',
  },

  // ═══ ENGINEERING (7 questions) ═══
  {
    id: 'q-eng-1',
    sectionId: 'engineering',
    question: 'The GASDALIE mutation set (G236A/S239D/A330L/I332E) enhances ADCC ~40-100×. What molecular contact does S239D create?',
    options: [
      'S239D introduces an aspartate that forms a new salt bridge with FcγRIIIa Lys158 (particularly in the V158 allele)',
      'S239D creates a hydrogen bond with the Asn297 glycan, stabilising the glycan-receptor interface',
      'S239D introduces a negative charge that repels FcγRIIb, reducing inhibitory signalling',
      'S239D disrupts an existing salt bridge with CH3 K409, freeing the CH2 effector face for receptor binding',
    ],
    correctIndex: 0,
    explanation: 'In the GASDALIE mutation set, each residue change creates specific new molecular contacts with FcγRIIIa: G236A adds van der Waals contacts at the lower hinge-receptor interface; S239D (Ser→Asp) introduces a negatively charged aspartate that forms a favourable electrostatic interaction (salt bridge) with Lys158 on FcγRIIIa; A330L (Ala→Leu) adds hydrophobic packing at a secondary contact site; and I332E (Ile→Glu) creates a hydrogen bond with Tyr157 on FcγRIIIa. The combined effect of these four mutations increases FcγRIIIa binding affinity ~100-fold and ADCC potency ~40-fold. The S239D-Lys158 salt bridge is particularly important for the V158 allele, where Lys158 is optimally positioned for this interaction.',
    difficulty: 'expert',
  },
  {
    id: 'q-eng-2',
    sectionId: 'engineering',
    question: 'What is the key difference between YTE (M252Y/S254T/T256E) and LS (M428L/N434S) half-life extension mutations in terms of their FcRn contacts?',
    options: [
      'YTE creates new contacts near the CH2-CH3 junction (M252/S254/T256 region), while LS modifies the CH3 domain surface (M428/N434) — both enhance pH 6.0 binding but through different binding epitope areas',
      'YTE enhances FcRn binding at pH 7.4, while LS enhances binding at pH 6.0',
      'YTE works by reducing FcRn affinity to slow release, while LS works by increasing pinocytosis rate',
      'YTE and LS target the same three FcRn contact residues but with different amino acid substitutions',
    ],
    correctIndex: 0,
    explanation: 'YTE (M252Y/S254T/T256E) and LS (M428L/N434S) enhance FcRn binding through different regions of the Fc-FcRn interface. YTE mutations are located in the CH2-CH3 junction region: M252Y creates aromatic packing with FcRn Glu130 (via β2-microglobulin), S254T adds van der Waals contacts, and T256E forms a salt bridge with FcRn His161 at pH 6.0. LS mutations are located further into CH3: M428L provides tighter hydrophobic packing in the FcRn binding pocket, and N434S creates a hydrogen bond with FcRn His166. YTE achieves ~4× half-life extension (ravulizumab: ~50 days), while LS achieves ~3× extension. Critically, both maintain pH 7.4 release — this must be verified by SPR, as "sticky" Fc variants that don\'t release at pH 7.4 paradoxically reduce half-life.',
    difficulty: 'expert',
  },
  {
    id: 'q-eng-3',
    sectionId: 'engineering',
    question: 'Which approved product uses FUT8 knockout technology (POTELLIGENT platform) for enhanced ADCC?',
    options: [
      'Mogamulizumab (Poteligeo, anti-CCR4) — produced in FUT8 knockout CHO cells by Kyowa Kirin',
      'Obinutuzumab (Gazyva, anti-CD20) — produced using GlycoMAb technology by Roche',
      'Trastuzumab emtansine (Kadcyla, anti-HER2 ADC) — produced in standard CHO cells',
      'Atezolizumab (Tecentriq, anti-PD-L1) — produced with LALA Fc mutations',
    ],
    correctIndex: 0,
    explanation: 'Mogamulizumab (Poteligeo, anti-CCR4 for cutaneous T cell lymphoma) was the first approved antibody produced using the POTELLIGENT technology platform developed by BioWa (subsidiary of Kyowa Kirin). POTELLIGENT uses CHO cells with complete FUT8 gene knockout, producing 100% afucosylated antibodies. Obinutuzumab (Gazyva) uses the different GlycoMAb platform (Roche/Glycart), which overexpresses GnTIII (MGAT3) to produce bisected, predominantly afucosylated glycans. Benralizumab (Fasenra, anti-IL-5Rα by AstraZeneca) is another approved afucosylated mAb. The choice between platforms has CMC implications: FUT8 KO produces cleaner afucosylated profiles, while GnTIII OE produces more complex bisected glycan mixtures requiring more sophisticated analytical characterisation.',
    difficulty: 'hard',
  },
  {
    id: 'q-eng-4',
    sectionId: 'engineering',
    question: 'Can YTE half-life extension be combined with afucosylation for enhanced ADCC? What is the concern?',
    options: [
      'Yes, they can be combined; the concern is that YTE may slightly reduce ADCC potency in some studies, and Met252Tyr creates a new oxidation-susceptible site that must be monitored',
      'No — YTE mutations are incompatible with afucosylated glycans because they disrupt the Asn297 glycan site',
      'Yes, but the combination reduces half-life rather than extending it due to mannose receptor recognition',
      'No — YTE mutations alter CH2 conformation making it impossible for FcγRIIIa to bind regardless of glycan status',
    ],
    correctIndex: 0,
    explanation: 'YTE mutations (M252Y/S254T/T256E) and afucosylation target different functions (half-life vs ADCC) at different sites and can be combined. However, there are two practical concerns: (1) Some studies report that YTE may modestly reduce ADCC potency (~2×), possibly due to subtle CH2 conformational effects on the FcγR binding face. This reduction is typically outweighed by the substantial half-life benefit. (2) The M252Y mutation introduces a tyrosine residue that is potentially susceptible to oxidation, creating a new CQA that must be monitored by peptide mapping. Additionally, M252Y is located near the FcRn binding site — oxidation of Tyr252 could reduce FcRn binding and negate the half-life benefit. Forced degradation studies must characterise this site.',
    difficulty: 'expert',
  },
  {
    id: 'q-eng-5',
    sectionId: 'engineering',
    question: 'What is the mechanism by which LALA (L234A/L235A) abolishes FcγR binding?',
    options: [
      'Replacing leucines with alanines removes hydrophobic side chains that pack into the FcγR lower hinge groove, eliminating critical van der Waals contacts',
      'LALA mutations destabilise CH2 domain folding, causing the FcγR binding face to become disordered',
      'Alanine substitutions create steric clashes with FcγR that actively repel receptor binding',
      'LALA mutations prevent Asn297 glycosylation, and aglycosylated Fc cannot bind FcγRs',
    ],
    correctIndex: 0,
    explanation: 'L234 and L235 are located in the lower hinge region of IgG1 and make direct hydrophobic contacts with a groove on the FcγR surface. The leucine side chains (with their branched 4-carbon aliphatic groups) pack tightly into hydrophobic pockets on FcγRI, FcγRIIa, FcγRIIb, and FcγRIIIa. Mutating both to alanine (which has only a single methyl group) drastically reduces the surface area of these hydrophobic contacts, effectively eliminating the binding energy contributed by the lower hinge-FcγR interaction. This reduces FcγR binding by >99% for all FcγRs. Importantly, LALA does NOT affect Asn297 glycosylation or Fc structure — it specifically removes the receptor contact residues. Residual C1q/CDC activity may remain because C1q binds a different face of CH2 (P329/P331), which is why LALA-PG adds P329G to abolish that interaction as well.',
    difficulty: 'medium',
  },
  {
    id: 'q-eng-6',
    sectionId: 'engineering',
    question: 'What are the DE mutations (S239D/I332E) and how do they differ from full GASDALIE in their effector function profile?',
    options: [
      'DE is a subset of GASDALIE using only 2 of 4 mutations; DE enhances ADCC ~20× with less CDC enhancement compared to full GASDALIE which enhances both ADCC ~40× and has modest CDC increase',
      'DE enhances CDC while GASDALIE enhances ADCC — they are complementary approaches',
      'DE and GASDALIE have identical functional profiles; DE is preferred only for manufacturing simplicity',
      'DE silences effector function like LALA, while GASDALIE enhances it',
    ],
    correctIndex: 0,
    explanation: 'The DE mutation set (S239D/I332E) comprises two of the four residue changes in GASDALIE (G236A/S239D/A330L/I332E). S239D creates the salt bridge with FcγRIIIa Lys158, and I332E creates the hydrogen bond with FcγRIIIa Tyr157. Together, DE achieves ~20× ADCC enhancement — less than full GASDALIE (~40-100×) because it lacks the G236A and A330L contributions. A key difference is in CDC: full GASDALIE can modestly enhance C1q binding due to the G236A change near the C1q binding face, while DE has minimal CDC effect. This makes DE preferred when enhanced ADCC without CDC is desired. The Xencor XmAb platform uses proprietary Fc modifications similar to DE principles for several clinical-stage programs.',
    difficulty: 'hard',
  },
  {
    id: 'q-eng-7',
    sectionId: 'engineering',
    question: 'Ravulizumab (ALXN1210) uses YTE mutations for half-life extension. What is its approximate half-life compared to eculizumab?',
    options: [
      '~50 days for ravulizumab vs ~11 days for eculizumab — approximately 4× extension, enabling Q8W dosing',
      '~21 days for ravulizumab vs ~7 days for eculizumab — approximately 3× extension',
      '~100 days for ravulizumab vs ~21 days for eculizumab — approximately 5× extension',
      '~30 days for both — YTE provides no measurable half-life benefit in clinical practice',
    ],
    correctIndex: 0,
    explanation: 'Ravulizumab (Ultomiris, Alexion/AstraZeneca) is an anti-C5 complement inhibitor engineered from eculizumab (Soliris) with four amino acid substitutions in the Fc region, including the YTE mutations (M252Y/S254T/T256E) for FcRn-mediated half-life extension. Eculizumab has a half-life of ~11 days requiring Q2W (every 2 weeks) IV dosing. Ravulizumab achieves ~49-50 days half-life, approximately 4× longer, enabling Q8W (every 8 weeks) dosing after a loading phase. This demonstrated the clinical feasibility of YTE-based half-life extension and was a key proof of concept for FcRn engineering. The CMC package required demonstration that the Fc mutations did not alter complement C5 binding or complement inhibitory activity.',
    difficulty: 'medium',
  },

  // ═══ CQA (6 questions) ═══
  {
    id: 'q-cqa-1',
    sectionId: 'cqa',
    question: 'In the Alt et al. 2016 risk ranking methodology for CQA classification, how is the risk score calculated?',
    options: [
      'Risk = max(Biological Activity, PK/PD, Immunogenicity, Safety impact scores) × Uncertainty factor, where impact scores range 2-20 and uncertainty 1-7',
      'Risk = sum of all impact scores × probability of occurrence, with each score on a 1-10 scale',
      'Risk = Severity × Occurrence × Detection (FMEA approach), each scored 1-10',
      'Risk = (clinical significance score + process variability score) / analytical method capability score',
    ],
    correctIndex: 0,
    explanation: 'Alt et al. (2016, Biologicals 44:291-305) proposed a structured risk ranking approach where each potential CQA is scored across four impact categories: Biological Activity (how much does the attribute affect potency, scored 2-20), PK/PD (pharmacokinetic impact, 2-20), Immunogenicity (risk of ADA induction, 2-20), and Safety (direct safety concern, 2-20). The maximum score across these four categories represents the worst-case impact. This is multiplied by an Uncertainty factor (1-7, where 1 = extensive literature evidence and 7 = no available data). The resulting risk score determines classification: High risk (>84) = CQA requiring tight specifications and release testing; Medium (28-84) = monitor and characterise; Low (<28) = non-critical attribute.',
    difficulty: 'hard',
  },
  {
    id: 'q-cqa-2',
    sectionId: 'cqa',
    question: 'Why is Met252 oxidation a critical quality attribute for FcRn-dependent pharmacokinetics?',
    options: [
      'Met252 is a direct FcRn contact residue; oxidation to Met(O)252 disrupts the hydrophobic packing at the FcRn interface, reducing binding affinity and accelerating clearance',
      'Met252 oxidation causes aggregation which bypasses FcRn recycling',
      'Oxidised Met252 triggers an immune response leading to anti-drug antibodies',
      'Met252 oxidation unfolds the CH3 domain, exposing the Protein A binding site to degradation',
    ],
    correctIndex: 0,
    explanation: 'Met252 (EU numbering) is located at the CH2-CH3 junction and makes direct hydrophobic contacts with FcRn at the binding interface. Oxidation converts the thioether side chain of methionine to methionine sulfoxide (Met(O)), which introduces a polar oxygen atom that disrupts hydrophobic packing with FcRn. SPR studies show that Met252 oxidation reduces FcRn binding affinity at pH 6.0, which impairs endosomal rescue and accelerates clearance. Notably, Met252 is also the site of the YTE "Y" mutation (M252Y) — in YTE-engineered mAbs, this vulnerability is eliminated because tyrosine replaces methionine. Met428 (the "L" site in LS: M428L) is less impactful because its side chain points partially away from the FcRn interface. Forced degradation with H₂O₂ is used to characterise Met oxidation rates.',
    difficulty: 'hard',
  },
  {
    id: 'q-cqa-3',
    sectionId: 'cqa',
    question: 'PLBL2 (phospholipase B-like 2) is a specific HCP of concern in mAb manufacturing. What is the risk?',
    options: [
      'PLBL2 co-purifies with Protein A eluate and degrades polysorbate surfactants in the formulation, leading to fatty acid particle formation and reduced shelf life',
      'PLBL2 cleaves the hinge region of IgG, generating fragments that reduce potency',
      'PLBL2 is immunogenic and co-administration with the mAb triggers severe allergic reactions',
      'PLBL2 oxidises methionine residues in the Fc, reducing FcRn binding',
    ],
    correctIndex: 0,
    explanation: 'PLBL2 (phospholipase B-like 2) is a CHO-derived host cell protein that has a strong affinity for the Protein A resin, causing it to co-purify with the antibody product through the capture step. Even at very low levels (sub-ppm), PLBL2 enzymatically hydrolyses polysorbate 20 and polysorbate 80 — the surfactants commonly used in mAb formulations to prevent aggregation at interfaces. This hydrolysis releases free fatty acids (oleic acid, palmitic acid) that are poorly soluble and form visible or subvisible particles over the product shelf life. Multiple high-profile cases of polysorbate degradation-related particles have been traced to residual PLBL2. Detection requires specific anti-PLBL2 ELISA or LC-MS/MS-based HCP identification methods, as generic HCP ELISAs may have poor coverage of this particular protein.',
    difficulty: 'expert',
  },
  {
    id: 'q-cqa-4',
    sectionId: 'cqa',
    question: 'What is the typical SEC-HPLC specification for monomer content in a therapeutic mAb, and what analytical method factors affect this measurement?',
    options: [
      '≥95% monomer at release; column (TSKgel G3000SWXL), mobile phase ionic strength and pH, and sample load can affect apparent aggregate/fragment levels through non-specific column interactions',
      '≥99.9% monomer at release; the measurement is independent of analytical conditions',
      '≥90% monomer for biosimilars, ≥99% for innovators; only column pore size matters',
      '≥80% monomer; SEC is not sensitive enough for tighter specifications',
    ],
    correctIndex: 0,
    explanation: 'The typical release specification for monomer content by SEC-HPLC is ≥95% (some products allow ≥97% or even ≥98% depending on process capability). Key analytical considerations: (1) Column choice — TSKgel G3000SWXL (Tosoh) is the industry standard for IgG, with appropriate pore size for resolving monomer (~150 kDa) from dimers (~300 kDa) and fragments. (2) Mobile phase — ionic strength (typically 100-200 mM phosphate/sulfate at pH 6.8-7.0) prevents non-specific electrostatic or hydrophobic interactions with the column matrix that can artificially retain aggregates or split the monomer peak. (3) Sample load — overloading can mask small aggregate peaks. (4) Detection — UV at 280 nm (for routine) or multi-angle light scattering (SEC-MALS, for absolute MW determination). SEC may underestimate large aggregates that are filtered out at the frit.',
    difficulty: 'medium',
  },
  {
    id: 'q-cqa-5',
    sectionId: 'cqa',
    question: 'In ICH Q10 control strategy design, what are the four tiers of control and how do they relate to CQA risk?',
    options: [
      'Tier 1: release testing (CQA specs), Tier 2: in-process controls (PAT/IPC), Tier 3: process parameter controls (CPP ranges), Tier 4: raw material controls — higher-risk CQAs require lower tiers (more direct testing)',
      'Tier 1: characterisation, Tier 2: validation, Tier 3: monitoring, Tier 4: process design — tiers are sequential development phases',
      'Tier 1: process parameters, Tier 2: in-process testing, Tier 3: release testing, Tier 4: stability — from upstream to downstream',
      'Tier 1: analytical method development, Tier 2: specification setting, Tier 3: comparability studies, Tier 4: lifecycle management',
    ],
    correctIndex: 0,
    explanation: 'ICH Q10 control strategy uses a tiered approach: Tier 1 is direct product testing (release and stability specifications for CQAs — most direct assurance of quality). Tier 2 is in-process testing and controls (PAT, real-time monitoring — provides assurance through process performance). Tier 3 is process parameter controls (CPP ranges derived from process characterisation — relies on demonstrated CPP-CQA relationships). Tier 4 is raw material controls (specifications for media, resins, buffers — indirect control through input quality). High-risk CQAs typically require Tier 1 control (release testing with specifications). As process understanding increases through QbD (ICH Q8), well-characterised CPP-CQA relationships may allow some attributes to rely on Tier 2-3 controls, enabling real-time release testing (RTRT) and reduced end-product testing.',
    difficulty: 'medium',
  },
  {
    id: 'q-cqa-6',
    sectionId: 'cqa',
    question: 'What is the minimum viral clearance target (log reduction value) that regulatory agencies expect from a mAb purification process, and what are the standard orthogonal clearance steps?',
    options: [
      '≥12-15 log₁₀ total LRV across ≥4 orthogonal steps: low-pH viral inactivation (pH 3.5, ≥30 min), Protein A chromatography, ion exchange chromatography, and 20 nm nanofiltration',
      '≥6 log₁₀ from a single virus filtration step; additional steps are optional',
      '≥20 log₁₀ total LRV using exclusively chemical inactivation methods',
      '≥4 log₁₀ per step from any 2 orthogonal methods; total LRV is additive without limit',
    ],
    correctIndex: 0,
    explanation: 'Regulatory agencies (FDA, EMA) expect a minimum of 12-15 log₁₀ total virus clearance from the purification process for CHO-derived mAbs, demonstrated using at least 4 orthogonal steps with different mechanisms of clearance. The standard platform includes: (1) Low-pH viral inactivation (pH 3.3-3.7, ≥30 minutes, ≥15°C) — inactivates enveloped viruses like MuLV (>4 LRV); (2) Protein A chromatography — partitioning-based clearance (varies, 2-4 LRV); (3) Anion exchange chromatography (typically flow-through mode) — electrostatic removal of viral particles (>4 LRV); (4) Nanofiltration through 20 nm filters (Planova/Virosart) — size-based removal of small non-enveloped viruses like MVM/MMV (>4 LRV). Model viruses include MuLV (enveloped retrovirus), Pseudorabies (enveloped herpesvirus), Reovirus (non-enveloped), and MVM/MMV (small non-enveloped parvovirus — the most challenging to clear).',
    difficulty: 'hard',
  },
];
