// src/batch-data.js — Sterile mAb batch manufacturing record simulator

export const BPR_STEPS = [
  {
    id: "step-1",
    step: 1,
    title: "Cell Bank Thaw & Recovery",
    icon: "🧊",
    color: "#38BDF8",
    phase: "Upstream",
    duration: "2–3 days",
    description: "Thaw working cell bank (WCB) vial(s) and expand in pre-production medium to generate sufficient inoculum for seed train. Critical for cell viability and mycoplasma-free status.",
    inputs: [
      { id: "wcb-vials", label: "WCB Vials Used", unit: "vials", target: "2", alert_low: "1", alert_high: "5" },
      { id: "thaw-temp", label: "Thaw Temperature", unit: "°C", target: "37", alert_low: "35", alert_high: "39" },
      { id: "recovery-medium", label: "Recovery Medium", unit: "mL", target: "50", alert_low: "40", alert_high: "60" },
    ],
    critical_params: [
      { param: "Cell Viability Post-Thaw", target: "≥70%", method: "Trypan blue exclusion or Vi-CELL", cqa_link: "Cell health — predictor of upstream performance" },
      { param: "Cell Concentration", target: "0.3–0.5 × 10⁶ cells/mL", method: "Hemocytometer / Vi-CELL", cqa_link: "Adequate seed density for expansion" },
      { param: "Mycoplasma (pre-culture)", target: "Negative", method: "PCR or Mycoalert rapid test", cqa_link: "Sterility / product quality CQA" },
    ],
    ipc_tests: [
      { test: "Cell Viability", spec: "NLT 70%", timing: "At thaw" },
      { test: "Cell Count", spec: "0.3–0.5 × 10⁶/mL", timing: "At thaw" },
      { test: "Appearance (turbidity)", spec: "Clear, no visible contamination", timing: "Day 1" },
    ],
    checkboxes: [
      "WCB vial identity verified (label, lot number)",
      "WCB temperature log reviewed (≤ -135°C continuous storage confirmed)",
      "Thaw performed in 37°C water bath with continuous gentle agitation",
      "Cells centrifuged (200×g, 5 min) to remove DMSO cryoprotectant",
      "Medium change performed; cells resuspended in fresh CD-CHO medium",
      "Bicontainment procedures followed (spill plan in place)",
      "Environmental monitoring strip placed in BSC during procedure",
    ],
  },
  {
    id: "step-2",
    step: 2,
    title: "Seed Train Expansion (N-2, N-1)",
    icon: "🌱",
    color: "#34D399",
    phase: "Upstream",
    duration: "7–10 days",
    description: "Serially expand cells through N-2 and N-1 bioreactor stages to generate production inoculum. Passage number tracking critical.",
    inputs: [
      { id: "seed-viability", label: "Seed Inoculum Viability", unit: "%", target: "95", alert_low: "90", alert_high: "100" },
      { id: "seed-density", label: "Seed Density", unit: "×10⁶/mL", target: "0.5", alert_low: "0.3", alert_high: "0.8" },
      { id: "n2-volume", label: "N-2 Vessel Volume", unit: "L", target: "2", alert_low: "1.5", alert_high: "2.5" },
    ],
    critical_params: [
      { param: "pH (N-2)", target: "7.00–7.20", method: "Inline pH probe + offline BGA", cqa_link: "Cell metabolism and glycosylation CQA" },
      { param: "dO₂ (N-2)", target: "30–50% air saturation", method: "Inline dissolved oxygen probe", cqa_link: "Cell growth and metabolic health" },
      { param: "Temperature (N-2)", target: "37.0°C ± 0.5°C", method: "Inline temperature probe", cqa_link: "Growth rate and culture performance" },
      { param: "Glucose (daily)", target: "2.0–8.0 g/L", method: "BGA (Nova BioProfile)", cqa_link: "Carbon source for metabolism" },
      { param: "Lactate (daily)", target: "NMT 4.0 g/L", method: "BGA (Nova BioProfile)", cqa_link: "Metabolic waste — indicator of culture stress" },
    ],
    ipc_tests: [
      { test: "Viability", spec: "NLT 90%", timing: "Daily" },
      { test: "Viable Cell Density", spec: "0.5–5.0 × 10⁶/mL per passage", timing: "Daily" },
      { test: "Glucose", spec: "2.0–8.0 g/L (supplement if <3 g/L)", timing: "Daily" },
      { test: "pH offline", spec: "7.00–7.20", timing: "Daily" },
      { test: "Osmolality", spec: "280–380 mOsm/kg", timing: "Every 2 days" },
    ],
    checkboxes: [
      "N-2 vessel autoclave-sterilized and integrity tested pre-fill",
      "Medium pre-warmed to 37°C prior to seeding",
      "Agitation set per BPR specification (typically 50–100 rpm for spinner)",
      "CO₂ overlay established for pH control (5% CO₂)",
      "Daily sampling via aseptic sampling valve (not dip tube breach)",
      "Offline BGA samples analyzed within 30 min of collection",
      "N-1 inoculation criteria verified before transfer",
    ],
  },
  {
    id: "step-3",
    step: 3,
    title: "Production Bioreactor (N stage)",
    icon: "🏭",
    color: "#A78BFA",
    phase: "Upstream",
    duration: "12–14 days",
    description: "Fed-batch production bioreactor. mAb synthesized and secreted into culture medium. IPC throughout culture. Titer and quality attribute monitoring.",
    inputs: [
      { id: "prod-seed-viability", label: "Inoculum Viability", unit: "%", target: "95", alert_low: "90", alert_high: "100" },
      { id: "prod-volume", label: "Bioreactor Working Volume", unit: "L", target: "200", alert_low: "180", alert_high: "220" },
      { id: "inoculation-density", label: "Inoculation Density", unit: "×10⁶ cells/mL", target: "0.5", alert_low: "0.3", alert_high: "0.7" },
    ],
    critical_params: [
      { param: "Temperature (Phase 1)", target: "37.0°C ± 0.5°C", method: "Inline probe + SCADA", cqa_link: "Growth rate; glycosylation CPP" },
      { param: "Temperature (Phase 2 shift)", target: "34.0°C ± 0.5°C", method: "Inline probe (temp shift at Day 4)", cqa_link: "Productivity and glycan profile CPP" },
      { param: "pH", target: "6.90–7.10", method: "Inline pH probe; offline BGA verification", cqa_link: "Glycosylation (sialylation, galactosylation) CPP" },
      { param: "dO₂", target: "30–40% air saturation", method: "Inline pO₂ probe", cqa_link: "Oxidation risk, metabolism CPP" },
      { param: "Glucose (feed trigger)", target: "Feed when <2 g/L", method: "Daily BGA", cqa_link: "Cell nutrition; production rate" },
      { param: "Lactate", target: "NMT 4.5 g/L", method: "Daily BGA", cqa_link: "Metabolic stress indicator" },
      { param: "Titer (Day 7, 10, harvest)", target: "≥2 g/L at harvest", method: "Protein A HPLC or A280", cqa_link: "Batch yield CQA" },
    ],
    ipc_tests: [
      { test: "Viability", spec: "NLT 85% at harvest decision", timing: "Daily" },
      { test: "VCD", spec: "Track growth curve per historical batch profile", timing: "Daily" },
      { test: "Glucose/Lactate/NH₄⁺", spec: "Per process parameters", timing: "Daily" },
      { test: "Titer (A280 or Prot-A HPLC)", spec: "Trend monitoring; harvest trigger", timing: "Day 7, 10, 12, 14" },
      { test: "pH offline (BGA)", spec: "Verify probe reading within ±0.05", timing: "Daily" },
      { test: "Osmolality", spec: "300–400 mOsm/kg", timing: "Every 2 days" },
    ],
    checkboxes: [
      "Bioreactor sterilization record reviewed and verified (SIP validated)",
      "Sparger integrity test completed (hold pressure for 30 min)",
      "All probes calibrated within 24h of inoculation (pH, pO₂, temp)",
      "Feed solutions sterile filtered (0.22 µm) and integrity tested",
      "Temperature shift authorized by QA at Day 4 per BPR",
      "Daily BGA documented in BPR within 1 hour of measurement",
      "Harvest decision criteria reviewed with QA (viability + titer)",
    ],
  },
  {
    id: "step-4",
    step: 4,
    title: "Harvest & Clarification",
    icon: "🌾",
    color: "#F59E0B",
    phase: "Downstream",
    duration: "1 day",
    description: "Centrifugation or depth filtration to remove cells and cell debris. Prepares clarified harvest for capture chromatography.",
    inputs: [
      { id: "harvest-volume", label: "Harvest Volume", unit: "L", target: "200", alert_low: "170", alert_high: "230" },
      { id: "harvest-titer", label: "Harvest Titer", unit: "g/L", target: "2.5", alert_low: "2.0", alert_high: "5.0" },
      { id: "harvest-viability", label: "Harvest Viability", unit: "%", target: "75", alert_low: "60", alert_high: "100" },
    ],
    critical_params: [
      { param: "Centrifugation Speed", target: "3,000–5,000 rpm per equipment SOP", method: "Centrifuge log", cqa_link: "Cell lysis — DNA/HCP release risk" },
      { param: "Depth Filtration Flux", target: "200–400 LMH", method: "Inline flow sensor", cqa_link: "Clarification efficiency and filter capacity" },
      { param: "Clarified Harvest Turbidity", target: "NMT 20 NTU", method: "Turbidimeter", cqa_link: "Downstream process performance CQA" },
    ],
    ipc_tests: [
      { test: "Turbidity post-clarification", spec: "NMT 20 NTU", timing: "Post-clarification" },
      { test: "Bioburden (pre-Prot-A)", spec: "NMT 10 CFU/100 mL", timing: "Post-clarification" },
      { test: "Titer (clarified harvest)", spec: "Verify against bioreactor titer", timing: "Post-clarification" },
    ],
    checkboxes: [
      "Harvest sample collected for IPC (viability, titer, bioburden) prior to centrifuge",
      "Centrifuge bowl sterilized (autoclave or CIP/SIP) per SOP",
      "Depth filter integrity test performed post-use (bubble point or water flow)",
      "Clarified harvest collected in autoclaved/gamma-irradiated bag",
      "Hold time started and logged (clarified harvest ≤ 24h hold at 2–8°C)",
      "Temperature of clarified harvest monitored during hold",
    ],
  },
  {
    id: "step-5",
    step: 5,
    title: "Protein A Capture Chromatography",
    icon: "🧲",
    color: "#F472B6",
    phase: "Downstream",
    duration: "1 day",
    description: "Highly selective affinity capture of mAb via Fc region binding to Protein A ligand (MabSelect SuRe or equivalent). Step yield typically 90–95%.",
    inputs: [
      { id: "prot-a-load-volume", label: "Load Volume", unit: "L", target: "200", alert_low: "150", alert_high: "250" },
      { id: "prot-a-load-titer", label: "Load Titer", unit: "g/L", target: "2.5", alert_low: "2.0", alert_high: "4.0" },
      { id: "prot-a-column-vol", label: "Column Volume", unit: "mL", target: "500", alert_low: "450", alert_high: "550" },
    ],
    critical_params: [
      { param: "Load: Equilibration (PBS pH 7.4)", target: "5 CV at 100–200 cm/h", method: "UV + conductivity", cqa_link: "Column conditioning for binding" },
      { param: "Load Flow Rate", target: "100–150 cm/h (residence time ≥4 min)", method: "AKTA flow meter", cqa_link: "Binding capacity utilization" },
      { param: "Wash 1 (PBS pH 7.4)", target: "5 CV until UV baseline", method: "UV 280 nm", cqa_link: "HCP removal efficiency" },
      { param: "Wash 2 (0.5M Arg, pH 4.0)", target: "3 CV", method: "UV + conductivity", cqa_link: "Reduces aggregates and impurities" },
      { param: "Elution (0.1M Acetate pH 3.5)", target: "Collect peak (UV rise to 50% post-peak)", method: "UV 280 nm + fraction collector", cqa_link: "mAb recovery and pool volume" },
      { param: "Strip (0.1M phosphoric acid)", target: "3 CV; conductivity returns to baseline", method: "Conductivity", cqa_link: "Column regeneration; HCP removal" },
    ],
    ipc_tests: [
      { test: "Step yield (A280)", spec: "NLT 85%", timing: "Post-elution" },
      { test: "HCP (ELISA)", spec: "NMT 10,000 ppm (pre-viral inactivation)", timing: "Elution pool" },
      { test: "Protein A leachate", spec: "NMT 100 ppm in eluate", timing: "Elution pool" },
      { test: "Aggregates (SEC)", spec: "NMT 5% HMW (pre-polishing)", timing: "Elution pool" },
    ],
    checkboxes: [
      "Column lifetime cycle count verified (NMT per qualification)",
      "Column packed bed evaluated (HETP and asymmetry within limits)",
      "Load volume calculated and authorized in BPR",
      "Protein A eluate pH confirmed 3.5 ± 0.1 immediately post-elution",
      "Pool volume and A280 measured; step yield calculated in real time",
      "Elution pool transferred to viral inactivation within 1h",
    ],
  },
  {
    id: "step-6",
    step: 6,
    title: "Viral Inactivation (Low pH Hold)",
    icon: "🦠",
    color: "#F87171",
    phase: "Downstream",
    duration: "1–2 hours",
    description: "Low pH incubation inactivates enveloped viruses (retrovirus, herpesvirus). ICH Q5A requirement. Critical hold: pH and time must be within validated range.",
    inputs: [
      { id: "vi-ph", label: "Inactivation pH", unit: "pH units", target: "3.5", alert_low: "3.4", alert_high: "3.6" },
      { id: "vi-temp", label: "Inactivation Temperature", unit: "°C", target: "18", alert_low: "15", alert_high: "25" },
      { id: "vi-time", label: "Hold Time", unit: "min", target: "90", alert_low: "60", alert_high: "120" },
    ],
    critical_params: [
      { param: "pH during hold", target: "3.4–3.6 (product-specific validated range)", method: "Calibrated pH probe + offline check", cqa_link: "Viral clearance efficacy — must be in validated range" },
      { param: "Temperature during hold", target: "15–25°C", method: "Calibrated temperature probe / logger", cqa_link: "Temperature affects inactivation kinetics" },
      { param: "Hold Time", target: "NLT 60 min; NMT 120 min", method: "Timer from pH confirmation", cqa_link: "Minimum time required for validated inactivation" },
    ],
    ipc_tests: [
      { test: "pH at hold initiation", spec: "3.4–3.6", timing: "Start of hold" },
      { test: "pH at hold completion", spec: "3.4–3.6", timing: "End of hold" },
      { test: "Temperature throughout hold", spec: "15–25°C", timing: "Continuous log" },
      { test: "Hold time", spec: "NLT 60 min", timing: "Verified from timed record" },
    ],
    checkboxes: [
      "pH probe calibrated with 2-point buffer calibration within 2h of use",
      "Offline pH verification performed within 5 min of hold initiation",
      "Timer started only after offline pH confirmed within spec (3.4–3.6)",
      "Temperature continuously logged (data logger attached to vessel)",
      "pH at end of hold confirmed and documented",
      "Neutralization performed with 1M Tris pH 8.0 immediately after hold",
      "Neutralized pool pH confirmed 5.0–5.5 prior to next step",
    ],
  },
  {
    id: "step-7",
    step: 7,
    title: "Polishing Chromatography (AEX + CEX)",
    icon: "✨",
    color: "#A78BFA",
    phase: "Downstream",
    duration: "1 day",
    description: "Two-step polishing: Anion exchange (AEX) in flow-through mode removes HCP, DNA, endotoxin. Cation exchange (CEX) separates charge variants. Final polished pool meets specification.",
    inputs: [
      { id: "aex-load-conc", label: "AEX Load Concentration", unit: "g/L", target: "3", alert_low: "1", alert_high: "10" },
      { id: "cex-load-conc", label: "CEX Load Concentration", unit: "g/L", target: "5", alert_low: "3", alert_high: "10" },
    ],
    critical_params: [
      { param: "AEX: pH of load (flow-through)", target: "pH 7.5–8.0 (above pI of impurities)", method: "pH meter", cqa_link: "Charge-based separation of HCP/DNA" },
      { param: "AEX: Conductivity of load", target: "NMT 10 mS/cm", method: "Conductivity meter", cqa_link: "Ionic strength affects impurity binding" },
      { param: "CEX: Salt gradient slope", target: "Per process curve; collect main peak fraction", method: "UV + conductivity trace", cqa_link: "Charge variant separation — acidic/basic species" },
      { param: "Combined HCP (post-polishing)", target: "NMT 100 ppm", method: "HCP ELISA", cqa_link: "Critical purity CQA for patient safety" },
      { param: "DNA (post-polishing)", target: "NMT 10 pg/dose", method: "qPCR or PicoGreen", cqa_link: "Critical safety CQA — residual CHO DNA" },
    ],
    ipc_tests: [
      { test: "Step yield (post-AEX)", spec: "NLT 85%", timing: "Post-AEX" },
      { test: "HCP (post-CEX)", spec: "NMT 100 ppm", timing: "Post-CEX" },
      { test: "DNA", spec: "NMT 10 pg/dose", timing: "Post-CEX" },
      { test: "Aggregates (SEC)", spec: "NMT 2% HMW", timing: "Post-CEX" },
      { test: "Charge variants (CEX or cIEF)", spec: "% main peak within process range", timing: "Post-CEX" },
    ],
    checkboxes: [
      "AEX column equilibrated (5 CV at target pH + conductivity, verified before load)",
      "AEX load diluted/adjusted to target pH and conductivity",
      "AEX flow-through fraction collected (UV ≤ 30 mAU indicates incomplete removal)",
      "CEX column equilibrated per SOP",
      "CEX gradient developed and fraction collected per timed/volume parameters",
      "Pool samples submitted to QC for HCP, DNA, aggregates",
    ],
  },
  {
    id: "step-8",
    step: 8,
    title: "Viral Filtration (20 nm filter)",
    icon: "🔎",
    color: "#60A5FA",
    phase: "Downstream",
    duration: "2–4 hours",
    description: "Size-exclusion-based removal of non-enveloped viruses using 20 nm (Planova 20N or Viresolve Pro) or 15 nm filter. ICH Q5A requirement. Filter integrity test mandatory.",
    inputs: [
      { id: "vf-pressure", label: "Filtration Pressure", unit: "psi", target: "30", alert_low: "20", alert_high: "40" },
      { id: "vf-flux", label: "Filtration Flux", unit: "LMH", target: "40", alert_low: "20", alert_high: "80" },
    ],
    critical_params: [
      { param: "Pre-use filter integrity test", target: "Diffusion or bubble point within spec", method: "Integrity tester (e.g., Sartocheck)", cqa_link: "MANDATORY — filter failure invalidates viral clearance claim" },
      { param: "Filtration pressure", target: "NMT 40 psi (per filter qualification)", method: "Inline pressure gauge", cqa_link: "Pressure limit for filter performance" },
      { param: "Post-use filter integrity test", target: "Pass (same limits as pre-use)", method: "Integrity tester", cqa_link: "Confirms filter integrity maintained throughout filtration" },
      { param: "Protein concentration in load", target: "NMT 20 g/L", method: "A280", cqa_link: "High conc can foul filter; yield and clearance impact" },
    ],
    ipc_tests: [
      { test: "Pre-use filter integrity (diffusion)", spec: "NMT X mL/min per filter spec", timing: "Before filtration" },
      { test: "Post-use filter integrity (diffusion)", spec: "NMT X mL/min (must pass)", timing: "After filtration" },
      { test: "Step yield (A280)", spec: "NLT 90%", timing: "Post-filtration" },
      { test: "Parvovirus spiking study (validation)", spec: "NLT 4 log₁₀ reduction (reference)", timing: "Process validation only" },
    ],
    checkboxes: [
      "Pre-use integrity test performed and result documented (PASS/FAIL)",
      "Filter housing assembled using aseptic technique per SOP",
      "Pressure monitored continuously; alarm set at 38 psi",
      "Filtration rate and total throughput (L/m²) within validation range",
      "Post-use integrity test performed within 2h of filtration completion",
      "Viral filtrate transferred to formulation step within 24h hold time",
    ],
  },
  {
    id: "step-9",
    step: 9,
    title: "Formulation & UF/DF",
    icon: "⚗️",
    color: "#34D399",
    phase: "Formulation",
    duration: "1 day",
    description: "Ultrafiltration/diafiltration (UF/DF) concentrates mAb to target concentration and exchanges buffer to formulation buffer (e.g., 25 mM His-HCl, 150 mM NaCl, 0.05% PS20, pH 6.0).",
    inputs: [
      { id: "form-target-conc", label: "Target Protein Concentration", unit: "mg/mL", target: "20", alert_low: "18", alert_high: "22" },
      { id: "form-buffer-vol", label: "Diafiltration Volumes", unit: "DV", target: "7", alert_low: "5", alert_high: "10" },
      { id: "form-ph", label: "Final Formulation pH", unit: "pH units", target: "6.0", alert_low: "5.8", alert_high: "6.2" },
    ],
    critical_params: [
      { param: "TMP (transmembrane pressure)", target: "5–15 psi during concentration", method: "Inline pressure gauges", cqa_link: "High TMP → shear aggregation risk" },
      { param: "Protein concentration (final)", target: "Target ± 10%", method: "A280 with ε (extinction coefficient)", cqa_link: "Dose accuracy CQA" },
      { param: "pH (final formulation)", target: "Target ± 0.2", method: "Calibrated pH meter (2-point calibration)", cqa_link: "Stability CQA; affects charge variant profile" },
      { param: "Osmolality", target: "270–330 mOsm/kg", method: "Freezing point osmometer", cqa_link: "Isotonicity for IV/SC injection" },
      { param: "Conductivity", target: "Per formulation spec (e.g., 14–18 mS/cm at 150 mM NaCl)", method: "Inline conductivity probe", cqa_link: "Monitors buffer exchange completeness" },
    ],
    ipc_tests: [
      { test: "Protein concentration (A280)", spec: "Target ± 10%", timing: "Post-UF/DF" },
      { test: "pH", spec: "Target ± 0.2", timing: "Post-formulation" },
      { test: "Osmolality", spec: "270–330 mOsm/kg", timing: "Post-formulation" },
      { test: "Conductivity", spec: "Per formulation spec", timing: "Post-UF/DF" },
      { test: "Bioburden (pre-filtration)", spec: "NMT 10 CFU/mL", timing: "Pre-sterile filtration" },
      { test: "Aggregates (SEC)", spec: "NMT 1% HMW", timing: "Post-formulation" },
    ],
    checkboxes: [
      "UF cassette flushed per SOP (3 CVs formulation buffer before load)",
      "TMP monitored throughout — reduce if >15 psi",
      "Diafiltration volumes documented (DV count); 7 DV minimum to achieve <5% residual impurities",
      "Excipient stock solution concentrations verified by independent calculation",
      "PS20 added last to prevent foaming during mixing",
      "Final protein concentration by A280 confirmed against independent check (e.g., SoloVPE)",
      "pH adjustment made with minimal 0.1M NaOH if outside target",
    ],
  },
  {
    id: "step-10",
    step: 10,
    title: "Fill / Finish",
    icon: "💉",
    color: "#FB923C",
    phase: "Fill/Finish",
    duration: "1–2 days",
    description: "Sterile filtration (0.22 µm) followed by aseptic filling into vials/syringes under ISO 5 environment. Final product IPC and release testing.",
    inputs: [
      { id: "fill-volume", label: "Target Fill Volume", unit: "mL", target: "5.0", alert_low: "4.9", alert_high: "5.1" },
      { id: "fill-vials", label: "Target Vials to Fill", unit: "vials", target: "10000", alert_low: "9000", alert_high: "11000" },
      { id: "fill-conc", label: "Protein Concentration Pre-Fill", unit: "mg/mL", target: "20", alert_low: "18", alert_high: "22" },
    ],
    critical_params: [
      { param: "Sterile filter integrity (pre-use)", target: "Bubble point or diffusion: PASS per filter spec", method: "Integrity tester (Sartocheck/Palltronic)", cqa_link: "MANDATORY sterility assurance" },
      { param: "Sterile filter integrity (post-use)", target: "PASS (same spec as pre-use)", method: "Integrity tester", cqa_link: "Confirm no breach during filtration" },
      { param: "Fill volume accuracy", target: "Target ± 2% (NMT ±5% individual)", method: "Gravimetric check (every 30 min)", cqa_link: "Dose accuracy CQA" },
      { param: "Environment monitoring (EM)", target: "ISO 5: 0 CFU/plate active air; 0 CFU/contact plate", method: "Active air sampler + settle plates", cqa_link: "Sterility assurance" },
      { param: "Container closure integrity", target: "No leakers — 100% visual inspection + vacuum test", method: "CCIT: headspace analysis or vacuum decay", cqa_link: "Sterility and product protection CQA" },
    ],
    ipc_tests: [
      { test: "Fill weight check", spec: "Target ± 2% (10 vials every 30 min)", timing: "Every 30 min during fill" },
      { test: "Visual inspection (100%)", spec: "No visible particles, cracks, incorrect fill", timing: "Post-fill, automated + manual" },
      { test: "Sterility (final product)", spec: "No growth USP <71>", timing: "End of batch" },
      { test: "Endotoxin (final product)", spec: "NMT 0.5 EU/mL (IV)", timing: "End of batch" },
      { test: "Protein concentration (final)", spec: "90–110% label claim", timing: "End of batch" },
      { test: "Subvisible particles (USP <787>)", spec: "≤6000 @ ≥10µm; ≤600 @ ≥25µm per container", timing: "End of batch" },
    ],
    checkboxes: [
      "Pre-use filter integrity test PASSED and documented",
      "ISO 5 environment qualification current (within 6-month requalification interval)",
      "Filling machine CIP/SIP cycle completed and documented",
      "Operator gowning qualification current (within 12-month interval)",
      "First article fill volume check and acceptance prior to production fill",
      "Stopper and vial depyrogenation records reviewed",
      "Post-use filter integrity test PASSED and documented",
      "Environmental monitoring samples labeled and submitted to micro lab",
    ],
  },
];

export const DEVIATION_SCENARIOS = [
  {
    id: "dev-1",
    step: 3,
    trigger: "pH excursion at production bioreactor",
    severity: "critical",
    description: "pH drops to 6.75 during Day 6 of production bioreactor (target 6.90–7.10). CO₂ overlay control system alarm.",
    guidance: "IMMEDIATE: Alert BPR responsible and QA. Document time of excursion. Investigate: gas controller failure? Elevated lactate (metabolic acidosis)? Check offline BGA. Correct pH with Na₂CO₃ addition per SOP or controller set-point adjustment. Document correction and resume. Assess impact: pH < 6.8 can affect glycosylation — stability samples may be needed.",
    required_actions: ["Document in BPR and deviation log", "QA notification within 1h", "Offline BGA to confirm probe", "Root cause investigation", "Assess impact on glycosylation CQA"],
    icon: "⚠️",
    color: "#F59E0B",
  },
  {
    id: "dev-2",
    step: 5,
    trigger: "Low Protein A step yield",
    severity: "major",
    description: "Protein A eluate step yield calculated at 78% (spec NLT 85%). Pool volume is within range but A280-based titer lower than expected.",
    guidance: "Hold pool. Check: load calculation error? Incorrect column volume? Dead volume in tubing accounted? A280 extinction coefficient correct? Reassay pool by alternative method (e.g., Protein A HPLC). Check flowthrough fraction for breakthrough. Assess column lot history. Document and notify QA.",
    required_actions: ["Pool held, do not proceed to next step", "QA notification", "Investigate load calculation and A280 assay", "Retest pool by HPLC", "Formal deviation report"],
    icon: "🚨",
    color: "#F472B6",
  },
  {
    id: "dev-3",
    step: 6,
    trigger: "pH excursion during viral inactivation hold",
    severity: "critical",
    description: "pH rises to 3.8 at 30 minutes into the inactivation hold (pH spec 3.4–3.6). Likely cause: inadequate acid addition or probe drift.",
    guidance: "CRITICAL: Stop timer immediately. pH must remain within 3.4–3.6 for the ENTIRE hold period. This deviation invalidates the viral inactivation step. Do NOT complete hold at out-of-spec pH. Notify QA immediately. The batch may require a validated re-run of viral inactivation or formal rejection if re-inactivation not feasible. pH probe recalibrate and re-check offline.",
    required_actions: ["Stop inactivation timer", "QA immediate notification (same day)", "Offline pH verification", "Formal deviation — critical/potential batch rejection", "Regulatory impact assessment per ICH Q5A"],
    icon: "🚨",
    color: "#F87171",
  },
  {
    id: "dev-4",
    step: 8,
    trigger: "Viral filter post-use integrity test failure",
    severity: "critical",
    description: "Post-use diffusion test value exceeds limit (12.5 mL/min vs. limit of 10 mL/min per filter qualification). Pre-use test passed.",
    guidance: "CRITICAL: Viral filtration step is INVALID for this batch. Viral clearance claim cannot be made for this batch if filter integrity cannot be confirmed. Immediately quarantine filtrate. Notify QA and regulatory affairs. Options: perform second viral filtration with new qualified filter (if process validation covers re-filtration). Otherwise batch may require rejection. Do NOT release product without valid viral clearance claim.",
    required_actions: ["Quarantine filtrate immediately", "Do not proceed to formulation", "QA and Regulatory notification", "Assess feasibility of re-filtration per process validation", "Formal deviation with potential batch rejection"],
    icon: "🚨",
    color: "#F87171",
  },
  {
    id: "dev-5",
    step: 10,
    trigger: "Fill weight out of specification",
    severity: "major",
    description: "Gravimetric check at 90 minutes shows 3 of 10 test vials with fill weight >target +5% (overfill). Previous check (60 min) was acceptable.",
    guidance: "STOP FILL LINE immediately. Quarantine vials since last passing check (60–90 min fill). Investigate: peristaltic pump tube stretch? Viscosity change in product? Investigate and correct. Resume filling only after corrective action verified by 2 consecutive passing checks. Quarantined vials to be 100% weighed and evaluated — overfilled vials may be relabeled if within approved overfill range, otherwise reject.",
    required_actions: ["Stop fill line", "Quarantine vials (60–90 min production)", "Document in BPR", "Root cause investigation", "Corrective action and verification before restart", "QA review of quarantined vials"],
    icon: "⚠️",
    color: "#F59E0B",
  },
  {
    id: "dev-6",
    step: 3,
    trigger: "Contamination alert (turbidity) in bioreactor",
    severity: "critical",
    description: "Day 8 bioreactor sample shows abnormal turbidity (culture appears pale pink instead of yellow). pH dropped rapidly. Potential microbial contamination.",
    guidance: "IMMEDIATE: Do not sample further (aerosol risk). Notify BSL-2 safety officer and QA. Quarantine bioreactor vessel. Take confirmatory sample using closed sampling valve only. Culture submitted for bioburden and identification. If contamination confirmed: bioreactor contents must be inactivated (autoclave or NaOH treatment per inactivation SOP) before disposal. Full investigation: environmental monitoring review, media sterilization records, sparger/probe insertion points.",
    required_actions: ["Stop all sampling", "BSL-2 safety officer notification", "QA notification within 1h", "Confirmatory closed-system sample", "Prepare for bioreactor inactivation if confirmed", "Environmental monitoring review"],
    icon: "☣️",
    color: "#F87171",
  },
  {
    id: "dev-7",
    step: 7,
    trigger: "High HCP post-polishing chromatography",
    severity: "major",
    description: "HCP result post-CEX polishing: 350 ppm (specification NMT 100 ppm). Process target typically <50 ppm. Two consecutive polishing steps did not achieve spec.",
    guidance: "Hold pool. Do not proceed to viral filtration. Investigate: AEX load pH/conductivity within spec? CEX gradient optimized? Review column performance (HETP, asymmetry). Can perform a re-run of AEX step (if hold time not exceeded) with adjusted conditions. Notify QA. If re-polishing not feasible, consider batch rejection. Document HCP lot-specific ELISA kit validation (matrix effects).",
    required_actions: ["Hold pool — do not proceed", "Review AEX/CEX process conditions from batch record", "QA notification", "Assess feasibility of re-polishing", "Formal deviation with batch quality impact assessment"],
    icon: "⚠️",
    color: "#F472B6",
  },
  {
    id: "dev-8",
    step: 9,
    trigger: "pH out of spec in final formulation",
    severity: "major",
    description: "Final formulation pH measures 5.5 (specification 5.8–6.2). pH is 0.3 units below lower limit. Target was 6.0.",
    guidance: "Do not proceed to fill. Investigate: buffer stock preparation error? Wrong formulation buffer lot? pH probe calibration? Confirm offline with second pH meter. If confirmed OOS: attempt pH adjustment with pre-calculated volume of 0.1M NaOH. Re-measure after mixing (minimum 15 min equilibration). If corrected to spec, document in BPR with QA approval. If not correctable: formal OOS, batch hold. Investigate buffer stock concentration.",
    required_actions: ["Do not proceed to sterile filtration/fill", "Confirm pH with second calibrated meter", "QA notification", "Attempt pH adjustment per SOP if QA approved", "Document all measurements and corrections in BPR"],
    icon: "⚠️",
    color: "#F59E0B",
  },
];

export const YIELD_STAGES = [
  { step: "Clarified Harvest", expected_yield: 100, typical_loss: 5 },
  { step: "Protein A Capture", expected_yield: 92, typical_loss: 8 },
  { step: "Viral Inactivation", expected_yield: 99, typical_loss: 1 },
  { step: "AEX Polishing", expected_yield: 88, typical_loss: 12 },
  { step: "CEX Polishing", expected_yield: 85, typical_loss: 15 },
  { step: "Viral Filtration", expected_yield: 93, typical_loss: 7 },
  { step: "UF/DF Formulation", expected_yield: 90, typical_loss: 10 },
  { step: "Fill/Finish", expected_yield: 95, typical_loss: 5 },
];
