/* ════════════════════════════════════════════════════════════ */
/*  CMC Master — Career & Interview Data                       */
/* ════════════════════════════════════════════════════════════ */

export const CAREER_PATHS = [
  {
    id:"ra", title:"Research Associate / Associate Scientist",
    levelNum:1, level:"Entry Level", icon:"🌱", color:"#22D3EE",
    years:"0–3 years",
    salary:{ us:"$60k–$80k", bay:"$72k–$92k", remote:"$58k–$78k" },
    degree:"BS/MS Chemistry, Biochemistry, Pharmaceutical Sciences, Biology",
    responsibilities:[
      "Run analytical assays (SEC-HPLC, CE-SDS, A280, ELISA) under supervision following validated SOPs",
      "Maintain lab notebooks and generate electronic data records per GMP requirements",
      "Prepare reagents, buffers, reference standards, and stability samples",
      "Assist in method development experiments and document troubleshooting steps",
      "Participate in deviation investigations with basic root cause identification",
      "Support tech transfer by executing transferred methods and generating comparison data",
      "Perform routine instrument qualification (IQ/OQ/PQ) checks and calibrations",
    ],
    technicalSkills:["HPLC/UPLC operation and maintenance","Protein biochemistry (SDS-PAGE, Western blot)","GMP documentation (lab notebooks, deviation reports)","Microsoft Excel data analysis","Basic statistical calculations (mean, SD, %CV)","Aseptic technique and sterility awareness"],
    softSkills:["Attention to detail and data integrity","Following complex SOPs precisely","Clear communication of experimental results","Team collaboration in a GMP environment"],
    companies:["Large pharma (Pfizer, Roche, AstraZeneca, J&J)","Mid-size biotech (Biogen, Regeneron, Alexion)","CROs (Charles River, Eurofins BioPharma, BioAgilytix)","CDMOs (Lonza, Samsung Biologics, WuXi Biologics)"],
    nextRole:"sci1",
    interviewTip:"Focus on hands-on lab experience. Be ready to explain the principle of 2–3 analytical methods you've run personally. Demonstrate GMP awareness — mention documentation habits, deviation handling. Show enthusiasm for learning.",
  },
  {
    id:"sci1", title:"Scientist I / Analytical Scientist",
    levelNum:2, level:"Junior Professional", icon:"🔬", color:"#34D399",
    years:"2–5 years",
    salary:{ us:"$80k–$105k", bay:"$90k–$120k", remote:"$78k–$100k" },
    degree:"BS+3 years or MS in Analytical Chemistry, Biochemistry, Pharmaceutical Sciences",
    responsibilities:[
      "Independently execute and troubleshoot QC release and stability assays for clinical material",
      "Author and execute analytical method development protocols, summarize results in scientific reports",
      "Draft method validation protocols and reports per ICH Q2(R1) for inclusion in regulatory submissions",
      "Execute forced degradation (stress) studies and interpret degradation pathways",
      "Contribute to CMC sections of IND amendments (3.2.S.4, 3.2.P.5) with analytical data",
      "Assist in reference standard qualification experiments and documentation",
      "Support tech transfer activities: execute methods at CRO/QC sites, generate transfer reports",
      "Write and revise analytical method SOPs; train junior scientists",
    ],
    technicalSkills:["HPLC/CE method development (column, gradient, buffer screening)","CE-SDS and icIEF hands-on proficiency","ICH Q2(R1) method validation (specificity, linearity, accuracy, precision, LOD/LOQ)","Empower 3 / Chromeleon data systems","JMP or Minitab for statistical analysis","Basic cell-based assay execution"],
    softSkills:["Clear scientific writing (protocols, reports, SOPs)","Problem-solving approach to assay failures","Effective time management across multiple projects","Building positive relationships cross-functionally (CMC, QC, Regulatory)"],
    companies:["Innovative biotech (Genentech, Amgen, Moderna)","Mid-pharma (Seagen, Incyte, Sarepta)","Analytical CROs (Pacific BioLabs, BioAgilytix)"],
    nextRole:"sci2",
    interviewTip:"Walk through a full method validation you personally executed — know the ICH Q2 acceptance criteria cold. Discuss a real troubleshooting example with data. Show you can write, not just pipette.",
  },
  {
    id:"sci2", title:"Scientist II / Senior Scientist",
    levelNum:3, level:"Mid-Level Professional", icon:"⚗️", color:"#F59E0B",
    years:"5–10 years",
    salary:{ us:"$100k–$140k", bay:"$118k–$162k", remote:"$95k–$132k" },
    degree:"MS or PhD preferred in Pharmaceutical Sciences, Analytical Chemistry, Biochemistry, Biology",
    responsibilities:[
      "Lead analytical method development and validation programs for multiple programs simultaneously",
      "Author complete CMC sections for IND/BLA submissions (3.2.S.3, 3.2.S.4, 3.2.P.5)",
      "Own control strategy development: CQA identification, specification setting, justification strategy",
      "Manage external CRO/CDMO analytical vendors — SOW, timeline, quality oversight",
      "Lead comparability studies for process changes: design, execution, interpretation, reporting",
      "Design and interpret long-term stability studies; author stability summaries for submission",
      "Interface directly with FDA/EMA in pre-submission meetings (analytical discussions)",
      "Mentor 2–4 junior scientists; lead hiring for the analytical team",
    ],
    technicalSkills:["Full ICH Q2 method validation authoring and regulatory defense","Bioassay development and validation (4PL, parallelism, USP <1032>/<1033>)","Regulatory CMC writing (IND, BLA sections)","Statistical process control (SPC), specification setting from process data","Comparability study design (analytical + PK bridge)","HOS techniques (CD, DSC, DLS, SEC-MALS, HDX-MS)","GMP audit support and CAPA ownership"],
    softSkills:["Scientific leadership without direct authority","Stakeholder management (CMC, QA, Regulatory, Clinical)","Strategic thinking: CMC decision-making at a program level","Clear and concise presentation of complex data to non-experts","Project management basics (Gantt, milestone tracking, risk identification)"],
    companies:["Top biotech (Regeneron, BioNTech, Vertex, Alnylam)","Global pharma (Roche/Genentech, AZ, Lilly, Pfizer)","Regulatory consulting (Halloran, Biologics Consulting Group)"],
    nextRole:"ad",
    interviewTip:"Present a control strategy or specification justification you built. Explain how you've navigated regulatory feedback. Show strategic thinking — not just tactical execution. Mention leadership of junior scientists.",
  },
  {
    id:"ad", title:"Associate Director / Director, CMC",
    levelNum:4, level:"Senior Leader", icon:"🎯", color:"#F472B6",
    years:"10–18 years",
    salary:{ us:"$148k–$200k", bay:"$170k–$230k", remote:"$142k–$195k" },
    degree:"PhD preferred; exceptional MS with track record of BLA/NDA contributions",
    responsibilities:[
      "Own end-to-end CMC strategy for 1–3 programs from IND through BLA/MAA submission",
      "Lead and develop cross-functional CMC teams (Analytical, Formulation, Manufacturing, Process Dev)",
      "Present CMC strategy and risk landscape to Executive Leadership and Board of Directors",
      "Serve as primary company contact in FDA/EMA Type A/B meetings for CMC topics",
      "Govern CMC Stage Gate decisions (IND-enabling, EOP2, Pre-BLA readiness reviews)",
      "Manage departmental budget ($5M–$25M); allocate resources across programs",
      "Oversee PPQ strategy and execution at commercial scale manufacturing sites",
      "Build and manage strategic CDMO/CRO partnerships at senior relationship level",
    ],
    technicalSkills:["BLA/NDA submission experience end-to-end (author → filed)","Pre-Approval Inspection (PAI) management and preparation","Process validation strategy (PPQ, CPV)","ICH Q8/Q9/Q10/Q11/Q12 expert-level mastery","Regulatory intelligence (FDA, EMA, PMDA policy landscape)","Multi-modality experience: mAbs, ADCs, bispecifics, or cell/gene therapy"],
    softSkills:["Executive presence and board-level communication","Influencing without authority across organizational silos","Talent development (hiring, performance management, succession planning)","Risk management: identify, quantify, and mitigate CMC risks to program","Strategic portfolio thinking — not just single-program focus"],
    companies:["Well-funded biotech (Series B–D, IPO-stage)","Big pharma VP/AD layer (Pfizer, Roche, Lilly, J&J)","Gene/cell therapy companies (Sarepta, bluebird bio, Novartis Gene Therapies)"],
    nextRole:"vp",
    interviewTip:"Lead with leadership stories, not just technical accomplishments. Be prepared to discuss a CMC crisis you navigated — a stability failure, a CRL, a manufacturing deviation. Show fiscal accountability and organizational thinking.",
  },
  {
    id:"vp", title:"Vice President / SVP, CMC & Technical Operations",
    levelNum:5, level:"Executive", icon:"🏆", color:"#A78BFA",
    years:"18–25+ years",
    salary:{ us:"$250k–$400k+", bay:"$290k–$460k+", remote:"$235k–$380k+" },
    degree:"PhD strongly preferred; rare MS with 25+ years and proven VP-level delivery",
    responsibilities:[
      "Set enterprise-wide CMC strategy and vision aligned with corporate pipeline goals",
      "Own CMC quality and regulatory risk for the entire pipeline portfolio",
      "Build and lead organizations of 50–300+ scientists across sites/functions",
      "Serve on Executive Leadership Team (ELT); report directly to CSO or CEO",
      "Drive Board-level reporting on CMC milestones, regulatory outcomes, and supply risk",
      "Represent company at FDA Advisory Committees, critical FDA meetings, investor days",
      "Lead CMC due diligence for M&A, licensing, and partnership activities",
      "Define manufacturing network strategy (internal vs. CDMO, sites, capacity)",
    ],
    technicalSkills:["Portfolio-level CMC lifecycle management","Multi-modality depth (small molecules, biologics, cell/gene therapy, RNA)","Global regulatory affairs (FDA, EMA, PMDA, ANVISA, NMPA)","Manufacturing network strategy and supply chain risk","Organizational design and change management"],
    softSkills:["C-suite leadership and communication","Board-level credibility on complex technical topics","Organizational culture building and retention","Crisis leadership under regulatory or supply pressure","External representation (FDA, investors, partners, media)"],
    companies:["Public biotech CEOs and CSOs","Big pharma ELT (SVP R&D, EVP Technical Operations)","CMC consulting partners (senior advisors, board members)"],
    nextRole:null,
    interviewTip:"Interviews at VP level are strategic conversations, not technical Q&As. Prepare 3–4 big leadership narratives: building an organization, overcoming a CMC crisis, presenting at FDA, navigating a BLA approval. Show enterprise thinking.",
  },
];

export const INTERVIEW_QUESTIONS = [
  // ── ANALYTICAL ──────────────────────────────────────────────
  {
    id:"iq1", category:"Analytical Methods", level:"Entry", icon:"🔬", color:"#22D3EE",
    question:"Explain the difference between a specification assay and a characterization assay for a monoclonal antibody.",
    answer:"A specification (release/stability) assay is included in the drug substance or drug product specification — it must be validated per ICH Q2(R1) and has defined acceptance criteria applied to every lot. Examples: SEC-HPLC (monomer purity ≥97%), CE-SDS NR (main peak ≥97%), potency (70–130% relative activity), endotoxin (<0.5 EU/mL), sterility (pass/fail). A characterization assay is used for extended structural and functional characterization — typically not applied to every lot. Examples: peptide mapping (every batch during characterization; annual lot confirmatory), intact mass, DSC, HDX-MS, NMR, SPR kinetics. ICH Q6B §3 defines characterization requirements; the line between the two can shift as programs mature — SEC starts as characterization and becomes release.",
    followUps:["What ICH guideline defines specifications for biologics?","How do you decide when to elevate a characterization assay to a specification?"],
    linkedMethods:["am-sec","am-peptide-map","am-dsc"],
    linkedICH:["q6b","q2r1"],
  },
  {
    id:"iq2", category:"Analytical Methods", level:"Mid-Level", icon:"🔬", color:"#22D3EE",
    question:"Your icIEF profile shows a new acidic peak at Month 3 stability that wasn't present at T0. Walk me through the investigation.",
    answer:"Step 1: Confirm it's real — repeat the icIEF on the same sample and a fresh aliquot, check instrument performance (pI markers). Step 2: Characterize the peak — preparative IEF fraction collection followed by peptide mapping (LC-MS/MS) to identify deamidation (N→D: +1 Da shift, N→isoAsp route). Confirm with parallel CEX-HPLC. Step 3: Determine kinetics — plot %acidic vs. time at multiple temperatures (5°C long-term, 25°C accelerated, 37°C forced). Is it progressive or plateauing? Step 4: Identify site — specific Asn residues in CDR loop are high risk for potency impact vs. Fc deamidation (less critical). Correlate with potency data. Step 5: Regulatory implication — if >5% change from T0 in the main isoform or >2% absolute increase in acidic species AND located in CDR → potential CQA elevation. May require spec update with ICH Q5C justification and updated control strategy.",
    followUps:["How do you correlate icIEF data to peptide mapping deamidation results?","What %acidic increase would prompt a formulation change?"],
    linkedMethods:["am-cief","am-peptide-map","am-iex"],
    linkedICH:["q5c","q6b"],
  },
  {
    id:"iq3", category:"Analytical Methods", level:"Senior", icon:"🔬", color:"#22D3EE",
    question:"Design a complete analytical control strategy for a Phase 3 mAb program going to BLA.",
    answer:"Start with a formal CQA risk assessment (ICH Q9 FMEA): score each quality attribute on Severity (patient risk if OOS), Occurrence (probability of failing), and Detectability. Classify as Critical, Key, or Non-Critical. Release spec (3.2.S.4.1): Appearance (visual), Identity (cIEF class identification or CE-SDS MW), Purity (SEC-HPLC ≥97%; CE-SDS NR ≥97%; reduced HC+LC), Potency (cell-based bioassay 70–130%), Concentration (A280 ±10%), pH (±0.3), Osmolality, Endotoxin (<0.5 EU/mL), Sterility, Particulates (USP <787>/<788>), Container Closure Integrity. Stability-indicating assays: SEC (aggregation trend), icIEF/IEX (charge variants — deamidation), potency (activity retention), RP-HPLC oxidation (Met, Trp), PE-HPLC glycan (for ADCC-dependent mAb). Spec setting: use Phase 3 PPQ batch data, Cpk ≥1.33 where possible, safety margin from nonclinical, clinical lots tolerance. All methods validated per ICH Q2(R1). Document strategy in 3.2.S.3.1 (CQA listing) and 3.2.S.4.5 (spec justification).",
    followUps:["How do you statistically justify an acceptance criterion using batch data?","What is the difference between a release spec and an end-of-shelf-life spec?"],
    linkedMethods:["am-sec","am-cief","am-ce-sds","am-cell-bioassay","am-a280","am-endotoxin"],
    linkedICH:["q6b","q9","q2r1"],
  },
  // ── FORMULATION ─────────────────────────────────────────────
  {
    id:"iq4", category:"Formulation Development", level:"Entry", icon:"💊", color:"#34D399",
    question:"What are the key excipients in a typical mAb liquid formulation and what is the function of each?",
    answer:"(1) Buffer (histidine pH 5.5–6.5, citrate pH 4.5–6, phosphate pH 6–8 at 10–25 mM): controls pH to minimize chemical degradation; histidine is preferred because it also acts as a cryoprotectant and antioxidant. (2) Tonicity agent (sucrose or sorbitol 5–10%, or NaCl 140 mM): achieves isotonicity (270–330 mOsm) to prevent osmotic stress during IV infusion. (3) Surfactant (polysorbate 80 or PS-20 at 0.01–0.05%): prevents surface-induced aggregation at air-liquid interface (agitation, shaking, freeze-thaw), adsorption to syringes and vials. (4) Cryoprotectant (sucrose or trehalose 5–10% for frozen/lyophilized): replaces water at protein surface during freezing, preventing freeze-induced aggregation via water substitution hypothesis. (5) Optional: methionine (0.1–1 mM) as antioxidant for Met/Trp oxidation; EDTA (0.01–0.1 mM) as metal chelator; arginine for viscosity reduction of high-concentration formulations.",
    followUps:["Why is histidine preferred over phosphate for mAb formulations?","How does polysorbate 80 prevent aggregation during freeze-thaw?"],
    linkedICH:["q8r2"],
  },
  {
    id:"iq5", category:"Formulation Development", level:"Mid-Level", icon:"💊", color:"#34D399",
    question:"Design a formulation screening DoE to address aggregation in a mAb that forms HMW species after 1 month at 5°C.",
    answer:"Phase 1 (Characterization): SEC-HPLC to quantify %HMW, DLS for size and PDI, nanoDSF for Tm and aggregation onset temperature (Tagg), MFI for subvisible particles. pH-Tm correlation (nanoDSF screen, pH 4.5–7.5 in 0.5 pH steps). Phase 2 (High-throughput screen, HTS): Screen 96 formulations using Optim2 (dynamic light scattering + fluorescence): 5 pH levels × 3 buffer systems × 4 excipient combinations. Score by Tm, Tagg, and colloidal stability (kD from DLS). Phase 3 (Rational DoE): Face-centered Central Composite Design (CCD): 3 factors (pH, sucrose %, PS-80 %), 3 levels each = 17–20 runs. Stress conditions: 40°C × 2 weeks (accelerated), 5 freeze-thaw cycles, agitation (200 rpm, 24h, 30 mL vial). Responses: %HMW (SEC), Tm shift (DSC), Z-average (DLS), MFI particle count. Statistical analysis in JMP: response surface models, optimize for minimum %HMW and maximum Tm. Confirm lead formulation with 3-month real-time stability at 5°C and 3-month accelerated at 25°C.",
    followUps:["What is the water substitution hypothesis for cryoprotectants?","When would you choose lyophilization over a liquid formulation?"],
    linkedICH:["q8r2"],
  },
  // ── PROCESS DEVELOPMENT ─────────────────────────────────────
  {
    id:"iq6", category:"Process Development", level:"Entry", icon:"🏭", color:"#F59E0B",
    question:"What is Protein A chromatography and why is it used as the capture step in mAb purification?",
    answer:"Protein A is a surface protein from Staphylococcus aureus that binds specifically to the Fc region of IgG antibodies through their CH2-CH3 interface with very high affinity (KD ~10⁻⁸ M). It's used as the first capture step because: (1) Extraordinary selectivity — takes the antibody from 1–5 g/L in complex cell culture supernatant (containing thousands of host cell proteins, DNA, media components) and produces >95% pure IgG in a single step; (2) High yield — typical recovery 97–99%; (3) Enables integrated viral inactivation — elution at low pH (pH 3.0–3.5) is immediately followed by a low pH hold (pH 3.5–3.7, 37°C, 60 min) which inactivates enveloped viruses (e.g., retroviruses). The paired capture + viral inactivation provides >4-log reduction value (LRV). Limitations: high resin cost ($1,000–$2,500/L), resin lifetime validation (typically 100–200 cycles), leached Protein A (trace quantities that must be cleared and monitored).",
    followUps:["What is the mechanism of low pH viral inactivation?","How do you validate resin lifetime?"],
    linkedICH:["q5c"],
  },
  {
    id:"iq7", category:"Process Development", level:"Mid-Level", icon:"🏭", color:"#F59E0B",
    question:"You are scaling a mAb process from 200L to 2000L for Phase 3. What are the key CMC considerations?",
    answer:"Scale-up must demonstrate equivalence across the full manufacturing train: (1) Upstream: maintain kLa (oxygen transfer coefficient) by matching agitation + sparging strategy; manage dissolved CO₂ accumulation (higher at scale, affects pH and glycosylation); confirm bioreactor mixing time within limits; run 2–3 engineering runs at 2000L before PPQ; (2) Downstream: scale columns by cross-sectional area while maintaining linear velocity and residence time; scale UF/DF by membrane area (same protein load per area); validate hold times at full scale; (3) Comparability: side-by-side analytics of 200L vs. 2000L batches — full characterization (SEC, CE-SDS, icIEF, glycan, potency, HOS, peptide map). Biological and physicochemical comparability must be established; (4) Viral clearance: if process changed, must maintain demonstrated clearance or re-validate affected steps; (5) Regulatory: scale change mid-Phase 3 requires IND CBE-30 or prior approval (align strategy at EOP2 meeting); (6) PPQ: ≥3 commercial-scale batches, all within specification, demonstrate Cpk ≥1.33 for critical parameters.",
    followUps:["What is a scale-down model and how is it qualified?","How do you handle a comparability failure between scales?"],
    linkedICH:["q11"],
  },
  // ── REGULATORY CMC ──────────────────────────────────────────
  {
    id:"iq8", category:"Regulatory CMC", level:"Mid-Level", icon:"📋", color:"#F472B6",
    question:"What is the difference between a Prior Approval Supplement, CBE-30, and Annual Report for post-approval changes?",
    answer:"These are the three tiers of FDA post-approval change reporting under 21 CFR 601.12 for biologics: (1) Prior Approval Supplement (PAS / Major Change): requires FDA review and approval BEFORE implementing. Typical examples: new manufacturing site, new formulation, change in drug substance manufacturer, extension of shelf-life beyond current approval. Review time ~6–12 months; (2) Changes Being Effected in 30 Days (CBE-30 / Moderate): must notify FDA ≥30 days before implementing. FDA can object within 30 days. Examples: minor process parameter adjustment within validation range, change from one equivalent filter supplier to another, analytical method improvement with bridging data; (3) Annual Report (Minor Change): document in the Annual Report filed within 60 days of BLA anniversary. Examples: minor SOP revision, replacement of equivalent equipment, editorial label corrections. ICH Q12 (Lifecycle Management) modernizes this: Established Conditions (ECs) define what triggers regulatory action; PACMPs pre-agree the reporting category for expected future changes.",
    followUps:["What is an Established Condition (EC) per ICH Q12?","When does a comparability study trigger a PAS vs. CBE-30?"],
    linkedICH:["q12"],
  },
  {
    id:"iq9", category:"Regulatory CMC", level:"Senior", icon:"📋", color:"#F472B6",
    question:"You receive an FDA Complete Response Letter (CRL) with a CMC deficiency about inadequate viral clearance. How do you respond?",
    answer:"(1) Immediate: read carefully to understand exactly what FDA is requesting — additional LRV data? Use of a specific relevant virus? Robustness demonstration? Calculation clarification? Engage regulatory counsel. (2) Assessment: review existing viral clearance reports — is the data actually there but poorly presented? Is a specific study genuinely missing? Did FDA miscalculate LRV? (3) Meet with FDA: request Type A meeting (urgent, ≤30 day response) if the deficiency is ambiguous or factually incorrect. Use the meeting to align on exactly what study would satisfy the request. (4) Commission studies if needed: qualified virus test labs (BioReliance, ViruSure, Cytovance) take 8–16 weeks; build into resubmission timeline. (5) Resubmission: Class 1 resubmission (complete response, no clinical data needed) — FDA has 6-month PDUFA goal. Prepare 3.2.S.2.5 section update with full viral clearance data, model virus selection justification (ICH Q5A), and clearance calculation summary table. (6) Supply impact: assess inventory bridge from approval; engage manufacturing and commercial teams on contingency.",
    followUps:["What is the ICH Q5A framework for viral safety of biological products?","What are the four standard viral clearance steps for CHO-derived mAbs?"],
    linkedICH:["q5c"],
  },
  // ── QbD / ICH ───────────────────────────────────────────────
  {
    id:"iq10", category:"QbD & ICH", level:"Mid-Level", icon:"🎯", color:"#A78BFA",
    question:"Explain CQAs, CPPs, and how they connect through the ICH Q8 QbD framework.",
    answer:"Per ICH Q8: A CQA (Critical Quality Attribute) is a physical, chemical, biological, or microbiological property that should be within an appropriate limit to ensure desired product quality. CQAs are identified via risk assessment: for a mAb, CQAs include: aggregation (%HMW), potency, glycosylation profile (afucosylation for ADCC-mediated MOA), charge variants, particulates, sequence variants. A CPP (Critical Process Parameter) is a process parameter whose variability has a direct impact on a CQA, and therefore must be monitored and controlled. Example: bioreactor dissolved oxygen setpoint → glycosylation (CQA). Other CPPs: pH, temperature, glucose feed timing, CO₂ accumulation → affect glycoform profile. The QbD framework: (1) Define QTPP (clinical performance → formulation requirements) → (2) Identify CQAs → (3) Risk Assessment linking process parameters to CQAs → (4) DoE studies to characterize parameter-attribute relationships → (5) Define Design Space (proven acceptable ranges) → (6) Control strategy (specs, IPCs, raw material controls). Working within Design Space is not a regulatory change.",
    followUps:["How do you distinguish a Critical Process Parameter from a Key Process Parameter?","What is the difference between design space and a proven acceptable range (PAR)?"],
    linkedICH:["q8r2","q9"],
  },
  // ── STABILITY ───────────────────────────────────────────────
  {
    id:"iq11", category:"Stability", level:"Mid-Level", icon:"📊", color:"#FB923C",
    question:"What is the key difference in establishing shelf-life for a small molecule vs. a biologic per ICH guidance?",
    answer:"Small molecules (ICH Q1A): Arrhenius kinetics apply — accelerated stability data (40°C/75% RH, 6 months) can be used to mathematically extrapolate and support a long-term shelf-life. Regression analysis with 95% confidence interval on degradant formation rate allows prediction. Biologics (ICH Q5C): real-time data at intended storage condition is required to support shelf-life. Accelerated data (25°C, 37°C) is for stress characterization and degradation pathway identification ONLY — it cannot be extrapolated to predict shelf-life. Reason: protein degradation (aggregation, deamidation, oxidation) does not follow simple Arrhenius kinetics because proteins undergo complex structural changes, concentration-dependent effects, and mixed degradation mechanisms. Practical implication: to file a BLA with a 24-month refrigerated shelf-life, you must have real-time data at 5°C showing specification compliance through 24 months. FDA expects ≥12 months real-time data at BLA submission, with shelf-life extension post-approval as data accrues.",
    followUps:["What stability-indicating assays must be in a mAb stability protocol?","How do you handle an out-of-trend result in a stability study?"],
    linkedICH:["q5c","q1a"],
  },
  // ── MANUFACTURING ───────────────────────────────────────────
  {
    id:"iq12", category:"Manufacturing & GMP", level:"Mid-Level", icon:"🏭", color:"#38BDF8",
    question:"Explain the key steps and critical controls in aseptic fill-finish manufacturing of a sterile injectable biologic.",
    answer:"Aseptic fill-finish is the highest patient-risk operation — product is exposed to the classified environment (ISO 5/Grade A). Step-by-step: (1) Drug product compounding: mix DS with formulation excipients in a formulation vessel. IPCs: concentration (A280), pH, osmolality, appearance; (2) Sterile filtration: 0.22 µm PES or PVDF sterilizing-grade filter. Pre-use: integrity test (forward flow or bubble point); post-use: second integrity test confirms filter didn't fail; bioburden tested on pre-filtration sample <0.5 EU/mL; (3) Filling: peristaltic pump or time-pressure fill into vials/syringes. Fill weight IPC: 100% in-process check ±2–3% of target. Environmental monitoring (EM): active air sampling (centrifugal or Anderson cascade), surface swabs, settle plates in Grade A/B; (4) Stoppering: nitrogen overlay in headspace for O₂-sensitive biologics; 100% stopper insertion verification (vision system); (5) Container closure integrity (CCI): vacuum decay, high-voltage leak detection, or dye ingress (USP <1207>); (6) 100% visual inspection: automated inspection line + manual AQL sampling per USP <1>; (7) Labeling and secondary packaging. Critical validations: aseptic process validation (media fills — 0 contaminated units in ≥3 runs of ≥5,000 units per PDA TR22/ISO 13408); sterile filter validation (bacterial retention, integrity correlation, extractables).",
    followUps:["What is the difference between Grade A and Grade B clean rooms?","What are the main contamination vectors in aseptic fill-finish?"],
    linkedICH:["q10"],
  },
  // ── BIOSIMILARS ─────────────────────────────────────────────
  {
    id:"iq13", category:"Biosimilars", level:"Senior", icon:"🔄", color:"#C084FC",
    question:"What is the totality-of-evidence approach for biosimilar development and how does analytical similarity drive it?",
    answer:"FDA's totality-of-evidence (ToE) approach evaluates the complete body of evidence — analytical, functional, nonclinical, PK/PD, and clinical — to conclude biosimilarity. The approach is stepwise and risk-based: (1) Analytical similarity (the cornerstone, ~50% weight): fingerprint-like characterization comparing biosimilar to reference product (RP) across 10–20 RP lots. Tests: SEC-HPLC, CE-SDS, icIEF, glycan HILIC-UPLC, peptide mapping, DSC, CD, SPR kinetics, cell-based potency, Fc receptor panel (FcγRI, FcγRIIIa, FcRn). FDA tiered approach: Tier 1 (equivalence testing — 90% CI within equivalence margins for most critical attributes like potency and aggregation); Tier 2 (graphical/descriptive comparison — charge variants, glycoform distribution); Tier 3 (qualitative fingerprinting — HOS). (2) PK/PD bridging (mandatory): equivalent PK (AUC, Cmax, t½) in a sensitive healthy volunteer or patient population. (3) Immunogenicity comparison (mandatory): comparative ADA rate and clinical impact. (4) Clinical efficacy (may be waived with strong Tier 1 analytical + PK): FDA 'analytical-only' pathway for highly characterized reference products (Humira, Herceptin, Avastin biosimilars approved this way).",
    followUps:["How many reference product lots are typically tested in a biosimilar analytical similarity study?","What is 90% CI equivalence testing in Tier 1 and what are typical equivalence margins?"],
    linkedICH:["q6b","q2r1"],
  },
  // ── ADVANCED MODALITIES ─────────────────────────────────────
  {
    id:"iq14", category:"Advanced Modalities", level:"Senior", icon:"🧬", color:"#34D399",
    question:"How does CMC development for CAR-T cell therapy differ fundamentally from traditional mAb development?",
    answer:"CAR-T is categorically different in almost every CMC dimension: (1) Starting material variability: autologous — each patient's T cells are the starting material. Inherent donor-to-donor variability in T cell health, subset composition, and transduction efficiency. No MCB/WCB concept — each patient is their own 'cell bank'. Allogeneic CAR-T uses donor-derived banks and is more analogous to conventional biologics; (2) Process: leukapheresis → T cell activation (CD3/CD28 beads or feeder cells) → viral vector transduction (lentivirus or retrovirus) → expansion (G-Rex or bioreactor) → cryopreservation → patient-specific batch release in 14–21 days; (3) CQAs: cell viability (≥70%), identity (CD3+, %CD4/CD8 composition), CAR transduction efficiency (%CAR+ by flow cytometry), VCN (vector copy number/cell, typically 0.5–5 for safety), sterility, mycoplasma (rapid test required due to time pressure), potency (antigen-specific killing, cytokine secretion assay), RCL (replication-competent lentivirus testing); (4) Scale: scale-OUT not scale-UP — many parallel small batches, not one large batch; (5) Shelf life: very short (days to weeks); (6) Regulatory: CBER (not CDER) oversight. ICH Q5A viral safety applies to the viral vector. Evolving regulatory framework — FDA published CAR-T guidance 2022.",
    followUps:["What are the unique stability challenges for CAR-T vs. mAbs?","How is the potency assay for a CAR-T different from a mAb potency assay?"],
  },
  // ── BEHAVIORAL ──────────────────────────────────────────────
  {
    id:"iq15", category:"Behavioral & Leadership", level:"Mid-Level", icon:"💼", color:"#60A5FA",
    question:"Tell me about a time you had to present complex CMC data to a non-scientific executive audience.",
    answer:"STAR framework: Situation: preparing a go/no-go recommendation for Phase 3 based on a stability finding (aggregation increasing at Month 9, approaching the 2% HMW specification limit at the current trajectory). Task: needed the VP of R&D to understand the risk and approve additional budget for formulation optimization work. Action: created a one-slide executive summary — used a traffic light system (green/yellow/red) rather than data tables. Showed a simple trend line with the specification limit highlighted. Translated '%HMW increase' to 'protein clumping that could make the drug less effective or cause immune reactions.' Proposed three options with cost/timeline/risk trade-offs. Rehearsed with a non-scientist friend to calibrate language. Result: VP approved the additional formulation study funding in 15 minutes. The study identified a refined polysorbate 80 concentration that stabilized the product. Key learnings: lead with the decision, not the data; put data in the appendix; make your recommendation explicit; use plain analogies for molecular concepts.",
    followUps:["How do you handle pushback from a non-scientist executive who doesn't believe the risk is real?","How do you build credibility with executive leaders as a scientist?"],
  },
  {
    id:"iq16", category:"Behavioral & Leadership", level:"Director", icon:"💼", color:"#60A5FA",
    question:"You disagree with the FDA's position on your specification range during a Type B meeting. How do you handle it?",
    answer:"In the meeting: stay calm and professional. Ask clarifying questions: 'Can you help us understand the specific patient safety or clinical concern driving the tighter limit?' Active listening — understand their perspective fully before responding. If it's a factual misunderstanding of the data, politely correct it with specific module cross-references ('As shown in Section 3.2.S.4.5, Table 4, the three sigma lower limit from 12 commercial lots is 0.8% HMW, providing a 2.5× safety margin to the clinical exposure threshold.'). Don't argue — document. Post-meeting: review and comment on meeting minutes carefully — these become the record. Evaluate the FDA's position scientifically: Is their concern valid? Is there additional data that could address it? Consider: can the specification be met without supply impact? Prepare a written response with supporting data if the position is technically untenable. For true impasse pre-BLA: request a Type A meeting for formal dispute resolution. Remember: FDA is a partner. They want approvable, safe drugs — approaching it as an adversarial relationship is always counterproductive.",
    followUps:["What preparation do you do before an FDA Type B meeting?","How do you track and respond to formal FDA meeting minutes?"],
  },
  {
    id:"iq17", category:"Behavioral & Leadership", level:"Director", icon:"💼", color:"#60A5FA",
    question:"How do you build a high-performing CMC analytical team in a fast-moving biotech?",
    answer:"Four pillars: (1) Hire for growth mindset + culture fit + T-shaped skills (deep in one area, broad curiosity). Use structured behavioral interviews + a practical case study. Technical excellence alone isn't enough — CMC is a team sport. (2) Psychological safety: celebrate experiments that teach something, even if they fail. Post-mortems are blame-free root cause exercises. People must feel safe flagging problems early — the only bad news is late news. (3) Invest in development: every direct report gets a personal development plan. Create exposure to regulatory interactions (invite Sci I/IIs to FDA meeting prep). Budget 5–10% of time for training and conferences. Create cross-training opportunities between analytical, formulation, and process dev — break silos. (4) Clear expectations + obstacle removal: clear RACI for each program, milestone-driven goals, regular 1:1s focused on development not status. Your job as a leader is to remove blockers, not add them. Retain talent by ensuring: interesting and impactful science, visible career trajectory, competitive compensation (benchmark annually), and a manager they respect. CMC attrition is expensive — each hire replacement costs 1–1.5× annual salary in lost productivity.",
    followUps:["How do you handle chronic underperformance in a critical technical role?","How do you prioritize multiple programs with limited headcount?"],
  },
  {
    id:"iq18", category:"Behavioral & Leadership", level:"Entry", icon:"💼", color:"#60A5FA",
    question:"Why do you want to work in CMC pharmaceutical development specifically?",
    answer:"Strong answer elements: (1) Intellectual depth — CMC sits at the intersection of chemistry, biology, engineering, and regulatory science. Every molecule is a puzzle that requires mastery across multiple disciplines; (2) Patient impact — the drug can only reach patients if CMC delivers a safe, consistent, well-characterized product. The quality work you do directly translates to patient safety; (3) Career breadth — CMC offers a path into analytical science, formulation, process development, regulatory affairs, or manufacturing operations, all within one functional family; (4) Innovation — biologics and advanced modalities (cell therapy, gene therapy, RNA) are among the most scientifically exciting areas in all of medicine right now; (5) Personal story — connect to a specific experience (lab coursework, internship, personal connection to a disease). Authenticity matters. Avoid: vague answers like 'I want to help people.' Be specific about what draws you to CMC vs. clinical or discovery research.",
    followUps:["Where do you see yourself in 5 years within CMC?","What specific aspect of CMC development excites you most right now?"],
  },
];

// ── Skills Matrix ───────────────────────────────────────────
export const SKILLS_MATRIX = [
  { skill:"SEC-HPLC (aggregation)", ra:2, sci1:4, sci2:5, ad:5, vp:3 },
  { skill:"CE-SDS (purity)", ra:2, sci1:4, sci2:5, ad:4, vp:3 },
  { skill:"icIEF (charge variants)", ra:1, sci1:3, sci2:5, ad:4, vp:3 },
  { skill:"Cell-based bioassay", ra:1, sci1:3, sci2:5, ad:4, vp:2 },
  { skill:"ICH Q2 method validation", ra:1, sci1:3, sci2:5, ad:5, vp:4 },
  { skill:"ICH Q6B specifications", ra:1, sci1:2, sci2:4, ad:5, vp:5 },
  { skill:"BLA/IND CMC authoring", ra:0, sci1:1, sci2:3, ad:5, vp:5 },
  { skill:"Formulation development", ra:1, sci1:2, sci2:4, ad:5, vp:4 },
  { skill:"Process development", ra:1, sci1:2, sci2:3, ad:5, vp:4 },
  { skill:"Regulatory interaction (FDA)", ra:0, sci1:0, sci2:2, ad:5, vp:5 },
  { skill:"Team leadership", ra:0, sci1:1, sci2:3, ad:5, vp:5 },
  { skill:"Strategic/portfolio thinking", ra:0, sci1:0, sci2:1, ad:4, vp:5 },
];
