export const PIPELINE = [
  { id:"s01", stage:"01", label:"Gene Construction", sub:"Molecular Biology", icon:"🧬", accent:"#C084FC",
    topics:[
      { id:"t01a", title:"Codon Optimization", body:"CHO cells prefer certain codons. Suboptimal usage causes ribosomal stalling and lower titer. Optimization is performed computationally before gene synthesis.", why:"Codon optimization locks in your manufacturing productivity ceiling. Poor codon usage limits titer to <1 g/L vs 5–10 g/L.", how:"Read Gustafsson et al. 2004. Ask your mentor: what titer difference did optimization produce?", ref:"ICH Q11 §3.2.S.2.1 | ICH Q5B" },
      { id:"t01b", title:"Expression Vector Design", body:"The optimized gene is cloned into a vector containing: promoter (CMV/EF1α), selection marker (GS/DHFR), Kozak sequence, signal peptide, and poly-A signal. Vector architecture profoundly affects expression level and genetic stability.", why:"The vector is a BLA-registered manufacturing raw material. These elements cannot be changed post-IND without comparability data.", how:"Ask to see the expression vector map. Read ICH Q5B on expression construct analysis.", ref:"ICH Q5B | ICH Q11 | FDA Phase 1 CMC Guidance" },
      { id:"t01c", title:"QTPP — Foundation of QbD", body:"The QTPP defines desired product characteristics linked to clinical intent: dosage form, route, strength, CQA targets, and container-closure. It is the compass for all CMC decisions.", why:"Starting without a QTPP means CMC activities lack a unified goal. Regulators expect QTPP-driven QbD thinking in BLA submissions.", how:"Read ICH Q8(R2). Study the A-Mab Case Study QTPP example.", ref:"ICH Q8(R2) | A-Mab Case Study (2009)" },
    ],
    questions:[
      { id:"q01a", level:"Foundational", q:"What is codon optimization and why is it performed before expressing a recombinant biologic in CHO cells? What manufacturing consequences does poor codon choice create?", why:"Codon optimization is irreversible — it locks in your productivity ceiling. Poor usage limits titer to <1 g/L vs 5–10 g/L.", how:"Read Gustafsson et al. 2004. Ask your mentor: what titer difference did optimization produce?", ref:"ICH Q11 §3.2.S.2.1 | ICH Q5B" },
      { id:"q01b", level:"Foundational", q:"What key genetic elements must an expression vector contain to drive stable, high-level expression in CHO cells, and why is each element a BLA-registered component?", why:"The vector is a permanent manufacturing raw material. Promoter, selection marker, and integration elements cannot be changed post-IND without comparability data.", how:"Ask to see the vector map. Read ICH Q5B. Research GS vs DHFR selection.", ref:"ICH Q5B | ICH Q11" },
      { id:"q01c", level:"Intermediate", q:"What is a developability assessment and which in silico and biophysical tools identify CMC sequence liabilities before committing to CLD investment?", why:"Failing in developability is cheap. Failing after 2 years of CLD is catastrophic. CDR deamidation hotspots create unstable CQAs nearly impossible to fix post-IND.", how:"Read Jarasch et al. 2015. Read Chennamsetty et al. on aggregation hotspot prediction.", ref:"ICH Q8 | FDA Characterization Guidance" },
      { id:"q01d", level:"Intermediate", q:"What is a QTPP and how does it cascade into CQA identification, analytical method selection, and specification setting throughout the CMC lifecycle?", why:"The QTPP anchors all CMC decisions. Regulators expect QTPP-driven thinking in BLA submissions.", how:"Read ICH Q8(R2). Study the A-Mab Case Study QTPP example.", ref:"ICH Q8(R2) | A-Mab Case Study" },
      { id:"q01e", level:"Advanced", q:"How does Fc engineering (LALA mutations, YTE, afucosylation knock-in) affect CMC development strategy, the CQA list, and potency assay design requirements?", why:"Fc engineering alters effector function, half-life, and FcRn binding — changing which quality attributes are CQAs and what potency assay format is required.", how:"Read Saunders 2019 on Fc engineering. Ask your mentor: what CMC challenges did Fc engineering create for our potency assay design?", ref:"ICH Q6B | FDA Potency Guidance (2008)" },
    ]
  },
  { id:"s02", stage:"02", label:"Transfection & Integration", sub:"Stable Cell Lines", icon:"⚡", accent:"#F472B6",
    topics:[
      { id:"t02a", title:"Stable vs Transient Transfection", body:"Transient transfection (HEK293, ExpiCHO) provides milligrams quickly. Stable transfection permanently integrates the vector into the CHO genome via electroporation, followed by drug selection to eliminate non-expressing cells.", why:"Transient material informs early CQA profiling but lacks cGMP documentation for clinical dosing.", how:"Ask your mentor: do we use transient material for any regulatory studies — what comparability is required?", ref:"FDA Phase 1 IND CMC Guidance | ICH Q11" },
      { id:"t02b", title:"Clonality Assurance — FDA 2021", body:"FDA and EMA require imaging evidence that each production clone originated from a single cell. Accepted methods: limiting dilution with Poisson statistics, FACS single-cell deposition, or automated imaging platforms (ClonePix, Solentim VIPS).", why:"Non-clonal lines harbor subpopulations producing heterogeneous product. FDA has issued BLA deficiencies for inadequate clonality data.", how:"Read FDA 2021 clonality Q&A. Ask your mentor: what imaging platform do we use?", ref:"FDA 2021 Clonality Guidance | ICH Q5D" },
    ],
    questions:[
      { id:"q02a", level:"Foundational", q:"What is the difference between transient and stable transfection for biologic production, and when is each material type appropriate for CMC and regulatory purposes?", why:"Transient material is analytically informative but lacks cGMP documentation for clinical dosing.", how:"Ask your mentor: do we use transient material for regulatory studies — what comparability is required?", ref:"FDA Phase 1 CMC Guidance | ICH Q11" },
      { id:"q02b", level:"Intermediate", q:"What documentation is required to demonstrate clonality assurance, and why is imaging evidence at single-cell deposition a firm FDA expectation per the 2021 guidance?", why:"Non-clonal lines harbor subpopulations producing heterogeneous product. FDA has issued BLA deficiencies for inadequate clonality data.", how:"Read FDA 2021 clonality Q&A. Ask your mentor: what imaging platform do we use?", ref:"FDA 2021 Clonality Guidance | ICH Q5D" },
      { id:"q02c", level:"Advanced", q:"What is NGS-based integration site analysis and why are regulators increasingly requesting it as part of cell substrate characterization in BLA packages?", why:"Integration into silenced chromatin causes expression loss. Integration near oncogenes creates theoretical safety concerns NGS alone can reveal.", how:"Read Thomas et al. 2018 on targeted integration in CHO.", ref:"ICH Q5B | ICH Q5D" },
    ]
  },
  { id:"s03", stage:"03", label:"Cell Line Development", sub:"Clone Selection", icon:"🔵", accent:"#38BDF8",
    topics:[
      { id:"t03a", title:"Clone Selection Criteria", body:"Lead clone selection balances: specific productivity (qP), growth rate, metabolic profile (lactate/ammonia), genetic stability, and product quality attributes. A structured multi-criteria decision matrix narrows hundreds of clones to 2–3 leads.", why:"Clone selection is the most consequential CMC decision. The selected clone defines manufacturing economics and quality attributes for the entire product lifecycle.", how:"Ask to see the clone funnel data. Ask your mentor: was titer or quality the primary driver?", ref:"ICH Q5D | ICH Q11" },
      { id:"t03b", title:"Genetic Stability Testing (ICH Q5D)", body:"ICH Q5D requires stable productivity and product quality over the full manufacturing duration (PDLs). Stability assessed at MCB, WCB, EOP, and extended limit. Sequence integrity, expression level, and key quality attributes all monitored.", why:"Genetic instability post-BLA means potentially having a different product. Missing EOP data is a CRL-triggering deficiency.", how:"Read ICH Q5D Section B.4. Build a stability testing matrix.", ref:"ICH Q5D | ICH Q5B | 21 CFR 610" },
    ],
    questions:[
      { id:"q03a", level:"Foundational", q:"What criteria drive lead production clone selection from hundreds of candidates, and how do you balance titer against product quality attributes when they conflict?", why:"Clone selection defines everything downstream forever. A clone with suboptimal glycosylation or aggregation tendency creates problems no downstream process can fully correct.", how:"Ask to see the clone funnel data. Ask your mentor: was there a higher-titer clone rejected for quality reasons?", ref:"ICH Q5D | ICH Q11" },
      { id:"q03b", level:"Foundational", q:"What is specific productivity (qP), how is it measured in fed-batch culture, and how does the qP vs. growth rate trade-off shape media and feeding strategy decisions?", why:"qP is the fundamental measure of cell productivity. High qP with sustainable viability gives best titer at scale.", how:"Read Dietmair et al. on qP. Ask your mentor: what qP threshold advanced clones?", ref:"ICH Q11 | FDA Process Development Guidance" },
      { id:"q03c", level:"Intermediate", q:"What does ICH Q5D require for genetic stability testing, how many PDLs must be covered, and what quality attributes must be monitored at end-of-production?", why:"Genetic instability during commercial manufacturing could cause product drift. Missing EOP data is a BLA deficiency that can trigger a CRL.", how:"Read ICH Q5D Section B.4. Build a stability test matrix.", ref:"ICH Q5D | ICH Q5B" },
    ]
  },
  { id:"s04", stage:"04", label:"Cell Banking", sub:"MCB / WCB", icon:"🏦", accent:"#34D399",
    topics:[
      { id:"t04a", title:"Two-Tier MCB/WCB System", body:"The MCB is derived from the selected clone — 100–500 vials cryopreserved at passage P+3 to P+7. Prepared once, it serves as the source for all WCBs throughout the product lifecycle. Multiple geographic storage sites provide redundancy.", why:"The MCB is irreplaceable. Contamination or storage failure threatens the entire program.", how:"Ask your mentor: how many MCB vials do we prepare — what geographic storage redundancy exists?", ref:"ICH Q5D | 21 CFR 610.18" },
    ],
    questions:[
      { id:"q04a", level:"Foundational", q:"What is the MCB/WCB two-tiered cell banking system and what is the regulatory rationale for maintaining this hierarchy throughout the product lifecycle?", why:"Every batch ever manufactured originates from the MCB. If lost without backup, the entire program is at risk.", how:"Read ICH Q5D Section A. Ask your mentor: how many MCB vials are stored and in how many locations?", ref:"ICH Q5D | 21 CFR 610.18" },
      { id:"q04b", level:"Intermediate", q:"What testing must be performed on the MCB before Phase 1 IND and what additional tests are required before BLA submission? How do these timelines affect program planning?", why:"Phase 1 requires basic identity, sterility, mycoplasma. BLA requires full adventitious agent characterization. Understanding this escalation prevents last-minute BLA delays.", how:"Build a two-column table: MCB tests at IND vs BLA. Use ICH Q5D as primary reference.", ref:"ICH Q5D | ICH Q5A(R1) | FDA Phase 1 CMC Guidance" },
    ]
  },
  { id:"s05", stage:"05", label:"Upstream Development", sub:"Bioreactor Process", icon:"🔬", accent:"#22D3EE",
    topics:[
      { id:"t05a", title:"CPPs & Glycosylation Control", body:"Key upstream CPP candidates: pH, dissolved oxygen, temperature, osmolality, CO2 accumulation, agitation. Glycosylation controlled by media: manganese activates galactosyltransferase, galactose supplementation increases galactosylation, copper depletion reduces fucosylation (↑ADCC), ammonia disrupts Golgi pH.", why:"CPP identification is a regulatory commitment. Missing a CPP means it may drift uncontrolled commercially, causing batch failures.", how:"Build a table: parameter → CQA impact → mechanism. Ask your mentor: which parameter had the most unexpected CQA impact in characterization DoE?", ref:"ICH Q8 | ICH Q11 | FDA Process Validation Guidance (2011)" },
      { id:"t05b", title:"Scale-Down Model Qualification", body:"A qualified SDM at 2–15L must be shown representative of the commercial bioreactor (1,000–20,000L) by side-by-side CQA profile comparison. Key parameters matched: kLa, mixing time, pCO2, osmolality, and temperature control. All process characterization studies run in the qualified SDM.", why:"The SDM is the foundation of all technical and regulatory data. An unqualified SDM invalidates process characterization.", how:"Read Hsu et al. on SDM qualification. Ask your mentor: has FDA ever challenged our SDM representativeness?", ref:"ICH Q11 | FDA Process Validation Guidance (2011)" },
    ],
    questions:[
      { id:"q05a", level:"Foundational", q:"What are the key bioreactor process parameters in fed-batch CHO culture and which are most commonly identified as CPPs? Give the mechanistic basis for at least three CPP–CQA relationships.", why:"CPP identification requires mechanistic understanding. This knowledge is required for characterization design and CPP classification in the BLA.", how:"Build a table: parameter → CQA impact → mechanism.", ref:"ICH Q8 | ICH Q11 | FDA Process Validation Guidance" },
      { id:"q05b", level:"Intermediate", q:"How does media composition — specifically manganese, galactose, and ammonia — mechanistically control mAb glycosylation and how is this built into the upstream control strategy?", why:"These are direct process levers for glycan CQAs. CMC leaders who understand these mechanisms design targeted media controls.", how:"Read Konrad et al. on manganese and galactosylation. Ask your mentor: do we actively control manganese — is it a CPP?", ref:"ICH Q8 | ICH Q6B" },
      { id:"q05c", level:"Advanced", q:"How do you design a full DoE for bioreactor process characterization to distinguish CPPs from KPPs from non-key parameters, and what statistical criteria support each classification?", why:"Process characterization DoE is a core CMC competency. Under-powered designs miss CPPs; classification output is a regulatory commitment.", how:"Read Box, Hunter & Hunter Chapter 3. Ask your mentor: what effect size did we power our bioreactor DoE to detect?", ref:"ICH Q8 | ICH Q9 | ICH Q11" },
      { id:"q05d", level:"Expert", q:"Upstream optimization improves titer 40% but shifts glycosylation outside historical comparability ranges. What is your full CMC and regulatory strategy to manage this?", why:"This is a classic CMC leadership dilemma — titer gain vs. CQA change. The strategy depends on direction, magnitude, and clinical relevance of the glycan change.", how:"Read ICH Q5E. Build a decision tree: what tests first, regulatory filing pathway if comparability demonstrated vs not.", ref:"ICH Q5E | ICH Q8 | FDA Comparability Guidance (2003)" },
    ]
  },
  { id:"s06", stage:"06", label:"Downstream Development", sub:"Purification Train", icon:"⚗️", accent:"#4ADE80",
    topics:[
      { id:"t06a", title:"Standard mAb Purification Train", body:"Platform mAb downstream: (1) Protein A capture; (2) Low pH viral inactivation (pH 3.4–3.7); (3) Polishing (CEX/AEX/HIC) — HCP, aggregate, charge variant removal; (4) Viral filtration (20 nm); (5) UF/DF — concentration and buffer exchange.", why:"This sequence is conserved across most mAb products. CMC leaders must explain every step's rationale fluently — asked in regulatory meetings, inspections, and CMC reviews.", how:"Draw the complete downstream flow diagram labeling each step's purpose. Read Shukla et al. 2007.", ref:"ICH Q11 | ICH Q5A(R1) | ICH Q6B" },
      { id:"t06b", title:"HCP Clearance & PLBL2 Risk", body:"HCPs monitored by ELISA (primary) and LC-MS (orthogonal). ELISA coverage depends on rabbit host immunogenicity — high-risk HCPs like PLBL2 (lipase that degrades polysorbate 80) may not be detected. PLBL2 has caused commercial product recalls.", why:"HCPs have caused product recalls. FDA scrutinizes HCP ELISA coverage and clearance strategy. This is a perennially hot inspection topic.", how:"Read Labrenz 2014 on PLBL2. Read Singer et al. 2021. Ask your mentor: do we specifically monitor PLBL2 by LC-MS?", ref:"ICH Q6B | FDA HCP Guidance | Labrenz 2014" },
    ],
    questions:[
      { id:"q06a", level:"Foundational", q:"What is the standard downstream purification train for a mAb and what is the specific scientific rationale for each step?", why:"Every CMC professional must explain each step's rationale fluently — asked in every CMC interview, regulatory meeting, and facility inspection.", how:"Draw the complete flow diagram. Label each step with purpose, CPPs, and CQA impact.", ref:"ICH Q11 | ICH Q5A(R1) | ICH Q6B" },
      { id:"q06b", level:"Foundational", q:"What are HCPs, why are they a critical quality attribute, and what are the specific limitations of HCP ELISA that require complementary LC-MS analysis?", why:"HCPs can be immunogenic and have caused recalls (PLBL2-mediated polysorbate degradation). ELISA coverage gaps mean high-risk HCPs may be missed.", how:"Read Singer et al. 2021. Ask your mentor: what is our ELISA coverage — do we monitor PLBL2 by LC-MS?", ref:"ICH Q6B | FDA HCP Guidance" },
      { id:"q06c", level:"Intermediate", q:"What is low pH viral inactivation, what model viruses validate it per ICH Q5A, and what manufacturing excursion constitutes a viral safety concern requiring regulatory notification?", why:"Low pH VI is a dedicated enveloped virus clearance step. A pH excursion above the upper validated limit is a potential viral safety event.", how:"Read ICH Q5A(R1) Section 4. Ask your mentor: what LRF was achieved in our VI validation?", ref:"ICH Q5A(R1) | FDA Points to Consider on Viral Safety | 21 CFR 312.32" },
      { id:"q06d", level:"Advanced", q:"How do you justify Protein A resin reuse in a BLA and what cycle lifetime studies demonstrate consistent HCP clearance across the claimed reuse cycles?", why:"Protein A costs $5,000–15,000/L. Reuse justification has both major quality and COGS implications. Regulators inspect this data thoroughly.", how:"Review your Protein A resin lifetime validation report. Ask your mentor: how many cycles do we qualify?", ref:"ICH Q11 | ICH Q6B | Cytiva MabSelect Platform Guidance" },
      { id:"q06e", level:"Expert", q:"Post-approval, you discover a polishing step is not clearing PLBL2, which is degrading polysorbate 80 in commercial drug product. What are your simultaneous CMC, analytical, and regulatory actions?", why:"Post-approval HCP safety discoveries require parallel analytical work, risk assessment, process modification, and regulatory filing under time pressure — the highest-consequence commercial CMC challenge.", how:"Read Labrenz 2014. Read FDA post-approval guidance. Ask your mentor: has a post-approval HCP finding ever required a process change?", ref:"ICH Q12 | FDA Post-Approval Guidance | ICH Q5E" },
    ]
  },
  { id:"s07", stage:"07", label:"Analytical Development", sub:"Methods & CQAs", icon:"📊", accent:"#A78BFA",
    topics:[
      { id:"t07a", title:"CQA Risk Assessment & Method Validation", body:"FMEA-based risk assessment scores each quality attribute on severity, occurrence, and detectability. High-risk attributes become CQAs. ICH Q2(R2) (2023) requires: specificity, linearity, range, accuracy, precision (repeatability/intermediate/reproducibility), DL/QL, and robustness.", why:"CQA determination is the most consequential analytical CMC decision. Method validation failures are a leading cause of FDA 483 observations.", how:"Read ICH Q8(R2), A-Mab Case Study, and ICH Q2(R2) (2023) in full.", ref:"ICH Q8 | ICH Q9 | ICH Q6B | ICH Q2(R2) | A-Mab Case Study" },
    ],
    questions:[
      { id:"q07a", level:"Foundational", q:"What is a CQA and how is a risk-based CQA identification process conducted for a standard mAb? Who must be involved and what tools structure the assessment?", why:"CQA identification is the cornerstone of QbD — all method development, process characterization, and spec setting flows from it.", how:"Read ICH Q8(R2) and A-Mab Case Study. Build your own CQA risk assessment table.", ref:"ICH Q8 | ICH Q9 | ICH Q6B | A-Mab Case Study" },
      { id:"q07b", level:"Foundational", q:"What is a potency assay and what does 'MOA relevance' mean in FDA's potency testing expectations for biologics?", why:"FDA's 2008 potency guidance requires assays reflecting biological activity attributable to the MOA. Binding-only assays are increasingly challenged.", how:"Read FDA 2008 Potency Guidance. Ask your mentor: how was our potency assay designed to reflect MOA?", ref:"FDA Potency Guidance (2008) | ICH Q6B | 21 CFR 610.10" },
      { id:"q07c", level:"Intermediate", q:"What are the ICH Q2(R2) validation parameters for a quantitative HPLC release method and how do acceptance criteria differ between HPLC and cell-based biological assays?", why:"Method validation is a legal requirement. Precision requirements differ substantially between physicochemical and biological assays.", how:"Read ICH Q2(R2) (2023). Create a validation plan template for SEC-HPLC.", ref:"ICH Q2(R2) | USP <1225>" },
      { id:"q07d", level:"Advanced", q:"How do you establish a primary reference standard for a biologic, what characterization is required, and how is a bridging study conducted when the primary reference supply is exhausted?", why:"Reference standards are the quality anchor for all lot-release decisions. Every result for the product's remaining commercial life depends on getting the bridge study right.", how:"Read USP <1033>. Ask your mentor: when do we need to plan the next reference standard?", ref:"USP <1033> | FDA Reference Standard Guidance (2018) | ICH Q6B" },
      { id:"q07e", level:"Expert", q:"What is multi-attribute monitoring (MAM) by LC-MS and how does implementing it as a release test change the analytical control strategy, regulatory filing, and resource requirements vs. a traditional approach?", why:"MAM is a paradigm shift — one LC-MS method simultaneously monitors dozens of PTMs, replacing multiple individual methods.", how:"Read Rogers et al. 2015 and FDA 2018 MAM workshop proceedings. Ask your mentor: are we implementing MAM for release testing?", ref:"FDA MAM Workshop (2018) | EMA Reflection Paper on MAM | Rogers et al. 2015" },
    ]
  },
  { id:"s08", stage:"08", label:"Formulation Development", sub:"Drug Product", icon:"💊", accent:"#FB923C",
    topics:[
      { id:"t08a", title:"Excipient Selection & Forced Degradation", body:"Standard biologic formulation: buffer (histidine, citrate — pH stability), tonicity agent (sucrose/mannitol), surfactant (PS20/PS80 — prevents surface aggregation), stabilizer (sucrose/trehalose — cryo/lyoprotection). Forced degradation studies identify degradation pathways at accelerated conditions.", why:"Every excipient is BLA-registered — changing one post-approval requires a PAS. Forced degradation reveals the formulation's weak points before committing to formal stability studies.", how:"Read Daugherty & Mrsny 2006. Write a one-sentence justification for each excipient.", ref:"ICH Q8 | ICH Q6B | ICH Q3E | ICH Q1A(R2)" },
    ],
    questions:[
      { id:"q08a", level:"Foundational", q:"What are the standard excipients in a biologic drug product formulation and what is the specific scientific rationale for each component?", why:"Every excipient is BLA-registered — cannot be changed post-approval without a PAS.", how:"Read Daugherty & Mrsny 2006. Write a one-sentence justification for each excipient.", ref:"ICH Q8 | ICH Q6B | ICH Q3E" },
      { id:"q08b", level:"Intermediate", q:"What are extractables and leachables from biologic drug product container-closure systems and how are they assessed per ICH Q3E (2024)?", why:"Leachables (silicone oil, tungsten, stopper degradants) have caused protein aggregation and product recalls.", how:"Read ICH Q3E (2024). Ask your mentor: what E&L findings occurred for our CCS?", ref:"ICH Q3E | USP <661> | BPOG E&L Guidance" },
      { id:"q08c", level:"Intermediate", q:"What are the primary and secondary drying phases of lyophilization, how is product collapse temperature (Tc) characterized, and why is knowledge of Tc critical for cycle development?", why:"Primary drying shelf temperature must be below Tc to prevent product collapse. Without Tc data, cycle development is guesswork.", how:"Read Nail & Akers on lyophilization. Ask your mentor: how was Tc characterized for our drug product?", ref:"FDA Lyophilization Guidance | ICH Q8 | USP <1>" },
      { id:"q08d", level:"Advanced", q:"How do you set and justify drug product release specifications under ICH Q6B, linking acceptance criteria to clinical PK/PD data and manufacturing batch history?", why:"Spec setting requires clinical justification plus manufacturing capability data. Regulators challenge specs lacking scientific basis.", how:"Read ICH Q6B and FDA 2014 specifications Q&A. Ask your mentor: how was our potency lower acceptance criterion determined?", ref:"ICH Q6B | FDA Specifications Q&A (2014) | ICH Q1E" },
    ]
  },
  { id:"s09", stage:"09", label:"Technology Transfer", sub:"Site Transfers", icon:"🔄", accent:"#F59E0B",
    topics:[
      { id:"t09a", title:"Transfer Package & Site Comparability", body:"Tech transfer package: MBRs/SOPs for all unit operations, raw material specifications, equipment qualification requirements, Process Description Document (PDD), analytical method procedures, and Transfer Plan with pre-defined acceptance criteria.", why:"'Tribal knowledge' staying in people's heads causes transfer failures. CMC leaders must ensure all process understanding is documented before transfer begins.", how:"Ask your mentor: what documents comprised our last DS tech transfer package?", ref:"ICH Q10 | ISPE Technology Transfer Guide | PDA TR65 | ICH Q5E" },
    ],
    questions:[
      { id:"q09a", level:"Foundational", q:"What key documents form the foundation of a biologic technology transfer package and what is the critical difference between a transfer plan and a batch record?", why:"'Tribal knowledge' staying in people's heads causes transfer failures. Inadequate documentation is a primary cause of CMO manufacturing failures.", how:"Read ISPE Technology Transfer Guide. Ask your mentor: were there knowledge gaps in our last transfer?", ref:"ICH Q10 | ISPE Technology Transfer Guide | PDA TR65" },
      { id:"q09b", level:"Advanced", q:"How do you design a site comparability study per ICH Q5E for first GMP batches at a new site, including analytical panel selection and statistical acceptance criteria?", why:"Site comparability is a regulatory requirement. Pre-defined criteria are essential — setting them after seeing data is specification shopping, a regulatory integrity violation.", how:"Read ICH Q5E. Draft a comparability acceptance criteria table.", ref:"ICH Q5E | FDA Comparability Guidance (2003) | ICH Q2(R2)" },
    ]
  },
  { id:"s10", stage:"10", label:"Clinical Manufacturing", sub:"Phase 1→3", icon:"🏭", accent:"#2DD4BF",
    topics:[
      { id:"t10a", title:"cGMP, Data Integrity & IND Evolution", body:"cGMP for biologics: 21 CFR 210/211, 600/610 (US); EU GMP Part I and Annex 2 (EU). FDA 2018 data integrity guidance defines ALCOA+ (Attributable, Legible, Contemporaneous, Original, Accurate, plus Complete and Consistent). CMC IND content escalates from Phase 1 through Phase 3.", why:"Data integrity failures — the most serious cGMP violation — can result in Warning Letters and consent decrees. CMC activities started too late in Phase 2 consistently drive BLA delays.", how:"Read 21 CFR 210/211 and EU GMP Part I. Create a US vs EU cGMP comparison table.", ref:"21 CFR Parts 210/211 | 21 CFR 600/610 | EU GMP Annex 2 | FDA Data Integrity Guidance" },
    ],
    questions:[
      { id:"q10a", level:"Foundational", q:"What is cGMP and which US and EU regulations govern biological drug substance and drug product manufacturing? What are the main differences between US and EU requirements?", why:"cGMP is the minimum quality standard required by law. FDA can place an IND on clinical hold for cGMP deficiencies.", how:"Read 21 CFR 210/211, 600/610. Read EU GMP Part I and Annex 2. Create a comparison table.", ref:"21 CFR Parts 210/211 | 21 CFR 600/610 | EU GMP Annex 2" },
      { id:"q10b", level:"Intermediate", q:"How does the CMC section of an IND evolve from Phase 1 through Phase 3, and which CMC activities most commonly become critical-path risks to BLA filing if not initiated early enough?", why:"Many programs fail at BLA because CMC wasn't upgraded adequately between Phase 2 and 3.", how:"Draw a CMC lifecycle Gantt from Phase 1 IND to BLA. Ask your mentor: what CMC activity most threatened our last BLA timeline?", ref:"FDA Phase 1 CMC Guidance | FDA Phase 2/3 CMC Guidance | ICH M4Q" },
    ]
  },
  { id:"s11", stage:"11", label:"Process Characterization", sub:"CPP / Design Space", icon:"🎯", accent:"#F472B6",
    topics:[
      { id:"t11a", title:"FMEA, DoE & Design Space", body:"FMEA classifies parameters: pCPP (requires characterization), KPP (affects yield not CQAs), non-key (demonstrated no effect). DoE then characterizes pCPPs. NOR: target operational range. PAR: wider range demonstrated safe by characterization. Design space: multidimensional combination within which product quality is assured.", why:"Risk assessment determines where to invest characterization resources. An underpowered risk assessment that misses pCPPs results in inadequate BLA data.", how:"Read ICH Q9. Run a mock FMEA for 5 bioreactor parameters.", ref:"ICH Q9 | A-Mab Case Study | ICH Q11 | ICH Q8(R2)" },
    ],
    questions:[
      { id:"q11a", level:"Foundational", q:"What is the difference between a CPP, KPP, and non-key parameter? Give concrete examples for a bioreactor step and explain the regulatory implications of each classification.", why:"Parameter classification is a regulatory commitment. CPPs have direct CQA impact — changing them requires a regulatory filing.", how:"Read ICH Q8 definitions. Classify pH, DO, feed volume, and agitation for your bioreactor.", ref:"ICH Q8 | ICH Q9 | ICH Q11" },
      { id:"q11b", level:"Intermediate", q:"How do you set the NOR and PAR for a CPP and what manufacturing flexibility does the design space concept provide compared to operating strictly within the NOR?", why:"Design space gives manufacturers ability to adjust within a pre-approved range without a regulatory filing.", how:"Read ICH Q8 Annex on design space. Ask your mentor: for one of our CPPs, what is the NOR vs PAR boundary?", ref:"ICH Q8(R2) | FDA Process Validation Guidance" },
      { id:"q11c", level:"Advanced", q:"Your DoE shows load challenge has a statistically significant effect on HCP clearance (20 vs 18 ng/mg) — both well within specification. Should it be classified as a CPP? Defend your scientific and regulatory reasoning.", why:"Statistical significance does not equal practical significance. ICH Q8 allows scientific judgment — if the effect is within spec and lacks clinical relevance, a non-CPP classification may be defensible.", how:"Read ICH Q8 on statistical vs. practical significance. Discuss with your mentor: what documentation would support a non-CPP classification?", ref:"ICH Q8(R2) | ICH Q9" },
    ]
  },
  { id:"s12", stage:"12", label:"Process Validation", sub:"PPQ & Lifecycle", icon:"✅", accent:"#38BDF8",
    topics:[
      { id:"t12a", title:"FDA 2011 Three-Stage Validation Lifecycle", body:"Stage 1 (Process Design): all development and characterization. Stage 2 (PPQ): commercial-scale confirmation with pre-defined acceptance criteria. Stage 3 (CPV): ongoing statistical monitoring using Shewhart control charts, Cpk/Ppk analysis. PPQ protocol must be approved before the first PPQ batch.", why:"FDA's 2011 guidance replaced the 3-batch event with a lifecycle approach. Validation is not complete at PPQ — Stage 3 is perpetual.", how:"Read FDA's 2011 Process Validation Guidance (24 pages) in full.", ref:"FDA Process Validation Guidance (2011) | ICH Q10 | ICH Q11" },
    ],
    questions:[
      { id:"q12a", level:"Foundational", q:"What are the three stages of FDA's 2011 process validation lifecycle, what is the key deliverable of each, and why is Stage 3 described as 'perpetual'?", why:"FDA's 2011 guidance replaced the 3-batch paradigm. Stage 3 is perpetual because commercial process monitoring never ends.", how:"Read FDA's 2011 PV Guidance in full. Create a one-page summary table.", ref:"FDA Process Validation Guidance (2011) | ICH Q10 | ICH Q11" },
      { id:"q12b", level:"Intermediate", q:"What elements must a PPQ protocol contain and why must it be approved before the first PPQ batch is manufactured?", why:"Pre-defined acceptance criteria are essential — setting them after seeing data is 'specification shopping,' a regulatory integrity violation.", how:"Draft a PPQ protocol outline for a bioreactor step. Ask your mentor: who reviews and approves our PPQ protocol?", ref:"FDA Process Validation Guidance (2011) | 21 CFR 211 | ICH Q8" },
      { id:"q12c", level:"Advanced", q:"What is Stage 3 Continued Process Verification (CPV) and what statistical tools detect process drift before batches fail specification?", why:"Companies neglecting CPV risk process drift going undetected until batch failure. FDA inspectors request CPV data.", how:"Read FDA 2011 PV Guidance Stage 3. Learn Shewhart control charts and Cpk/Ppk interpretation.", ref:"FDA Process Validation Guidance (2011) | ASTM E2587 | ICH Q10" },
      { id:"q12d", level:"Expert", q:"During execution of your final PPQ batch, a critical IPC result falls outside the pre-defined acceptance criterion. What are your immediate steps, investigation approach, and batch disposition decision framework?", why:"A PPQ failure at the last batch is high-stakes — a CMC leadership judgment call with BLA timeline implications.", how:"Build a flowchart: deviation → Phase I → Phase II → assignable cause assessment → disposition.", ref:"FDA PV Guidance (2011) | FDA OOS Guidance (2006) | 21 CFR 211.192" },
    ]
  },
  { id:"s13", stage:"13", label:"Commercial Manufacturing", sub:"GMP Operations", icon:"🏭", accent:"#22D3EE",
    topics:[
      { id:"t13a", title:"APQR & Post-Approval Change Control", body:"APQR compiles annual batch data: release results, OOS/OOT occurrences, deviations, change controls, stability data, complaint trends, CPV statistical outputs. Required by 21 CFR 211.180(e) and EU GMP Chapter 1. Post-approval changes classified: AR, CBE-0, CBE-30, or PAS.", why:"FDA inspectors request APQRs. Incorrect change classification — filing a PAS change as an AR — can result in a Warning Letter.", how:"Read 21 CFR 211.180(e), EU GMP Chapter 1, and FDA 2004 post-approval guidance.", ref:"21 CFR 211.180(e) | EU GMP Chapter 1 | ICH Q10 | FDA Post-Approval Changes Guidance (2004)" },
    ],
    questions:[
      { id:"q13a", level:"Foundational", q:"What is an APQR and what information must it compile? What regulatory deficiency arises from an APQR that fails to identify a concerning manufacturing trend?", why:"FDA inspectors request APQRs. A poor APQR missing concerning trends is an inspection finding.", how:"Read 21 CFR 211.180(e) and EU GMP Chapter 1. Ask your mentor: what was the key APQR finding last year?", ref:"21 CFR 211.180(e) | EU GMP Chapter 1 | ICH Q10" },
      { id:"q13b", level:"Intermediate", q:"How do you classify a post-approval manufacturing change under FDA's biologics reporting framework (PAS/CBE-30/CBE-0/Annual Report)?", why:"Incorrect classification is a regulatory violation — filing a PAS change as an Annual Report can result in a Warning Letter.", how:"Read FDA 2004 post-approval guidance. Build a change categorization decision tree.", ref:"FDA Post-Approval Changes Guidance (2004) | ICH Q12 | 21 CFR 601.12" },
      { id:"q13c", level:"Expert", q:"A field complaint reports visible particulates in your commercial drug product. Walk through your immediate regulatory reporting obligations, investigation steps, and supply continuity considerations.", why:"Product quality complaints leading to recalls are the highest-consequence commercial CMC events. Field Alert Reports must be filed within 3 business days.", how:"Read 21 CFR 600.14 on Field Alert Reports. Read FDA recall guidance.", ref:"21 CFR 600.14 | FDA Recall Guidance | ICH Q10" },
    ]
  },
  { id:"s14", stage:"14", label:"Stability & Shelf Life", sub:"ICH Q5C", icon:"📅", accent:"#4ADE80",
    topics:[
      { id:"t14a", title:"ICH Q5C Stability Program Design", body:"ICH Q5C requires: long-term (5°C ± 3°C), accelerated (25°C/60%RH), and stress conditions. Time points: 0, 3, 6, 9, 12, 18, 24 months and annually thereafter. Unlike small molecules, accelerated data for biologics generally CANNOT be used for shelf-life extrapolation — real-time data is required.", why:"Stability studies are irreversible time-dependent experiments. Missed time points create gaps that regulators cite.", how:"Read ICH Q5C and Q1A side by side. Build a full stability protocol matrix.", ref:"ICH Q5C | ICH Q1A(R2) | ICH Q1E" },
    ],
    questions:[
      { id:"q14a", level:"Foundational", q:"What ICH guidelines govern stability for biologic drug products and how do they differ from small molecule requirements regarding accelerated condition shelf-life extrapolation?", why:"Unlike small molecules, biologic stability cannot use accelerated data for shelf-life extrapolation — real-time data is required.", how:"Read ICH Q5C and Q1A side by side. Create a comparison table.", ref:"ICH Q5C | ICH Q1A(R2) | ICH Q1E | ICH Q1B" },
      { id:"q14b", level:"Intermediate", q:"How do you design a formal stability protocol for a biologic DS and DP — including storage conditions, time points, and analytical panel selection per ICH Q5C?", why:"Stability studies are irreversible. Missed time points create data gaps regulators cite.", how:"Design a complete stability protocol for a liquid mAb at 5°C.", ref:"ICH Q5C | ICH Q1A(R2) | FDA Stability Guidance" },
      { id:"q14c", level:"Advanced", q:"If a commercial drug product shows an OOT stability result at 24 months but remains within specification, what is the investigation pathway and potential regulatory action?", why:"OOT results require investigation even without a spec failure — the trend may predict a future OOS and may require shelf-life shortening.", how:"Read ICH Q10 on OOT investigations. Build a decision tree.", ref:"ICH Q10 | FDA Stability Guidance | ICH Q5C" },
    ]
  },
  { id:"s15", stage:"15", label:"BLA Filing", sub:"Submissions", icon:"📋", accent:"#F59E0B",
    topics:[
      { id:"t15a", title:"CTD Module 3 Architecture & QOS", body:"Module 3 (CMC): 3.2.S Drug Substance and 3.2.P Drug Product — each covering: manufacturer, characterization, manufacture, specification, reference standards, CCS, and stability. The Quality Overall Summary (QOS) precedes Module 3 — the first document a regulatory reviewer reads.", why:"Module 3 is the CMC backbone of every BLA. Fluency in CTD architecture prevents both gaps and redundancies.", how:"Download ICH M4Q and map every CMC deliverable to a specific CTD section.", ref:"ICH M4Q | FDA BLA Guidance | EMA Quality CTD Guidance" },
    ],
    questions:[
      { id:"q15a", level:"Foundational", q:"What is the CTD Module 3 structure and what information belongs in 3.2.S (Drug Substance) vs. 3.2.P (Drug Product)?", why:"Module 3 is the CMC module of every IND and BLA. Fluency in CTD architecture prevents both gaps and redundancies.", how:"Download ICH M4Q. Map every CMC deliverable to a specific CTD section number.", ref:"ICH M4Q | FDA BLA Guidance | EMA Quality CTD Guidance" },
      { id:"q15b", level:"Intermediate", q:"What CMC topics should be addressed in a Type B pre-BLA meeting and how must questions be formulated to receive maximally useful FDA commitments?", why:"Pre-BLA meetings prevent CRLs. Specific questions with data summaries can get FDA commitments preventing deficiencies worth 6–18 months of delay.", how:"Read FDA 2009 Formal Meetings Guidance. Draft 5 specific CMC questions for a hypothetical pre-BLA meeting.", ref:"FDA Formal Meetings Guidance (2009) | PDUFA Meeting Procedures" },
      { id:"q15c", level:"Advanced", q:"How do ICH Q8, Q9, Q10, Q11, and Q12 form an integrated Quality framework and what is the practical implication of each for a commercial biologic CMC program?", why:"The ICH Quality guidelines are interdependent. Q8 (design/CQA), Q9 (risk), Q10 (quality system), Q11 (DS development), Q12 (lifecycle) define the modern CMC paradigm.", how:"Read each guideline. Create a one-page integration map.", ref:"ICH Q8(R2) | ICH Q9 | ICH Q10 | ICH Q11 | ICH Q12" },
    ]
  },
  { id:"s16", stage:"16", label:"Post-Approval & Lifecycle", sub:"ICH Q12", icon:"♾️", accent:"#C084FC",
    topics:[
      { id:"t16a", title:"ICH Q12: ECs, PACMPs & Comparability", body:"ICH Q12 (2020) introduced Established Conditions (ECs) — the BLA-filed information subset triggering a submission when changed — and Post-Approval Change Management Protocols (PACMPs) — pre-agreed frameworks for anticipated future changes. A well-designed PACMP can convert a 12+ month PAS to a 30-day CBE-30.", why:"Early adopters of PACMPs are finding significant regulatory time savings. CMC leaders who understand Q12 can design BLA submissions with lifecycle flexibility from the start.", how:"Read ICH Q12 and Implementation Working Group training materials.", ref:"ICH Q12 | FDA Draft Guidance on Q12 Implementation | EMA Q12 Q&A" },
    ],
    questions:[
      { id:"q16a", level:"Foundational", q:"What is the US post-approval change reporting framework for biologics (PAS/CBE-30/CBE-0/AR) and what drives the category determination for a given manufacturing change?", why:"Incorrect classification is a regulatory violation — filing a PAS change as an Annual Report can result in a Warning Letter.", how:"Read FDA 2004 post-approval guidance. Build a change categorization decision tree.", ref:"FDA Post-Approval Changes Guidance (2004) | ICH Q12 | 21 CFR 601.12" },
      { id:"q16b", level:"Intermediate", q:"What are ICH Q12 Established Conditions (ECs) and PACMPs, and how can a PACMP reduce a PAS timeline (12+ months) to CBE-30 (30 days)?", why:"A well-designed PACMP has direct commercial value for manufacturing lifecycle management.", how:"Read ICH Q12 Sections 3 and 4. Draft a one-page PACMP outline for a raw material supplier change.", ref:"ICH Q12 | FDA Draft PACMP Guidance | EMA PACMP Q&A" },
      { id:"q16c", level:"Expert", q:"A competitor launches a biosimilar to your approved mAb. You are planning 3 manufacturing changes over 3 years that may shift CQA profiles. How do you develop a CMC lifecycle strategy balancing manufacturing economics, regulatory complexity, and biosimilar competitive dynamics?", why:"This synthesis question integrates ICH Q12, comparability strategy, regulatory categorization, biosimilar competition, and manufacturing economics — the kind of strategic thinking CMC directors practice daily.", how:"Develop a 3-year CMC lifecycle plan. For each change: filing category, comparability strategy, biosimilar implication, risk mitigation.", ref:"ICH Q12 | ICH Q5E | FDA Post-Approval Guidance | FDA Biosimilar Guidance" },
    ]
  },
];

export const DOMAINS = [
  { id:"dom_up", label:"Upstream Bioprocess", icon:"🔬", accent:"#22D3EE", desc:"Bioreactor operations, cell culture, media, scale-up, PAT, intensification",
    questions:[
      { id:"du01", level:"Foundational", q:"What is the difference between batch, fed-batch, and perfusion bioreactor modes for mAb production? What are the productivity and product quality trade-offs of each?", why:"Bioreactor mode is a fundamental platform decision affecting titer, product quality, facility fit, and COGS over the entire commercial product lifecycle.", how:"Ask your mentor: why did we choose fed-batch — were alternatives evaluated and what were the COGS implications?", ref:"ICH Q11 | FDA Process Development Guidance" },
      { id:"du02", level:"Foundational", q:"What is viable cell density (VCD), viability, and cell-specific productivity (qP), and why are daily measurements essential for interpreting bioreactor performance?", why:"VCD, viability, and qP together define integrated manufacturing performance. A viability drop below 70–80% is an early signal of metabolic stress that can shift CQAs before any specification failure.", how:"Review your site's bioreactor IPC monitoring system.", ref:"ICH Q11 | FDA Process Validation Guidance" },
      { id:"du03", level:"Intermediate", q:"How does pCO2 accumulation in a large-scale bioreactor affect cell metabolism and glycosylation, and what process strategies control pCO2 in 10,000–20,000L bioreactors?", why:"pCO2 accumulation is a major scale-up challenge — it shifts intracellular pH, inhibits growth, and can alter glycosylation.", how:"Read Mostafa & Gu 2003 on pCO2 effects. Ask your mentor: is pCO2 a CPP in our process?", ref:"ICH Q8 | ICH Q11" },
      { id:"du04", level:"Intermediate", q:"What is the role of copper in CHO cell culture media and what effect does copper concentration have on N-glycosylation, specifically core fucosylation and ADCC activity?", why:"Copper depletion reduces core fucosylation — a deliberate lever for increasing ADCC activity, a CQA for Fc-effector function mAbs.", how:"Read Qian et al. on copper depletion and afucosylation.", ref:"ICH Q8 | ICH Q6B" },
      { id:"du05", level:"Advanced", q:"How do you perform a cell culture process scale-up from 2L SDM to 20,000L commercial bioreactor and what engineering parameters must be maintained or adjusted?", why:"Scale-up is a fundamental CMC challenge. kLa, mixing time, pCO2, shear stress, and nutrient gradients all change with scale.", how:"Read Nienow 2006 on scale-up principles. Ask your mentor: what were the top 3 challenges in our commercial scale-up?", ref:"ICH Q11 | FDA Process Validation Guidance" },
      { id:"du06", level:"Advanced", q:"How do you design a risk-based PAT strategy for a commercial mAb bioreactor process, linking inline and at-line measurements to the formal control strategy?", why:"PAT enables real-time monitoring and control, reducing end-product testing burden and enabling real-time release testing.", how:"Read FDA 2004 PAT Guidance.", ref:"FDA PAT Guidance (2004) | ICH Q8(R2) | ICH Q13" },
      { id:"du07", level:"Expert", q:"A commercial bioreactor run shows unexpectedly high ammonia accumulation not observed in the SDM during characterization. How do you investigate and what are the batch disposition and CMC implications?", why:"SDM representativeness failures have real-time batch disposition and long-term CMC program implications.", how:"Develop an investigation plan. Ask your mentor: has our SDM ever failed to predict a commercial-scale finding?", ref:"ICH Q11 | FDA OOS Guidance (2006) | FDA PV Guidance (2011)" },
      { id:"du08", level:"Expert", q:"What is continuous bioreactor manufacturing and how does ICH Q13 address the unique CMC and process validation challenges, including the regulatory definition of 'batch'?", why:"ICH Q13 (2022) provides the first comprehensive guidance on validation, batch definition, and control strategy for continuous upstream.", how:"Read ICH Q13 on continuous manufacturing for biologics.", ref:"ICH Q13 | ICH Q8 | FDA Continuous Manufacturing Guidance" },
    ]
  },
  { id:"dom_ds", label:"Downstream Purification", icon:"⚗️", accent:"#34D399", desc:"Chromatography, viral clearance, filtration, UF/DF, impurity clearance, resin reuse",
    questions:[
      { id:"dd01", level:"Foundational", q:"What are the key impurities that must be cleared during mAb downstream purification, what are the patient risks of each, and what regulatory specification limits apply?", why:"Impurity clearance is the primary function of downstream processing. Understanding which impurities exist, their risks, and spec limits is essential for designing and defending a purification process.", how:"Build an impurity table: impurity | source | patient risk | regulatory limit | detection method.", ref:"ICH Q6B | FDA HCP Guidance | FDA Residual DNA Guidance" },
      { id:"dd02", level:"Foundational", q:"What is the mechanism of Protein A affinity chromatography, what are the main commercial resin options, and what are the key advantages and limitations of each?", why:"Protein A is the workhorse of mAb capture. CMC leaders must understand the chemistry, resin options, and limitations.", how:"Review the Cytiva and Repligen Protein A resin portfolios.", ref:"ICH Q11 | Cytiva MabSelect Technical Guide | ICH Q6B" },
      { id:"dd03", level:"Intermediate", q:"What is the difference between bind-elute and flow-through chromatography modes and when is each preferred in a mAb polishing sequence?", why:"Mode selection directly affects impurity clearance mechanism and process economics.", how:"Build a table: chromatography step | mode | target impurities | key CPPs.", ref:"ICH Q11 | Shukla et al. 2007 | ICH Q6B" },
      { id:"dd04", level:"Intermediate", q:"What is the orthogonal viral clearance strategy required by ICH Q5A and why must a minimum of two independent clearance steps with different mechanisms be demonstrated?", why:"Orthogonal mechanisms provide independent barriers. If one step fails, the second provides backup. This two-step requirement is a patient safety standard that cannot be waived.", how:"Read ICH Q5A(R1) Section 5. Build a table of clearance mechanisms for each purification step.", ref:"ICH Q5A(R1) | PDA TR41 | FDA Points to Consider (1998)" },
      { id:"dd05", level:"Advanced", q:"How do you develop a process characterization package for a chromatography polishing step (e.g., CEX) including DoE design, CPP classification, and NOR/PAR definition?", why:"Chromatography PC studies are the scientific backbone of BLA Module 3.2.S.2.2.", how:"Build a CEX characterization DoE: factors (pH, conductivity, load challenge, flow rate), responses (HCP, aggregates, yield).", ref:"ICH Q8 | ICH Q11 | FDA Process Validation Guidance" },
      { id:"dd06", level:"Advanced", q:"How do you justify Protein A resin reuse in a BLA and what cycle lifetime studies demonstrate consistent HCP clearance and product quality across the claimed reuse cycles?", why:"Protein A costs $5,000–15,000/L. Reuse justification has both major quality and COGS implications.", how:"Review your Protein A resin lifetime validation report.", ref:"ICH Q11 | ICH Q6B | Cytiva MabSelect Platform Guidance" },
      { id:"dd07", level:"Expert", q:"How would you approach developing a downstream purification process for a bispecific antibody that contains a mixture of homo- and heterodimers requiring separation?", why:"Bispecific antibodies require separation of hetero- from homodimers — a challenge not present in conventional mAbs.", how:"Read Liu et al. on bispecific antibody manufacturing challenges.", ref:"ICH Q11 | ICH Q6B | Bispecific Antibody Manufacturing Literature" },
      { id:"dd08", level:"Expert", q:"You are developing the downstream process for a novel modality (ADC or gene therapy vector). What platform knowledge from mAb purification transfers, and what novel regulatory challenges arise?", why:"Platform extension to novel modalities requires identifying transferable vs. modality-specific process knowledge.", how:"Read FDA guidance on ADC CMC and gene therapy manufacturing.", ref:"FDA ADC CMC Guidance | FDA Gene Therapy CMC Guidance | ICH Q11" },
    ]
  },
  { id:"dom_dp", label:"Drug Product & Formulation", icon:"💊", accent:"#FB923C", desc:"Formulation design, excipients, container-closure, stability, lyophilization, E&L",
    questions:[
      { id:"df01", level:"Foundational", q:"What is protein aggregation, what are the physical and chemical mechanisms driving it in biologics, and how is aggregation risk assessed during formulation development?", why:"Aggregation is the most important immunogenicity CQA for biologics.", how:"Read Roberts 2014 on protein aggregation mechanisms.", ref:"ICH Q6B | USP <787> | ICH Q5C" },
      { id:"df02", level:"Foundational", q:"What are polysorbate 20 and polysorbate 80, why are they used, and what is the PLBL2-mediated polysorbate degradation risk and its clinical consequences?", why:"Polysorbates prevent surface aggregation but are susceptible to enzymatic degradation by PLBL2 and other HCPs. Degradation causes particle formation and product recalls.", how:"Read Labrenz 2014 on PLBL2.", ref:"ICH Q8 | ICH Q3E | ICH Q5C | Labrenz 2014" },
      { id:"df03", level:"Intermediate", q:"What is DSF (differential scanning fluorimetry) and how is it used in formulation screening to rank excipient combinations by thermal stability (Tm)?", why:"DSF is a high-throughput formulation screening tool measuring Tm as a proxy for conformational stability.", how:"Read Niesen et al. 2007 on DSF.", ref:"ICH Q8(R2) | ICH Q5C | Niesen et al. 2007" },
      { id:"df04", level:"Intermediate", q:"What are the primary and secondary drying phases of lyophilization, how is product collapse temperature (Tc) characterized, and why is knowledge of Tc critical?", why:"Primary drying shelf temperature must be below Tc to prevent product collapse.", how:"Read Nail & Akers on lyophilization.", ref:"FDA Lyophilization Guidance | ICH Q8" },
      { id:"df05", level:"Advanced", q:"What are extractables and leachables, how is a safety risk assessment conducted per ICH Q3E (2024), and what analytical tools identify and quantify leachable species?", why:"Leachables from containers have caused protein aggregation and patient safety issues.", how:"Read ICH Q3E (2024) and BPOG extractables guidance.", ref:"ICH Q3E | BPOG E&L Guidance | PDA TR66 | USP <661>" },
      { id:"df06", level:"Advanced", q:"What is the subcutaneous (SC) delivery bioavailability challenge for biologics and what formulation strategies improve bioavailability for high-dose mAbs?", why:"SC delivery achieves only 50–85% bioavailability vs IV. High-dose mAbs face viscosity challenges (>25 cP makes injection painful).", how:"Read Richter & Bhatt 2018 on SC bioavailability.", ref:"ICH Q8 | EMA Reflection Paper on SC Administration" },
      { id:"df07", level:"Expert", q:"Your drug product shows increasing sub-visible particle counts at 9-month real-time stability time points. How do you systematically investigate root cause and what regulatory actions may be required?", why:"Sub-visible particle increases are an immunogenicity safety signal. Root causes include protein aggregation, silicone oil, tungsten, or CCS interactions.", how:"Design an investigation plan: particle characterization (MFI, Raman, FTIR), forced studies, CCS compatibility assessment.", ref:"USP <787> | USP <788> | ICH Q5C | FDA Sub-Visible Particle Guidance" },
      { id:"df08", level:"Expert", q:"What is a drug-device combination product under 21 CFR Part 3 and how do CMC development and regulatory submission requirements differ when an auto-injector is involved?", why:"Combination products require device CMC (human factors, injection force, delivery volume verification) on top of drug CMC. FDA's OCP requirements can add 12+ months.", how:"Read 21 CFR Part 3. Read ISO 11608.", ref:"21 CFR Part 3 | ISO 11608 | FDA OCP Guidance | ICH Q8" },
    ]
  },
  { id:"dom_an", label:"Analytical Methods & CQAs", icon:"📊", accent:"#A78BFA", desc:"Method development, validation, characterization, potency, HOS, MAM, OOS",
    questions:[
      { id:"da01", level:"Foundational", q:"What is N-glycosylation and how does the glycan profile of a mAb drug substance affect effector function (ADCC/CDC), pharmacokinetics, and immunogenicity?", why:"Glycosylation is the most complex and clinically consequential CQA for most mAbs.", how:"Read Jefferis 2009 review on glycosylation and antibody pharmacology.", ref:"ICH Q6B | A-Mab Case Study | Jefferis 2009 Review" },
      { id:"da02", level:"Foundational", q:"What is an OOS investigation and what are the two phases defined in FDA's 2006 guidance? What constitutes adequate Phase I vs. Phase II investigation?", why:"OOS investigations are the most cited category in FDA Warning Letters.", how:"Read FDA 2006 OOS Guidance in full. Build a Phase I/Phase II investigation flowchart.", ref:"FDA OOS Guidance (2006) | 21 CFR 211.192" },
      { id:"da03", level:"Intermediate", q:"What analytical methods characterize primary structure and higher-order structure (HOS) of a biologic, and why is HOS characterization increasingly important in BLA submissions?", why:"HOS characterization demonstrates that the biologic folds correctly — essential for potency, safety, and comparability.", how:"Read EMA reflection paper on HOS characterization.", ref:"ICH Q6B | EMA Reflection Paper on HOS | FDA Characterization Guidance" },
      { id:"da04", level:"Intermediate", q:"What is analytical ultracentrifugation (AUC) and why is it the gold standard orthogonal method for aggregate characterization compared to SEC-HPLC?", why:"AUC measures aggregation under near-native conditions without dilution or column-analyte interactions — the primary limitations of SEC.", how:"Read Berkowitz et al. on AUC for biopharmaceuticals.", ref:"ICH Q6B | USP <787> | Berkowitz et al. 2006" },
      { id:"da05", level:"Intermediate", q:"What are the key cell-based bioassay formats for mAb potency testing and what are the relative advantages and regulatory acceptance of each?", why:"Potency assay format selection is a critical analytical CMC decision. Cell-based assays are MOA-relevant but variable; binding assays are precise but may not be accepted as stand-alone.", how:"Read FDA 2008 Potency Guidance.", ref:"FDA Potency Guidance (2008) | ICH Q6B | 21 CFR 610.10" },
      { id:"da06", level:"Advanced", q:"What is the analytical comparability assessment required by ICH Q5E for a manufacturing process change, and how do you select appropriate statistical acceptance criteria for each CQA?", why:"Analytical comparability is the scientific defense that manufacturing changes are safe. Statistical acceptance criteria must be pre-defined.", how:"Read ICH Q5E. Read FDA 2003 comparability guidance.", ref:"ICH Q5E | FDA Comparability Guidance (2003) | ICH Q2(R2)" },
      { id:"da07", level:"Expert", q:"How would you design a specification-setting exercise for a new molecular entity biologic entering Phase 1, and how do specifications evolve from IND through BLA?", why:"Specification evolution from Phase 1 to BLA is one of the most important analytical CMC activities. Phase 1 specs are broad; BLA specs are tight, justified by clinical data.", how:"Read ICH Q6B Section 3. Read FDA's 2014 specification Q&A.", ref:"ICH Q6B | FDA Specification Q&A (2014) | ICH Q8" },
      { id:"da08", level:"Expert", q:"What is multi-attribute monitoring (MAM) by LC-MS and how does implementing it as a release test change the analytical control strategy and regulatory filing?", why:"MAM is a paradigm shift — one LC-MS method simultaneously monitors dozens of PTMs, replacing multiple individual methods.", how:"Read Rogers et al. 2015 and FDA 2018 MAM workshop proceedings.", ref:"FDA MAM Workshop (2018) | EMA Reflection Paper on MAM | Rogers et al. 2015" },
    ]
  },
  { id:"dom_reg", label:"Regulatory & Submissions", icon:"📋", accent:"#F59E0B", desc:"IND, BLA, CTD Module 3, FDA/EMA strategy, CRLs, ICH framework, PAI",
    questions:[
      { id:"dr01", level:"Foundational", q:"What is an IND and what CMC information is required in each section under FDA's Phase 1 IND CMC guidance?", why:"The IND is the regulatory vehicle for clinical investigation. CMC professionals must know what is required at Phase 1 to prepare an adequate package without over-investing.", how:"Read FDA Phase 1 IND CMC Guidance (2003). Build a checklist of all CMC sections.", ref:"FDA Phase 1 IND CMC Guidance (2003) | 21 CFR 312 | ICH M4Q" },
      { id:"dr02", level:"Foundational", q:"What is the CTD and how does ICH M4Q Module 3 organize the CMC information in a BLA submission?", why:"Module 3 is the CMC backbone of every BLA. Knowing the architecture fluently prevents both gaps and redundancies.", how:"Download ICH M4Q. Map every CMC deliverable to a specific CTD section number.", ref:"ICH M4Q | FDA BLA Guidance | EMA Quality CTD Guidance" },
      { id:"dr03", level:"Intermediate", q:"What are the different types of FDA meetings (Type A, B, B-Pre-Phase 3, C) and how do you structure a Type B pre-BLA meeting request to get maximally useful CMC commitments?", why:"Pre-BLA meetings prevent CRLs. Specific questions with data summaries can get FDA commitments preventing deficiencies worth 6–18 months of delay.", how:"Read FDA 2009 Formal Meetings Guidance. Draft 5 specific CMC questions for a hypothetical pre-BLA meeting.", ref:"FDA Formal Meetings Guidance (2009) | PDUFA Meeting Procedures" },
      { id:"dr04", level:"Intermediate", q:"What are the most common CMC-related reasons biologics receive Complete Response Letters (CRLs), and how does a proactive CMC development strategy prevent each failure mode?", why:"CRLs delay approval 6–18 months and cost tens of millions of dollars.", how:"Search FDA website for published CRL action letters. Identify 5 with CMC-related findings.", ref:"21 CFR 601 | FDA BLA Action Letters | FDA CDER Review Guidance" },
      { id:"dr05", level:"Advanced", q:"What is a Pre-Approval Inspection (PAI) for a biologic BLA, what areas do FDA investigators focus on, and how does a CMC leader prepare the organization?", why:"PAI is the final hurdle before approval. Most common observations: incomplete validation data, data integrity issues, inadequate OOS investigations.", how:"Read FDA PAI Compliance Program 7346.832.", ref:"FDA PAI Compliance Program 7346.832 | 21 CFR Parts 210/211 | EU GMP" },
      { id:"dr06", level:"Advanced", q:"What are the key CMC differences between FDA (BLA) and EMA (MAA) filing requirements for a biologic and how do you manage a harmonized global CMC submission?", why:"FDA and EMA have divergent expectations on batch numbering, stability protocols, comparability presentation, and process validation scope.", how:"Compare FDA BLA guidance with EMA quality dossier guidance. List 5 specific differences.", ref:"ICH M4Q | FDA BLA Guidance | EMA ICH CTD Q&A" },
      { id:"dr07", level:"Expert", q:"How do you develop a CMC regulatory strategy for a biologic entering Phase 1 today that maximizes development efficiency, minimizes BLA CMC risk, and builds in ICH Q12 lifecycle flexibility from the start?", why:"This synthesis question integrates QTPP, QbD, ICH Q12 ECs, platform strategies, and regulatory interaction planning into a coherent multi-year strategy.", how:"Draft a 2-page CMC regulatory strategy memo. Ask your mentor to critique it.", ref:"All ICH Q Guidelines | FDA Phase 1–BLA CMC Guidances | ICH Q12 | ICH M4Q" },
      { id:"dr08", level:"Expert", q:"What is Breakthrough Therapy Designation (FDA) or PRIME (EMA) and how does expedited review status change the CMC development strategy?", why:"Breakthrough/PRIME designations accelerate timelines — creating CMC pressure to compress activities that normally take years.", how:"Read FDA Breakthrough Therapy Guidance and EMA PRIME guidance.", ref:"FDA Breakthrough Therapy Guidance | EMA PRIME Guideline | 21 CFR 312.82" },
    ]
  },
  { id:"dom_val", label:"Process Validation", icon:"✅", accent:"#38BDF8", desc:"PPQ, cleaning validation, aseptic fills, Stage 1–3 lifecycle, PVLP, CPV",
    questions:[
      { id:"dv01", level:"Foundational", q:"What is the difference between process validation and process qualification, and how does FDA's 2011 lifecycle approach redefine validation as a continual activity?", why:"The 2011 guidance reframed validation from a 3-batch event to a scientific lifecycle process.", how:"Read FDA's 2011 Process Validation Guidance in full.", ref:"FDA Process Validation Guidance (2011) | ICH Q10 | ICH Q11" },
      { id:"dv02", level:"Foundational", q:"What is cleaning validation and what is the MACO calculation using a health-based exposure limit (HBEL/PDE)? Why have the old 10 ppm and 0.001-dose criteria been replaced?", why:"The old criteria are not health-based. HBEL limits are now required because they are patient-safety-justified.", how:"Read ISPE Cleaning Validation Guide. Read EMA HBEL guideline. Calculate a mock MACO.", ref:"ISPE Cleaning Validation Guide | EMA HBEL Guideline | EU GMP Annex 15" },
      { id:"dv03", level:"Intermediate", q:"What statistical approach supports the number of PPQ batches selected for a BLA and what statistical acceptance criteria are typically applied?", why:"PPQ batch number and statistical criteria must be pre-defined and scientifically justified.", how:"Read FDA 2011 PV Guidance on PPQ design. Read on tolerance intervals.", ref:"FDA Process Validation Guidance (2011) | ASTM E2281 | ICH Q8" },
      { id:"dv04", level:"Intermediate", q:"What is aseptic process validation (media fill), what are FDA expectations for media fill size and contamination rates, and how are worst-case interventions incorporated?", why:"Aseptic manufacturing failures mean sterility failures — patient deaths. Zero tolerance for contaminated units.", how:"Read FDA 2004 Aseptic Processing Guidance and EU GMP Annex 1 (2022).", ref:"FDA 2004 Aseptic Processing Guidance | EU GMP Annex 1 (2022) | USP <71>" },
      { id:"dv05", level:"Advanced", q:"What is Continued Process Verification (CPV) and what statistical tools, control chart rules, and Cpk thresholds does FDA expect?", why:"Stage 3 CPV is a perpetual regulatory obligation. FDA inspectors request CPV data and ask about trend investigations.", how:"Read FDA 2011 PV Guidance Stage 3. Learn Western Electric control chart rules.", ref:"FDA Process Validation Guidance (2011) | ASTM E2587 | ICH Q10" },
      { id:"dv06", level:"Advanced", q:"What is the validation strategy for a lyophilization process and what studies demonstrate uniformity across the lyophilizer shelf (edge, center, and corner positions)?", why:"Lyophilizer validation must demonstrate uniform product quality across all shelf positions. Edge and corner effects are well-documented phenomena.", how:"Read FDA Guidance on Lyophilized Products.", ref:"FDA Lyophilization Guidance | EU GMP Annex 15 | ICH Q8" },
      { id:"dv07", level:"Expert", q:"How would you apply process validation principles to a novel modality (mRNA/LNP or gene therapy vector) where no established platform validation approach exists?", why:"Novel modalities present unique validation challenges — no industry platform, evolving regulatory expectations.", how:"Read FDA guidance on gene therapy CMC. Read ICH Q13 on continuous manufacturing validation principles.", ref:"FDA Gene Therapy CMC Guidance | ICH Q13 | FDA mRNA Guidance" },
      { id:"dv08", level:"Expert", q:"During commercial manufacturing, Stage 3 CPV monitoring shows a sustained upward trend in bioreactor ammonia over 18 months without spec failures. What investigation steps and regulatory actions are required?", why:"Sustained upward trends without failures are the 'silent risk' in CPV — they signal drift that will eventually cause batch failure.", how:"Build a CPV trend investigation plan.", ref:"FDA Process Validation Guidance (2011) | ICH Q10 | ASTM E2587" },
    ]
  },
  { id:"dom_bio", label:"Biosimilars CMC", icon:"🔄", accent:"#4ADE80", desc:"351(k) pathway, analytical similarity tiers, reference product, interchangeability, totality of evidence",
    questions:[
      { id:"db01", level:"Foundational", q:"What is a biosimilar and how does FDA's 351(k) approval pathway differ from the 351(a) pathway? What role does CMC/analytical similarity play in the totality-of-evidence approach?", why:"Biosimilars are approved through analytical similarity + clinical extrapolation — not identical replication. CMC/analytical similarity is the centerpiece.", how:"Read FDA 2012 Biosimilar Development Guidance. Read the BPCI Act.", ref:"FDA Biosimilar Development Guidance (2012) | BPCI Act | 21 USC 351(k)" },
      { id:"db02", level:"Foundational", q:"What is reference product characterization in biosimilar development and why is it the critical first CMC step?", why:"You must understand the reference product deeply before designing your biosimilar process. The reference product's CQA distribution defines the similarity acceptance ranges.", how:"Read FDA 2019 guidance on reference product characterization.", ref:"FDA Reference Product Characterization Guidance (2019) | ICH Q6B" },
      { id:"db03", level:"Intermediate", q:"What is FDA's tiered analytical similarity assessment approach (Tiers 1, 2, and 3) and how does the tier assignment of each CQA determine the statistical rigor required?", why:"Tiered similarity testing organizes quality attributes by clinical relevance. Tier 1 requires formal equivalence testing. Tier 2 uses quality ranges. Tier 3 is descriptive.", how:"Read FDA 2019 Statistical Approaches to Analytical Similarity Guidance.", ref:"FDA Statistical Similarity Guidance (2019) | ICH Q6B | Tsong et al." },
      { id:"db04", level:"Intermediate", q:"What is interchangeability designation for a biosimilar, how does it differ from basic biosimilarity, and what studies are required?", why:"Interchangeability allows pharmacists to substitute the biosimilar without prescriber intervention — a significant commercial advantage.", how:"Read FDA 2019 Interchangeability Guidance.", ref:"FDA Interchangeability Guidance (2019) | BPCI Act" },
      { id:"db05", level:"Advanced", q:"How does a post-approval manufacturing change by the originator affect the ongoing biosimilar similarity assessment and what obligation does the biosimilar developer have?", why:"Originator post-approval changes can shift the reference product's CQA profile — changing the similarity target.", how:"Read FDA guidance on reference product characterization.", ref:"FDA Biosimilar Guidance | ICH Q12 | ICH Q5E" },
      { id:"db06", level:"Advanced", q:"What is the 'totality of evidence' standard for biosimilar approval and how do analytical similarity, PK/PD studies, and clinical safety data each contribute?", why:"Biosimilar approval is a holistic regulatory judgment. Robust analytical similarity can reduce or eliminate clinical data requirements.", how:"Read FDA's biosimilar development guidance and scientific considerations guidance.", ref:"FDA Biosimilar Scientific Considerations Guidance | FDA Biosimilar Development Guidance" },
      { id:"db07", level:"Expert", q:"How would you design a CMC development strategy for a biosimilar to a complex biologic (e.g., Fc-fusion protein with multiple glycoforms) where demonstrating analytical similarity is particularly challenging?", why:"Complex biologics have inherently higher product heterogeneity, making similarity assessment more challenging.", how:"Read FDA complex biologic biosimilar guidances.", ref:"FDA Complex Drug Biosimilar Guidance | ICH Q6B" },
      { id:"db08", level:"Expert", q:"As a CMC leader at an originator company, how does your post-approval manufacturing change strategy need to account for biosimilar competition, and what proactive CMC stewardship activities are required?", why:"Originator CMC leaders must think strategically about how manufacturing changes affect the biosimilar landscape.", how:"Read ICH Q12 on lifecycle management.", ref:"ICH Q12 | ICH Q5E | FDA Biosimilar Guidance | FDA Reference Product Guidance" },
    ]
  },
  { id:"dom_qbd", label:"Quality by Design & ICH", icon:"🎯", accent:"#F59E0B", desc:"QbD, design space, PAT, RTRT, ICH Q8–Q13 integrated framework",
    questions:[
      { id:"dq01", level:"Foundational", q:"What is Quality by Design (QbD) and how does it fundamentally differ from the traditional quality-by-testing (QbT) approach? What specific ICH Q8 tools operationalize QbD?", why:"QbD is the paradigm shift that underpins the entire modern CMC regulatory framework.", how:"Read ICH Q8(R2). Read FDA 2006 Critical Path Initiative white paper.", ref:"ICH Q8(R2) | FDA Critical Path Initiative | A-Mab Case Study" },
      { id:"dq02", level:"Foundational", q:"What is a design space in ICH Q8 and how does it differ from a proven acceptable range (PAR) and a normal operating range (NOR)?", why:"Design space is the multidimensional combination of input variables within which product quality is assured. Operating within it doesn't require a regulatory filing.", how:"Read ICH Q8 Annex on design space.", ref:"ICH Q8(R2) | FDA Process Validation Guidance | ICH Q10" },
      { id:"dq03", level:"Intermediate", q:"What is PAT per FDA's 2004 guidance and how does PAT implementation change the control strategy?", why:"PAT enables real-time monitoring and control, reducing end-product testing burden and enabling real-time release testing.", how:"Read FDA 2004 PAT Guidance.", ref:"FDA PAT Guidance (2004) | ICH Q8(R2) | ICH Q13" },
      { id:"dq04", level:"Intermediate", q:"What is the ICH Q9 Quality Risk Management framework and how are FMEA and risk ranking tools applied in CMC development programs?", why:"ICH Q9 provides the framework for systematically managing quality risks throughout the product lifecycle.", how:"Read ICH Q9. Apply FMEA to a unit operation: identify failure modes, assess severity/occurrence/detectability.", ref:"ICH Q9 | A-Mab Case Study | ICH Q8 | ICH Q11" },
      { id:"dq05", level:"Advanced", q:"What is ICH Q10 (Pharmaceutical Quality System) and how do its four elements — process performance monitoring, CAPA, change management, and management review — create a lifecycle quality management system?", why:"ICH Q10 defines the quality system framework within which all CMC development and manufacturing activities operate.", how:"Read ICH Q10 in full. Map each of its four elements to specific activities in your organization.", ref:"ICH Q10 | ICH Q8(R2) | 21 CFR Part 210/211 | EU GMP Part I" },
      { id:"dq06", level:"Advanced", q:"What is ICH Q13 on continuous manufacturing, what is the definition of 'batch' in a continuous manufacturing context, and how does process validation differ from traditional batch manufacturing?", why:"ICH Q13 (2022) is the newest addition to the ICH quality framework, addressing a manufacturing paradigm where product flows continuously.", how:"Read ICH Q13.", ref:"ICH Q13 | ICH Q8 | FDA Continuous Manufacturing Guidance" },
      { id:"dq07", level:"Expert", q:"How would you implement a fully integrated QbD program for a biologic entering Phase 1 today, and what differentiates a gold-standard QbD CMC submission from a compliance-only approach?", why:"A true QbD submission demonstrates deep process understanding, proactive risk management, and built-in lifecycle flexibility.", how:"Draft a QbD implementation plan covering: QTPP, CQA risk assessment, DoE program, control strategy, PAT, and ICH Q12 EC designation.", ref:"ICH Q8(R2) | ICH Q9 | ICH Q10 | ICH Q11 | ICH Q12 | A-Mab Case Study" },
      { id:"dq08", level:"Expert", q:"How does the concept of 'Established Conditions' (ECs) in ICH Q12 interact with the design space concept in ICH Q8, and how can a CMC leader use EC designation to maximize post-approval manufacturing flexibility?", why:"ECs are the subset of design space information that triggers a regulatory submission when changed.", how:"Read ICH Q12 Sections 2 and 3 on ECs. Read ICH Q8 Annex on design space.", ref:"ICH Q12 | ICH Q8(R2) | FDA Draft Q12 Implementation Guidance" },
    ]
  },
  { id:"dom_novel", label:"Novel Modalities", icon:"🚀", accent:"#F472B6", desc:"ADCs, mRNA/LNPs, CAR-T, gene therapy, bispecifics",
    questions:[
      { id:"dn01", level:"Foundational", q:"What is an antibody-drug conjugate (ADC) and what are the three structural components (antibody, linker, payload) whose CMC development must be independently developed and integrated?", why:"ADCs are among the most CMC-complex molecules. Each component requires independent CMC development, but all three must work together.", how:"Read FDA 2019 Guidance on ADC CMC.", ref:"FDA ADC CMC Guidance (2019) | ICH Q11 | ICH Q6B" },
      { id:"dn02", level:"Foundational", q:"What are lipid nanoparticles (LNPs) as delivery vehicles for mRNA therapeutics, and what are the unique CMC challenges for LNP manufacturing, characterization, and stability?", why:"mRNA/LNP products have unique CMC challenges: LNP encapsulation efficiency, mRNA integrity, particle size, lipid composition, and ultra-low temperature storage.", how:"Read FDA guidance on mRNA products.", ref:"FDA mRNA CMC Guidance | ICH Q11 | ICH Q6B" },
      { id:"dn03", level:"Intermediate", q:"What is Drug-to-Antibody Ratio (DAR) in an ADC, why is it a critical quality attribute, and what analytical methods measure and control DAR distribution?", why:"DAR directly affects potency, PK, and tolerability. Too high DAR causes aggregation and toxicity; too low reduces potency.", how:"Read Hamblett et al. 2004 on ADC DAR and activity.", ref:"FDA ADC CMC Guidance | ICH Q6B | Hamblett et al. 2004" },
      { id:"dn04", level:"Intermediate", q:"What are viral vector gene therapies (AAV, lentiviral), why are empty capsid ratio and vector genome titer critical quality attributes, and what manufacturing challenges affect scalability?", why:"Gene therapy viral vectors have unique CQAs (empty/full capsid ratio, VG titer, potency) and manufacturing challenges.", how:"Read FDA Gene Therapy CMC Guidance.", ref:"FDA Gene Therapy CMC Guidance | ICH Q11 | ICH Q6B" },
      { id:"dn05", level:"Intermediate", q:"What are bispecific antibodies, what are the different molecular formats, and what unique CMC challenges do bispecifics present vs. conventional mAbs?", why:"Bispecific antibodies have substantially higher CMC complexity — correct heterodimerization and separation from homodimers are required.", how:"Read Liu et al. 2017 on bispecific antibody manufacturing challenges.", ref:"FDA Bispecific Antibody CMC Guidance | ICH Q11 | ICH Q6B" },
      { id:"dn06", level:"Advanced", q:"What are CAR-T cell therapies and what unique CMC challenges arise from autologous (patient-specific) manufacturing vs. allogeneic (off-the-shelf) approaches?", why:"CAR-T autologous manufacturing creates unprecedented CMC challenges: patient-specific production, chain of identity requirements, short shelf life.", how:"Read FDA guidance on CAR-T cell therapy CMC.", ref:"FDA Cell Therapy CMC Guidance | ICH Q11 | 21 CFR 1271" },
      { id:"dn07", level:"Expert", q:"How would you develop a CMC strategy for a first-in-class bispecific T-cell engager (BiTE format) entering Phase 1, considering the unique manufacturing, characterization, and regulatory challenges?", why:"BiTE-format bispecifics have unique CMC complexity: single-chain constructs, unique purification challenges, potency assays reflecting T-cell engagement.", how:"Read FDA bispecific antibody CMC guidance.", ref:"FDA Bispecific CMC Guidance | ICH Q11 | ICH Q6B" },
      { id:"dn08", level:"Expert", q:"What is the CMC regulatory framework for RNA interference (RNAi) therapeutics (siRNA, ASOs), and how does it differ from protein biologic and small molecule regulatory pathways?", why:"RNAi therapeutics are complex synthetic oligonucleotides requiring a CMC approach distinct from both biologics and small molecules.", how:"Read FDA guidance on oligonucleotide CMC.", ref:"FDA Oligonucleotide CMC Guidance | ICH Q11 | 21 CFR 312" },
    ]
  },
  { id:"dom_lead", label:"CMC Leadership", icon:"🏆", accent:"#FCD34D", desc:"CMC strategy, career development, COGS, regulatory strategy, cross-functional communication",
    questions:[
      { id:"dl01", level:"Foundational", q:"What is a CMC development plan and how does a CMC leader build one that links all CMC activities to a BLA submission critical path?", why:"CMC is on the critical path of every drug development program. A CMC development plan maps every activity to a timeline and identifies critical path risks.", how:"Ask your mentor to show you the CMC development plan for your current program.", ref:"FDA Phase 1–BLA CMC Guidances | ICH M4Q" },
      { id:"dl02", level:"Foundational", q:"What is CMC readiness and what criteria determine whether a program is ready to advance from Phase 1 to Phase 2, Phase 2 to Phase 3, and Phase 3 to BLA?", why:"Phase-gate decisions require CMC readiness criteria. CMC leaders must know what minimum CMC package is required at each gate.", how:"Read FDA Phase 1, 2/3 CMC guidances. Build a CMC readiness checklist for each development gate.", ref:"FDA Phase 1 CMC Guidance | FDA Phase 2/3 CMC Guidance | ICH M4Q" },
      { id:"dl03", level:"Intermediate", q:"What is cost of goods (COGS) for a biologic and how do CMC development decisions made in development affect commercial manufacturing economics?", why:"CMC decisions made in development have multi-decade cost implications. CMC leaders who understand COGS make better development investment decisions.", how:"Ask your mentor to explain COGS for one of your programs.", ref:"ISPE Baseline Guides on Facility Design and COGS" },
      { id:"dl04", level:"Intermediate", q:"How does a CMC leader effectively communicate a complex technical risk to a non-technical executive team, and what framework structures this communication?", why:"CMC leaders who cannot translate scientific complexity into business decisions are career-limited.", how:"Practice the SBAR framework (Situation, Background, Assessment, Recommendation).", ref:"ICH Q9 | CMC Leadership Communication Best Practices" },
      { id:"dl05", level:"Advanced", q:"What is CMC IP strategy for a biologic and how do trade secrets vs. patents interact with regulatory disclosure requirements?", why:"CMC IP strategy is a critical intersection of science, law, and regulatory affairs. Some process knowledge disclosed in the BLA cannot be protected as a trade secret.", how:"Research 12-year data exclusivity for biologics under BPCIA.", ref:"BPCIA Section 351(k) | FDA Biological Product Exclusivity | 35 USC Patents" },
      { id:"dl06", level:"Advanced", q:"What is a CMO governance model and how do sponsor-CMO quality agreements, technical oversight, and regulatory accountability work in practice?", why:"Most biologics are manufactured at CMOs for clinical supply. Understanding the sponsor-CMO governance model is essential for CMC leaders managing external manufacturing.", how:"Read FDA guidance on contract manufacturing. Ask your mentor: how is CMO oversight structured for our programs?", ref:"FDA Contract Manufacturing Guidance | ICH Q10 | 21 CFR 211" },
      { id:"dl07", level:"Expert", q:"If starting a new Phase 1 biologic program today with a BLA target in 5 years, what are the 10 most important CMC decisions you would make in the first 90 days and why?", why:"This synthesis question marks the transition from CMC scientist to CMC leader. The answer should integrate molecular biology, process development, analytical, formulation, regulatory, and COGS.", how:"Draft a 2-page CMC strategy memo. Ask your mentor to critique it.", ref:"All ICH Q Guidelines | FDA Phase 1–BLA CMC Guidances | ICH M4Q" },
      { id:"dl08", level:"Expert", q:"A major manufacturing quality crisis (e.g., aseptic fill contamination affecting a Phase 3 batch) requires simultaneous crisis management, regulatory notification, patient safety assessment, and executive communication. How do you lead the response?", why:"Manufacturing quality crises test every dimension of CMC leadership simultaneously — scientific judgment, regulatory knowledge, risk communication.", how:"Build a crisis management playbook: first 24 hours, first 7 days, first 30 days.", ref:"21 CFR 312.32 | 21 CFR 600.14 | FDA Safety Reporting Guidance | ICH Q10" },
    ]
  },
];

export const GLOSSARY = [
  { term:"BLA", def:"Biologics License Application — the FDA regulatory submission required for approval of a biologic drug in the US. CMC information is in Module 3 of the CTD.", cat:"Regulatory" },
  { term:"IND", def:"Investigational New Drug — the regulatory application allowing a sponsor to begin clinical trials in the US. CMC content escalates from Phase 1 through Phase 3.", cat:"Regulatory" },
  { term:"CTD", def:"Common Technical Document — the standardized format for regulatory submissions globally. Module 3 contains all CMC (quality) information.", cat:"Regulatory" },
  { term:"QOS", def:"Quality Overall Summary — the reviewer-friendly narrative preceding Module 3 in a CTD submission. The first document a regulatory reviewer reads.", cat:"Regulatory" },
  { term:"PAI", def:"Pre-Approval Inspection — FDA facility inspection during BLA review to verify cGMP compliance and that submitted data accurately reflects manufacturing operations.", cat:"Regulatory" },
  { term:"PAS", def:"Prior Approval Supplement — the highest-level post-approval regulatory filing category requiring FDA review and approval before implementation.", cat:"Regulatory" },
  { term:"CBE-30", def:"Changes Being Effected (30-day notification) — a regulatory filing category for moderate-risk post-approval changes. Sponsor may implement 30 days after FDA receipt.", cat:"Regulatory" },
  { term:"PACMP", def:"Post-Approval Change Management Protocol — a pre-agreed framework with regulators (ICH Q12) for managing anticipated future manufacturing changes, potentially converting PAS to CBE-30.", cat:"Regulatory" },
  { term:"EC", def:"Established Conditions — the subset of information filed in a BLA (per ICH Q12) that triggers a regulatory submission when changed. Everything outside ECs is operational flexibility.", cat:"Regulatory" },
  { term:"APQR", def:"Annual Product Quality Review — annual compilation of all commercial batch data, OOS/OOT results, deviations, change controls, stability data, and CPV trends. Required by 21 CFR 211.180(e).", cat:"Quality" },
  { term:"QTPP", def:"Quality Target Product Profile — a prospective summary of desired quality characteristics of a drug product ensuring desired quality, safety, and efficacy. The foundation of QbD.", cat:"QbD" },
  { term:"CQA", def:"Critical Quality Attribute — a physical, chemical, biological, or microbiological property that must be within an appropriate limit to ensure desired product quality, safety, and efficacy.", cat:"QbD" },
  { term:"CPP", def:"Critical Process Parameter — a process parameter whose variability has an impact on a CQA and therefore should be monitored or controlled to produce the desired quality.", cat:"QbD" },
  { term:"KPP", def:"Key Process Parameter — a parameter that affects process performance (yield, cycle time) but has no demonstrated impact on CQAs within the studied range.", cat:"QbD" },
  { term:"NOR", def:"Normal Operating Range — the target parameter range used in routine manufacturing. Narrower than the PAR, providing a guard band against specification failure.", cat:"QbD" },
  { term:"PAR", def:"Proven Acceptable Range — the wider range of a CPP demonstrated safe and effective by process characterization data. Operating within PAR does not require a regulatory filing.", cat:"QbD" },
  { term:"DoE", def:"Design of Experiments — a structured statistical approach to studying effects of multiple input variables simultaneously. Captures interaction effects that OFAT cannot.", cat:"QbD" },
  { term:"FMEA", def:"Failure Mode and Effects Analysis — a risk management tool analyzing potential failure modes (severity × occurrence × detectability) to prioritize risk mitigation.", cat:"QbD" },
  { term:"PAT", def:"Process Analytical Technology — a system for designing, analyzing, and controlling manufacturing through timely measurements of critical quality and performance attributes.", cat:"QbD" },
  { term:"MCB", def:"Master Cell Bank — a collection of cells of uniform composition prepared from a single source, stored under defined conditions. The irreplaceable genetic reference for the product.", cat:"Cell Science" },
  { term:"WCB", def:"Working Cell Bank — derived from one or more vials of the MCB, used for the production of all manufactured batches throughout the product lifecycle.", cat:"Cell Science" },
  { term:"PDL", def:"Population Doublings Limit — the number of cell population doublings from the MCB to end of production, used to express the extent of genetic stability studies.", cat:"Cell Science" },
  { term:"EOP", def:"End of Production — cells at the limit of the manufacturing duration, used to demonstrate genetic stability across the full production cycle.", cat:"Cell Science" },
  { term:"qP", def:"Specific Productivity — the rate of product formation per cell per unit time (pg/cell/day). A measure of cell-level efficiency independent of culture density.", cat:"Cell Science" },
  { term:"HCP", def:"Host Cell Proteins — proteins derived from the host cell used in manufacturing. A critical process-related impurity with immunogenicity and product stability implications.", cat:"Manufacturing" },
  { term:"Protein A", def:"A bacterial surface protein (from Staphylococcus aureus) used in chromatography to selectively capture mAbs via Fc region binding. The first and most important purification step.", cat:"Manufacturing" },
  { term:"LRF", def:"Log Reduction Factor — a measure of viral load reduction achieved by a process step. Calculated as log10(input virus titer / output virus titer).", cat:"Manufacturing" },
  { term:"UF/DF", def:"Ultrafiltration/Diafiltration — membrane filtration technique to concentrate and buffer-exchange purified drug substance to the formulation buffer at target concentration.", cat:"Manufacturing" },
  { term:"kLa", def:"Volumetric Mass Transfer Coefficient — a measure of oxygen transfer efficiency in a bioreactor. Critical for DO control and the primary scale-up challenge parameter.", cat:"Manufacturing" },
  { term:"CEX", def:"Cation Exchange Chromatography — binds positively charged proteins at low salt. Used in bind-elute mode for aggregate and HCP removal in polishing.", cat:"Manufacturing" },
  { term:"AEX", def:"Anion Exchange Chromatography — binds negatively charged impurities (DNA, endotoxin, viruses). Used in flow-through mode in mAb purification.", cat:"Manufacturing" },
  { term:"SEC", def:"Size-Exclusion Chromatography — separates molecules by size. Primary analytical method for aggregate and fragment characterization, with known limitations (dilution artifacts).", cat:"Analytical" },
  { term:"AUC", def:"Analytical Ultracentrifugation — biophysical technique for accurate aggregate and fragment quantification under near-native conditions. The gold standard orthogonal method to SEC.", cat:"Analytical" },
  { term:"icIEF", def:"Imaged Capillary Isoelectric Focusing — electrophoretic technique separating protein species by isoelectric point. Used for charge variant analysis of biologics.", cat:"Analytical" },
  { term:"MAM", def:"Multi-Attribute Monitoring — LC-MS based peptide mapping approach that simultaneously monitors multiple quality attributes (deamidation, oxidation, glycosylation) in a single analysis.", cat:"Analytical" },
  { term:"DAR", def:"Drug-to-Antibody Ratio — the average number of drug molecules conjugated per antibody in an ADC. A critical quality attribute affecting potency, PK, and safety.", cat:"Analytical" },
  { term:"OOS", def:"Out-of-Specification — a test result falling outside the established acceptance criteria. Requires Phase I (lab) and potentially Phase II (manufacturing) investigation per FDA 2006 guidance.", cat:"Quality" },
  { term:"OOT", def:"Out-of-Trend — a test result within specification but showing a concerning trend compared to historical data. Requires investigation and trending assessment per ICH Q10.", cat:"Quality" },
  { term:"CAPA", def:"Corrective and Preventive Action — actions taken to eliminate causes of an existing nonconformity and prevent recurrence. A core element of ICH Q10.", cat:"Quality" },
  { term:"PPQ", def:"Process Performance Qualification — Stage 2 of FDA's process validation lifecycle. Commercial-scale confirmation that the process design consistently produces acceptable product.", cat:"Validation" },
  { term:"CPV", def:"Continued Process Verification — Stage 3 of FDA's process validation lifecycle. Ongoing statistical monitoring of commercial manufacturing using control charts and Cpk/Ppk analysis.", cat:"Validation" },
  { term:"MACO", def:"Maximum Allowable Carryover — the maximum amount of residual product allowed in equipment after cleaning. Calculated using health-based exposure limits (PDE/ADE).", cat:"Validation" },
  { term:"SDM", def:"Scale-Down Model — a smaller-scale bioreactor or unit operation demonstrated to be representative of commercial manufacturing scale. All process characterization studies are conducted in the qualified SDM.", cat:"Validation" },
  { term:"PDE", def:"Permitted Daily Exposure — a health-based exposure limit used in cleaning validation MACO calculations. Replaces arbitrary 10 ppm and 0.001-dose criteria with toxicologically-justified limits.", cat:"Validation" },
  { term:"ADC", def:"Antibody-Drug Conjugate — a biologic consisting of a monoclonal antibody linked to a cytotoxic drug via a linker. One of the most CMC-complex molecular modalities.", cat:"Novel Modalities" },
  { term:"LNP", def:"Lipid Nanoparticle — a delivery vehicle for mRNA therapeutics, consisting of ionizable lipid, phospholipid, cholesterol, and PEGylated lipid. Requires ultra-low temperature storage.", cat:"Novel Modalities" },
  { term:"CAR-T", def:"Chimeric Antigen Receptor T-cell therapy — an autologous cell therapy where a patient's T-cells are genetically engineered to express a cancer-specific CAR. Creates unprecedented chain-of-identity CMC challenges.", cat:"Novel Modalities" },
];
