// src/compendial-data.js — USP/EP/JP/ICH cross-reference compendium

export const COMPENDIAL_METHODS = [
  {
    id: "sterility",
    test: "Sterility Testing",
    category: "safety",
    usp: "<71>",
    ep: "2.6.1",
    jp: "G4-2",
    ich: "ICH Q2A (method validation)",
    principle: "Membrane filtration (preferred for most products) or direct inoculation into Fluid Thioglycollate Medium (anaerobes) and Soybean-Casein Digest Medium (aerobes/fungi). Incubation 14 days at specified temps.",
    acceptance: "No microbial growth observed in test vessels at 14 days",
    product_types: ["Injectables", "Ophthalmics", "Implants", "Biologics"],
    notes: "Parametric release may replace end-product sterility testing for terminally sterilized products. SCDm method must show no growth in 14 days per USP <71>.",
    icon: "🦠",
    color: "#F472B6",
  },
  {
    id: "endotoxin",
    test: "Bacterial Endotoxins (LAL)",
    category: "safety",
    usp: "<85>",
    ep: "2.6.14",
    jp: "4.01",
    ich: "—",
    principle: "Limulus Amebocyte Lysate (LAL) test detects gram-negative bacterial endotoxins (lipopolysaccharides). Methods: gel-clot, turbidimetric (kinetic), chromogenic (kinetic or endpoint), recombinant Factor C (rFC) assay.",
    acceptance: "Product-specific EU/mL limit based on: Endotoxin Limit = K/M where K = 5 EU/kg/h (IV) or 0.5 EU/kg/h (intrathecal) and M = maximum dose/kg/h",
    product_types: ["All parenterals", "Medical devices", "Biologics"],
    notes: "Maximum Valid Dilution (MVD) = Endotoxin Limit × concentration / 0.125 (gel-clot) or lambda. IPC spike recovery 50–200% required.",
    icon: "🧫",
    color: "#F59E0B",
  },
  {
    id: "particulate-inj",
    test: "Particulate Matter in Injections",
    category: "physical",
    usp: "<788>",
    ep: "2.9.19",
    jp: "6.07",
    ich: "—",
    principle: "Light obscuration (particle counter) counts particles ≥10 µm and ≥25 µm per container. For small-volume preparations (<100 mL): alternate microscopic method available.",
    acceptance: "LVP (≥100 mL): ≤25 @ ≥10µm, ≤3 @ ≥25µm per mL. SVP (<100 mL): ≤6000 @ ≥10µm, ≤600 @ ≥25µm per container",
    product_types: ["Small molecule injectables", "IV solutions", "Parenterals"],
    notes: "Biological products use USP <787> with different limits. Visible particle inspection per USP <1> / EP 2.9.20 is separate test.",
    icon: "🔬",
    color: "#38BDF8",
  },
  {
    id: "particulate-bio",
    test: "Subvisible Particulates (Biologics)",
    category: "physical",
    usp: "<787>",
    ep: "2.9.19",
    jp: "—",
    ich: "ICH Q6B",
    principle: "Light obscuration OR micro-flow imaging (MFI) for proteinaceous particles. MFI preferred as it can morphologically distinguish protein aggregates from silicone oil or glass particles.",
    acceptance: "USP <787>: ≤6000 @ ≥10µm, ≤600 @ ≥25µm per container. More stringent than <788>.",
    product_types: ["mAbs", "Fusion proteins", "Vaccines", "Peptide injectables"],
    notes: "USP <787> was created specifically for biologics recognizing that protein particles behave differently. Resonant mass measurement (Archimedes) emerging for high-concentration mAbs.",
    icon: "🧬",
    color: "#A78BFA",
  },
  {
    id: "elemental-impurities",
    test: "Elemental Impurities",
    category: "purity",
    usp: "<232>/<233>",
    ep: "2.4.20",
    jp: "—",
    ich: "ICH Q3D",
    principle: "USP <232>: limits for 24 elemental impurities (4 classes). USP <233>: ICP-MS or ICP-OES procedures. ICH Q3D risk-based approach: PDEs for oral, parenteral, inhalation routes.",
    acceptance: "Class 1 (Cd, Pb, As, Hg): strictest PDEs. Route-dependent PDEs per ICH Q3D Table A.2.1",
    product_types: ["All drug products", "Biologics", "Drug substances"],
    notes: "ICH Q3D replaced USP <231> Heavy Metals test which was deemed insufficiently sensitive. ICP-MS preferred for low ppb detection. Risk assessment approach allows reduced testing if risk factors low.",
    icon: "⚗️",
    color: "#34D399",
  },
  {
    id: "residual-solvents",
    test: "Residual Solvents",
    category: "purity",
    usp: "<467>",
    ep: "5.4",
    jp: "2.46",
    ich: "ICH Q3C(R8)",
    principle: "GC headspace analysis for Class 1, 2, and 3 solvents. Class 1 (avoid): benzene 2 ppm, carbon tetrachloride 4 ppm. Class 2 (limit): acetonitrile 410 ppm, methanol 3000 ppm. Class 3 (low risk): acetone 5000 ppm.",
    acceptance: "Per ICH Q3C(R8) Appendix 1: PDE-based limits. Class 3: NMT 5000 ppm (option 1) or PDE 50 mg/day",
    product_types: ["All drug substances and products"],
    notes: "Water-soluble samples dissolved in water; water-insoluble in DMSO. Static headspace injection with GC-FID. Method must be validated for all Class 1/2 solvents used in synthesis.",
    icon: "🌡️",
    color: "#60A5FA",
  },
  {
    id: "dissolution",
    test: "Dissolution",
    category: "performance",
    usp: "<711>",
    ep: "2.9.3",
    jp: "6.10",
    ich: "ICH Q6A",
    principle: "Apparatus 1 (basket) or Apparatus 2 (paddle) most common. Paddle 50 or 75 rpm; basket 100 rpm. Media: 0.1N HCl, pH 4.5 acetate, pH 6.8 phosphate (BCS classification-driven). Enhanced: biorelevant FaSSIF/FeSSIF.",
    acceptance: "Q = amount dissolved at specified time. Q+5% at first timepoint; Q at second. BCS Class I/III fast-dissolve: ≥85% in 15 min",
    product_types: ["Oral solid dosage forms", "Modified release"],
    notes: "f2 similarity factor used for comparing dissolution profiles during SUPAC changes. Modified release: 3+ timepoints required. Dissolution may be used for in vitro–in vivo correlation (IVIVC).",
    icon: "💊",
    color: "#F59E0B",
  },
  {
    id: "disintegration",
    test: "Disintegration",
    category: "performance",
    usp: "<701>",
    ep: "2.9.1",
    jp: "6.09",
    ich: "—",
    principle: "Basket-rack assembly oscillating in liquid medium. Tablets/capsules must disintegrate completely (no residue on mesh) within specified time. Immediate release: 37±2°C in water or HCl.",
    acceptance: "Uncoated tablets: NMT 15 min. Enteric-coated: intact in 0.1N HCl for 2h; disintegrates in pH 6.8 buffer within 60 min. Suppositories: NMT 30 min at 37°C.",
    product_types: ["Tablets", "Capsules", "Suppositories"],
    notes: "Disintegration is a surrogate — not the same as dissolution. For buccal/sublingual tablets: 4 min or less. Hard shells: longer than soft gel. Disc may be added for floating tablets.",
    icon: "💊",
    color: "#34D399",
  },
  {
    id: "water-kf",
    test: "Water Determination (Karl Fischer)",
    category: "physical",
    usp: "<921>",
    ep: "2.5.12",
    jp: "2.48",
    ich: "ICH Q6A",
    principle: "Volumetric KF (>1% water): iodine/sulfur dioxide titration. Coulometric KF (<1% water): electrochemically generated iodine. Karl Fischer reaction: H₂O + I₂ + SO₂ + ROH + base → sulfate ester + HI (neutralized). Reaction stoichiometry 1:1 water:iodine.",
    acceptance: "Product-specific NMT limit. Typical: API NMT 0.5%; lyophilized product NMT 2–3%",
    product_types: ["Drug substances", "Lyophilized biologics", "Hygroscopic solids"],
    notes: "Volumetric: sample dissolved in Karl Fischer solvent. Coulometric: sample dissolved or titrated with direct electrode generation. Oven/pyrolysis KF for insoluble materials. Interferences: aldehydes, ketones, ascorbic acid.",
    icon: "💧",
    color: "#38BDF8",
  },
  {
    id: "lod",
    test: "Loss on Drying",
    category: "physical",
    usp: "<731>",
    ep: "2.2.32",
    jp: "2.41",
    ich: "—",
    principle: "Sample dried at specified temperature (typically 105°C) and/or reduced pressure until constant weight. LOD includes water and volatile solvents. Gravimetric measurement of weight loss.",
    acceptance: "Product-specific NMT limit (e.g., NMT 1.0% for many APIs). Temperature/time/conditions specified in individual monograph.",
    product_types: ["Drug substances", "Excipients", "Solid dosage forms"],
    notes: "Less specific than KF (includes volatile solvents). Cannot distinguish water from other volatiles. Preferred for non-hygroscopic materials or when KF interferences present. Oven or desiccator drying.",
    icon: "🌡️",
    color: "#A78BFA",
  },
  {
    id: "ph",
    test: "pH Measurement",
    category: "physical",
    usp: "<791>",
    ep: "2.2.3",
    jp: "2.54",
    ich: "—",
    principle: "Potentiometric measurement using glass electrode + reference electrode (calomel or Ag/AgCl). pH = -log[H⁺]. Calibrate with 2–3 certified buffer standards bracketing expected pH range. Temperature compensation required.",
    acceptance: "Product-specific range (e.g., 6.8–7.2 for IV formulations). Narrow range (±0.3) typical for biologics.",
    product_types: ["All liquid drug products", "Reconstituted powders", "Biologics"],
    notes: "Calibration buffers must be within 2 pH units of measurement. Response linearity ≥96.5% Nernst factor. Temperature-compensated electrode preferred. Air equilibration can shift pH in CO₂-sensitive products.",
    icon: "📊",
    color: "#F472B6",
  },
  {
    id: "osmolality",
    test: "Osmolality",
    category: "physical",
    usp: "<785>",
    ep: "2.2.35",
    jp: "2.47",
    ich: "—",
    principle: "Freezing point osmometry (primary method): freezing point depression ΔTf = 1.86°C per osmolal. Vapor pressure osmometry: alternative. Calibrate with NaCl standards.",
    acceptance: "Isotonic parenterals: 270–330 mOsm/kg. Ophthalmic: 290–330 mOsm/kg. Hypertonic/hypotonic as specified.",
    product_types: ["Injectables", "Ophthalmics", "Dialysis solutions"],
    notes: "Osmolality (mOsm/kg solvent) vs. osmolarity (mOsm/L solution). Clinical important: iso-osmotic reduces injection site pain and hemolysis. Sample size: typically 20–150 µL.",
    icon: "⚗️",
    color: "#60A5FA",
  },
  {
    id: "aerosol-ddp",
    test: "Aerosols — Delivered Dose",
    category: "performance",
    usp: "<601>",
    ep: "2.9.18",
    jp: "—",
    ich: "ICH Q8",
    principle: "Delivered dose uniformity (DDU): individual actuations collected in impactor or dose collection tube, assayed by HPLC. Aerodynamic particle size distribution (APSD): Andersen cascade impactor (ACI) or next-generation impactor (NGI) classifies particles by aerodynamic diameter.",
    acceptance: "DDU: NLT 75% and NMT 125% of label dose per actuation (individual); mean within ±15%. APSD: fine particle fraction/mass (FPF/FPM) as per label claim.",
    product_types: ["MDI", "DPI", "Nasal sprays", "Inhalation solutions"],
    notes: "In vitro-in vivo correlation for inhalation products is developing area. Critical quality attribute: fine particle dose (FPD) for lung deposition. Inhalation: particles ≤5 µm reach lower airways.",
    icon: "💨",
    color: "#FB923C",
  },
  {
    id: "viscosity",
    test: "Viscosity",
    category: "physical",
    usp: "<912>",
    ep: "2.2.8",
    jp: "2.53",
    ich: "—",
    principle: "Kinematic viscosity: Ubbelohde or Cannon-Fenske capillary viscometer (ν = η/ρ). Dynamic viscosity: rotational viscometry (Brookfield, cone-and-plate). Rheology: oscillatory measurement for viscoelastic characterization.",
    acceptance: "Product-specific. Ophthalmics: typically 15–25 cP. HiConc mAb: can exceed 50 cP at ≥150 mg/mL — limits injectability.",
    product_types: ["Ophthalmics", "High-concentration biologics", "Topicals", "Sustained release"],
    notes: "High viscosity in concentrated mAb formulations is a major developability challenge. Arginine, NaCl, and other viscosity-reducing excipients used. Measured at relevant temperature (25°C or body temperature).",
    icon: "💧",
    color: "#34D399",
  },
  {
    id: "optical-rotation",
    test: "Optical Rotation / Specific Rotation",
    category: "identity",
    usp: "<781>",
    ep: "2.2.7",
    jp: "2.42",
    ich: "ICH Q6A",
    principle: "Polarimetry: plane-polarized light rotated by chiral compounds. α = observed rotation. Specific rotation [α]²⁰D = α/(l×c) where l = path length (dm), c = concentration (g/100 mL). Sodium D-line (589 nm) standard.",
    acceptance: "Compendial specific rotation range (e.g., insulin: [α]²⁰D = −61° to −67°)",
    product_types: ["Chiral APIs", "Natural product derivatives", "Amino acids", "Sugars"],
    notes: "ICH Q6A: chirality must be addressed. Optical rotation is identity test but not sufficient alone for chiral purity — requires chiral HPLC. Thalidomide case study demonstrates in vivo racemization issue.",
    icon: "🔮",
    color: "#A78BFA",
  },
  {
    id: "residue-ignition",
    test: "Residue on Ignition (Sulfated Ash)",
    category: "purity",
    usp: "<281>",
    ep: "2.4.14",
    jp: "2.44",
    ich: "ICH Q6A",
    principle: "Ignite sample at ≥600°C in sulfuric acid to ash. Measures inorganic residue (metal salts, mineral impurities). Gravimetric endpoint. Repeated treatment with H₂SO₄ and ignition until constant weight.",
    acceptance: "API: NMT 0.1% for most; NMT 0.05% for high-purity compounds",
    product_types: ["Drug substances", "Excipients"],
    notes: "More specific than loss on ignition (no H₂SO₄). Detects metallic impurities not caught by elemental analysis. Precursor to ICH Q3D implementation — historically was the sole metal impurity test.",
    icon: "🔥",
    color: "#F59E0B",
  },
  {
    id: "microbial-limits",
    test: "Microbial Enumeration / Microbial Limits",
    category: "safety",
    usp: "<61>/<62>",
    ep: "2.6.12/2.6.13",
    jp: "G3-1/G3-2",
    ich: "—",
    principle: "USP <61>: TAMC (total aerobic microbial count) and TYMC (total yeast & mold count) by pour plate or membrane filtration. USP <62>: tests for specified organisms (E. coli, Salmonella, Staphylococcus aureus, Pseudomonas aeruginosa, Bile-tolerant gram-negative bacteria).",
    acceptance: "Non-sterile oral: TAMC ≤1000 CFU/g; TYMC ≤100 CFU/g; absent E. coli. Aqueous preparations: TAMC ≤100; TYMC ≤10. Specified organisms: absent in defined sample quantity.",
    product_types: ["Non-sterile oral solids and liquids", "Topicals", "Excipients"],
    notes: "Suitability testing (method validation) required: each organism recovery ≥70% in presence of product matrix. Neutralization of preservatives (e.g., inactivators for benzalkonium chloride). R2A agar for slow-growing organisms.",
    icon: "🦠",
    color: "#34D399",
  },
  {
    id: "assay-hplc",
    test: "Chromatography (HPLC)",
    category: "purity",
    usp: "<621>",
    ep: "2.2.29",
    jp: "2.01",
    ich: "ICH Q2(R1)",
    principle: "System suitability requirements: tailing factor ≤2.0; theoretical plates ≥2000; RSD of standard ≤1.0% (5 injections); resolution ≥2.0 between critical pair. Detector: UV, DAD, fluorescence, MS, ELSD per application.",
    acceptance: "Method-specific. Assay: acceptance criteria per specification. Impurities: reporting threshold, identification threshold, qualification threshold per ICH Q3B.",
    product_types: ["All drug substances and products"],
    notes: "ICH Q2(R1) validation: accuracy, precision, specificity, LOD/LOQ, linearity, range, robustness. USP <621> covers HPLC system suitability. ICH Q14 (new): analytical procedure development.",
    icon: "📈",
    color: "#38BDF8",
  },
  {
    id: "color-clarity",
    test: "Color and Clarity of Solutions",
    category: "physical",
    usp: "<631>/<1351>",
    ep: "2.2.1/2.2.2",
    jp: "2.09",
    ich: "—",
    principle: "Color: visual comparison to reference color standards (BY, Y, GY, B, R color scales). Clarity: comparison to opalescence reference suspension (formazin or silica suspension as reference). Absorbance measurement at 400–450 nm for quantitative color.",
    acceptance: "Parenteral: 'Practically colorless' = ≤B7/Y7 or A450 ≤0.05. Clarity: 'Clear' = opalescence not exceeding reference I standard.",
    product_types: ["Injectable solutions", "Biologics", "Oral liquids"],
    notes: "Routine release test for injectables. Color shift can indicate oxidation (protein Met oxidation, product degradation). Near-UV turbidity at 340 nm used for protein aggregation monitoring.",
    icon: "🔭",
    color: "#A78BFA",
  },
];

export const COMPENDIAL_CATEGORIES = [
  { id: "all", label: "All Tests", icon: "📗" },
  { id: "safety", label: "Safety", icon: "🛡️" },
  { id: "purity", label: "Purity", icon: "🧪" },
  { id: "physical", label: "Physical", icon: "📐" },
  { id: "performance", label: "Performance", icon: "⚡" },
  { id: "identity", label: "Identity", icon: "🔍" },
];

export const COMPENDIAL_PRODUCT_TYPES = [
  "All",
  "Injectables",
  "mAbs",
  "Oral solid dosage forms",
  "Drug substances",
  "Biologics",
  "Ophthalmics",
];
