// src/excipient-data.js — Excipient compatibility and formulation data

export const EXCIPIENTS = [
  {
    id: "ps20",
    name: "Polysorbate 20",
    abbrev: "PS20",
    cas: "9005-64-5",
    class: "Surfactant",
    icon: "🧴",
    color: "#38BDF8",
    primary_function: "Prevent interfacial aggregation; solubilization",
    product_types: ["mAb liquid", "Lyophilized biologic", "Vaccine"],
    conc_range: { mAb_liquid: "0.01–0.1% w/v", lyophilized: "0.01–0.05% w/v" },
    mechanism: "Non-ionic surfactant; HLB ~17; monolaurate ester of sorbitol + PEO. Reduces surface/interfacial tension. Preferentially adsorbs at air-water and water-container interfaces.",
    degradation: "Oxidative cleavage at unsaturated fatty acid ester bonds; hydrolysis by esterases (HCPs). Forms lyso-PS20 + free fatty acids (lauric acid mainly). Less susceptible than PS80 due to saturated laurate.",
    regulatory: "Ph. Eur. 0427; NF 19; GRAS; ICH Q3D exempt",
  },
  {
    id: "ps80",
    name: "Polysorbate 80",
    abbrev: "PS80",
    cas: "9005-65-6",
    class: "Surfactant",
    icon: "🧴",
    color: "#60A5FA",
    primary_function: "Prevent interfacial aggregation; solubilization",
    product_types: ["mAb liquid", "Lyophilized biologic", "Small molecule injectable"],
    conc_range: { mAb_liquid: "0.02–0.1% w/v", lyophilized: "0.01–0.05% w/v" },
    mechanism: "Non-ionic surfactant; HLB ~15; mono-oleate ester of sorbitol + PEO. More effective than PS20 for hydrophobic protein stabilization.",
    degradation: "Oxidative cleavage at oleate double bond (C18:1); hydrolysis generates oleic acid (major) + other FFAs. Oleic acid insoluble → generates visible/subvisible particles. Also autooxidation via peroxide formation.",
    regulatory: "Ph. Eur. 0428; NF 20; GRAS; ICH Q3D exempt",
  },
  {
    id: "sucrose",
    name: "Sucrose",
    abbrev: "Sucrose",
    cas: "57-50-1",
    class: "Lyoprotectant / Cryoprotectant",
    icon: "🍬",
    color: "#F472B6",
    primary_function: "Cryo/lyoprotection; bulking agent",
    product_types: ["Lyophilized biologic", "Liquid biologic"],
    conc_range: { lyophilized: "5–10% w/v (in solution pre-lyo)", liquid_biologic: "5–10% w/v" },
    mechanism: "Vitrification theory (glass formation); water replacement hypothesis. Hydrogen bonding to protein surface hydroxyl/amino groups during freeze/drying replaces water of hydration.",
    degradation: "Maillard reaction with amines at elevated temp/pH. Acid hydrolysis to glucose + fructose (invert sugar) at low pH. Maillard products (Amadori) can covalently modify protein.",
    regulatory: "Ph. Eur. 0204; USP-NF; GRAS",
  },
  {
    id: "trehalose",
    name: "Trehalose",
    abbrev: "Trehalose",
    cas: "6138-23-4",
    class: "Lyoprotectant / Cryoprotectant",
    icon: "🌿",
    color: "#34D399",
    primary_function: "Cryo/lyoprotection; preferred over sucrose for mAb lyo",
    product_types: ["Lyophilized biologic"],
    conc_range: { lyophilized: "5–10% w/v (pre-lyo solution)" },
    mechanism: "Same as sucrose (vitrification + water replacement). Higher glass transition temperature (Tg') than sucrose; more chemically stable (α,α-1,1 glycosidic bond resistant to acid hydrolysis). No reducing end → no Maillard.",
    degradation: "Very resistant to chemical degradation. Slight hygroscopicity. Non-reducing — no Maillard with amines.",
    regulatory: "NF 26; GRAS; widely used in biologic lyophilizates",
  },
  {
    id: "mannitol",
    name: "Mannitol",
    abbrev: "Mannitol",
    cas: "69-65-8",
    class: "Bulking Agent / Tonicity Agent",
    icon: "🧊",
    color: "#A78BFA",
    primary_function: "Bulking agent (lyophilized cake structure); isotonicity",
    product_types: ["Lyophilized biologic", "Small molecule injectable", "Oral solid"],
    conc_range: { lyophilized: "1–4% w/v", injectable: "5% w/v (isotonic)", oral_solid: "up to 80% w/w" },
    mechanism: "Crystalline bulking agent; forms elegant cake in lyophilizate. Provides mechanical structure but is NOT a good lyoprotectant alone. Must be combined with amorphous lyoprotectant (sucrose/trehalose). Tonicity contribution: ~285 mOsm at 5%.",
    degradation: "Very stable. Can crystallize during freeze-drying (good for cake structure). Mannitol crystallization can exclude protein from amorphous phase if no amorphous stabilizer present → aggregation risk.",
    regulatory: "Ph. Eur. 0559; USP-NF; GRAS",
  },
  {
    id: "histidine",
    name: "L-Histidine HCl",
    abbrev: "His-HCl",
    cas: "645-35-2",
    class: "Buffer",
    icon: "🔬",
    color: "#F59E0B",
    primary_function: "pH buffer (pH 5.5–6.5); antioxidant (singlet O₂ quenching)",
    product_types: ["mAb liquid", "Lyophilized biologic"],
    conc_range: { mAb_liquid: "10–25 mM", lyophilized: "10–20 mM" },
    mechanism: "Imidazole ring pKa 6.04 (buffering range pH 5.5–7.0). Preferred buffer for mAbs — does not crystallize during lyophilization (unlike phosphate/citrate). Dual role: buffer + radical scavenger. Inhibits metal-catalyzed oxidation.",
    degradation: "Imidazole susceptible to oxidation (especially photooxidation, singlet O₂). Histidine oxidation products can accumulate in oxidatively stressed formulations.",
    regulatory: "Ph. Eur. 0699; USP-NF amino acid monograph; GRAS",
  },
  {
    id: "citrate",
    name: "Citrate Buffer",
    abbrev: "Citrate",
    cas: "77-92-9",
    class: "Buffer",
    icon: "🍋",
    color: "#FBBF24",
    primary_function: "pH buffer (pH 3.5–5.5); chelating agent",
    product_types: ["mAb liquid (low pH)", "Small molecule injectable", "Oral liquid"],
    conc_range: { mAb_liquid: "10–25 mM", injectable: "5–50 mM" },
    mechanism: "Triprotic acid: pKa 3.13, 4.76, 6.40. Effective buffer pH 3.0–6.5. Chelates divalent metal cations (Ca²⁺, Mg²⁺, Cu²⁺) — antioxidant via metal chelation. Can cause injection site burning if >25 mM.",
    degradation: "Stable. Can crystallize during lyophilization → pH shift upon reconstitution ('pH excursion' issue).",
    regulatory: "Ph. Eur. 0456; USP-NF; GRAS",
  },
  {
    id: "phosphate",
    name: "Phosphate Buffer",
    abbrev: "PBS / NaPhos",
    cas: "7558-79-4",
    class: "Buffer",
    icon: "🔵",
    color: "#38BDF8",
    primary_function: "pH buffer (pH 6.0–8.0); isotonic formulation",
    product_types: ["Small molecule injectable", "Diagnostic buffers", "Oral liquid"],
    conc_range: { injectable: "10–100 mM", oral_liquid: "50–100 mM" },
    mechanism: "Diprotic: pKa 2.15, 7.20, 12.35. Second pKa ideal for physiological pH buffering. Combined with NaCl → phosphate-buffered saline (PBS) isotonic at 150 mM NaCl + 10 mM phosphate.",
    degradation: "Crystallizes as calcium phosphate during lyophilization at high concentrations → severe pH drop (pH 3–4) upon reconstitution. Incompatible with Ca²⁺ and Mg²⁺ at high concentrations.",
    regulatory: "Ph. Eur. / USP-NF; GRAS",
  },
  {
    id: "arginine",
    name: "L-Arginine",
    abbrev: "Arg / Arg-HCl",
    cas: "74-79-3",
    class: "Stabilizer / Viscosity Reducer",
    icon: "💊",
    color: "#C084FC",
    primary_function: "Solubility enhancer; viscosity reducer for high-conc mAb; aggregation inhibitor",
    product_types: ["mAb liquid", "High-concentration subcutaneous mAb"],
    conc_range: { mAb_liquid: "50–150 mM", sc_mab: "100–200 mM" },
    mechanism: "Guanidinium-like side chain interacts with exposed hydrophobic patches of protein. Reduces protein-protein interactions → lower viscosity. Also enhances refolding of denatured proteins. Tonicity contribution significant at high concentrations.",
    degradation: "Susceptible to Maillard reaction with reducing sugars (avoid combination with lactose/glucose). Arginine + glucose → browning at elevated temps.",
    regulatory: "Ph. Eur. 0505; USP-NF amino acid; GRAS",
  },
  {
    id: "nacl",
    name: "Sodium Chloride",
    abbrev: "NaCl",
    cas: "7647-14-5",
    class: "Tonicity Agent",
    icon: "🧂",
    color: "#94A3B8",
    primary_function: "Isotonicity adjustment; solubility modifier",
    product_types: ["All injectables", "Ophthalmic", "Nasal"],
    conc_range: { injectable: "0–150 mM", isotonic: "0.9% w/v (154 mM)" },
    mechanism: "Provides osmolality. Colligative property: ~2 osmoles per mole NaCl. Low NaCl can destabilize mAbs via salting-in (increased solubility of hydrophobic regions); high NaCl at some proteins can increase aggregation via salting-out.",
    degradation: "Stable. Very hygroscopic in dry form. Compatible with most excipients at physiological concentrations.",
    regulatory: "Ph. Eur. 0193; USP-NF; GRAS",
  },
  {
    id: "edta",
    name: "EDTA (Disodium)",
    abbrev: "EDTA",
    cas: "139-33-3",
    class: "Chelating Agent / Antioxidant",
    icon: "⛓️",
    color: "#34D399",
    primary_function: "Metal chelation; antioxidant protection; antimicrobial potentiator",
    product_types: ["mAb liquid", "Small molecule injectable", "Ophthalmic"],
    conc_range: { injectable: "0.05–0.1 mM", ophthalmic: "0.01–0.1% w/v" },
    mechanism: "Hexadentate chelator; binds Cu²⁺, Fe²⁺/³⁺, Zn²⁺ with high affinity (log K ~18 for Cu). Prevents Fenton/Haber-Weiss metal-catalyzed oxidation (H₂O₂ + Fe²⁺ → •OH). Also increases membrane permeability of gram-negative bacteria (antimicrobial potentiator).",
    degradation: "Stable at physiological conditions. Photodegradation possible at high UV exposure.",
    regulatory: "Ph. Eur. 1004; USP-NF; GRAS (at low concentrations)",
  },
  {
    id: "benzyl-alcohol",
    name: "Benzyl Alcohol",
    abbrev: "BnOH",
    cas: "100-51-6",
    class: "Antimicrobial Preservative",
    icon: "🔬",
    color: "#F472B6",
    primary_function: "Antimicrobial preservative in multidose vials",
    product_types: ["Multidose injectable vials", "Small molecule injectables"],
    conc_range: { multidose_vial: "0.9–1.0% w/v" },
    mechanism: "Lipophilic — disrupts bacterial cell membranes. Effective against gram-positive bacteria, less against gram-negative. Bacteriostatic. Oxidizes to benzaldehyde then benzoic acid.",
    degradation: "Oxidizes to benzaldehyde (aldehyde — Maillard risk with amines) and then benzoic acid. Photooxidation accelerated. Incompatible with oxidizing agents.",
    regulatory: "Ph. Eur. 0256; USP-NF; FDA warning: avoid in neonates (gasping syndrome at >99 mg/kg/day)",
  },
  {
    id: "peg3350",
    name: "PEG 3350",
    abbrev: "PEG 3350",
    cas: "25322-68-3",
    class: "Polymeric Excipient / Laxative",
    icon: "🔗",
    color: "#60A5FA",
    primary_function: "Osmotic laxative; protein precipitant; coating polymer",
    product_types: ["Oral liquid", "Protein crystallization", "Film coating"],
    conc_range: { oral_liquid: "17 g/dose", protein_cryst: "10–20% w/v" },
    mechanism: "Hydrophilic polymer; excluded volume effect precipitates proteins at high concentrations. As laxative: non-absorbed, osmotically draws water into colon. Incompatible with strong oxidizing agents.",
    degradation: "Peroxide impurities in PEG can oxidize proteins — critical for biologic compatibility. Specify peroxide limit for PEG used in biologics.",
    regulatory: "Ph. Eur. 1444; USP-NF; GRAS; FDA-approved laxative",
  },
  {
    id: "hpmc",
    name: "Hydroxypropyl Methylcellulose",
    abbrev: "HPMC / Hypromellose",
    cas: "9004-65-3",
    class: "Polymer / Viscosity Modifier / Film Coat",
    icon: "🌾",
    color: "#A78BFA",
    primary_function: "Film coating; matrix former for ER tablets; viscosity builder; ophthalmic lubricant",
    product_types: ["Oral solid (film coat/ER matrix)", "Ophthalmic drops", "Capsule shell"],
    conc_range: { film_coat: "2–5% w/w coating", er_matrix: "10–40% w/w tablet", ophthalmic: "0.5–1.0% w/v" },
    mechanism: "Cellulose ether — methoxyl and hydroxypropyl substitution determines solubility, Tg, and gel temperature. HPMC E type: immediate release film coat. HPMC K type: higher viscosity, controlled release matrix. Gels on heating (thermoreversible).",
    degradation: "Very stable. Slight reduction in viscosity with prolonged heating. Compatible with most APIs. Some grades contain trace metal impurities.",
    regulatory: "Ph. Eur. 0346; USP-NF 'Hypromellose'; GRAS; widely used in capsule shells (HPMC caps)",
  },
  {
    id: "croscarmellose",
    name: "Croscarmellose Sodium",
    abbrev: "CCS / Ac-Di-Sol",
    cas: "74811-65-7",
    class: "Superdisintegrant",
    icon: "💊",
    color: "#FB923C",
    primary_function: "Tablet disintegration acceleration via swelling and wicking",
    product_types: ["Oral tablet (IR)", "Capsule fill"],
    conc_range: { tablet_intragranular: "1–4% w/w", extragranular: "0.5–2% w/w" },
    mechanism: "Cross-linked sodium carboxymethylcellulose. Swells 4–8× in water by absorption. Wicking action draws water into tablet matrix. Disintegration time typically <5 min at 2% w/w.",
    degradation: "Incompatible with strongly acidic conditions (loses swelling capacity). Avoid with highly water-soluble drugs (bridging effect). Metal salt incompatibility possible due to carboxylate groups.",
    regulatory: "Ph. Eur. 0985; USP-NF; GRAS",
  },
  {
    id: "mg-stearate",
    name: "Magnesium Stearate",
    abbrev: "MgSt",
    cas: "557-04-0",
    class: "Lubricant",
    icon: "🔩",
    color: "#94A3B8",
    primary_function: "Tablet/capsule lubrication; anti-sticking; glidant (minor)",
    product_types: ["Oral tablet", "Oral capsule fill"],
    conc_range: { tablet: "0.25–1.5% w/w" },
    mechanism: "Hydrophobic fatty acid salt. Coats particles and punch faces → reduced friction during compression. Hydrophobic coating delays tablet wetting and dissolution. Excessive MgSt → slower dissolution. Shear-sensitive: over-mixing degrades performance.",
    degradation: "Incompatible with strong acids (liberate Mg²⁺ + stearic acid). Can interact with some APIs via ionic exchange. Incompatible with aspirin (saponification). Oxidizing agents degrade stearate.",
    regulatory: "Ph. Eur. 0229; USP-NF; GRAS; concentration critical — NMT 1% typically",
  },
  {
    id: "mcc",
    name: "Microcrystalline Cellulose",
    abbrev: "MCC / Avicel",
    cas: "9004-34-6",
    class: "Filler / Binder / Disintegrant",
    icon: "🌾",
    color: "#34D399",
    primary_function: "Direct compression filler-binder; tablet matrix structure; disintegrant",
    product_types: ["Oral tablet", "Oral capsule fill"],
    conc_range: { tablet_filler: "up to 80% w/w", capsule: "as needed to fill" },
    mechanism: "Defibrillated cellulose; compressible due to hydrogen bonding during compression. Excellent binding capacity, moderate disintegration (capillary action). PH-101 (fine, 50µm) for WG; PH-102 (medium, 100µm) for DC. PH-200 for capsule fill.",
    degradation: "Very stable chemically. Minor moisture absorption but generally non-reactive. Not hydrolyzed under normal conditions. Compatible with most APIs and excipients.",
    regulatory: "Ph. Eur. 0316; USP-NF; GRAS",
  },
  {
    id: "lactose",
    name: "Lactose Monohydrate",
    abbrev: "Lactose",
    cas: "64044-51-5",
    class: "Filler / Diluent",
    icon: "🥛",
    color: "#F59E0B",
    primary_function: "Tablet/capsule filler; DPI carrier particle",
    product_types: ["Oral solid", "DPI (carrier)"],
    conc_range: { tablet: "up to 80% w/w", dpi_carrier: "up to 99.9% w/w" },
    mechanism: "Disaccharide (galactose + glucose). Monohydrate form preferred for stability. Flow and compressibility grade-dependent. Spray-dried lactose: DC grade. Alpha-lactose monohydrate: wet granulation. Used in DPI as coarse carrier (~63–212 µm) for micronized drug.",
    degradation: "Reducing sugar — MAJOR Maillard reactant with primary amines (APIs, amino acid excipients). React with Lys, Arg, N-termini → brown discoloration. Incompatible with: arginine, lysine-containing APIs, amine-bearing small molecules (amlodipine), benzyl alcohol.",
    regulatory: "Ph. Eur. 1061; USP-NF; GRAS; widely used but reducing sugar incompatibility is critical concern",
  },
];

export const INCOMPATIBILITIES = [
  {
    id: "inc-1",
    excipient1: "lactose",
    excipient2: "arginine",
    severity: "avoid",
    color: "#F472B6",
    mechanism: "Maillard reaction: reducing aldehyde of lactose reacts with guanidinium/amine group of arginine → Amadori products → brown discoloration and loss of arginine/drug activity",
    mitigation: "Replace lactose with non-reducing sugar (mannitol, microcrystalline cellulose, DCPD). Use trehalose or sucrose if sugar required.",
    refs: "Maillard LC (1912); USP general notices; Wirth DD et al. J Pharm Sci 1998",
  },
  {
    id: "inc-2",
    excipient1: "lactose",
    excipient2: "benzyl-alcohol",
    severity: "caution",
    color: "#F59E0B",
    mechanism: "Benzyl alcohol oxidizes to benzaldehyde which can condense with primary amines (Maillard-like Schiff base formation). Additionally lactose reducing aldehyde adds to amine-bearing drugs.",
    mitigation: "Monitor for discoloration and impurity formation. Consider alternative preservative (phenol, thimerosal) or different excipient.",
    refs: "Pharmaceutical degradation chemistry review",
  },
  {
    id: "inc-3",
    excipient1: "mg-stearate",
    excipient2: "aspirin",
    severity: "avoid",
    color: "#F472B6",
    mechanism: "Base-catalyzed saponification: magnesium stearate (basic pH) catalyzes hydrolysis of aspirin ester bond → acetic acid + salicylate. Accelerated in humid conditions. Significant potency loss.",
    mitigation: "Use sodium stearyl fumarate or glyceryl behenate as lubricant alternative. Minimize MgSt level and mixing time if required.",
    refs: "Tsai T et al. Drug Dev Ind Pharm 1994",
  },
  {
    id: "inc-4",
    excipient1: "ps80",
    excipient2: "peg3350",
    severity: "caution",
    color: "#F59E0B",
    mechanism: "PEG peroxide impurities promote PS80 oxidative degradation, generating free oleic acid → subvisible particles in biologic formulations. Effect depends on PEG peroxide content.",
    mitigation: "Specify peroxide limit for PEG (<10 ppm). Antioxidant (methionine) may provide protection. Use low-peroxide PEG grades.",
    refs: "Doshi N et al. J Pharm Sci 2015",
  },
  {
    id: "inc-5",
    excipient1: "phosphate",
    excipient2: "nacl",
    severity: "monitor",
    color: "#34D399",
    mechanism: "At high concentrations during lyophilization, disodium hydrogen phosphate crystallizes preferentially → remaining solution enriched in monosodium phosphate → pH drops from 7.4 to <4 upon reconstitution. Effect amplified by NaCl crystallization.",
    mitigation: "Use histidine or citrate buffer for lyophilized products. Limit phosphate concentration <25 mM. Use histidine as primary buffer for mAb lyophilizates.",
    refs: "Williams NA, Guglielmo J. PDA J Pharm Sci Technol 1993",
  },
  {
    id: "inc-6",
    excipient1: "edta",
    excipient2: "citrate",
    severity: "monitor",
    color: "#34D399",
    mechanism: "Both are chelating agents — redundant chelation can significantly reduce free divalent metal ion concentration, potentially affecting enzyme-dependent biological assays or metal-dependent biological activity.",
    mitigation: "Use either chelator, not both. If both required, confirm no interference with product activity assay.",
    refs: "General formulation chemistry",
  },
  {
    id: "inc-7",
    excipient1: "benzyl-alcohol",
    excipient2: "ps80",
    severity: "caution",
    color: "#F59E0B",
    mechanism: "Benzyl alcohol (preservative) at >0.5% can cause protein aggregation/unfolding by competing with PS80 for protein surface. Both affect protein-surfactant interactions.",
    mitigation: "Concentration-dependent. Ensure PS80 concentration sufficient to counteract benzyl alcohol protein-destabilization. Validate formulation with aggregation testing.",
    refs: "Zbacnik TJ et al. J Pharm Sci 2017",
  },
  {
    id: "inc-8",
    excipient1: "mannitol",
    excipient2: "sucrose",
    severity: "monitor",
    color: "#34D399",
    mechanism: "In lyophilized products, mannitol crystallization during annealing can exclude sucrose from amorphous phase. If sucrose-to-protein ratio insufficient, protein aggregation during lyophilization possible.",
    mitigation: "Maintain sucrose:protein mass ratio ≥1:1. Optimize annealing step to control mannitol crystallization kinetics. Verify by DSC (Tg of amorphous phase) and XRPD.",
    refs: "Carpenter JF et al. Pharm Res 1997; Chang BS et al. Pharm Res 1996",
  },
  {
    id: "inc-9",
    excipient1: "histidine",
    excipient2: "ps20",
    severity: "monitor",
    color: "#34D399",
    mechanism: "Histidine can sensitize PS20 to photooxidation via singlet oxygen generation from His photooxidation products. Under light stress, His + PS20 combination may show greater PS20 degradation than PS20 alone.",
    mitigation: "Light protection for histidine/PS20 mAb formulations (amber vials, light-protected packaging). Ensure light protection during manufacturing and storage.",
    refs: "Research in photostability of mAb formulations",
  },
  {
    id: "inc-10",
    excipient1: "croscarmellose",
    excipient2: "mg-stearate",
    severity: "caution",
    color: "#F59E0B",
    mechanism: "Excessive magnesium stearate coats CCS particles, reducing their water absorption capacity and swelling. Reduces disintegration efficiency — longer disintegration times and potentially slower dissolution.",
    mitigation: "Add MgSt last in blending, limit mixing time with CCS. Keep MgSt <1% when used with CCS. Consider sodium stearyl fumarate as alternative lubricant.",
    refs: "Bolhuis GK et al. Drug Dev Ind Pharm 1996",
  },
];

export const FUNCTION_MAP = {
  "Surfactant": { description: "Reduce surface/interfacial tension; prevent denaturation at interfaces", examples: ["ps20", "ps80"] },
  "Lyoprotectant": { description: "Protect proteins during freezing and drying via vitrification/water replacement", examples: ["sucrose", "trehalose"] },
  "Cryoprotectant": { description: "Protect proteins during freezing via preferential exclusion or vitrification", examples: ["sucrose", "trehalose", "mannitol"] },
  "Buffer": { description: "Maintain stable pH during storage; critical for protein stability", examples: ["histidine", "citrate", "phosphate"] },
  "Tonicity Agent": { description: "Achieve isotonicity (270–330 mOsm/kg) to prevent hemolysis and injection pain", examples: ["nacl", "mannitol", "sucrose"] },
  "Chelating Agent": { description: "Sequester metal ions (Cu²⁺, Fe²⁺) that catalyze oxidation", examples: ["edta", "citrate"] },
  "Bulking Agent": { description: "Provide elegant cake structure in lyophilized products; fill volume in liquid", examples: ["mannitol", "lactose", "mcc"] },
  "Antimicrobial": { description: "Preserve sterility of multidose vials during in-use period", examples: ["benzyl-alcohol"] },
  "Lubricant": { description: "Reduce tablet ejection force and die-wall friction during compression", examples: ["mg-stearate"] },
  "Disintegrant": { description: "Facilitate rapid tablet breakup by swelling/wicking upon contact with water", examples: ["croscarmellose"] },
  "Viscosity Reducer": { description: "Reduce protein-protein interactions → lower viscosity in high-conc formulations", examples: ["arginine"] },
};
