/* ════════════════════════════════════════════════════════════ */
/*  CMC Master App — Supplementary Data                        */
/*  Analytical Methods · CTD Navigator · Timeline · ICH Guide  */
/* ════════════════════════════════════════════════════════════ */

// ── Analytical Methods ──────────────────────────────────────
export const ANALYTICAL_METHODS = [
  // ── IDENTITY ─────────────────────────────────────────────
  {
    id:"am-peptide-map",
    category:"Identity",
    icon:"🔗",
    color:"#22D3EE",
    name:"Peptide Mapping",
    fullName:"Reversed-Phase LC-MS/MS Peptide Mapping",
    abbreviation:"LC-MS/MS",
    purpose:"Primary structure confirmation; detection of sequence variants, modifications (deamidation, oxidation, glycosylation sites).",
    principle:"Protein is denatured, reduced, alkylated, then digested with a site-specific protease (trypsin, Lys-C). The resulting peptides are separated by RP-HPLC and sequenced by tandem MS. Each peptide generates characteristic fragment ions (b/y ions) enabling unambiguous sequence assignment.",
    detects:["Amino acid sequence","Post-translational modifications","Deamidation (N→D/Q→E)","Oxidation (Met, Trp)","Glycosylation sites","Disulfide bond mapping","Sequence variants / misincorporations"],
    parameters:[
      { name:"Column", typical:"C18 RP (1.7 µm, 150 mm)" },
      { name:"Mobile Phase", typical:"0.1% FA in H₂O / ACN gradient" },
      { name:"MS Resolution", typical:">50,000 FWHM (Orbitrap)" },
      { name:"Sequence Coverage", typical:">95% required (ICH Q6B)" },
      { name:"Digest Enzyme", typical:"Trypsin (Lys-C for hard regions)" },
      { name:"Run Time", typical:"60–90 min" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1 / 3.2.S.4.1",
    ichRef:"ICH Q6B §3",
    keyConsiderations:[
      "Reference standard peptide map must be established and qualified",
      "Deamidation can be artifactual — control sample prep pH and temperature",
      "Met oxidation increases during harsh storage; monitor as CQA",
      "Compare each lot against reference standard chromatogram",
      "Sequence variants ≥0.05% relative abundance must be investigated",
    ],
    regulatoryNote:"Required for BLA/NDA characterization. FDA expects ≥95% sequence coverage with confirmed modifications. EMA requires disulfide bond assignment.",
    cqaLink:"Primary sequence integrity, PTM profile",
  },
  {
    id:"am-intact-mass",
    category:"Identity",
    icon:"⚖️",
    color:"#22D3EE",
    name:"Intact Mass Analysis",
    fullName:"Native/Denatured Intact Mass by ESI-TOF/Orbitrap",
    abbreviation:"ESI-MS",
    purpose:"Molecular weight confirmation; glycoform profiling; lot-to-lot consistency; detection of unexpected modifications at the intact level.",
    principle:"Protein ionized by electrospray under native (non-denaturing) or denaturing conditions. Multiple charge states observed; deconvolution software reconstructs the true neutral mass. Mass accuracy to <10 ppm identifies modifications (e.g., Met+16 Da oxidation; deamidation +1 Da).",
    detects:["Molecular weight (monoisotopic / average)","Glycoform distribution (N-linked)","Disulfide pairing","Truncations / degradants","Heavy/light chain mass","Pyroglutamate cyclization (−17 Da)"],
    parameters:[
      { name:"Mass Accuracy", typical:"<5 ppm (Orbitrap), <10 ppm (TOF)" },
      { name:"Charge States", typical:"20–60+ for IgG" },
      { name:"Sample Prep", typical:"IdeS digest, DTT reduction for subunit analysis" },
      { name:"Expected MW", typical:"~148 kDa for IgG1 backbone + glycans" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1",
    ichRef:"ICH Q6B §3",
    keyConsiderations:[
      "Subunit analysis (Fd, Fc, LC) improves resolution for glycoform profiling",
      "Native MS reveals higher-order assemblies (e.g., half-antibodies, aggregates)",
      "C-terminal Lys clipping is common and expected — document the pattern",
      "Glycan heterogeneity causes broad peaks; compare glycoform ratios lot-to-lot",
    ],
    regulatoryNote:"Routinely expected at BLA. FDA frequently requests native MS data to assess higher-order structure. Used to confirm identity in QC release (abbreviated version).",
    cqaLink:"Molecular identity, glycoform profile",
  },
  {
    id:"am-ce-sds",
    category:"Purity",
    icon:"📏",
    color:"#34D399",
    name:"CE-SDS",
    fullName:"Capillary Electrophoresis – Sodium Dodecyl Sulfate (Reduced & Non-Reduced)",
    abbreviation:"CE-SDS",
    purpose:"Size-based separation of protein chains under denaturing conditions. Detects fragments, aggregates visible on denatured gel, and heavy/light chain ratio.",
    principle:"SDS denatures and uniformly charges proteins by mass. Capillary gel electrophoresis separates fragments by size. Non-reduced (NR) CE-SDS resolves intact mAb, half-antibody, and aggregates. Reduced (R) CE-SDS resolves heavy chain (HC ~50 kDa) and light chain (LC ~25 kDa) separately.",
    detects:["Heavy chain","Light chain","Non-glycosylated HC","Low molecular weight species (fragments)","High molecular weight species (aggregates)","% Main peak purity"],
    parameters:[
      { name:"Gel Buffer", typical:"SDS gel buffer, pH 6.9" },
      { name:"Sample Prep (NR)", typical:"Alkylation with NEM to block free thiols" },
      { name:"Sample Prep (R)", typical:"DTT reduction + IAA alkylation" },
      { name:"Purity Acceptance", typical:"≥95% main peak (lot release)" },
      { name:"Detection", typical:"UV 220 nm" },
      { name:"MW Marker", typical:"Internal standard peptide ladder" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1",
    ichRef:"ICH Q6B §4.1",
    keyConsiderations:[
      "NR CE-SDS: free alkylation critical — incomplete alkylation causes artifacts",
      "R CE-SDS: HC/LC ratio (expected 2:1 for IgG) must be consistent",
      "Fragments at <25 kDa and >150 kDa are separately reported",
      "Sensitivity advantage over SDS-PAGE: UV area integration vs. band density estimation",
      "Platform method across most biopharmaceutical companies",
    ],
    regulatoryNote:"FDA considers CE-SDS a primary purity method. Required as a release assay. Trending of % purity over stability studies feeds into shelf-life determination.",
    cqaLink:"Purity, size-based integrity",
  },
  {
    id:"am-cief",
    category:"Identity",
    icon:"⚡",
    color:"#22D3EE",
    name:"cIEF / icIEF",
    fullName:"Capillary Isoelectric Focusing (imaged or conventional)",
    abbreviation:"cIEF",
    purpose:"Charge heterogeneity profiling — separation of acidic, main, and basic isoforms based on isoelectric point (pI).",
    principle:"In a pH gradient (ampholyte mixture), proteins migrate until their net charge is zero (pI). Imaging cIEF (icIEF) illuminates the entire capillary with UV, eliminating mobilization step. Deamidation shifts peaks acidic; C-terminal Lys gives basic peaks.",
    detects:["Acidic variants (deamidation, sialylation)","Main isoform","Basic variants (C-term Lys, Arg, N-term pyroglutamate)","pI shifts due to formulation changes","Aggregates at charge boundaries"],
    parameters:[
      { name:"pI Range", typical:"Ampholyte mixture pH 3–10 or 5–8" },
      { name:"pI Markers", typical:"Internal pI markers (certified)",  },
      { name:"Resolution", typical:"ΔpI ~0.01–0.02 pH units" },
      { name:"Run Time", typical:"10–15 min (icIEF)" },
      { name:"Detection", typical:"UV 280 nm (whole-column imaging)" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1 / 3.2.S.4.1",
    ichRef:"ICH Q6B §4",
    keyConsiderations:[
      "Correlate icIEF profile to peptide map deamidation data",
      "C-terminal Lys clipping reduces basic species (enzymatic — document origin)",
      "Formulation pH can shift the profile — include in comparability studies",
      "% acidic + % basic species must be tracked vs. reference standard",
      "IgG1 typically shows 3–5 main peaks; pattern should be consistent lot-to-lot",
    ],
    regulatoryNote:"FDA expects charge variant profiling at BLA. The pattern must be qualified against DS lots used in clinical studies. Significant shifts trigger comparability bridging.",
    cqaLink:"Charge heterogeneity, deamidation level",
  },
  // ── PURITY/AGGREGATION ───────────────────────────────────
  {
    id:"am-sec",
    category:"Purity",
    icon:"🔵",
    color:"#34D399",
    name:"SEC-HPLC",
    fullName:"Size-Exclusion Chromatography – HPLC",
    abbreviation:"SEC-HPLC",
    purpose:"Quantitative measurement of monomer purity and aggregation/fragment content. Primary purity release assay for biotherapeutics.",
    principle:"Non-denaturing aqueous gel filtration: larger molecules elute first (excluded from pores). Isocratic separation under physiological conditions preserves native conformation. Detection at UV 280 nm. Molecular weight calibrated with protein standards or coupled to MALS (SEC-MALS).",
    detects:["Monomer %","High-molecular-weight species (HMWs) — dimers, oligomers, aggregates","Low-molecular-weight species (LMWs) — fragments","Particle populations","Non-covalent complexes (at native conditions)"],
    parameters:[
      { name:"Column", typical:"SEC 200 or 300 Å, 300×7.8 mm" },
      { name:"Mobile Phase", typical:"150 mM Na-phosphate pH 6.8–7.4" },
      { name:"Flow Rate", typical:"0.5–1.0 mL/min" },
      { name:"HMW Acceptance", typical:"≤2% (release); tighter at BLA" },
      { name:"Run Time", typical:"25–35 min" },
      { name:"Coupling", typical:"SEC-MALS for absolute MW determination" },
    ],
    phases:{ "Pre-IND":true, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1",
    ichRef:"ICH Q6B §4.1",
    keyConsiderations:[
      "Native conditions — results may differ from CE-SDS (denaturing)",
      "SEC can underestimate aggregates that don't enter pores or that interact with column",
      "Couple with DLS and MFI for orthogonal aggregate confirmation",
      "Flow rate and mobile phase salt affect separation — validate robustly",
      "Aggregates are a critical CQA — trending over stability is mandatory",
      "HMW increase rate defines shelf-life in Arrhenius-based stability models",
    ],
    regulatoryNote:"Universal biopharmaceutical release test. FDA expects SEC trending from multiple stability time points. Aggregates are immunogenicity risk factors per ICH Q6B and FDA guidance.",
    cqaLink:"Purity, aggregation, immunogenicity risk",
  },
  {
    id:"am-iex",
    category:"Purity",
    icon:"🔋",
    color:"#34D399",
    name:"IEX-HPLC (CEX/AEX)",
    fullName:"Ion-Exchange Chromatography (Cation-Exchange / Anion-Exchange)",
    abbreviation:"IEX-HPLC",
    purpose:"Charge heterogeneity profiling with higher resolution than cIEF; quantification of acidic and basic species; batch-to-batch consistency.",
    principle:"At a pH below the pI, protein binds cation exchange resin; charge variants elute with a salt gradient. Acidic species (lower pI) elute earlier; basic species (higher pI) later. AEX separates at pH above pI. Resolution of charge variants enables fingerprinting.",
    detects:["Acidic isoforms (deamidation, sialylation, oxidation)","Main peak","Basic isoforms (C-term Lys, Arg variants, N-term pyro-Glu)","Charge-related PTMs","Glycoform distribution (partial)"],
    parameters:[
      { name:"Column (CEX)", typical:"ProPac WCX-10, 4×250 mm" },
      { name:"Column (AEX)", typical:"ProPac SAX-10" },
      { name:"Gradient", typical:"20–500 mM NaCl over 40 min, pH 5–7" },
      { name:"Detection", typical:"UV 280 nm" },
      { name:"Main Peak", typical:"Report %Main; sum acidic / basic species" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1 / 3.2.S.4.1",
    ichRef:"ICH Q6B",
    keyConsiderations:[
      "Method must be validated for specificity vs. cIEF (orthogonal methods)",
      "pH and salt gradient control critical — any drift shifts elution pattern",
      "Forced-degradation studies must show appropriate separation of stressed peaks",
      "Correlate CEX acidic peak increase with deamidation from peptide map",
      "Used in process analytical technology (PAT) at harvest to monitor cell culture",
    ],
    regulatoryNote:"Required for characterization; often used as release test alongside cIEF. EMA and FDA expect charge variant trending throughout stability program.",
    cqaLink:"Charge heterogeneity, deamidation, PTM profile",
  },
  {
    id:"am-sec-mals",
    category:"Purity",
    icon:"💡",
    color:"#34D399",
    name:"SEC-MALS",
    fullName:"Size-Exclusion Chromatography with Multi-Angle Light Scattering",
    abbreviation:"SEC-MALS",
    purpose:"Absolute molecular weight determination of monomer and aggregate species without calibration standards. Gold standard for aggregate characterization.",
    principle:"After SEC separation, protein passes through a MALS detector. Light scattering intensity at multiple angles + differential refractive index (dRI) gives absolute molecular weight independent of hydrodynamic radius. Conjugated molecules (PEGylated, ADC drug-antibody ratio) can be characterized.",
    detects:["Absolute molecular weight of each peak","Weight-average molecular weight (Mw)","Polydispersity (Mw/Mn)","ADC drug-to-antibody ratio (DAR)","PEG size on PEGylated proteins","Glycan mass contribution"],
    parameters:[
      { name:"Detectors", typical:"18-angle MALS + dRI + UV" },
      { name:"dn/dc", typical:"0.185 mL/g for proteins (standard)" },
      { name:"MW Range", typical:"1 kDa to >1 MDa" },
      { name:"Mass Accuracy", typical:"±2–3% for mAb monomer" },
    ],
    phases:{ "Pre-IND":false, "IND":false, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1",
    ichRef:"ICH Q6B",
    keyConsiderations:[
      "Not a routine QC method — used for extended characterization",
      "Essential for biosimilar comparability to innovator",
      "Column equilibration critical — baseline drift invalidates dRI signal",
      "Buffer matching between SEC mobile phase and sample critical",
    ],
    regulatoryNote:"FDA expects SEC-MALS in BLA characterization sections. Required for biosimilar analytical similarity exercises to characterize aggregate species.",
    cqaLink:"Absolute aggregate characterization, molecular weight",
  },
  // ── POTENCY ─────────────────────────────────────────────
  {
    id:"am-cell-bioassay",
    category:"Potency",
    icon:"🧫",
    color:"#F472B6",
    name:"Cell-Based Bioassay",
    fullName:"Reporter Gene / Functional Cell-Based Bioassay",
    abbreviation:"CBA",
    purpose:"Measure biological activity (potency) of a biotherapeutic using a relevant cell line expressing the target receptor. Directly measures mechanism of action.",
    principle:"Cells engineered with a target receptor and reporter gene (luciferase, GFP, NFAT-RE) are exposed to the drug. Receptor activation triggers the signaling cascade and reporter expression. Luminescence/fluorescence is measured and compared to a reference standard using parallel-line analysis or 4-parameter logistic (4PL) model.",
    detects:["Biological potency (% relative potency vs. RS)","EC50 (half-maximal effective concentration)","Efficacy (Emax)","Mode of action integrity","Lot-to-lot consistency"],
    parameters:[
      { name:"Cell Line", typical:"Engineered CHO, Jurkat, HEK293" },
      { name:"Model", typical:"4PL logistic (slope, EC50, asymptotes)" },
      { name:"Parallelism", typical:"Required (same slope as RS ±10%)" },
      { name:"Precision", typical:"CV ≤30% intra-assay; ≤40% inter-assay" },
      { name:"RS Concentration", typical:"EC50 concentration; within linear range" },
      { name:"Acceptance", typical:"Relative potency 70–130% (release)" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1",
    ichRef:"ICH Q2(R1), USP <1033>, USP <1032>",
    keyConsiderations:[
      "Parallelism test is the fundamental validity criterion — dose-response curves must be parallel",
      "Cell passage number must be tightly controlled (acceptable range defined in SOP)",
      "Reference standard vial thaw-use cycle must be qualified; avoid re-freeze",
      "Biological assay variability (CV 20–40%) is inherent — design accordingly",
      "Statistical model validation per USP <1032> required before clinical use",
      "Stability-indicating: correlates potency loss to degradation pathways",
    ],
    regulatoryNote:"FDA requires a validated, relevance-demonstrating potency assay for BLA. ICH Q6B: 'biological activity reflecting mechanism of action should be measured.' Critical for lot release at all clinical phases.",
    cqaLink:"Biological activity, mechanism of action",
  },
  {
    id:"am-elisa",
    category:"Potency",
    icon:"🩺",
    color:"#F472B6",
    name:"ELISA (Binding)",
    fullName:"Enzyme-Linked Immunosorbent Assay (Target Binding)",
    abbreviation:"ELISA",
    purpose:"Quantify binding affinity to target antigen or receptor. Used as a potency surrogate or as a relative binding characterization assay.",
    principle:"Target antigen coated on a microplate captures the antibody drug. After washing, a secondary HRP-conjugated anti-Fc antibody binds. Substrate TMB produces color proportional to drug concentration. Signal vs. concentration plotted as 4PL curve.",
    detects:["Target binding (antigen)","Fc receptor binding (FcγRI, FcγRIIIa, FcRn)","Anti-drug antibody (ADA) in immunogenicity assays","Drug concentration in serum (PK ELISA)","% Binding relative to reference standard"],
    parameters:[
      { name:"Plate Coating", typical:"Antigen 1–5 µg/mL in carbonate buffer" },
      { name:"Detection Ab", typical:"Anti-human IgG-HRP, 1:5000" },
      { name:"Dynamic Range", typical:"5–500 ng/mL (typical mAb)" },
      { name:"Precision", typical:"CV ≤15% intra-assay" },
      { name:"Sensitivity", typical:"LLOQ typically 1–5 ng/mL" },
    ],
    phases:{ "Pre-IND":true, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1 / 3.2.S.3.2",
    ichRef:"ICH Q2(R1), FDA Bioanalytical Method Guidance",
    keyConsiderations:[
      "Antigen quality and lot consistency is critical — changes in antigen invalidate ELISA",
      "Hook effect at high concentrations — dilute samples appropriately",
      "ELISA detects binding but not necessarily correct mechanism of action",
      "Complement with cell-based bioassay for potency — ELISA is a surrogate",
      "FcRn binding ELISA used to estimate half-life predictions for Fc-engineered mAbs",
    ],
    regulatoryNote:"ELISA widely used in QC. If used as potency assay, must demonstrate correlation to biological function. FDA prefers cell-based assays as primary potency for BLA.",
    cqaLink:"Binding affinity, potency surrogate",
  },
  {
    id:"am-spr",
    category:"Potency",
    icon:"📡",
    color:"#F472B6",
    name:"Surface Plasmon Resonance (SPR)",
    fullName:"SPR Binding Kinetics — Biacore / ProteOn",
    abbreviation:"SPR",
    purpose:"Real-time, label-free measurement of binding kinetics (kon, koff) and equilibrium affinity (KD) between drug and target.",
    principle:"Ligand immobilized on a gold-coated sensor chip. Analyte flows over surface; binding changes the refractive index, detected as SPR signal (RU). Association phase (analyte injection) → dissociation phase (buffer wash). Global kinetic fitting yields kon, koff, KD.",
    detects:["Association rate constant (kon)","Dissociation rate constant (koff)","Equilibrium dissociation constant (KD)","Stoichiometry of binding","Avidity effects (bivalent binding)","Epitope binning (competition SPR)"],
    parameters:[
      { name:"Chip Surface", typical:"CM5 (carboxymethyl dextran), anti-Fc capture" },
      { name:"Analyte", typical:"Antigen or receptor at multiple concentrations" },
      { name:"KD Range", typical:"pM–µM (Biacore 8K+ resolves sub-pM)" },
      { name:"Kinetic Fit", typical:"1:1 Langmuir or bivalent analyte model" },
      { name:"Temperature", typical:"25°C or 37°C" },
    ],
    phases:{ "Pre-IND":true, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.2",
    ichRef:"ICH Q6B",
    keyConsiderations:[
      "Mass transport limitation can cause kon artifacts — use high flow rates",
      "Regeneration conditions must be optimized to not damage ligand",
      "Non-specific binding to dextran matrix must be assessed",
      "Avidity of bivalent antibody can confound true KD — use Fab fragments for monomeric KD",
      "Biosimilar comparability requires KD within 10-fold of innovator; full kinetics preferred",
    ],
    regulatoryNote:"Expected in BLA characterization. Biosimilar guidelines (FDA, EMA) require full kinetic characterization. Potency correlation to KD strengthens mechanistic understanding.",
    cqaLink:"Binding kinetics, affinity",
  },
  // ── GLYCOSYLATION ────────────────────────────────────────
  {
    id:"am-glycan",
    category:"Glycosylation",
    icon:"🌿",
    color:"#A78BFA",
    name:"N-Glycan Analysis",
    fullName:"Released N-Glycan Profiling by HILIC-UPLC-FLR or LC-MS",
    abbreviation:"HILIC-UPLC",
    purpose:"Quantify glycoform distribution at Fc Asn-297. Glycosylation impacts effector function, clearance, and immunogenicity.",
    principle:"N-glycans released by PNGase F enzyme digestion from denatured protein. Released glycans labeled with 2-AB or RapiFluor-MS fluorescent tag. Separated by HILIC stationary phase (retains glycans by hydrophilic interaction). Peaks identified by database matching and confirmed by MS.",
    detects:["G0F, G1F, G2F (afucosylated G0, G1, G2)","High mannose species (Man5–Man9)","Sialylated glycoforms (G1FS1, G2FS2)","Bisecting GlcNAc","Afucosylation (key for ADCC function)","Galactosylation levels"],
    parameters:[
      { name:"Column", typical:"ACQUITY UPLC Glycan BEH Amide 1.7µm" },
      { name:"Detection", typical:"FLR (Ex 330nm/Em 420nm for 2-AB)" },
      { name:"Mobile Phase", typical:"ACN/100 mM ammonium formate gradient" },
      { name:"Glycan Release", typical:"PNGase F 37°C, 18 h" },
      { name:"Labeling", typical:"2-AB or RapiFluor-MS (30 min, ambient)" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1",
    ichRef:"ICH Q6B §3, EMA Biosimilar Guidelines",
    keyConsiderations:[
      "Afucosylation (%) is a CQA for ADCC-dependent mAbs (anti-CD20, anti-HER2)",
      "High mannose correlates with faster clearance (shorter half-life in vivo)",
      "Cell culture conditions (glucose, manganese, ammonia) strongly affect glycosylation",
      "Lot-to-lot consistency essential — biosimilar guidelines require comparative glycan fingerprints",
      "Fc engineering can alter glycan processing — characterize both Fc and Fab glycosites",
      "Sialylation affects complement activation and circulatory half-life",
    ],
    regulatoryNote:"Mandatory BLA characterization. FDA/EMA biosimilar guidelines: side-by-side glycan comparison with innovator. Afucosylation is often a key CQA driving spec setting.",
    cqaLink:"Effector function (ADCC/CDC), clearance, immunogenicity",
  },
  // ── PHYSICAL/CHEMICAL ────────────────────────────────────
  {
    id:"am-dls",
    category:"Physical/Chemical",
    icon:"🔵",
    color:"#FB923C",
    name:"Dynamic Light Scattering (DLS)",
    fullName:"Dynamic Light Scattering — Hydrodynamic Diameter",
    abbreviation:"DLS",
    purpose:"Rapid measurement of hydrodynamic diameter and polydispersity. Detection of nanometer-scale aggregates and particles invisible to SEC.",
    principle:"A laser illuminates the protein solution. Brownian motion causes intensity fluctuations (speckle pattern). Autocorrelation of fluctuations gives diffusion coefficient D. Stokes-Einstein equation converts D to hydrodynamic radius (Rh). Large particles (aggregates) cause slower diffusion → larger Rh.",
    detects:["Monomer hydrodynamic radius","Aggregate populations (nm–µm scale)","Polydispersity index (PDI)","Z-average diameter","Onset of aggregation during stress studies","Concentration-dependent self-association"],
    parameters:[
      { name:"Typical Rh (IgG monomer)", typical:"~5.5–6.0 nm" },
      { name:"PDI Acceptance", typical:"<0.2 for monodisperse sample" },
      { name:"Concentration", typical:"0.5–10 mg/mL" },
      { name:"Temperature", typical:"4°C, 25°C, 40°C for thermal studies" },
      { name:"Sensitivity", typical:"Detects as few as 0.01% large aggregates by intensity" },
    ],
    phases:{ "Pre-IND":true, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1 / 3.2.P.2",
    ichRef:"ICH Q6B, USP <1911>",
    keyConsiderations:[
      "Intensity-weighted: biased toward large particles — use volume or number distributions for accuracy",
      "Small % of large aggregates dominates intensity signal — complement with SEC and MFI",
      "pH, ionic strength, temperature ramping (DLS melting curves) gives stability characterization",
      "Used extensively in formulation screening (excipient compatibility)",
      "Concentration dependence of Rh reveals self-association (protein-protein interaction, kD)",
    ],
    regulatoryNote:"Expected in BLA characterization. Used in formulation development studies. Aggregate trending in stability programs should include orthogonal methods (DLS + SEC + MFI).",
    cqaLink:"Aggregation, colloidal stability",
  },
  {
    id:"am-dsc",
    category:"Physical/Chemical",
    icon:"🌡️",
    color:"#FB923C",
    name:"Differential Scanning Calorimetry (DSC)",
    fullName:"DSC — Thermal Stability (Tm) Characterization",
    abbreviation:"DSC",
    purpose:"Determine thermal unfolding transitions (melting temperature, Tm) to characterize higher-order structural stability and compare formulations/mutants.",
    principle:"The sample is heated at a controlled rate and the heat absorbed vs. a reference cell is measured. Protein unfolding is endothermic — peak in excess heat capacity (Cp) marks Tm. IgG typically shows 2–4 transitions (CH2, Fab, CH3). Formulation stabilizers increase Tm.",
    detects:["Tm1, Tm2, Tm3 (individual domain melting)","Tonset (onset of first unfolding)","Enthalpy of unfolding (ΔH)","Reversibility of unfolding","Comparison across formulations","Conformational stability fingerprint"],
    parameters:[
      { name:"Scan Rate", typical:"1°C/min (60–90°C range)" },
      { name:"Concentration", typical:"0.5–2 mg/mL" },
      { name:"Typical IgG Tm1", typical:"65–75°C (CH2 domain)" },
      { name:"Typical IgG Tm2", typical:"80–90°C (Fab + CH3)" },
      { name:"Buffer", typical:"Match formulation buffer" },
    ],
    phases:{ "Pre-IND":true, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1 / 3.2.P.2",
    ichRef:"ICH Q6B",
    keyConsiderations:[
      "Formulation development: excipients that increase Tm by >2–3°C are beneficial stabilizers",
      "pH optimum for stability often corresponds to highest Tm",
      "Glycosylation at Asn-297 stabilizes CH2 domain — deglycosylated mAb shows lower Tm1",
      "Irreversible aggregation on cooling indicates thermodynamic vs. kinetic stability",
      "Biosimilar fingerprinting: DSC thermogram must match innovator within tight tolerances",
    ],
    regulatoryNote:"Higher-order structure characterization expected in BLA. Used in biosimilar similarity exercises. FDA expects DSC data in characterization and comparability reports.",
    cqaLink:"Conformational stability, higher-order structure",
  },
  {
    id:"am-mfi",
    category:"Physical/Chemical",
    icon:"🔍",
    color:"#FB923C",
    name:"Micro-Flow Imaging (MFI)",
    fullName:"Micro-Flow Imaging — Subvisible Particle Counting",
    abbreviation:"MFI",
    purpose:"Count and characterize subvisible particles (2–200 µm) in biopharmaceutical drug product. Meets USP <788> and <789> requirements.",
    principle:"Sample flows through an illuminated flow cell. Digital images captured at high frame rate. Image analysis software detects, counts, and morphologically characterizes each particle. Equivalent circular diameter (ECD), aspect ratio, and transparency distinguish protein particles from silicone oil and glass.",
    detects:["Particles ≥2 µm, ≥5 µm, ≥10 µm, ≥25 µm (cumulative count)","Protein aggregates (transparent, irregular)","Silicone oil droplets (round, high transparency)","Glass particles from vials (angular, dark)","Rubber particles from stoppers"],
    parameters:[
      { name:"USP <788> Limits", typical:"≤6000 particles/mL ≥10 µm; ≤600/mL ≥25 µm" },
      { name:"Volume Analyzed", typical:"0.5–1.0 mL per run" },
      { name:"Frame Rate", typical:"23 frames/sec" },
      { name:"Morphological", typical:"ECD, aspect ratio, circularity, transparency" },
    ],
    phases:{ "Pre-IND":false, "IND":false, "Ph1":false, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.P.5.1",
    ichRef:"USP <788>, <789>, <787>; ICH Q6B",
    keyConsiderations:[
      "Silicone oil: can mask protein particles — use siliconized vs. non-siliconized syringes in study design",
      "MFI morphology analysis differentiates particle types — protein aggregates are irregular and translucent",
      "Shipping/agitation studies must include MFI to assess mechanical stress particle generation",
      "Temperature cycling stress increases protein particles — combine with SEC data for comparability",
      "USP <787> (subvisible particles in therapeutic protein injections) allows MFI in lieu of LO method",
    ],
    regulatoryNote:"Mandatory for drug product lot release per USP <788>. FDA expects morphological characterization beyond count at BLA. Trending across stability mandatory.",
    cqaLink:"Particle count, physical stability, patient safety",
  },
  // ── SAFETY ──────────────────────────────────────────────
  {
    id:"am-endotoxin",
    category:"Safety",
    icon:"🦠",
    color:"#F59E0B",
    name:"Endotoxin (LAL Test)",
    fullName:"Limulus Amebocyte Lysate (LAL) Endotoxin Test",
    abbreviation:"LAL / BET",
    purpose:"Detect and quantify bacterial endotoxins (LPS from gram-negative bacteria) in parenteral drug products. Prevents pyrogenic reactions in patients.",
    principle:"Horseshoe crab amebocyte lysate contains a clotting cascade that is activated by endotoxin. Three formats: Gel-Clot (qualitative), Turbidimetric (turbidity vs. concentration), Chromogenic (color production by cleaved synthetic peptide). Endotoxin Units (EU) standardized against USP reference endotoxin.",
    detects:["Lipopolysaccharide (LPS) from gram-negative bacteria","Total endotoxin in EU/mL or EU/dose","β-glucan interference (use recombinant Factor C to distinguish)"],
    parameters:[
      { name:"Parenteral Limit", typical:"0.5 EU/mL; or K/M (K=max dose; M=5 EU/kg/hr)" },
      { name:"Intrathecal Limit", typical:"0.2 EU/mL" },
      { name:"Sensitivity", typical:"0.001–0.01 EU/mL (kinetic chromogenic)" },
      { name:"Spike Recovery", typical:"50–200% (confirms absence of interference)" },
      { name:"Compendial", typical:"USP <85>, EP 2.6.14, JP 4.01" },
    ],
    phases:{ "Pre-IND":false, "IND":false, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1 / 3.2.P.5.1",
    ichRef:"USP <85>; ICH Q6B",
    keyConsiderations:[
      "Interference testing (Maximum Valid Dilution, MVD) must be done for every new product matrix",
      "Recombinant Factor C (rFC) assay is FDA-acceptable and avoids horseshoe crab reliance",
      "Enhanced detection via recombinant cascade reagent (ECR) for biologics matrices",
      "Process control: bioburden at harvest and bulk drug substance should be tracked",
    ],
    regulatoryNote:"Mandatory release test for parenterals. FDA acceptance of rFC stated in 2020 guidance. EU: EMA supports rFC. Must pass lot release before clinical or commercial use.",
    cqaLink:"Safety (pyrogenicity), patient risk",
  },
  {
    id:"am-bioburden",
    category:"Safety",
    icon:"🧪",
    color:"#F59E0B",
    name:"Bioburden & Sterility",
    fullName:"Bioburden Testing and Sterility Testing (USP <71>)",
    abbreviation:"Bioburden / Sterility",
    purpose:"Ensure microbiological quality of drug substance and drug product. Sterility testing confirms absence of viable microorganisms in final product.",
    principle:"Bioburden: sample filtered through membrane; membrane incubated on growth media (TAMC/TYMC). Colony counts per mL/g. Sterility: USP <71> direct inoculation or membrane filtration into two media (FTM and SCDM) incubated 14 days. Rapid methods: ATP bioluminescence, CO₂ monitoring, flow cytometry.",
    detects:["Total aerobic microbial count (TAMC)","Total yeast/mold count (TYMC)","Absence of specified organisms","Absence of viable microorganisms (sterility test)","Microbial contamination during process"],
    parameters:[
      { name:"Bioburden Limit (DS)", typical:"≤10 CFU/10 mL (pre-filtration)" },
      { name:"Sterility Test", typical:"14 days incubation, 2 media, 20–21 containers" },
      { name:"Media (Sterility)", typical:"FTM (anaerobes) + SCDM (aerobes + fungi)" },
      { name:"Temperature", typical:"30–35°C (FTM) / 20–25°C (SCDM)" },
    ],
    phases:{ "Pre-IND":false, "IND":false, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1 / 3.2.P.5.1",
    ichRef:"USP <71>, <61>, <62>; ICH Q6B",
    keyConsiderations:[
      "Sterility test has statistical limitations — cannot guarantee sterility of entire lot",
      "Parametric release (alternative to sterility testing) based on validated sterilization process",
      "Rapid sterility methods (Millipore Milliflex, BacT/ALERT) cut time from 14 days to 2–5 days",
      "Bioburden trending at each process step identifies contamination introduction points",
    ],
    regulatoryNote:"Release requirement for all parenteral drug products. USP <71> is the compendial standard. FDA accepts rapid microbiological methods (RMMs) with full validation.",
    cqaLink:"Microbiological quality, patient safety",
  },
  // ── STRUCTURAL ───────────────────────────────────────────
  {
    id:"am-cd",
    category:"Structural",
    icon:"🌀",
    color:"#38BDF8",
    name:"Circular Dichroism (CD)",
    fullName:"UV Circular Dichroism Spectroscopy — Secondary & Tertiary Structure",
    abbreviation:"CD",
    purpose:"Confirm secondary structure (α-helix, β-sheet content) and tertiary structure (near-UV CD fingerprint). Characterize higher-order structure for comparability.",
    principle:"Polarized light has differential absorption of left- vs. right-circularly polarized light by chiral chromophores. Far-UV CD (190–250 nm): peptide bond backbone — reveals α-helix (negative at 208, 222 nm), β-sheet (negative at 218 nm). Near-UV CD (260–320 nm): aromatic residues (Phe, Tyr, Trp) — tertiary structure environment.",
    detects:["Secondary structure content (% α-helix, β-sheet, random coil)","Tertiary structure fingerprint","Thermal melting transitions (Tm from CD signal at 222 nm)","Formulation-induced conformational changes","Denaturation monitoring"],
    parameters:[
      { name:"Far-UV range", typical:"190–250 nm, 0.1–0.5 mg/mL" },
      { name:"Near-UV range", typical:"260–320 nm, 0.5–2.0 mg/mL" },
      { name:"Pathlength", typical:"0.1 mm (far-UV), 10 mm (near-UV)" },
      { name:"Scan Rate", typical:"50 nm/min, 3 accumulations" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1",
    ichRef:"ICH Q6B §3, FDA HOS Guidance",
    keyConsiderations:[
      "IgG antibodies: predominantly β-sheet (characteristic negative band at ~217 nm)",
      "Near-UV CD most sensitive to subtle structural changes near aromatic residues",
      "Thermal CD melting correlates with DSC data — orthogonal confirmation of Tm",
      "Buffer must be free of chiral or UV-absorbing components (avoid TRIS at far-UV)",
      "Biosimilar comparison: spectra must overlay within ±5% across full wavelength range",
    ],
    regulatoryNote:"FDA Higher Order Structure (HOS) guidance (2023) explicitly cites CD as key technique. Required for BLA and biosimilar submissions. Near-UV particularly valued for tertiary fingerprinting.",
    cqaLink:"Higher-order structure, conformational integrity",
  },
  {
    id:"am-a280",
    category:"Physical/Chemical",
    icon:"📊",
    color:"#FB923C",
    name:"UV Spectrophotometry (A280)",
    fullName:"Protein Concentration by UV Absorbance at 280 nm",
    abbreviation:"A280",
    purpose:"Rapid, non-destructive protein concentration measurement using Beer-Lambert law with sequence-derived extinction coefficient.",
    principle:"Aromatic residues (Trp, Tyr) and disulfide bonds absorb UV at 280 nm. Extinction coefficient (ε) calculated from amino acid sequence using Pace/Edelhoch method. Concentration = A280 / (ε × pathlength). Corrected for turbidity at 320 nm.",
    detects:["Protein concentration (mg/mL)","Aggregation (turbidity at 320 nm)","Nucleic acid contamination (A260/A280 ratio)"],
    parameters:[
      { name:"Wavelength", typical:"280 nm (primary), 320 nm (baseline)" },
      { name:"ε (IgG)", typical:"~1.4–1.5 mL·mg⁻¹·cm⁻¹" },
      { name:"Pathlength", typical:"1 cm (cuvette) or µL volume (NanoDrop)" },
      { name:"Acceptance", typical:"Within 10% of target concentration" },
    ],
    phases:{ "Pre-IND":true, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1 / 3.2.P.5.1",
    ichRef:"ICH Q6B, USP <857>",
    keyConsiderations:[
      "Extinction coefficient must be experimentally verified (amino acid analysis or dry weight)",
      "Turbidity correction at 320 nm critical for aggregated samples",
      "Formulation excipients (e.g., polysorbate 80) do not absorb at 280 nm — minimal interference",
      "High-concentration formulations (>50 mg/mL): use 0.1 cm pathlength or SoloVPE system",
    ],
    regulatoryNote:"Universal release test. Must be validated per ICH Q2(R1). Extinction coefficient must be justified. Used throughout process for in-process controls.",
    cqaLink:"Drug concentration, dose accuracy",
  },
  // ── PROCESS IMPURITIES ──────────────────────────────────────
  {
    id:"am-hcp-elisa",
    category:"Process Impurities",
    icon:"🧫",
    color:"#F59E0B",
    name:"HCP ELISA",
    fullName:"Host Cell Protein (HCP) Enzyme-Linked Immunosorbent Assay",
    abbreviation:"HCP ELISA",
    purpose:"Quantify residual host cell proteins (e.g., CHO-derived) carried over into drug substance following downstream purification. HCPs can cause immunogenicity or catalytic degradation of product.",
    principle:"Polyclonal anti-HCP antibodies (generic or process-specific) are used in a sandwich ELISA format. HCPs in the sample bind to capture antibodies; detection antibodies conjugated to HRP generate colorimetric signal (TMB). Concentration interpolated from standard curve of reference HCP preparation. Coverage of process HCPs by antibody is verified by 2D gel immunostaining.",
    detects:["Total HCP concentration (ng/mL → ppm relative to product)","Individual HCPs via orthogonal LC-MS","HCP coverage by antibody reagent","Process consistency lot-to-lot"],
    parameters:[
      { name:"Assay Range", typical:"1.6–100 ng/mL (typical LLOQ ~1 ng/mL)" },
      { name:"Acceptance Criteria", typical:"<100 ppm (ng HCP / mg product); process-specific" },
      { name:"Antibody Coverage", typical:">70% of process HCPs (2D Western blot)" },
      { name:"Spike Recovery", typical:"80–120% at 3 concentration levels" },
      { name:"Matrix Tolerance", typical:"Dilute-to-fit; verify MRD (minimum required dilution)" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1 / 3.2.P.5.1",
    ichRef:"ICH Q6B §3.2; FDA Guidance on HCP (2021)",
    keyConsiderations:[
      "Process-specific HCP reagents may be required if product is not CHO-derived",
      "Antibody coverage assessment by 2D Western blot is expected at BLA — quantify % reactive spots",
      "Individual problematic HCPs (e.g., CHO phospholipase B-like 2, PLBL2) may require orthogonal LC-MS quantification",
      "Validate per ICH Q2(R1): specificity, linearity, range, LOD, LOQ, precision, accuracy",
      "EMA and FDA both scrutinize HCP data at BLA; unexpected HCP elevation is a CMC hold risk",
    ],
    regulatoryNote:"FDA (2021) HCP Guidance recommends process-specific immunoassays, antibody coverage >70%, and orthogonal LC-MS characterization. EMA aligns with ICH Q6B for limits; typically <100 ppm for mAbs.",
    cqaLink:"Process-related impurity; immunogenicity risk",
  },
  {
    id:"am-pra-elisa",
    category:"Process Impurities",
    icon:"🔴",
    color:"#F59E0B",
    name:"Protein A ELISA",
    fullName:"Residual Protein A (rPrA) Enzyme-Linked Immunosorbent Assay",
    abbreviation:"PrA ELISA",
    purpose:"Detect and quantify Protein A (Staphylococcal) ligand leached from Protein A affinity chromatography resin (MabSelect, Prosep) into the drug substance. Residual PrA is immunogenic and cytotoxic.",
    principle:"Sandwich ELISA using anti-Protein A antibodies. Residual PrA in sample binds to plate-coated capture antibody; HRP-conjugated detection antibody generates TMB signal. Calibration curve built from known concentration of Protein A standard. MRD and matrix effects assessed with spike-recovery during validation.",
    detects:["Residual Protein A ligand concentration (ng/mL)","Leachable from affinity resin","Process consistency of downstream clearance"],
    parameters:[
      { name:"LLOQ", typical:"1–2 ng/mL" },
      { name:"Acceptance Criteria", typical:"≤1–10 ppm (ng PrA / mg product); typically ≤2 ng/mL in DS" },
      { name:"Spike Recovery", typical:"80–120%" },
      { name:"Format", typical:"Sandwich ELISA; 96-well plate; OD450 nm" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1 / 3.2.P.5.1",
    ichRef:"ICH Q6B §3.2; resin supplier clearance guidelines",
    keyConsiderations:[
      "Protein A leaching increases at low pH during viral inactivation — ensure clearance is validated post-VI step",
      "Limit is often resin manufacturer-derived (e.g., Cytiva guidance: ≤1 ppm recommended)",
      "Cleared by ion exchange steps; demonstrate ≥3-log clearance in validation",
      "Cross-check with resin leachables study from resin supplier extractables data",
      "BLA expectation: provide 3 consecutive DS lots; demonstrate consistent clearance",
    ],
    regulatoryNote:"Required for mAb and Fc-fusion DS manufactured via Protein A affinity capture. No universal regulatory limit, but industry standard is ≤1–10 ppm; agencies scrutinize if no dedicated removal step after affinity.",
    cqaLink:"Process-related impurity; immunogenicity and cytotoxicity risk",
  },
  {
    id:"am-qpcr",
    category:"Safety",
    icon:"🧬",
    color:"#F472B6",
    name:"Residual DNA (qPCR)",
    fullName:"Quantitative PCR for Residual Host Cell DNA",
    abbreviation:"qPCR / rt-PCR",
    purpose:"Detect and quantify residual host cell DNA (e.g., CHO genomic DNA) in biological drug substance. Residual DNA from tumorigenic/continuous cell lines poses theoretical oncogenicity and infectivity risk; WHO and FDA set limits per dose.",
    principle:"Real-time quantitative PCR (TaqMan or SYBR Green) using species-specific primers targeting repetitive genomic elements (e.g., CHO LINE-1 retroelements or Alu-like sequences). Fluorescent signal monitored per cycle; Ct values compared to standard curve of genomic DNA. Absolute quantification in pg DNA per mL or ng per dose.",
    detects:["Residual host cell DNA (pg/mL)", "DNA size distribution (≤200 bp fragments typical after downstream processing)", "Process consistency of nuclease treatment and clearance"],
    parameters:[
      { name:"LOD", typical:"<10 pg/mL (or per assay; kit-dependent)" },
      { name:"Acceptance Criteria", typical:"≤10 ng DNA/dose (WHO TRS 926); FDA recommends ≤10 ng/dose and ≤200 bp fragment size" },
      { name:"Primers", typical:"CHO-specific (LINE-1/SINE) or universal (human) depending on cell line" },
      { name:"Format", typical:"TaqMan probe 5-point standard curve; run in triplicate" },
    ],
    phases:{ "Pre-IND":false, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.4.1 / 3.2.P.5.1",
    ichRef:"ICH Q5A; WHO TRS 926 Annex 4; FDA CDER/CBER guidance on residual DNA",
    keyConsiderations:[
      "Must use cell-line-specific primers — CHO primers will not detect HEK293 DNA adequately",
      "Benzonase (nuclease) treatment during DS manufacture reduces DNA fragment size; this is acceptable if ≤200 bp confirmed",
      "Validate per ICH Q2(R1): efficiency >90%, linearity over 5 log range, specificity (no non-specific amplification)",
      "Matrix inhibition can suppress amplification — verify spike recovery ≥50% in drug substance matrix",
      "Both qPCR and Threshold Immunoassay are accepted by regulators; qPCR is now preferred for specificity",
    ],
    regulatoryNote:"WHO TRS 926 (2013) sets limit of ≤10 ng DNA/dose. FDA CBER accepts this limit with additional requirement that average DNA fragment size ≤200 bp. Both FDA and EMA expect the method validated for the specific cell line used.",
    cqaLink:"Safety impurity; oncogenicity/infectivity risk from continuous cell lines",
  },
  // ── BINDING / KINETICS ───────────────────────────────────────
  {
    id:"am-octet",
    category:"Binding/Kinetics",
    icon:"🌊",
    color:"#60A5FA",
    name:"Bio-Layer Interferometry (Octet)",
    fullName:"Bio-Layer Interferometry (BLI) — Octet / FortéBio Platform",
    abbreviation:"BLI / Octet",
    purpose:"Label-free, real-time measurement of binding kinetics (kon, koff, KD), specificity, and protein titer. Used for Fc receptor binding (FcRn, FcγRIIIa), antigen binding confirmation, QC titer assays, and process monitoring.",
    principle:"Fiber-optic biosensor tips coated with ligand are dipped into analyte wells in a 96/384-well plate. Binding of analyte to the ligand tip changes the interference pattern of reflected white light — a wavelength shift (nm) proportional to bound mass. Association and dissociation phases are measured in real time without microfluidics. Global 1:1 fitting to Langmuir model extracts kinetic constants.",
    detects:["Binding on-rate (kon, M⁻¹s⁻¹)","Binding off-rate (koff, s⁻¹)","Equilibrium dissociation constant (KD = koff/kon)","Binding specificity (selectivity against off-targets)","Fc receptor binding (FcRn affinity at pH 6 vs. pH 7.4)","Protein A/G titer in cell culture supernatant","mAb concentration in process streams"],
    parameters:[
      { name:"KD Range", typical:"1 pM – 1 µM (analyte-dependent)" },
      { name:"kon Range", typical:"10³ – 10⁷ M⁻¹s⁻¹" },
      { name:"koff Range", typical:"10⁻⁵ – 10⁻¹ s⁻¹" },
      { name:"Association Time", typical:"60–300 s (analyte-dependent)" },
      { name:"Dissociation Time", typical:"120–600 s" },
      { name:"Throughput", typical:"96-well plate; 16 samples simultaneously (Octet RED96e)" },
      { name:"Titer Assay Range", typical:"0.01–10 mg/mL (Protein A Biosensor)" },
    ],
    phases:{ "Pre-IND":true, "IND":true, "Ph1":true, "Ph2":true, "Ph3":true, "BLA":true },
    ctdSection:"3.2.S.3.1 / 3.2.S.4.1",
    ichRef:"ICH Q6B §3.2; ASTM E2917 (biosensor methods)",
    keyConsiderations:[
      "Vs SPR: Octet is plate-based (higher throughput, lower sensitivity) vs. SPR microfluidics (lower throughput, ≥10× higher sensitivity for weak binders)",
      "Tip loading density must be optimized — too high causes steric effects; too low reduces signal",
      "Regeneration must be validated to remove bound analyte without damaging ligand; glycine pH 1.5–2.0 common",
      "For FcRn binding, run at pH 6.0 (binding) and pH 7.4 (release) to mimic endosomal recycling",
      "Titer assays require Protein A biosensor calibrated with certified reference standard",
      "Mass transport limitation (MTL) must be checked — if rate increases with analyte flow, data is MTL-limited",
    ],
    regulatoryNote:"FDA expects binding characterization (antigen and Fc receptors) in BLA 3.2.S.3.1. BLI data is accepted alongside SPR. FcRn binding data increasingly expected to support PK half-life predictions. Titer BLI assays must be validated per ICH Q2(R1) for process QC use.",
    cqaLink:"Biological activity, antigen binding, Fc effector function (FcγRIIIa), half-life (FcRn)",
  },
];

// ── CTD Navigator ───────────────────────────────────────────
export const CTD_MODULES = [
  {
    id:"m1",
    module:1,
    label:"Module 1 — Regional Administrative",
    icon:"🗂️",
    color:"#94A3B8",
    description:"Region-specific documents: cover letters, application forms, patient information leaflets, prescribing information, and labeling. Not harmonized across regions — each submission target (FDA, EMA, PMDA) has unique Module 1 requirements.",
    sections:[
      { id:"1.1", label:"1.1 — Comprehensive Table of Contents", description:"Complete document index for the entire submission dossier.", keyContent:["Master document index","Cross-reference to all modules"], tips:"FDA uses eCTD; ensure all hyperlinks and bookmarks validate." },
      { id:"1.2", label:"1.2 — Application Form / Cover Letter", description:"FDA Form 356h (BLA) or EMA application form. Contains administrative data including applicant info, product name, dosage form, strength, route.", keyContent:["BLA/NDA/MAA form","Applicant information","Proposed indication"], tips:"BLA: submit Form 356h signed by authorized representative. EMA: submit EMA Application Form eSubmission." },
      { id:"1.4", label:"1.4 — Information Amendments (FDA) / 1.3 Labeling (EMA)", description:"For FDA: proposed US Prescribing Information (USPI), patient labeling, carton/container labels. For EMA: EU SmPC, labeling, package leaflet.", keyContent:["USPI (FDA 2006 labeling rule format)","Indications, contraindications, dosage","Patient Medication Guide"], tips:"FDA PLR labeling format required. Boxed warnings reviewed by DMEPA. EMA SmPC follows CHMP template." },
    ]
  },
  {
    id:"m2",
    module:2,
    label:"Module 2 — Summaries & Overviews",
    icon:"📋",
    color:"#38BDF8",
    description:"Technical summaries that bridge the detailed data in Modules 3–5. Written for expert reviewers. Quality Overall Summary (QOS) is the CMC narrative; nonclinical and clinical overviews provide integrated scientific arguments.",
    sections:[
      { id:"2.3", label:"2.3 — Quality Overall Summary (QOS)", description:"A narrative summary of all CMC (Module 3) content. Structured per ICH M4Q(R1). Describes DS and DP manufacturing, characterization, specifications, and stability. Must be internally consistent with Module 3 data.", keyContent:["DS and DP manufacturing summary","Specification tables and rationale","Critical quality attributes (CQAs) and justification","Stability summary and proposed shelf-life","Container closure system description"], tips:"QOS is often the first document FDA reviewers read. Clarity and cross-references are critical. Every specification must be justified. Use tabular format for clarity." },
      { id:"2.4", label:"2.4 — Nonclinical Overview", description:"Integrated narrative of pharmacology, ADME, and toxicology data. Discusses adequacy of nonclinical package to support clinical use.", keyContent:["Primary pharmacodynamics","Safety pharmacology","Pharmacokinetics/ADME","Repeat-dose toxicology","Reproductive and developmental tox","Genotoxicity"], tips:"Written by nonclinical lead; CMC team provides drug substance characterization to support toxicology study materials." },
      { id:"2.5", label:"2.5 — Clinical Overview", description:"Scientific discussion of clinical development, benefit-risk assessment, and conclusions. Integrates PK, PD, efficacy, and safety.", keyContent:["Clinical pharmacology","Efficacy summary","Safety summary","Benefit-risk analysis"], tips:"Must be internally consistent with Module 5 study reports. FDA's clinical reviewers scrutinize the benefit-risk argument." },
      { id:"2.6", label:"2.6 — Nonclinical Written Summaries", description:"Detailed tables and written summaries of all nonclinical studies. Tabulated study summaries and pharmacology/PK/toxicology written summaries.", keyContent:["Pharmacology written summary","Pharmacokinetics written summary","Toxicology written summary","Tabulated study summaries"], tips:"Each study table must follow ICH M4S format. Include study number, species, dose, duration, findings, and NOAEL." },
      { id:"2.7", label:"2.7 — Clinical Summary", description:"Comprehensive summary of clinical studies with patient-level data, population PK, PD, exposure-response, integrated benefit-risk.", keyContent:["Biopharmaceutics","PK (absorption, distribution, metabolism)","Exposure-response","Clinical efficacy summary","Clinical safety summary","Patient-level tabulations"], tips:"Largest Module 2 section. Patient-level tables must match individual study reports in Module 5." },
    ]
  },
  {
    id:"m3",
    module:3,
    label:"Module 3 — Quality (CMC)",
    icon:"🔬",
    color:"#34D399",
    description:"The complete Chemistry, Manufacturing, and Controls (CMC) dossier. Organized per ICH M4Q(R1) into Body of Data (3.2) covering Drug Substance (S) and Drug Product (P), plus appendices, literature, and regional information. Most extensive module for biologics.",
    sections:[
      { id:"3.2.S", label:"3.2.S — Drug Substance (DS)", description:"Complete characterization and control strategy for the active biologic molecule. Organized into 7 subsections.", keyContent:["S.1 General Info","S.2 Manufacture","S.3 Characterization","S.4 Control","S.5 Reference Standards","S.6 Container Closure","S.7 Stability"], tips:"DS is the heart of the CMC package. All characterization must be done on representative material from the intended commercial process. Reference standard must be fully characterized." },
      { id:"3.2.S.1", label:"3.2.S.1 — General Information", description:"Basic molecular description, properties, and structure of the drug substance.", keyContent:["INN (International Non-proprietary Name)","Molecular formula and weight","Amino acid sequence and disulfide bonds","Schematic structure / domain organization","List of post-translational modifications"], tips:"Include ribbon diagram of protein structure where available. Clearly annotate all glycosylation sites, disulfide bonds, CDRs (for mAbs)." },
      { id:"3.2.S.2", label:"3.2.S.2 — Manufacture", description:"Complete manufacturing process description for drug substance including cell banking, fermentation/cell culture, purification, and filling.", keyContent:["Cell line origin and banking (MCB/WCB)","Manufacturing process description (step-by-step)","Process controls and IPCs","Scale and manufacturing site","Process validation strategy (PPQ approach)","Resin lifetime and viral clearance studies"], tips:"Each unit operation must include operating parameters, IPCs, and acceptance criteria. Process validation must span PPQ runs (≥3 batches at commercial scale per FDA guidance)." },
      { id:"3.2.S.3", label:"3.2.S.3 — Characterization", description:"Extensive structural and biological characterization of the drug substance including primary structure, higher-order structure, biological activity, and immunochemical properties.", keyContent:["Primary structure (sequence, glycosylation, disulfide bonds)","Higher-order structure (HOS) — CD, FTIR, DSC, HDX-MS","Biological activity (potency, binding, FcR interactions)","Immunochemical properties (target antigen binding)","Physicochemical properties (pI, extinction coefficient, aggregation profile)","Process-related impurities characterization"], tips:"Use ICH Q6B as the characterization framework. Include orthogonal methods for each attribute. HOS toolkit: far-UV CD, near-UV CD, DSC, DLS, SEC-MALS, HDX-MS." },
      { id:"3.2.S.4", label:"3.2.S.4 — Control of Drug Substance", description:"Specification, analytical methods, validation, batch analyses, and justification of specification. This is the quality control framework for DS.", keyContent:["3.2.S.4.1 — Specification (table with tests, methods, acceptance criteria)","3.2.S.4.2 — Analytical Procedures (method descriptions)","3.2.S.4.3 — Validation (ICH Q2 full validation for all QC methods)","3.2.S.4.4 — Batch Analyses (≥3 representative clinical/commercial batches)","3.2.S.4.5 — Justification of Specification (CQA linkage)"], tips:"ICH Q2(R1) method validation: specificity, linearity, range, accuracy, precision, LOD/LOQ. Spec justification: use CQA risk assessment, clinical lots data, and safety margin principles." },
      { id:"3.2.S.5", label:"3.2.S.5 — Reference Standards & Materials", description:"Establishment and qualification of the primary and working reference standards used in all drug substance analytical testing.", keyContent:["Reference standard establishment and characterization","Certificate of Analysis for reference materials","Storage conditions and stability of RS","Replenishment strategy","Bridging protocol when RS is replaced"], tips:"RS must be fully characterized — same assay suite as DS characterization. Traceability to primary RS critical. FDA expects 2-tiered system: primary RS (fully characterized) and working RS (qualified against primary)." },
      { id:"3.2.S.6", label:"3.2.S.6 — Container Closure System (DS)", description:"Description of container closure system for drug substance storage (bulk) including materials and suitability testing.", keyContent:["Container description (stainless steel, biocontainer, cryovessels)","Extractables and leachables assessment","Compatibility studies (DS in contact with materials)","Suitability for intended storage conditions"], tips:"Biocontainers (plastic bags) require full extractables characterization. Migration studies at drug substance concentration and storage temperature." },
      { id:"3.2.S.7", label:"3.2.S.7 — Stability (DS)", description:"Stability studies for drug substance establishing shelf-life and storage conditions per ICH Q5C.", keyContent:["Stability protocol (ICH Q5C conditions, time points)","Long-term studies (intended storage condition)","Accelerated/intermediate studies","Degradation pathway summary","Proposed shelf-life and storage conditions"], tips:"ICH Q5C: real-time data to support shelf-life. Accelerated studies (37°C/6 mo) detect aggregation, oxidation, deamidation. Long-term (–20°C or –80°C) extends over product lifecycle." },
      { id:"3.2.P", label:"3.2.P — Drug Product (DP)", description:"All CMC information for the final formulated drug product. Organized into 8 subsections covering formulation, manufacture, specifications, and stability.", keyContent:["P.1 Description","P.2 Pharmaceutical Development","P.3 Manufacture","P.4 Excipients","P.5 Control","P.6 Reference Standards","P.7 Container Closure","P.8 Stability"], tips:"Pharmaceutical Development (P.2) is a critical narrative showing the science behind formulation and container choices. FDA reviewers expect a Quality-by-Design rationale." },
      { id:"3.2.P.1", label:"3.2.P.1 — Description & Composition", description:"Physical description, composition, and fill volume of the drug product.", keyContent:["Dosage form description (liquid for injection, lyophilized powder)","Composition table: component, function, amount","Regulatory status of excipients","Reconstitution volume (if lyophilized)"], tips:"Include appearance specification in composition description. Reference each excipient's compendial status (USP/EP/JP)." },
      { id:"3.2.P.2", label:"3.2.P.2 — Pharmaceutical Development", description:"Scientific narrative of formulation development including excipient selection, compatibility, target product profile, and container closure selection rationale.", keyContent:["Target Product Profile (TPP)","Formulation screening data (DoE studies)","Excipient rationale and compatibility data","Freeze-thaw and agitation studies","Container closure selection rationale","Leachables risk assessment for DP","In-use stability (multi-dose or after reconstitution)"], tips:"This is where QbD lives. Show design space experimentation. Include DoE outputs. Justify each excipient's function. Polysorbate 80 concentration must be justified against subvisible particle data." },
      { id:"3.2.P.3", label:"3.2.P.3 — Manufacture (DP)", description:"Drug product manufacturing process including formulation, sterile filtration, filling, lyophilization (if applicable), and inspection.", keyContent:["Manufacturing process flow diagram","Description of each unit operation","In-process controls (IPC) and acceptance criteria","Manufacturing site and batch size","Process validation approach (PPQ)","Aseptic process validation (media fills)"], tips:"Sterile filtration validation: filter integrity, bacterial retention, extractables. Lyophilization cycle validation per FDA guidance. Aseptic media fill per PDA TR 22." },
      { id:"3.2.P.5", label:"3.2.P.5 — Control of Drug Product", description:"Specification, analytical methods, validation, and batch analyses for drug product lot release.", keyContent:["3.2.P.5.1 — Specification (tests, methods, acceptance criteria)","3.2.P.5.2 — Analytical Procedures","3.2.P.5.3 — Validation","3.2.P.5.4 — Batch Analyses (≥3 representative DP batches)","3.2.P.5.6 — Justification of Specification"], tips:"DP specification includes: appearance, identity (HPLC, CD, or dot blot), potency, purity (SEC, CE-SDS), concentration, pH, osmolality, particulates (USP <787>, <788>), sterility, endotoxin, and container closure integrity." },
      { id:"3.2.P.8", label:"3.2.P.8 — Stability (DP)", description:"Stability studies for drug product establishing shelf-life and storage conditions per ICH Q5C, Q1A(R2).", keyContent:["DP stability protocol (ICH conditions)","Primary stability batches (≥3 at commercial scale)","Photostability (ICH Q1B)","In-use stability","Post-approval stability commitments"], tips:"DP stability includes: accelerated (25°C/60% RH or 40°C/75% RH for 6 mo), long-term (2–8°C for refrigerated biologics). Protein-specific tests at each time point. Trending per ICH Q1E." },
    ]
  },
  {
    id:"m4",
    module:4,
    label:"Module 4 — Nonclinical Study Reports",
    icon:"🐭",
    color:"#F59E0B",
    description:"Complete nonclinical study reports: pharmacology, pharmacokinetics, and toxicology. Each study report follows CDISC SEND format for electronic submission. Covers safety pharmacology, repeat-dose tox, reproductive tox, genotoxicity (limited for biologics).",
    sections:[
      { id:"4.2.1", label:"4.2.1 — Pharmacology", description:"Primary pharmacodynamics (target engagement, mechanism), secondary pharmacodynamics (off-target), safety pharmacology (cardiovascular, CNS, respiratory).", keyContent:["In vitro binding studies","In vivo efficacy models","Safety pharmacology battery (ICH S7A/S7B)","Antigen characterization"], tips:"Biologics: safety pharmacology battery may be incorporated into general toxicology studies in relevant species. Justify species selection (human target homology)." },
      { id:"4.2.2", label:"4.2.2 — Pharmacokinetics / ADME", description:"PK characterization in nonclinical species: single-dose IV/SC PK, tissue distribution, immunogenicity (ADA assessment), species comparison.", keyContent:["Single and repeat-dose PK","Tissue distribution (if relevant)","Drug-drug interaction potential","ADA characterization in tox species"], tips:"Biologics typically do not undergo CYP-mediated metabolism. Focus on catabolism, FcRn recycling, target-mediated drug disposition (TMDD)." },
      { id:"4.2.3", label:"4.2.3 — Toxicology", description:"Complete toxicology package: single-dose, repeat-dose (13 and 26 weeks), reproductive and developmental toxicology, genetic toxicology (typically negative for biologics), carcinogenicity (usually waived).", keyContent:["Acute dose-response","Subchronic/chronic toxicology (GLP)","Reproductive tox (embryofetal development, PNDT)","Local tolerance studies","Immunotoxicology (ICH S8)"], tips:"Species selection: use species pharmacologically responsive to the biologic (receptor homology >80%). Often only one species required for mAbs if only one relevant species exists." },
    ]
  },
  {
    id:"m5",
    module:5,
    label:"Module 5 — Clinical Study Reports",
    icon:"🏥",
    color:"#F472B6",
    description:"Complete clinical study reports for all human studies supporting the application: Phase 1 (safety/PK), Phase 2 (dose-finding/signal), Phase 3 (confirmatory efficacy/safety), and supporting studies (bioequivalence, special populations). Organized per ICH E3 format.",
    sections:[
      { id:"5.3.1", label:"5.3.1 — Biopharmaceutics Studies", description:"Relative bioavailability, bioequivalence, and in vitro dissolution (not typically relevant for parenterals). For biologics: SC vs IV comparison, concentration-effect relationships.", keyContent:["Absolute bioavailability (SC route)","Drug product comparability to clinical material"], tips:"SC biologics: absolute bioavailability must be characterized (typically 50–90% for mAbs). Include PopPK model to bridge formulations." },
      { id:"5.3.3", label:"5.3.3 — PK & PK/PD Studies", description:"All pharmacokinetic and pharmacokinetic/pharmacodynamic studies: dose-linearity, time-dependence, population PK, covariate analysis, exposure-response.", keyContent:["First-in-human (FIH) PK","Dose-escalation PK summary","Population PK model","Exposure-response analysis","Special populations (renal/hepatic impairment, pediatric)"], tips:"PopPK report should follow FDA Guidance on Population PK. Covariate analysis (body weight, ADA, FcRn polymorphism) often required for dosing rationale." },
      { id:"5.3.5", label:"5.3.5 — Efficacy Study Reports", description:"Full study reports for all Phase 2/3 efficacy trials. Includes statistical analysis plans, blind review and unblinding procedures, and primary/secondary endpoint data.", keyContent:["Phase 2 proof-of-concept studies","Phase 3 pivotal trials (pre-specified primary endpoint)","Subgroup analyses","Long-term extension studies"], tips:"FDA: must include all studies — positive and negative. Pre-specified analysis plans (SAP) are binding. Subgroup analyses must be clearly labeled as exploratory." },
      { id:"5.3.6", label:"5.3.6 — Safety Study Reports", description:"Integrated safety summary, individual patient narratives for SAEs, immunogenicity (ADA) characterization, special safety studies.", keyContent:["Adverse event tables (pooled)","Serious adverse events (SAE) narratives","ADA incidence and clinical impact","Immunogenicity assessment per FDA guidance"], tips:"ADA assay validation must follow FDA 2019 Immunogenicity Guidance. Titer and neutralizing ADA must be reported. Clinical impact of ADA on PK and efficacy/safety must be analyzed." },
    ]
  },
];

// ── CMC Development Timeline ────────────────────────────────
export const CMC_TIMELINE = [
  {
    phase:"Target Identification & Hit-to-Lead",
    shortPhase:"Hit-to-Lead",
    years:"Year 0–1",
    icon:"🎯",
    color:"#94A3B8",
    keyMilestone:"Select lead molecule(s) for IND-enabling studies",
    regulatoryEvent:"Pre-IND meeting preparation",
    deliverables:[
      { category:"Cell Line", items:["Transient expression for initial material","Stable clone selection initiated","CHO or NS0 cell line development begins"] },
      { category:"Analytics", items:["Initial SDS-PAGE / SEC for purity","Basic ELISA for potency","ELISA-based binding assay established"] },
      { category:"Formulation", items:["Identify initial formulation buffer","Thermal stability screening (DSF)"] },
    ]
  },
  {
    phase:"IND-Enabling Studies",
    shortPhase:"Pre-IND",
    years:"Year 1–2",
    icon:"📋",
    color:"#60A5FA",
    keyMilestone:"IND submission enabling first-in-human dosing",
    regulatoryEvent:"IND filing; Pre-IND meeting with FDA (optional but recommended)",
    deliverables:[
      { category:"Cell Line & Manufacturing", items:["Research cell bank (RCB) established","Small-scale process development (bioreactor <100L)","Protein A capture + polishing steps defined","DS manufacturing for tox studies (GLP lots)","Process characterization at small scale"] },
      { category:"Characterization (Abbreviated)", items:["Primary sequence confirmed (peptide mapping)","Molecular weight confirmed (intact MS)","SEC-HPLC purity (≥85%)","CE-SDS (reduced + non-reduced)","Glycan profiling initiated","Potency assay (cell-based) development"] },
      { category:"Analytical Development", items:["QC release methods developed","Potency assay qualified (not validated)","Reference standard established (initial)","In-process assays developed"] },
      { category:"Formulation", items:["Formulation screening (pH, ionic strength, excipients)","Initial forced degradation studies","Select tentative DP formulation","Compatibility with container closure"] },
      { category:"GMP Manufacturing", items:["First GMP DS lots (Phase 1 clinical)","First GMP DP lots (Phase 1 clinical)","Initial specifications set (broad)","Certificate of Analysis generated"] },
      { category:"Regulatory", items:["IND Module 2 QOS draft","Module 3 (CMC): abbreviated characterization","DS and DP specifications","Stability commitments (≥3 months at 3 temperatures)"] },
    ]
  },
  {
    phase:"Phase 1 — First-in-Human",
    shortPhase:"Phase 1",
    years:"Year 2–4",
    icon:"🧪",
    color:"#34D399",
    keyMilestone:"Safety/PK characterization; dose escalation",
    regulatoryEvent:"IND Annual Reports; CMC amendments for process changes; Type B meeting for Phase 2",
    deliverables:[
      { category:"Manufacturing Scale-Up", items:["Scale-up to Phase 1/2 scale (200–2000L)","Process optimization and characterization","Hold time studies (DS and intermediates)","Resin lifetime studies initiated"] },
      { category:"Analytics & Methods", items:["Full ICH Q2 method validation for release assays","Potency assay validation in progress","Reference standard fully characterized (Phase 1 RS)","SEC, CE-SDS, cIEF/icIEF, A280 validated"] },
      { category:"Characterization (Extended)", items:["Full peptide mapping with modifications","Intact mass analysis","Glycan profiling (HILIC-UPLC)","DLS (colloidal stability)","DSC (thermal stability)","CD spectroscopy (HOS) initial data"] },
      { category:"Formulation", items:["Formulation finalized (if not planned change)","In-use stability study","Freeze-thaw characterization (≥5 cycles)","Extractables/leachables (Phase 1)","Photostability (ICH Q1B)"] },
      { category:"Stability", items:["Ongoing long-term stability for DS and DP","Accelerated stability (25°C or 37°C, 6 months)","Stability results support Phase 1 shelf-life","Stability protocol per ICH Q5C"] },
      { category:"CMC Amendments", items:["Any manufacturing process change requires CMC amendment","Comparability studies if change post-Phase 1 start","Updated specifications based on clinical lot data"] },
    ]
  },
  {
    phase:"Phase 2 — Dose-Finding & Efficacy Signal",
    shortPhase:"Phase 2",
    years:"Year 3–6",
    icon:"📊",
    color:"#F59E0B",
    keyMilestone:"Establish Phase 3 dose(s); lock commercial process",
    regulatoryEvent:"End of Phase 2 (EOP2) meeting with FDA — critical CMC discussion",
    deliverables:[
      { category:"Process Lock", items:["Commercial-scale process defined","Upstream parameters locked (bioreactor conditions, media)","Downstream steps fixed (columns, ultrafiltration)","Hold times validated","Cell age (EOPC) established"] },
      { category:"Full Characterization", items:["Complete ICH Q6B characterization package","HOS full toolkit (CD, DSC, DLS, FTIR, HDX-MS)","Biological activity — potency assay validated","FcR binding panel (FcγRI, FcγRIIIa, FcRn, C1q)","Glycan CQA assessment and spec setting"] },
      { category:"Control Strategy", items:["Formal CQA risk assessment (Criticality scoring)","Design space definition (if QbD approach)","In-process controls and raw material controls","Impurity profiles and acceptance criteria","Extractables & leachables — full study"] },
      { category:"Reference Standard", items:["Phase 2/3 reference standard established","Full characterization vs. Phase 1 RS","Bridging study data (RS-to-RS)","RS vial stability study"] },
      { category:"Stability", items:["Long-term stability supports Phase 2 shelf-life","Commercial package configuration tested","Accelerated degradation studies (stress)","CQA stability trend analysis"] },
      { category:"Comparability", items:["Process change comparability studies (analytical)","Phase 1 to Phase 2 scale bridging","In vitro comparability: SEC, CE-SDS, potency, HOS","In vivo PK/PD bridging if needed"] },
    ]
  },
  {
    phase:"Phase 3 — Pivotal Efficacy & Safety",
    shortPhase:"Phase 3",
    years:"Year 5–9",
    icon:"🏆",
    color:"#F472B6",
    keyMilestone:"Generate data to support BLA submission; process validation",
    regulatoryEvent:"Pre-BLA meeting; Rolling Review submission possible; Facility inspection preparation",
    deliverables:[
      { category:"Process Performance Qualification (PPQ)", items:["≥3 commercial-scale PPQ batches","PPQ batches at intended commercial site","Demonstrate consistent process performance","PPQ report with all batch data and statistical analysis","Annual Product Review (APR) data"] },
      { category:"Analytical Method Revalidation", items:["Validate all commercial QC methods (ICH Q2)","Technology transfer to commercial QC lab","Method transfer studies (pass/fail criteria)","Laboratory equivalency demonstrated"] },
      { category:"Validation Studies", items:["Viral clearance validation (2–4 steps, ≥4-log clearance each)","Mycoplasma testing of cell banks","Adventitious virus testing (in vitro/in vivo)","Filter integrity validation at scale","Cleaning validation (equipment, facilities)"] },
      { category:"Specifications Tightening", items:["Refine specifications based on PPQ and Phase 3 lots","Statisticalspec setting (mean ± 3σ for continuous parameters)","Trending analysis of process controls","Justify each acceptance criterion"] },
      { category:"Stability — Final", items:["≥3 PPQ batches on stability","Real-time data to support proposed shelf-life","Trend analysis per ICH Q1E","Post-approval stability commitment defined"] },
      { category:"Supplier Qualification", items:["Critical raw material supplier audits","Cell culture media and feed qualification","Biocontainer extractables clearance","Regulatory starting material (RSM) designation"] },
    ]
  },
  {
    phase:"BLA / NDA Submission",
    shortPhase:"BLA",
    years:"Year 8–11",
    icon:"📤",
    color:"#A78BFA",
    keyMilestone:"File Biologics License Application (BLA) or NDA",
    regulatoryEvent:"FDA PDUFA goal: 12-month standard review; 6-month priority review; Facility inspection",
    deliverables:[
      { category:"eCTD Assembly", items:["Complete Module 2 QOS (quality narrative)","Module 3 CMC sections fully compiled","All referenced studies cross-linked","Electronic submission validation (eCTD v4.0)"] },
      { category:"FDA Interactions", items:["Pre-BLA meeting (discuss data needs, strategy)","Respond to FDA information requests (IRs / CRs)","Facility inspection readiness","PAI (Pre-Approval Inspection) at manufacturing site"] },
      { category:"Post-Submission CMC", items:["Respond to deficiency letters","Manufacturing changes during review require Prior Approval Supplements (PAS) or CBE-30","Labeling negotiations (CMC-relevant claims)"] },
    ]
  },
  {
    phase:"Post-Approval Lifecycle",
    shortPhase:"Post-Approval",
    years:"Year 11+",
    icon:"♻️",
    color:"#34D399",
    keyMilestone:"Commercial manufacturing; ongoing lifecycle management",
    regulatoryEvent:"Annual reports; PAS/CBE for changes; Post-approval studies",
    deliverables:[
      { category:"Change Management", items:["Post-approval supplements for manufacturing changes","Comparability studies for any process/formulation change","ICH Q12 lifecycle management plan","PACMP (Post-Approval Change Management Protocol)"] },
      { category:"Ongoing Monitoring", items:["Annual Product Review (APR / PQR)","Annual stability updates","Process trending and CPV (Continued Process Verification)","Returned goods and out-of-specification (OOS) investigations"] },
      { category:"Lifecycle Extensions", items:["New formulations or concentrations","New indications (supplemental BLAs)","New manufacturing sites (site change supplements)","Biosimilar reference product characterization support"] },
    ]
  },
];

// ── ICH Guidelines Quick Reference ─────────────────────────
export const ICH_GUIDELINES = [
  { id:"q1a", code:"ICH Q1A(R2)", topic:"Stability Testing of New Drug Substances and Products", category:"Quality", color:"#34D399",
    summary:"Defines conditions, time points, and acceptance criteria for stability studies. Long-term, accelerated, and intermediate conditions specified.",
    key:["Long-term: 25°C/60% RH or 30°C/65% RH for 12+ months","Accelerated: 40°C/75% RH for 6 months","Intermediate: 30°C/65% RH if accelerated fails","Refrigerated: 5°C long-term; 25°C accelerated"],
    cmc:"Biological drugs typically stored at 2–8°C; accelerated at 25°C. Real-time data required to support claimed shelf-life." },
  { id:"q2r1", code:"ICH Q2(R1)", topic:"Validation of Analytical Procedures", category:"Quality", color:"#34D399",
    summary:"Framework for analytical method validation: specificity, linearity, range, accuracy, precision (repeatability/intermediate/reproducibility), LOD, LOQ, robustness.",
    key:["Specificity: demonstrates method measures only intended analyte","Linearity: linear response across range (r² ≥0.999)","Precision: repeatability (same day, same analyst), intermediate (different day/analyst)","Accuracy: % recovery 98–102% typical for quantitative methods"],
    cmc:"All QC release methods must be validated per Q2. Bioassays follow USP <1033>/<1032> in addition to Q2." },
  { id:"q5c", code:"ICH Q5C", topic:"Stability Testing of Biotechnological/Biological Products", category:"Quality", color:"#34D399",
    summary:"Stability requirements specific to biologics. Addresses protein-specific degradation pathways and real-time data requirements.",
    key:["No accelerated stability surrogates — real-time data required for shelf-life","Relevant stability-indicating tests: aggregation, deamidation, oxidation, potency","Minimum 3 lots on stability; primary stability batches defined","Long-term: data must exceed proposed shelf-life before approval"],
    cmc:"Critical: accelerated stability (37°C) is informational only for biologics — cannot extrapolate to shelf-life claim." },
  { id:"q6b", code:"ICH Q6B", topic:"Specifications: Test Procedures and Acceptance Criteria for Biotechnological/Biological Products", category:"Quality", color:"#34D399",
    summary:"Framework for establishing specifications for biotechnological products. Covers identity, purity, potency, quantity, and safety tests.",
    key:["Identity: physicochemical + immunochemical methods","Purity: process-related (HCPs, DNA) and product-related (aggregates, fragments)","Potency: biological activity reflecting mechanism of action","Safety: sterility, endotoxin, adventitious agents"],
    cmc:"Specifications must be justified based on: analytical capability, clinical lot data, and safety margins. CQA linkage required." },
  { id:"q8r2", code:"ICH Q8(R2)", topic:"Pharmaceutical Development", category:"Quality", color:"#34D399",
    summary:"Framework for quality-by-design (QbD) approach to pharmaceutical development. Defines Target Product Profile, CQAs, design space, and control strategy.",
    key:["Target Product Profile (TPP): desired clinical performance attributes","Quality Target Product Profile (QTPP): quality attributes linked to TPP","CQAs: attributes that must be controlled to ensure product quality","Design Space: proven acceptable ranges (PARs) for process parameters"],
    cmc:"QbD approach: DoE studies define design space; validated process parameters within design space don't require post-approval changes." },
  { id:"q9", code:"ICH Q9", topic:"Quality Risk Management", category:"Quality", color:"#34D399",
    summary:"Risk management framework for pharmaceutical quality. FMEA (Failure Mode and Effects Analysis) and other tools for systematic risk assessment.",
    key:["FMEA: Severity × Occurrence × Detectability = RPN","Risk prioritization for CQA identification","Formal risk assessment required for control strategy justification","Risk review triggers: process changes, OOS investigations"],
    cmc:"CQA classification (critical vs. non-critical) requires formal risk assessment. Risk tools: FMEA, HACCP, fault trees, Ishikawa diagrams." },
  { id:"q10", code:"ICH Q10", topic:"Pharmaceutical Quality System", category:"Quality", color:"#34D399",
    summary:"Pharmaceutical Quality System (PQS) model based on ISO 9001 adapted for pharma. Covers product lifecycle from development through discontinuation.",
    key:["Quality management system: SOPs, deviation management, CAPA","Knowledge management: process and product understanding","Continual improvement: process trending, CPV","Change management: documented, risk-based"],
    cmc:"Commercial manufacturing must operate under a validated PQS. Annual Product Reviews assess process trends and CQA trending." },
  { id:"q11", code:"ICH Q11", topic:"Development and Manufacture of Drug Substances (Chemical and Biotechnological)", category:"Quality", color:"#34D399",
    summary:"Guidance on demonstrating understanding of drug substance development and manufacturing for both small molecules and biologics.",
    key:["Development history: materials, process, product understanding","Selection of starting materials (including biological starting materials)","Process description at commercial scale","Control strategy development"],
    cmc:"For biologics: cell line development, cell banking, culture and purification process must be fully documented and understood." },
  { id:"q12", code:"ICH Q12", topic:"Technical and Regulatory Considerations for Pharmaceutical Product Lifecycle Management", category:"Quality", color:"#34D399",
    summary:"Framework for managing post-approval changes more efficiently. Establishes Established Conditions (ECs) and Post-Approval Change Management Protocols (PACMPs).",
    key:["Established Conditions (ECs): parameters that require regulatory submission when changed","PACMPs: pre-approved protocols for expected future changes","Product Lifecycle Management (PLCM) document","Structured approach: categorize changes by risk level"],
    cmc:"Allows companies to prospectively agree with regulators on what changes can be implemented as CBE-30 vs. PAS. Reduces change management burden." },
];

// ── Regulatory Pathways ─────────────────────────────────────
export const REGULATORY_PATHWAYS = [
  { id:"bla", name:"Biologics License Application (BLA)", icon:"🇺🇸", color:"#60A5FA", agency:"FDA (CDER/CBER)",
    products:"Monoclonal antibodies, proteins, vaccines, blood products, gene therapies, cell therapies",
    keyReqs:["21 CFR Part 601 (biologics regulations)","Complete safety (12-month IND minimum) and efficacy data","3 PPQ batches at commercial scale","Validated viral clearance","BsUFA or PDUFA filing fee"],
    reviewTime:"12 months (standard) / 6 months (priority review / breakthrough therapy)",
    designations:["Breakthrough Therapy Designation (BTD) — intensive FDA guidance","Fast Track — rolling review","Accelerated Approval — surrogate endpoint","Priority Review — serious condition"],
    notes:"BLA replaces NDA for biologics. Biosimilars file as 351(k) BLA. Approval = Biologics License (can be revoked)." },
  { id:"nda", name:"New Drug Application (NDA)", icon:"🇺🇸", color:"#38BDF8", agency:"FDA (CDER)",
    products:"Small molecule drugs; some protein products from established cell lines",
    keyReqs:["21 CFR Part 314","Full Phase 3 efficacy and safety data","Drug substance and drug product CMC","cGMP manufacturing compliance"],
    reviewTime:"12 months standard / 6 months priority",
    designations:["QIDP (Qualified Infectious Disease Product)","Rare Pediatric Disease Priority Review Voucher"],
    notes:"Biologics Act of 2009 (ACA §7002): most proteins transitioned from NDA to BLA by 2020." },
  { id:"maa", name:"Marketing Authorization Application (MAA)", icon:"🇪🇺", color:"#34D399", agency:"EMA (CHMP)",
    products:"All medicinal products for EU market (centralized procedure recommended for biologics)",
    keyReqs:["ICH CTD format","Benefit-risk demonstrated","GMP compliance (EMA GMP guidelines)","Parallel scientific advice available"],
    reviewTime:"210 days (active review days) + clock-stops",
    designations:["Accelerated Assessment — major public health interest (150-day review)","Conditional Marketing Authorization","Exceptional Circumstances (ongoing obligation studies)"],
    notes:"Biosimilar pathway: Article 8 of Directive 2001/83/EC. CHMP Scientific Advice highly recommended pre-submission." },
  { id:"biosimilar", name:"Biosimilar Pathway (FDA 351(k))", icon:"🔄", color:"#A78BFA", agency:"FDA (CDER)",
    products:"Biologics with an approved reference product (RP) in US",
    keyReqs:["Analytical similarity (fingerprint-like analysis)","PK/PD bridging studies","Safety + immunogenicity comparison to RP","Clinical efficacy (may be waived with robust analytical package)","Same mechanism of action, route, dosage form"],
    reviewTime:"12 months (similar to BLA)",
    designations:["Interchangeable designation — substitutable at pharmacy without prescriber intervention"],
    notes:"Totality-of-evidence approach. EMA Article 10(4): similar biological medicinal product (SBMP). 12-year data exclusivity for reference product." },
];

// ── Process Flow Connections ────────────────────────────────
export const PROCESS_CONNECTIONS = [
  { from:"Cell Line Dev", to:"Cell Banking", icon:"→" },
  { from:"Cell Banking", to:"Upstream Process", icon:"→" },
  { from:"Upstream Process", to:"Harvest/Clarification", icon:"→" },
  { from:"Harvest/Clarification", to:"Protein A Capture", icon:"→" },
  { from:"Protein A Capture", to:"Viral Inactivation (Low pH)", icon:"→" },
  { from:"Viral Inactivation", to:"Polishing Chromatography", icon:"→" },
  { from:"Polishing Chromatography", to:"Viral Filtration", icon:"→" },
  { from:"Viral Filtration", to:"UF/DF (Concentration)", icon:"→" },
  { from:"UF/DF", to:"Formulation & Bulk Fill", icon:"→" },
  { from:"Formulation & Bulk Fill", to:"Drug Substance (Bulk)", icon:"→" },
  { from:"Drug Substance (Bulk)", to:"DP Compounding", icon:"→" },
  { from:"DP Compounding", to:"Sterile Filtration", icon:"→" },
  { from:"Sterile Filtration", to:"Aseptic Fill-Finish", icon:"→" },
  { from:"Aseptic Fill-Finish", to:"Inspection & Release", icon:"→" },
];
