// src/oos-data.js — FDA 2006 OOS Guidance + ICH Q10 decision framework

export const OOS_TREE = {
  start: {
    id: "start",
    phase: "Initial Assessment",
    question: "Has an Out-of-Specification (OOS) or Out-of-Trend (OOT) result been obtained?",
    guidance: "Document the result immediately. Do not discard samples or data. Initiate formal OOS investigation per 21 CFR 211.192 and FDA 2006 OOS Guidance.",
    example: "An HPLC potency result for ibuprofen 200 mg tablets returns 94.8% against a specification of 97.0–103.0%. The analyst flags the result and initiates the OOS procedure.",
    ref: "FDA 2006 OOS Guidance; 21 CFR 211.192",
    yes: "phase1-start",
    no: null,
    yesLabel: "Yes — OOS result confirmed",
    noLabel: "No — result in spec",
    type: "decision",
  },
  "phase1-start": {
    id: "phase1-start",
    phase: "Phase 1 — Laboratory Investigation",
    question: "Phase 1: Conduct immediate laboratory investigation. Is there an obvious assignable cause (e.g., sample preparation error, instrument malfunction, calculation error)?",
    guidance: "Review: analyst records, raw data, instrument logs, reagent status, standard prep, dilution factors, integration parameters. Check for transcription errors. Interview analyst. Review environmental logs (temp, humidity).",
    example: "Analyst reviews lab notebook and discovers the reference standard solution was prepared 22 days ago — SOP specifies a maximum use period of 14 days. This is a documented, potential assignable cause.",
    ref: "FDA 2006 OOS Guidance Section IVA",
    yes: "phase1-invalidate",
    no: "phase1-no-cause",
    yesLabel: "Yes — assignable lab cause found",
    noLabel: "No — no obvious cause found",
    type: "decision",
  },
  "phase1-invalidate": {
    id: "phase1-invalidate",
    phase: "Phase 1 — Invalidation",
    question: "Is the assignable cause sufficient to invalidate the result (documented, confirmed, not merely suspected)?",
    guidance: "Causes that can invalidate: confirmed instrument failure with log evidence, documented analyst error (wrong dilution factor noted in records), confirmed reagent/standard failure with documented evidence. Suspicion alone is NOT sufficient. Document everything in a deviation report.",
    example: "A balances calibration log shows it was last calibrated 14 months ago against a 12-month interval. This documented instrument failure, with supporting calibration logs, is sufficient to invalidate the OOS result.",
    ref: "FDA 2006 OOS Guidance Section IVA; Barr Laboratories case precedent",
    yes: "phase1-retest",
    no: "phase2a-start",
    yesLabel: "Yes — result invalidated with documentation",
    noLabel: "No — cannot fully document/confirm cause",
    type: "decision",
  },
  "phase1-retest": {
    id: "phase1-retest",
    phase: "Phase 1 — Retest",
    question: "After correcting the confirmed error, does the retest result pass specification?",
    guidance: "Perform retest on same retained sample. Use same method. Document all steps. Only one retest allowed in Phase 1. If passes, document resolution and close the deviation.",
    example: "After correcting the miscalibrated balance and reweighing the sample, the analyst retests the same retained sample. The retest returns 100.8% — within the 97–103% specification.",
    ref: "FDA 2006 OOS Guidance Section IVA",
    yes: "phase1-pass",
    no: "phase2a-start",
    yesLabel: "Yes — retest passes",
    noLabel: "No — retest still OOS",
    type: "decision",
  },
  "phase1-pass": {
    id: "phase1-pass",
    phase: "Resolution",
    question: "RESOLVED — Phase 1 Investigation Complete",
    guidance: "Original result invalidated due to confirmed laboratory error. Retest passes specification. Document complete investigation in deviation report. No Phase 2 investigation required. Close deviation with appropriate CAPA if systemic issue identified.",
    example: "Investigation closed: confirmed balance calibration failure caused the OOS. CAPA: recalibrate all balances monthly; add calibration check to analyst pre-analysis checklist. Batch released.",
    ref: "FDA 2006 OOS Guidance",
    yes: null,
    no: null,
    type: "result",
    outcome: "pass",
  },
  "phase1-no-cause": {
    id: "phase1-no-cause",
    phase: "Phase 1 → Phase 2 Escalation",
    question: "No assignable cause found in Phase 1. Notify QA and management. Proceed to Phase 2A expanded laboratory investigation?",
    guidance: "All Phase 1 findings must be documented before proceeding. Phase 2 must be pre-approved by QA and management. The batch remains on hold. No further testing without written QA authorization.",
    example: "After thorough Phase 1 review (analyst records, instruments, standards, sample prep) no assignable cause is identified. QA Director notified. Phase 2A authorization form completed and signed before proceeding.",
    ref: "FDA 2006 OOS Guidance Section IVB",
    yes: "phase2a-start",
    no: null,
    yesLabel: "Yes — escalate to Phase 2A (QA authorized)",
    type: "decision",
  },
  "phase2a-start": {
    id: "phase2a-start",
    phase: "Phase 2A — Expanded Lab Investigation",
    question: "Phase 2A: Re-examine retained original sample. Retest additional portions of same sample. Can expanded laboratory testing confirm or explain the OOS result?",
    guidance: "Test multiple portions (aliquots) of the original retained sample. Use different analyst, different instrument if possible. Check method ruggedness. Perform IPC review. Analyze reference standard validity. Statistical evaluation of expanded results.",
    example: "A second analyst retests three aliquots from the same retained vial on a different HPLC system. Two of three results pass (99.4%, 101.2%) but one fails (95.1%). The mixed results are inconclusive — investigation continues.",
    ref: "FDA 2006 OOS Guidance Section IVB1",
    yes: "phase2a-confirm",
    no: "phase2a-inconclusive",
    yesLabel: "Yes — additional testing clarifies result",
    noLabel: "No — results still inconclusive",
    type: "decision",
  },
  "phase2a-confirm": {
    id: "phase2a-confirm",
    phase: "Phase 2A — Expanded Results",
    question: "Does expanded Phase 2A testing confirm the original result was an isolated lab error (all expanded tests pass)?",
    guidance: "If all retests pass and statistical analysis supports it, document as isolated analyst or instrument error. However, if any retests also fail, this confirms a potentially real OOS — must proceed to Phase 2B manufacturing investigation.",
    example: "All five aliquots from Phase 2A return results between 99.1–102.3%. Statistical analysis (t-test) supports the original result was an outlier. Laboratory error confirmed — no Phase 2B required.",
    ref: "FDA 2006 OOS Guidance Section IVB",
    yes: "phase2a-resolved",
    no: "phase2b-start",
    yesLabel: "Yes — all expanded tests pass; lab error confirmed",
    noLabel: "No — some retests OOS; real OOS suspected",
    type: "decision",
  },
  "phase2a-resolved": {
    id: "phase2a-resolved",
    phase: "Resolution",
    question: "RESOLVED — Phase 2A Investigation: Laboratory Error Confirmed",
    guidance: "Document full investigation. Apply appropriate CAPA. Close deviation. Batch may be released if no manufacturing issues found. Regulatory reporting may be required if product is on market (Field Alert Report per 21 CFR 314.81).",
    example: "Investigation documents isolated analyst pipetting error confirmed by Phase 2A expanded testing. All five additional aliquots pass. CAPA: enhanced analyst training and independent second-analyst verification for this method. Batch released.",
    ref: "FDA 2006 OOS Guidance; 21 CFR 314.81",
    type: "result",
    outcome: "pass",
  },
  "phase2a-inconclusive": {
    id: "phase2a-inconclusive",
    phase: "Phase 2A → Phase 2B Escalation",
    question: "Phase 2A inconclusive. Proceed to Phase 2B — full manufacturing investigation?",
    guidance: "Notify QA Director and potentially regulatory affairs. Ensure all documentation is current. Batch remains on hold. Phase 2B authorization required. Batch disposition cannot be determined until Phase 2B is complete.",
    example: "Phase 2A testing shows mixed results — some aliquots pass, some fail. No pattern explained by laboratory factors. QA Director and VP of Manufacturing notified. Phase 2B manufacturing investigation authorized.",
    ref: "FDA 2006 OOS Guidance Section IVB2",
    yes: "phase2b-start",
    no: null,
    yesLabel: "Yes — proceed to Phase 2B (QA authorized)",
    type: "decision",
  },
  "phase2b-start": {
    id: "phase2b-start",
    phase: "Phase 2B — Manufacturing Investigation",
    question: "Phase 2B: Full manufacturing investigation. Review batch records, in-process results, equipment logs, raw materials, environmental monitoring. Is a manufacturing assignable cause identified?",
    guidance: "Review: batch production records (BPR), equipment maintenance/calibration logs, raw material CoAs and test results, in-process control (IPC) results, process parameters and deviations, environmental monitoring data, change control history, operator training records.",
    example: "Review of BPR for a lyophilized mAb batch reveals the bioreactor pH dropped to 6.3 for 3.5 hours during production (specification: 7.0–7.4). The pH deviation occurred but was not formally escalated at the time.",
    ref: "FDA 2006 OOS Guidance Section IVB2; 21 CFR 211.192",
    yes: "phase2b-cause-found",
    no: "phase2b-no-cause",
    yesLabel: "Yes — manufacturing cause identified",
    noLabel: "No — no manufacturing cause found",
    type: "decision",
  },
  "phase2b-cause-found": {
    id: "phase2b-cause-found",
    phase: "Phase 2B — Cause Found",
    question: "Is the manufacturing assignable cause sufficient to make a formal rejection decision (documented, confirmed)?",
    guidance: "If confirmed manufacturing cause: batch likely fails. Document cause, conduct impact assessment, develop CAPA plan. Notify regulatory affairs if marketed product. Consider implications for other batches produced under the same conditions.",
    example: "The bioreactor pH excursion to 6.3 for 3.5 hours is confirmed by electronic batch record logs and is well-documented with operator alarm acknowledgment records. A confirmed manufacturing cause exists for the low potency OOS result.",
    ref: "FDA 2006 OOS Guidance; ICH Q10",
    yes: "phase2b-reject",
    no: "phase2b-further",
    yesLabel: "Yes — cause confirmed; reject batch",
    noLabel: "No — cause suspected but not confirmed",
    type: "decision",
  },
  "phase2b-reject": {
    id: "phase2b-reject",
    phase: "Final Decision — REJECT",
    question: "BATCH REJECTION — OOS Investigation Complete",
    guidance: "Batch must be rejected/disposed per SOP. Mandatory CAPA required. Regulatory notification may be required (drug shortage, product recall assessment). Complete all documentation within required timeline (typically 30 business days). Field alert / adverse event reporting if applicable.",
    example: "Batch 2401-MAB rejected due to confirmed pH process deviation causing low potency. CAPA: install automated pH correction system, revise alarm management SOP, retrain operators. Regulatory notification assessment initiated.",
    ref: "21 CFR 211.192; FDA 2006 OOS Guidance; ICH Q10 Section 3.2",
    type: "result",
    outcome: "fail",
  },
  "phase2b-no-cause": {
    id: "phase2b-no-cause",
    phase: "Phase 2B — Unresolved",
    question: "No manufacturing cause confirmed. OOS result is unexplained. What is the final disposition decision?",
    guidance: "An unexplained OOS result that cannot be traced to a confirmed laboratory error must be treated as a real OOS. The batch CANNOT be released based on passing retest results alone (Barr Laboratories precedent). Batch must be rejected.",
    example: "Despite thorough Phase 2B review of all manufacturing records, no root cause can be identified. Per United States v. Barr Laboratories (1993) and FDA 2006 guidance, this unexplained OOS must be treated as real. Batch is rejected.",
    ref: "FDA 2006 OOS Guidance; United States v. Barr Laboratories (1993); 21 CFR 211.192",
    yes: "phase2b-reject",
    no: null,
    yesLabel: "Reject batch (required — Barr Laboratories precedent)",
    type: "decision",
  },
  "phase2b-further": {
    id: "phase2b-further",
    phase: "Phase 2B — Further Review",
    question: "Suspected but unconfirmed manufacturing cause. Is there sufficient evidence for a scientifically justified disposition decision via additional analysis?",
    guidance: "Perform additional analysis: accelerated stability (bracketed approach), additional in-process samples, extended statistical evaluation. All testing must be pre-planned and QA-approved. Cannot 'test into compliance.' If evidence still insufficient, batch must be rejected.",
    example: "Blend uniformity is suspected but cannot be confirmed from batch records alone. Additional testing of retained blend samples is conducted under QA oversight. Results confirm non-uniform blend — manufacturing cause now confirmed. Batch rejected.",
    ref: "FDA 2006 OOS Guidance; ICH Q10",
    yes: "phase2b-reject",
    no: "phase2b-reject",
    yesLabel: "Analysis complete → confirmed cause → reject",
    noLabel: "Still unresolved → must reject",
    type: "decision",
  },
};

export const ROOT_CAUSES = [
  {
    category: "Analyst Error",
    icon: "👤",
    color: "#F59E0B",
    examples: [
      "Incorrect sample preparation (wrong dilution, missed dilution step)",
      "Wrong standard concentration used for calculations",
      "Incorrect integration parameters applied post-run",
      "Calculation or transcription error in data processing",
      "Sample contamination during preparation (improper handling technique)",
      "Wrong solvent used for dissolution or dilution",
      "Failure to equilibrate column before sample injection",
      "Sample weight recorded incorrectly (balance or note error)",
    ]
  },
  {
    category: "Instrument / Equipment",
    icon: "⚙️",
    color: "#38BDF8",
    examples: [
      "HPLC pump failure (pressure spike, gradient error, degasser failure)",
      "Detector drift or lamp failure (UV lamp aging causing baseline drift)",
      "Autosampler malfunction (needle plugging, incorrect injection volume)",
      "Balance out of calibration or beyond calibration interval",
      "pH meter electrode failure or improper calibration procedure",
      "Temperature control failure in incubator, water bath, or stability chamber",
      "Pipette out of calibration or tip defect causing volume error",
      "Column degradation or void volume causing peak distortion",
    ]
  },
  {
    category: "Reagent / Standard",
    icon: "🧪",
    color: "#34D399",
    examples: [
      "Reference standard expired, degraded, or beyond use-period per SOP",
      "Reagent contamination or prepared at wrong concentration",
      "Degraded mobile phase (microbial growth, evaporation-related concentration change)",
      "Buffer prepared at wrong pH or wrong ionic strength",
      "Water system failure (TOC out of spec, conductivity, microbial contamination)",
      "Wrong reagent lot with different purity grade used without verification",
      "Reagent stored improperly (temperature excursion during storage)",
    ]
  },
  {
    category: "Environmental",
    icon: "🌡️",
    color: "#A78BFA",
    examples: [
      "Temperature excursion in stability chamber during storage period",
      "Humidity excursion affecting hygroscopic sample or mobile phase",
      "Vibration or mechanical interference during precision weighing",
      "Power fluctuation or UPS failure affecting sensitive instrument",
      "Static charge affecting powder weighing of fine particles",
      "Cross-contamination from adjacent lab activity (aerosols, vapors)",
    ]
  },
  {
    category: "Manufacturing",
    icon: "🏭",
    color: "#F472B6",
    examples: [
      "Raw material out of specification (impurity, potency, or physical property)",
      "Critical process parameter deviation (temperature, time, pH, agitation speed)",
      "Equipment cleaning failure or carryover contamination from previous batch",
      "Wrong order of addition of components during formulation",
      "Blend or mixing uniformity failure (under- or over-mixing)",
      "Fill weight or fill volume error during aseptic filling",
      "Lyophilization cycle deviation (collapse, incomplete sublimation)",
      "Membrane filter failure during sterile filtration",
      "Bioreactor pH, dissolved oxygen, or temperature excursion",
    ]
  },
  {
    category: "Sampling",
    icon: "🧫",
    color: "#FB923C",
    examples: [
      "Sample taken from non-representative location in vessel or blend",
      "Sample container contamination (residual cleaning agent, previous product)",
      "Sample degradation during transport, storage, or excessive hold time",
      "Wrong sample taken due to labeling mix-up or confusion",
      "Inadequate sample volume leading to poor precision or detection issues",
      "Sampling technique error (not agitating bulk before sampling)",
    ]
  },
];

export const OOT_CRITERIA = [
  {
    rule: "Westgard 1₂s Warning",
    description: "One result exceeds mean ± 2SD",
    action: "Warning only — increase monitoring frequency; no OOS investigation required",
    type: "warning",
    color: "#F59E0B",
  },
  {
    rule: "Westgard 1₃s Reject",
    description: "One result exceeds mean ± 3SD",
    action: "Reject run; investigate possible systemic cause; consider OOS investigation",
    type: "reject",
    color: "#F472B6",
  },
  {
    rule: "Westgard 2₂s",
    description: "Two consecutive results both exceed same ± 2SD limit",
    action: "Systematic error signal — investigate cause; review process and method",
    type: "trend",
    color: "#FB923C",
  },
  {
    rule: "Westgard R₄s",
    description: "Range between two results exceeds 4SD",
    action: "Random error signal — check analyst technique, reagents, instrument precision",
    type: "alert",
    color: "#F59E0B",
  },
  {
    rule: "Westgard 10₇",
    description: "Ten consecutive results all above or below the mean",
    action: "Strong trend — systematic bias; investigate process drift, standard aging, column aging",
    type: "trend",
    color: "#38BDF8",
  },
  {
    rule: "CUSUM",
    description: "Cumulative sum exceeds decision interval h (typically h = 5σ)",
    action: "Process mean has shifted — investigate root cause; consider process re-validation",
    type: "trend",
    color: "#A78BFA",
  },
  {
    rule: "Linear Trend (6 points)",
    description: "Six consecutive results trending monotonically up or down",
    action: "Trend investigation required — column degradation, reagent aging, process drift",
    type: "trend",
    color: "#60A5FA",
  },
];

// ── Case Study Scenarios for Investigation Simulator ───────────
export const OOS_SCENARIOS = [
  {
    id: "s1",
    icon: "💊",
    difficulty: "Beginner",
    diffColor: "#34D399",
    title: "Low HPLC Potency",
    product: "Ibuprofen 200 mg Tablet — Lot Release",
    method: "HPLC Potency Assay (USP)",
    finding: { result: "94.8%", spec: "97.0–103.0%", status: "OOS" },
    trueCause: "lab-error",
    truePhase: "Phase 1 Resolved",
    phases: [
      {
        id: "phase1",
        title: "Phase 1 — Laboratory Investigation",
        color: "#34D399",
        intro: "HPLC potency result is 94.8% against a specification of 97.0–103.0%. Conduct Phase 1 lab investigation. Reveal each item to see what the records show.",
        items: [
          {
            id: "s1-a", area: "Analyst Records", icon: "📋",
            finding: "Dilution factor verified correct (50 µg/mL target from 1 mg/mL stock, 20× dilution). Sample weight of 204.1 mg is within ±0.5 mg tolerance. No calculation or transcription errors in lab notebook.",
            isIssue: false, isCause: false,
          },
          {
            id: "s1-b", area: "Reference Standard", icon: "🧪",
            finding: "Reference standard solution was prepared 22 days ago. SOP QC-105 specifies a maximum use period of 14 days at 2–8°C. This SOP limit has been exceeded by 8 days — a documented laboratory error.",
            isIssue: true, isCause: true,
          },
          {
            id: "s1-c", area: "HPLC System", icon: "⚙️",
            finding: "Instrument calibrated 48 days ago (interval: 6 months — within spec). System suitability: RSD of 5 replicates = 0.41% (spec ≤2%). Tailing factor 1.12 (spec 0.8–1.8). Column within expected plate count. All pass.",
            isIssue: false, isCause: false,
          },
          {
            id: "s1-d", area: "Sample Preparation", icon: "🔬",
            finding: "Sample dissolved in methanol per SOP, then diluted with mobile phase. Blank chromatogram shows no interfering peaks. Correct column lot used. Procedure matches SOP QC-105 in all respects.",
            isIssue: false, isCause: false,
          },
        ],
        question: "What is your Phase 1 determination?",
        options: [
          {
            id: "o1a", label: "Assignable cause confirmed — invalidate result and retest",
            correct: true,
            feedback: "Correct! The reference standard solution was 22 days old against a 14-day SOP maximum. This is a documented, confirmable laboratory error per FDA 2006 OOS Guidance Section IVA. A documented SOP violation with supporting date records is sufficient for Phase 1 invalidation. Proceed to retest using a freshly prepared standard.",
          },
          {
            id: "o1b", label: "No confirmed cause — escalate to Phase 2A",
            correct: false,
            feedback: "Incorrect. The reference standard solution exceeded its 14-day SOP use period by 8 days. This is a documented assignable cause with clear supporting evidence (preparation date in lab notebook vs. SOP requirement). Escalation to Phase 2A is not required when a confirmed lab error has been identified.",
          },
        ],
      },
      {
        id: "retest",
        title: "Phase 1 — Retest with Fresh Standard",
        color: "#34D399",
        intro: "Prepare a fresh reference standard solution from the same certified lot. Retest the original retained sample.",
        items: [
          {
            id: "s1-e", area: "Fresh Standard Prep", icon: "🧪",
            finding: "New reference standard solution prepared from RS Lot #2024-041 (expires 2026-06). UV verification at 272 nm confirms expected absorptivity. Preparation logged and witnessed by QA. Use period labeled: expires 14 days from today.",
            isIssue: false, isCause: false,
          },
          {
            id: "s1-f", area: "Retest Results", icon: "📊",
            finding: "Retest on retained sample: 100.6% (spec 97.0–103.0%). Three replicate injections: 100.2%, 100.6%, 101.0%. RSD = 0.39%. System suitability fully compliant. Result PASSES specification.",
            isIssue: false, isCause: false,
          },
        ],
        question: "Final batch disposition?",
        options: [
          {
            id: "o2a", label: "Close investigation — lab error confirmed. Batch cleared for release.",
            correct: true,
            feedback: "Correct! Confirmed laboratory error (expired reference standard solution) + passing retest on retained sample = valid Phase 1 invalidation. Document full investigation in deviation report. Implement CAPA (add reference standard expiry check to pre-analysis checklist in SOP QC-105). Batch may proceed to release.",
          },
          {
            id: "o2b", label: "Reject batch — original OOS result stands",
            correct: false,
            feedback: "Incorrect. When a confirmed, documented laboratory error is identified and the retest of the retained sample passes specification, the original result is validly invalidated per FDA 2006 OOS Guidance. The batch may be released. Rejection is not warranted when Phase 1 invalidation criteria are met.",
          },
        ],
      },
    ],
    finalVerdictLabel: "Laboratory Error — Phase 1 Resolved",
    finalVerdictColor: "#34D399",
    finalVerdictIcon: "✅",
    keyLearning: "Reference standard solution age must be verified before every analysis session. A single pre-analysis checklist item (confirm standard preparation date) would have prevented this OOS.",
    capa: "Revise SOP QC-105: analyst must record reference standard preparation date on each run worksheet. QC supervisor to verify expiry before approving run for analysis.",
  },
  {
    id: "s2",
    icon: "🧬",
    difficulty: "Intermediate",
    diffColor: "#F59E0B",
    title: "Bioassay Low Potency — mAb",
    product: "Monoclonal Antibody — Lot 2401-MAB (Pre-release)",
    method: "Cell-Based Potency Bioassay (Luciferase Reporter)",
    finding: { result: "76% RA", spec: "80–120% RA", status: "OOS" },
    trueCause: "manufacturing",
    truePhase: "Phase 2B → Reject",
    phases: [
      {
        id: "phase1",
        title: "Phase 1 — Laboratory Investigation",
        color: "#34D399",
        intro: "Cell-based potency bioassay result is 76% relative activity against a specification of 80–120%. Investigate the laboratory systematically.",
        items: [
          {
            id: "s2-a", area: "Cell Line Status", icon: "🧫",
            finding: "Cell passage number P28 — within validated range P20–P35. Cell viability: 97.4% (spec ≥90%). Mycoplasma test negative (last weekly test). Cell morphology normal under microscopy. Cell line authenticated by STR profiling this quarter.",
            isIssue: false, isCause: false,
          },
          {
            id: "s2-b", area: "Reference Standard", icon: "🧪",
            finding: "Reference standard vial from qualified lot RS-mAb-23, within use period. Reconstituted per SOP. Concentration confirmed by A280: 2.0 mg/mL ± 5%. No visible aggregation. Reference standard response curve meets acceptance criteria.",
            isIssue: false, isCause: false,
          },
          {
            id: "s2-c", area: "Assay Execution", icon: "📋",
            finding: "Analyst performed all steps per SOP BIO-027 with no deviations noted. Plate reader calibrated last month. CO₂ and temperature incubator logs show 37.0°C ± 0.5°C and 5.0% CO₂ ± 0.2% throughout the 6-hour incubation. No equipment alarms triggered during the run.",
            isIssue: false, isCause: false,
          },
          {
            id: "s2-d", area: "Parallelism & Curve Fit", icon: "📊",
            finding: "Sample and reference standard dose–response curves are parallel (F-test p = 0.42; spec: p > 0.05). 4-PL fit R² = 0.998. EC50 is genuinely shifted — the sample curve is displaced relative to reference, confirming the potency difference is a real biological signal, not a curve-fitting artifact.",
            isIssue: true, isCause: false,
          },
        ],
        question: "What is your Phase 1 determination?",
        options: [
          {
            id: "o1a", label: "No laboratory cause found — escalate to Phase 2A",
            correct: true,
            feedback: "Correct. All laboratory factors are confirmed satisfactory — cells, reference standard, assay execution, and incubator conditions are all within requirements. The parallelism test confirms the assay is technically valid and the reduced potency is a genuine result. Phase 1 cannot identify a lab error. Escalate to Phase 2A per FDA guidance.",
          },
          {
            id: "o1b", label: "Invalidate — assay is inherently variable (bioassay imprecision)",
            correct: false,
            feedback: "Incorrect. Bioassay imprecision is not a documented assignable cause for invalidation. The assay met all system suitability and parallelism criteria. General method variability cannot be used to dismiss an OOS result — that would be 'testing into compliance,' which FDA explicitly prohibits.",
          },
        ],
      },
      {
        id: "phase2a",
        title: "Phase 2A — Expanded Lab Investigation",
        color: "#F59E0B",
        intro: "QA authorized Phase 2A. Retest additional aliquots from the same retained sample, using a second analyst and a second instrument where possible.",
        items: [
          {
            id: "s2-e", area: "Second Analyst — Independent Run", icon: "👤",
            finding: "Second analyst performs independent bioassay on a separate retained sample aliquot (different cell passage, same lot). Result: 78% RA. Still OOS (spec 80–120%). Parallelism confirmed (p = 0.38).",
            isIssue: true, isCause: false,
          },
          {
            id: "s2-f", area: "Third Aliquot — Original Analyst", icon: "🔬",
            finding: "Original analyst reruns a third aliquot using a fresh vial of reference standard from the same lot. Result: 75% RA. Consistently OOS. Three results now: 76%, 78%, 75% — %CV = 2.1% showing high precision within a consistently low range.",
            isIssue: true, isCause: false,
          },
          {
            id: "s2-g", area: "Method Ruggedness", icon: "⚙️",
            finding: "Review of assay method validation data: inter-analyst %CV = 8.2%, inter-day %CV = 9.4%. Three Phase 2A results (76%, 78%, 75%) have %CV = 2.1% — far more consistent than method variability would predict. This rules out random assay variability as the cause.",
            isIssue: false, isCause: false,
          },
        ],
        question: "What is your Phase 2A conclusion?",
        options: [
          {
            id: "o2a", label: "All retests OOS — real OOS confirmed. Escalate to Phase 2B manufacturing investigation.",
            correct: true,
            feedback: "Correct. All three results (76%, 78%, 75%) are consistently OOS and far more consistent than method variability would explain. The laboratory has confirmed no role in the low result. This is a real OOS. Proceed immediately to Phase 2B manufacturing investigation. Batch remains on hold.",
          },
          {
            id: "o2b", label: "Results are within bioassay variability — close as lab error",
            correct: false,
            feedback: "Incorrect. The three results (75–78%) are all OOS and have %CV = 2.1% — much tighter than the validated method variability of ~9%. The low results are reproducible across analysts and vials. This is not bioassay variability — it is a genuine product potency deficit requiring Phase 2B investigation.",
          },
        ],
      },
      {
        id: "phase2b",
        title: "Phase 2B — Manufacturing Investigation",
        color: "#F472B6",
        intro: "QA Director and VP Manufacturing authorized Phase 2B. Full review of batch production records, equipment logs, in-process data, and raw materials.",
        items: [
          {
            id: "s2-h", area: "Bioreactor pH Logs", icon: "📈",
            finding: "CRITICAL: Electronic batch record pH log shows a drop from 7.15 to 6.5 over 4.5 hours on Day 7 of the 14-day production run. The pH specification is 7.0–7.4. The CO₂ flow controller alarm triggered but was acknowledged by the operator without corrective action being taken. pH recovered overnight.",
            isIssue: true, isCause: true,
          },
          {
            id: "s2-i", area: "In-Process Cell Viability (Day 8)", icon: "🧫",
            finding: "Day 8 IPC viability (the day after the pH excursion): 89.2%. Alert limit is 85%; action limit is 80%. Value is within both limits but is 6 points below historical average (~95.4% for this process). Some cellular stress consistent with the prior pH excursion.",
            isIssue: true, isCause: false,
          },
          {
            id: "s2-j", area: "Raw Material Review", icon: "📋",
            finding: "All raw material lots used in this batch were reviewed. All meet specification. Cell culture media lot matches three previous successful batches from the same qualified vendor. No formula or vendor changes.",
            isIssue: false, isCause: false,
          },
          {
            id: "s2-k", area: "Equipment Maintenance", icon: "⚙️",
            finding: "Bioreactor preventive maintenance performed 3 months ago per schedule. All sensor calibrations are current. CO₂ mass flow controller was calibrated 6 weeks ago. No scheduled maintenance overdue.",
            isIssue: false, isCause: false,
          },
        ],
        question: "Phase 2B conclusion and batch disposition?",
        options: [
          {
            id: "o3a", label: "Manufacturing cause confirmed (pH excursion) — reject batch",
            correct: true,
            feedback: "Correct! The 4.5-hour pH excursion to 6.5 (0.5 units below the 7.0 lower spec) on Day 7 is a confirmed, documented manufacturing assignable cause. Bioreactor pH directly affects mAb folding, glycosylation, and potency. The excursion was not corrected despite alarm notification. This confirmed cause requires batch rejection. Mandatory CAPA required. Assess impact on concurrent batches from the same campaign.",
          },
          {
            id: "o3b", label: "pH excursion is minor — batch may proceed with documentation",
            correct: false,
            feedback: "Incorrect. A 4.5-hour pH excursion to 6.5 — 0.5 units outside the 7.0 lower limit — is a significant process deviation for a mAb. Bioreactor pH is a critical process parameter (CPP) because it directly impacts protein folding, N-linked glycosylation, and biological activity. The confirmed low potency results are scientifically consistent with this deviation. Batch must be rejected.",
          },
        ],
      },
    ],
    finalVerdictLabel: "True OOS — Batch Rejected (Phase 2B, Manufacturing)",
    finalVerdictColor: "#F472B6",
    finalVerdictIcon: "❌",
    keyLearning: "Bioreactor pH deviations must trigger immediate corrective action — not just alarm acknowledgment. Operators must understand the scientific consequence of pH excursions on protein quality. CPP deviations require immediate supervisor notification.",
    capa: "Revise alarm management SOP: pH deviations >0.1 unit require immediate supervisor notification and corrective action within 30 minutes. Implement automated CO₂ correction algorithm. Enhanced operator training on CPP criticality and protein science.",
  },
  {
    id: "s3",
    icon: "💧",
    difficulty: "Beginner",
    diffColor: "#34D399",
    title: "IV Solution pH Out of Spec",
    product: "Sodium Bicarbonate 8.4% Injection — QC Release",
    method: "pH Determination (USP <791>)",
    finding: { result: "6.7", spec: "7.0–8.5", status: "OOS" },
    trueCause: "instrument",
    truePhase: "Phase 1 Resolved",
    phases: [
      {
        id: "phase1",
        title: "Phase 1 — Laboratory Investigation",
        color: "#34D399",
        intro: "pH of a sodium bicarbonate 8.4% IV injection is 6.7 — below the specification of 7.0–8.5. This is a critical test for an injectable product. Investigate all relevant factors.",
        items: [
          {
            id: "s3-a", area: "pH Meter Calibration", icon: "⚙️",
            finding: "pH meter calibration record reviewed: last calibrated with fresh pH 4.0 and 7.0 buffers on the previous testing day. SOP-INST-08 requires a 2-point calibration before each use or at the start of each working day. No calibration was performed today before this measurement was taken.",
            isIssue: true, isCause: true,
          },
          {
            id: "s3-b", area: "Electrode Condition", icon: "🔬",
            finding: "pH electrode inspected: no visible cracks, deposits, or fouling. However, electrode was stored dry overnight in air. SOP-INST-08 requires storage in 3M KCl storage solution between uses. Dry storage can cause reference junction clogging and a sluggish, inaccurate response.",
            isIssue: true, isCause: true,
          },
          {
            id: "s3-c", area: "Buffer Solutions", icon: "🧪",
            finding: "pH 4.0 and 7.0 certified buffer solutions are within their expiry dates, stored at room temperature per label. A reference meter reads pH 7.01 for the pH 7.0 buffer (pass). Buffers are not the issue.",
            isIssue: false, isCause: false,
          },
          {
            id: "s3-d", area: "Sample Handling", icon: "📋",
            finding: "Sample correctly collected, no dilution performed (direct pH measurement per USP <791>). Temperature at measurement: 23°C (method specifies 20–25°C). Sample not exposed to air or CO₂ beyond normal handling time. No visible cloudiness or precipitate.",
            isIssue: false, isCause: false,
          },
        ],
        question: "What is your Phase 1 determination?",
        options: [
          {
            id: "o1a", label: "Two instrument errors confirmed — invalidate and retest with recalibrated meter",
            correct: true,
            feedback: "Correct! Two documented instrument-related laboratory errors were identified: (1) mandatory pre-use calibration was not performed, in violation of SOP-INST-08; (2) electrode stored dry overnight instead of in 3M KCl, affecting junction potential. Both are confirmed, documented instrument errors sufficient for Phase 1 invalidation. Recalibrate properly after electrode reconditioning and retest.",
          },
          {
            id: "o1b", label: "For injectables, any pH OOS requires Phase 2B — patient safety risk too high",
            correct: false,
            feedback: "Incorrect. The severity of the test (injectable product) does not override the investigation process. FDA 2006 OOS guidance applies equally to all dosage forms. When a confirmed, documented instrument error is identified, Phase 1 invalidation is appropriate — even for parenteral products. Phase 2B is only required when no lab cause can be confirmed.",
          },
          {
            id: "o1c", label: "No clear single cause — escalate to Phase 2A",
            correct: false,
            feedback: "Incorrect. Two separate, confirmed instrument errors were found: missing pre-use calibration and improper electrode storage. Each alone would be sufficient cause for Phase 1 invalidation. Two confirmed causes only strengthens the Phase 1 invalidation. Escalation to Phase 2A is not warranted.",
          },
        ],
      },
      {
        id: "retest",
        title: "Phase 1 — Retest with Recalibrated Instrument",
        color: "#34D399",
        intro: "Recondition the electrode, recalibrate the pH meter with fresh buffers, then retest the retained sample.",
        items: [
          {
            id: "s3-e", area: "Electrode Reconditioning & Calibration", icon: "⚙️",
            finding: "Electrode soaked in 3M KCl for 30 minutes per SOP. Two-point calibration with fresh pH 4.0 and 7.0 buffers: slope 59.2 mV/decade (expected range 57–61 mV/decade — pass). Calibration logged and witnessed by QC supervisor before any sample measurement.",
            isIssue: false, isCause: false,
          },
          {
            id: "s3-f", area: "Retest pH Result", icon: "📊",
            finding: "Retest on retained sample: pH 7.42 (spec 7.0–8.5). Duplicate measurement: pH 7.44. Both PASS specification. Results are consistent with the expected pH range for sodium bicarbonate 8.4% solution. No product quality issue exists.",
            isIssue: false, isCause: false,
          },
        ],
        question: "Final batch disposition?",
        options: [
          {
            id: "o2a", label: "Confirmed instrument errors — close investigation. Batch cleared for release.",
            correct: true,
            feedback: "Correct! Two confirmed, documented instrument errors + passing retest on retained sample = valid Phase 1 invalidation. Document the full investigation in the deviation report. CAPA: add pH meter calibration verification to daily instrument log; add electrode storage check to analyst pre-analysis checklist. Retrain analysts on SOP-INST-08. Batch may be released.",
          },
          {
            id: "o2b", label: "Reject batch — cannot guarantee pH was truly in specification during manufacture",
            correct: false,
            feedback: "Incorrect. The OOS result was caused by confirmed, documented analytical instrument errors — not a product quality problem. The retained sample, tested correctly with a properly calibrated and conditioned electrode, passes specification. This is precisely the scenario Phase 1 invalidation is designed for. Batch may proceed.",
          },
        ],
      },
    ],
    finalVerdictLabel: "Instrument Error — Phase 1 Resolved",
    finalVerdictColor: "#34D399",
    finalVerdictIcon: "✅",
    keyLearning: "pH measurement errors from missed calibration or improper electrode storage are among the most preventable laboratory errors. A single pre-analysis instrument check prevents OOS investigations and batch holds.",
    capa: "Revise SOP-INST-08 to include: (1) daily electrode storage check on instrument log; (2) calibration timestamp check before each sample run. Install reminder placard on pH meter. Supervisor sign-off required on calibration log for each working day.",
  },
  {
    id: "s4",
    icon: "📈",
    difficulty: "Intermediate",
    diffColor: "#F59E0B",
    title: "Moisture Upward Trend — OOT",
    product: "Lyophilized Anti-IL-6 mAb — 18-Month Stability",
    method: "Karl Fischer Water Determination (USP <921>)",
    finding: { result: "0.38% w/w", spec: "≤0.50% w/w", status: "OOT — Result In Spec" },
    trueCause: "oot",
    truePhase: "OOT — Enhanced Monitoring",
    isOOT: true,
    phases: [
      {
        id: "oot-assess",
        title: "OOT Statistical Assessment",
        color: "#38BDF8",
        intro: "The current result (0.38%) passes the specification limit (≤0.50%) — this is NOT an OOS. However, historical trending data raises a statistical concern. Investigate the data pattern and potential causes.",
        items: [
          {
            id: "s4-a", area: "Historical Trending Data", icon: "📈",
            finding: "Stability moisture results (18-month study): T=0M: 0.18%, T=3M: 0.21%, T=6M: 0.26%, T=9M: 0.29%, T=12M: 0.33%, T=18M: 0.38%. Six consecutive upward points. Linear regression slope: +0.011% per month. Westgard Linear Trend Rule (6 consecutive monotonic points) is TRIGGERED. Projected to exceed 0.50% spec at approximately T=30–32 months.",
            isIssue: true, isCause: false,
          },
          {
            id: "s4-b", area: "Karl Fischer Method", icon: "⚙️",
            finding: "KF reagent standardization factor: 5.10 mg/mL — within acceptable use range (4.90–5.30). Titration endpoint was clear with no premature endpoint. Titration cell cleaned and dried per SOP before use. Instrument calibration is current (last verified 3 weeks ago). Method not the issue.",
            isIssue: false, isCause: false,
          },
          {
            id: "s4-c", area: "Stability Chamber Conditions", icon: "🌡️",
            finding: "Chamber temperature and humidity logs for the full 18-month period: 25.0°C ± 0.5°C, 60%RH ± 2.5%RH throughout. All readings within ICH Q1A(R2) long-term stability conditions. No temperature or humidity excursions recorded. Chamber conditions are not the cause of the trend.",
            isIssue: false, isCause: false,
          },
          {
            id: "s4-d", area: "Stability Setup Configuration", icon: "📦",
            finding: "Stability placement records reviewed: vials placed in open trays in the chamber. Product specification QS-002 and stability protocol ST-2024-006 both require desiccant pouches (silica gel) co-stored with vials. The batch record for the stability pull setup shows desiccant pouches were NOT included — an oversight during the T=0 setup.",
            isIssue: true, isCause: true,
          },
        ],
        question: "This result is within specification (0.38% vs. spec ≤0.50%). What action is required?",
        options: [
          {
            id: "o1a", label: "OOT — Initiate enhanced monitoring and investigate the desiccant omission as root cause",
            correct: true,
            feedback: "Correct! This is an OOT situation — in-spec but statistically trending. The Westgard Linear Trend rule is triggered (6 consecutive upward points) per USP <1010> and ICH Q10. The missing desiccant is the likely root cause of accelerated moisture ingress. Required actions: (1) initiate OOT investigation and document findings; (2) increase testing frequency at next timepoints; (3) assess whether desiccant needs to be added retroactively; (4) evaluate projected OOS timepoint vs. product shelf life.",
          },
          {
            id: "o1b", label: "Initiate full OOS investigation and place stability batch on hold",
            correct: false,
            feedback: "Incorrect. The result (0.38%) passes the specification limit (≤0.50%). This is NOT an OOS — no OOS investigation is required, and placing the batch on hold is not appropriate. This is an OOT situation requiring enhanced monitoring and root cause investigation, but not an OOS investigation or batch hold.",
          },
          {
            id: "o1c", label: "Result is within specification — no action needed, continue normal stability monitoring",
            correct: false,
            feedback: "Incorrect. While the individual result passes spec, the Westgard Linear Trend rule has been triggered (6 consecutive monotonically increasing points). ICH Q10 and USP <1010> require OOT investigation when statistical trend rules are violated — even when individual results are within specification. Without action, the product is projected to exceed spec at approximately T=30–32 months, well before the intended shelf life.",
          },
        ],
      },
    ],
    finalVerdictLabel: "OOT — Enhanced Monitoring Required",
    finalVerdictColor: "#38BDF8",
    finalVerdictIcon: "⚠️",
    keyLearning: "OOT detection requires proactive statistical trending programs — individual result compliance is not sufficient. Results within spec can still signal a developing product quality issue that will become an OOS if not addressed.",
    capa: "Implement automated stability trending software to flag Westgard rule violations at each timepoint. Add desiccant placement verification to stability setup checklist with supervisor sign-off. Evaluate additional stability samples stored with desiccant for comparison.",
  },
];
