// src/oos-data.js — FDA 2006 OOS Guidance + ICH Q10 decision framework

export const OOS_TREE = {
  start: {
    id: "start",
    phase: "Initial Assessment",
    question: "Has an Out-of-Specification (OOS) or Out-of-Trend (OOT) result been obtained?",
    guidance: "Document the result immediately. Do not discard samples or data. Initiate formal OOS investigation per 21 CFR 211.192 and FDA 2006 OOS Guidance.",
    ref: "FDA 2006 OOS Guidance; 21 CFR 211.192",
    yes: "phase1-start",
    no: null,
    yesLabel: "Yes — OOS result confirmed",
    noLabel: "No — result in spec",
    type: "decision",
  },
  "phase1-start": {
    id: "phase1-start",
    phase: "Phase 1 — Laboratory Investigation",
    question: "Phase 1: Conduct immediate laboratory investigation. Is there an obvious assignable cause (e.g., sample preparation error, instrument malfunction, calculation error)?",
    guidance: "Review: analyst records, raw data, instrument logs, reagent status, standard prep, dilution factors, integration parameters. Check for transcription errors. Interview analyst. Review environmental logs (temp, humidity).",
    ref: "FDA 2006 OOS Guidance Section IVA",
    yes: "phase1-invalidate",
    no: "phase1-no-cause",
    yesLabel: "Yes — assignable lab cause found",
    noLabel: "No — no obvious cause found",
    type: "decision",
  },
  "phase1-invalidate": {
    id: "phase1-invalidate",
    phase: "Phase 1 — Invalidation",
    question: "Is the assignable cause sufficient to invalidate the result (documented, confirmed, not suspected)?",
    guidance: "Causes that can invalidate: confirmed instrument failure with log evidence, documented analyst error (wrong dilution factor noted in records), confirmed reagent/standard failure with documented evidence. Suspicion alone is NOT sufficient. Document everything in deviation report.",
    ref: "FDA 2006 OOS Guidance Section IVA; Barr Laboratories case precedent",
    yes: "phase1-retest",
    no: "phase2a-start",
    yesLabel: "Yes — result invalidated with documentation",
    noLabel: "No — cannot fully document/confirm cause",
    type: "decision",
  },
  "phase1-retest": {
    id: "phase1-retest",
    phase: "Phase 1 — Retest",
    question: "After correcting the confirmed error, does the retest result pass specification?",
    guidance: "Perform retest on same retained sample. Use same method. Document all steps. Only one retest allowed in Phase 1. If passes, document resolution.",
    ref: "FDA 2006 OOS Guidance Section IVA",
    yes: "phase1-pass",
    no: "phase2a-start",
    yesLabel: "Yes — retest passes",
    noLabel: "No — retest still OOS",
    type: "decision",
  },
  "phase1-pass": {
    id: "phase1-pass",
    phase: "Resolution",
    question: "RESOLVED — Phase 1 Investigation Complete",
    guidance: "Original result invalidated due to confirmed laboratory error. Retest passes specification. Document complete investigation in deviation report. No Phase 2 investigation required. Close deviation with appropriate CAPA if systemic issue identified.",
    ref: "FDA 2006 OOS Guidance",
    yes: null,
    no: null,
    type: "result",
    outcome: "pass",
  },
  "phase1-no-cause": {
    id: "phase1-no-cause",
    phase: "Phase 1 → Phase 2 Escalation",
    question: "No assignable cause found in Phase 1. Expand laboratory investigation with additional testing (Phase 2A). Notify QA and management. Continue to Phase 2A?",
    guidance: "All Phase 1 findings must be documented before proceeding. Phase 2 must be pre-approved by QA/Management. Do not proceed without documented authorization.",
    ref: "FDA 2006 OOS Guidance Section IVB",
    yes: "phase2a-start",
    no: null,
    yesLabel: "Yes — escalate to Phase 2A",
    noLabel: "Stop",
    type: "decision",
  },
  "phase2a-start": {
    id: "phase2a-start",
    phase: "Phase 2A — Expanded Lab Investigation",
    question: "Phase 2A: Re-examine retained original sample. Retest additional portions of same sample. Can expanded laboratory testing confirm or explain the OOS result?",
    guidance: "Test multiple portions (aliquots) of the original retained sample. Use different analyst, different instrument if possible. Check method ruggedness. Perform IPC review. Analyze reference standard validity. Statistical evaluation of expanded results.",
    ref: "FDA 2006 OOS Guidance Section IVB1",
    yes: "phase2a-confirm",
    no: "phase2a-inconclusive",
    yesLabel: "Yes — additional testing clarifies",
    noLabel: "No — results still inconclusive",
    type: "decision",
  },
  "phase2a-confirm": {
    id: "phase2a-confirm",
    phase: "Phase 2A — Expanded Results",
    question: "Does expanded Phase 2A testing confirm the original result was an isolated lab error (all expanded tests pass)?",
    guidance: "If all retests pass and statistical analysis supports it, document as isolated analyst or instrumental error. However, if any retests also fail, this confirms a potentially real OOS — must proceed to Phase 2B manufacturing investigation.",
    ref: "FDA 2006 OOS Guidance Section IVB",
    yes: "phase2a-resolved",
    no: "phase2b-start",
    yesLabel: "Yes — all expanded tests pass; lab error confirmed",
    noLabel: "No — some retests OOS; real OOS suspected",
    type: "decision",
  },
  "phase2a-resolved": {
    id: "phase2a-resolved",
    phase: "Resolution",
    question: "RESOLVED — Phase 2A Investigation: Laboratory Error Confirmed",
    guidance: "Document full investigation. Apply appropriate CAPA. Close deviation. Batch may be released if no manufacturing issues found. Regulatory reporting may be required if product is on market (Field Alert Report / 15-day safety report per 21 CFR 314.81).",
    ref: "FDA 2006 OOS Guidance; 21 CFR 314.81",
    type: "result",
    outcome: "pass",
  },
  "phase2a-inconclusive": {
    id: "phase2a-inconclusive",
    phase: "Phase 2A → Phase 2B Escalation",
    question: "Phase 2A inconclusive. Proceed to Phase 2B — full manufacturing investigation?",
    guidance: "Notify QA Director and potentially regulatory affairs. All documentation current. Batch placed on hold. Phase 2B authorization required.",
    ref: "FDA 2006 OOS Guidance Section IVB2",
    yes: "phase2b-start",
    no: null,
    yesLabel: "Yes — proceed to Phase 2B",
    type: "decision",
  },
  "phase2b-start": {
    id: "phase2b-start",
    phase: "Phase 2B — Manufacturing Investigation",
    question: "Phase 2B: Full manufacturing investigation. Review batch records, in-process results, equipment logs, raw materials, environmental monitoring. Is a manufacturing assignable cause identified?",
    guidance: "Review: batch production records (BPR), equipment maintenance/calibration logs, raw material CoAs and test results, in-process control (IPC) results, process parameters and deviations, environmental monitoring data, change control history, operator training records.",
    ref: "FDA 2006 OOS Guidance Section IVB2; 21 CFR 211.192",
    yes: "phase2b-cause-found",
    no: "phase2b-no-cause",
    yesLabel: "Yes — manufacturing cause identified",
    noLabel: "No — no manufacturing cause found",
    type: "decision",
  },
  "phase2b-cause-found": {
    id: "phase2b-cause-found",
    phase: "Phase 2B — Cause Found",
    question: "Is the manufacturing assignable cause sufficient to make a formal rejection decision (documented, confirmed)?",
    guidance: "If confirmed manufacturing cause: batch likely fails. Document cause, impact assessment, CAPA plan. Notify regulatory affairs if marketed product. Consider implications for other batches made under same conditions.",
    ref: "FDA 2006 OOS Guidance; ICH Q10",
    yes: "phase2b-reject",
    no: "phase2b-further",
    yesLabel: "Yes — cause confirmed; reject batch",
    noLabel: "No — cause suspected but not confirmed",
    type: "decision",
  },
  "phase2b-reject": {
    id: "phase2b-reject",
    phase: "Final Decision — REJECT",
    question: "BATCH REJECTION — OOS Investigation Complete",
    guidance: "Batch must be rejected/disposed per SOP. Mandatory CAPA required. Regulatory notification may be required (drug shortage, product recall assessment). Complete all documentation within required timeline (typically 30 business days). Consider reprocessing only if validated and pre-approved. Field alert / adverse event reporting if applicable.",
    ref: "21 CFR 211.192; FDA 2006 OOS Guidance; ICH Q10 Section 3.2",
    type: "result",
    outcome: "fail",
  },
  "phase2b-no-cause": {
    id: "phase2b-no-cause",
    phase: "Phase 2B — Unresolved",
    question: "No manufacturing cause confirmed. OOS result is unexplained. What is the final disposition decision?",
    guidance: "An unexplained OOS result that cannot be traced to a confirmed laboratory error must be treated as a real OOS. The batch CANNOT be released based on passing retest results alone (Barr Laboratories precedent). Consider: retesting from retained samples under QA oversight, formal batch rejection, regulatory consultation.",
    ref: "FDA 2006 OOS Guidance; United States v. Barr Laboratories (1993); 21 CFR 211.192",
    yes: "phase2b-reject",
    no: null,
    yesLabel: "Reject batch (recommended)",
    type: "decision",
  },
  "phase2b-further": {
    id: "phase2b-further",
    phase: "Phase 2B — Further Review",
    question: "Suspected but unconfirmed manufacturing cause. Is there sufficient evidence for a scientifically justified disposition decision (additional batch testing, statistical analysis)?",
    guidance: "Perform additional analysis: accelerated stability (bracketed approach), additional in-process samples, extended statistical evaluation. All testing must be pre-planned and QA-approved. Cannot 'test into compliance.'",
    ref: "FDA 2006 OOS Guidance; ICH Q10",
    yes: "phase2b-reject",
    no: "phase2b-reject",
    yesLabel: "Complete analysis → reject",
    noLabel: "Unable to resolve → reject",
    type: "decision",
  },
};

export const ROOT_CAUSES = [
  {
    category: "Analyst Error",
    icon: "👤",
    color: "#F59E0B",
    examples: [
      "Incorrect sample preparation (wrong dilution, missed dilution step)",
      "Wrong standard concentration used",
      "Incorrect integration parameters applied",
      "Calculation/transcription error in data processing",
      "Sample contamination during prep (improper handling)",
      "Wrong solvent used for dissolution",
      "Failure to equilibrate column before injection",
    ]
  },
  {
    category: "Instrument / Equipment",
    icon: "⚙️",
    color: "#38BDF8",
    examples: [
      "HPLC pump failure (pressure spike, gradient error)",
      "Detector drift or lamp failure (UV lamp aging)",
      "Autosampler malfunction (needle plugging, injection volume error)",
      "Balance out of calibration",
      "pH meter electrode failure / improper calibration",
      "Temperature control failure in incubator/water bath",
      "Pipette out of calibration or tip defect",
    ]
  },
  {
    category: "Reagent / Standard",
    icon: "🧪",
    color: "#34D399",
    examples: [
      "Reference standard expired or degraded",
      "Reagent contamination or wrong concentration",
      "Degraded mobile phase (microbial growth, evaporation)",
      "Buffer prepared at wrong pH",
      "Water system failure (TOC out of spec, conductivity)",
      "Wrong lot of reagent with different purity",
    ]
  },
  {
    category: "Environmental",
    icon: "🌡️",
    color: "#A78BFA",
    examples: [
      "Temperature excursion in stability chamber",
      "Humidity excursion affecting hygroscopic sample",
      "Vibration interference during weighing",
      "Power fluctuation affecting instrument",
      "Static charge affecting powder weighing",
    ]
  },
  {
    category: "Manufacturing",
    icon: "🏭",
    color: "#F472B6",
    examples: [
      "Raw material out of specification",
      "Process parameter deviation (temp, time, pH, speed)",
      "Equipment cleaning/carryover contamination",
      "Wrong order of addition of components",
      "Blend uniformity failure",
      "Fill weight/volume error",
      "Lyophilization cycle deviation",
      "Filtration membrane failure",
    ]
  },
  {
    category: "Sampling",
    icon: "🧫",
    color: "#FB923C",
    examples: [
      "Sampling from wrong location (non-representative)",
      "Sample container contamination",
      "Sample degradation during transport/storage",
      "Wrong sample taken (mix-up)",
      "Inadequate sample volume leading to poor precision",
    ]
  },
];

export const OOT_CRITERIA = [
  {
    rule: "Westgard 1₂s Warning",
    description: "One result exceeds mean ± 2SD",
    action: "Warning only — increase monitoring frequency; no OOS investigation required",
    type: "warning",
    color: "#F59E0B",
  },
  {
    rule: "Westgard 1₃s Reject",
    description: "One result exceeds mean ± 3SD",
    action: "Reject run; investigate possible systemic cause; consider OOS investigation",
    type: "reject",
    color: "#F472B6",
  },
  {
    rule: "Westgard 2₂s",
    description: "Two consecutive results both exceed same ± 2SD limit",
    action: "Systematic error signal — investigate cause; review process and method",
    type: "trend",
    color: "#FB923C",
  },
  {
    rule: "Westgard R₄s",
    description: "Range between two results exceeds 4SD",
    action: "Random error signal — check analyst technique, reagents, instrument precision",
    type: "alert",
    color: "#F59E0B",
  },
  {
    rule: "Westgard 10₇",
    description: "Ten consecutive results all above or below the mean",
    action: "Strong trend — systematic bias; investigate process drift, standard aging, column aging",
    type: "trend",
    color: "#38BDF8",
  },
  {
    rule: "CUSUM",
    description: "Cumulative sum exceeds decision interval h (typically h=5σ)",
    action: "Process mean has shifted — investigate root cause; consider process re-validation",
    type: "trend",
    color: "#A78BFA",
  },
  {
    rule: "Linear Trend (6 points)",
    description: "Six consecutive results trending monotonically up or down",
    action: "Trend investigation required — column degradation, reagent aging, process drift",
    type: "trend",
    color: "#60A5FA",
  },
];
