/* ════════════════════════════════════════════════════════════ */
/*  CMC Master — QbD / CQA / CPP / COA Master Data            */
/* ════════════════════════════════════════════════════════════ */

// ─ Quality Target Product Profile (QTPP) ─────────────────────
export const QTPP = [
  { attribute:"Dosage Form & Route", target:"Sterile liquid (solution) for IV or SC injection", justification:"Biologics cannot be administered orally; IV ensures 100% bioavailability; SC enables self-administration" },
  { attribute:"Protein Concentration", target:"10–50 mg/mL (product-specific)", justification:"Balances dose convenience vs. viscosity/stability constraints; high-conc SC formulations require ≤20 mPa·s viscosity" },
  { attribute:"Container Closure System", target:"Type I borosilicate glass vial/PFS with fluoropolymer-coated bromobutyl stopper", justification:"Minimizes extractables/leachables; optimal CCI; industry standard for protein biologics" },
  { attribute:"Shelf Life", target:"≥24 months at 2–8°C (refrigerated)", justification:"Supports global supply chain; patient convenience; ICH Q5C real-time data required to BLA submission" },
  { attribute:"Potency (Biological Activity)", target:"70–130% vs. reference standard (relative potency)", justification:"Ensures therapeutic effect at prescribed dose; validated cell-based potency assay required per ICH Q6B §3.5" },
  { attribute:"Safety Profile", target:"Sterile; Endotoxin ≤0.5 EU/mg; No visible/subvisible particles beyond USP <788>; Pyrogen-free", justification:"Patient safety; ICH Q6B safety specifications; USP <1>, <787>, <788>" },
  { attribute:"Identity", target:"Confirmed as mAb [X] by CE-SDS MW pattern and icIEF pI profile vs. reference standard", justification:"Protects patient from wrong drug; lot release identity test per ICH Q6B §3.1" },
  { attribute:"Purity", target:"Monomer ≥97% SEC-HPLC; HCP ≤100 ppm; Residual Protein A ≤2 ppm; DNA ≤10 pg/mg", justification:"Aggregates and process impurities linked to immunogenicity; clearance per ICH Q6B §3.3" },
  { attribute:"Pharmacokinetic Target", target:"Half-life 10–21 days (IgG1 FcRn recycling mechanism)", justification:"Supports monthly/biweekly dosing; neonatal Fc receptor (FcRn) binding is a CQA for PK" },
];

// ─ CQA List ───────────────────────────────────────────────────
export const CQA_LIST = [
  {
    id:"cqa-aggregation", name:"Aggregation (HMW Species)", abbreviation:"HMW",
    category:"Purity", risk:"Critical", color:"#F472B6",
    rationale:"HMW aggregates are linked to immunogenicity risk — pre-formed aggregates can trigger anti-drug antibody (ADA) responses. Aggregates ≥0.1 µm are most immunogenic. Upward HMW trend is the primary stability-indicating signal for protein biologics.",
    spec:"≤2% by SEC-HPLC at release; ≤5% end-of-shelf-life",
    testMethods:["am-sec","am-dls","am-mfi","am-sec-mals"],
    linkedICH:["q6b","q8r2","q5c"],
    ctdSection:"3.2.S.4",
    patientRisk:"ADA formation, infusion reactions, altered PK (faster clearance of aggregated species)",
    controlTier:"Release spec + Stability spec",
    mitigation:"Formulation optimization (pH, sucrose, PS-80); UF/DF TMP control; minimize freeze-thaw cycles; cold chain",
  },
  {
    id:"cqa-fragmentation", name:"Fragmentation / LMW Degradants", abbreviation:"LMW",
    category:"Purity", risk:"Critical", color:"#F472B6",
    rationale:"Fragmentation produces non-functional protein fragments (Fc/2, Fab, half-antibody) with altered PK and potential immunogenicity. CE-SDS (non-reduced) is the primary release test; intact mass spectrometry for characterization.",
    spec:"LMW ≤3% (CE-SDS NR); specific bands <1% each",
    testMethods:["am-ce-sds","am-intact-mass"],
    linkedICH:["q6b","q5c"],
    ctdSection:"3.2.S.4",
    patientRisk:"Loss of potency, altered PK, immunogenicity potential from protein fragments",
    controlTier:"Release spec + Stability spec",
    mitigation:"Optimize purification; control process temperatures and hold times; low pH hold parameters",
  },
  {
    id:"cqa-potency", name:"Potency / Biological Activity", abbreviation:"Potency",
    category:"Function", risk:"Critical", color:"#F59E0B",
    rationale:"Potency directly determines therapeutic dose. Per ICH Q6B §3.5, every biologic lot must have a validated potency assay on the release specification. A 4-parameter logistic (4PL) cell-based assay with parallelism testing is the gold standard.",
    spec:"70–130% relative potency vs. reference standard",
    testMethods:["am-cell-bioassay","am-elisa","am-spr"],
    linkedICH:["q6b","q2r1"],
    ctdSection:"3.2.S.4",
    patientRisk:"Therapeutic failure (low potency) or exaggerated pharmacology/toxicity (high potency)",
    controlTier:"Release spec + Stability spec (USP <1033> for bioassay validation)",
    mitigation:"Reference standard lifecycle management; assay suitability controls; parallelism verification; orthogonal PD assays",
  },
  {
    id:"cqa-glycosylation", name:"Glycosylation Profile (Afucosylation %)", abbreviation:"Glycan",
    category:"Function", risk:"Critical", color:"#A78BFA",
    rationale:"For ADCC-dependent mAbs, afucosylation % directly governs FcγRIIIa binding affinity and NK-cell cytotoxicity. G0F/G1F/G2F/Man5 distribution impacts efficacy, FcRn recycling (PK), and immunogenicity. ICH Q6B §3.4 requires glycosylation characterization for all biologics.",
    spec:"Afucosylation 5–15%; G0+G1+G2 ≥60%; each high-mannose species <5%",
    testMethods:["am-glycan","am-peptide-map"],
    linkedICH:["q6b","q8r2"],
    ctdSection:"3.2.S.3",
    patientRisk:"Reduced ADCC efficacy (low afucosylation); altered FcRn recycling (high mannose → faster clearance); immunogenic unusual glycoforms",
    controlTier:"Release spec + Process control (bioreactor conditions)",
    mitigation:"Bioreactor DO, pH, temperature, galactose supplementation; CHO cell line selection; regular lot release testing",
  },
  {
    id:"cqa-charge-variants", name:"Charge Variant Profile (Main/Acidic/Basic %)", abbreviation:"Charge",
    category:"Identity/Purity", risk:"Key→Critical if CDR", color:"#22D3EE",
    rationale:"Charge variants arise from deamidation (Asn→Asp), oxidation (Met, Trp), C-term Lys truncation, N-term pyroGlu. CDR deamidation directly impacts antigen binding. Charge profile is a fingerprint for identity and comparability studies.",
    spec:"Main peak ≥75%; Acidic ≤15%; Basic ≤10% (icIEF); CDR deamidation sites monitored by peptide mapping",
    testMethods:["am-cief","am-iex","am-peptide-map"],
    linkedICH:["q6b","q5c"],
    ctdSection:"3.2.S.4",
    patientRisk:"CDR deamidation/oxidation → reduced target binding → therapeutic failure; basic species (C-term Lys) low patient risk",
    controlTier:"Release + Stability spec; CEX as stability-indicating method; peptide mapping for site-specific monitoring",
    mitigation:"Optimize bioreactor pH/temperature; formulation pH 5.5–6.5; antioxidants (Met 1 mM); N2 headspace",
  },
  {
    id:"cqa-hcp", name:"Host Cell Proteins (HCP)", abbreviation:"HCP",
    category:"Process Impurity", risk:"Critical", color:"#FB923C",
    rationale:"CHO-derived HCPs can trigger immune responses, degrade product via enzymatic activity (lipases degrade PS-80; proteases cleave mAb), and accumulate in patients with repeated dosing. FDA/EMA expect <100 ppm; leading programs achieve <10 ppm.",
    spec:"≤100 ppm (ng HCP/mg protein) by generic CHO HCP ELISA; individual high-risk HCPs <1 ppm",
    testMethods:["am-elisa"],
    linkedICH:["q6b","q11"],
    ctdSection:"3.2.S.2",
    patientRisk:"Immunogenicity; PS-80 degradation in formulated product; adverse events with chronic dosing; anti-drug antibodies",
    controlTier:"Release spec; multi-step purification train clearance; orthogonal mass spec for individual HCP identification",
    mitigation:"Protein A + CEX + AEX purification train; high-coverage polyclonal HCP ELISA; individual HCP tracking at scale",
  },
  {
    id:"cqa-endotoxin", name:"Endotoxin / Bacterial Pyrogens", abbreviation:"ET",
    category:"Safety", risk:"Critical", color:"#F59E0B",
    rationale:"Endotoxins (LPS from gram-negative bacteria) are potent pyrogens. Nanogram quantities can cause fever, septic shock, and death in IV patients. LAL kinetic chromogenic assay (KCA) is the standard method per USP <85> and EP 2.6.14.",
    spec:"≤0.5 EU/mg protein for DS; ≤0.2 EU/mL for IV DP",
    testMethods:["am-endotoxin"],
    linkedICH:["q6b"],
    ctdSection:"3.2.S.4",
    patientRisk:"Life-threatening pyrogenic reactions, septic shock, fever requiring hospitalization",
    controlTier:"Release spec on every lot; spike recovery (IPC) 50–200%; environmental monitoring",
    mitigation:"WFI-grade water; depyrogenation of containers (250°C dry heat); GMP manufacturing environment; validated LAL method",
  },
  {
    id:"cqa-particulates", name:"Sub-visible Particulates", abbreviation:"SvP",
    category:"Safety", risk:"Critical", color:"#60A5FA",
    rationale:"Sub-visible particles (1–100 µm) include protein aggregates, silicone oil, glass delamination, and rubber stopper particles. Protein particles in the 0.1–10 µm range are most immunogenic. USP <787>/<788> limits required for injectable products.",
    spec:"≤6,000 particles/container ≥10 µm; ≤600 ≥25 µm (USP <788>); MFI as orthogonal method",
    testMethods:["am-mfi","am-dls"],
    linkedICH:["q6b"],
    ctdSection:"3.2.P.5",
    patientRisk:"Embolism (large particles); immunogenicity (protein aggregates); infusion reactions; altered PK",
    controlTier:"Release spec (light obscuration + MFI); stability monitoring; container closure system qualification",
    mitigation:"Optimized PS-80; minimize freeze-thaw; syringe/vial surface qualification; peroxide-controlled PS-80 lots",
  },
  {
    id:"cqa-sterility", name:"Sterility (Absence of Viable Microorganisms)", abbreviation:"Sterility",
    category:"Safety", risk:"Critical", color:"#34D399",
    rationale:"Sterile injectable products must be completely free of viable microorganisms. Bacterial contamination of IV drugs can cause life-threatening sepsis. Sterility testing per USP <71> is required for every lot. The SAL design basis is 10⁻⁶.",
    spec:"No growth in USP <71> (14-day incubation at 22.5°C and 32.5°C)",
    testMethods:["am-bioburden"],
    linkedICH:["q6b"],
    ctdSection:"3.2.P.5",
    patientRisk:"Sepsis, endocarditis, and death from IV administration of contaminated product",
    controlTier:"Release spec every lot; aseptic process validation (media fills, 3× per campaign); 0 contaminated units",
    mitigation:"ISO 5 fill environment; 0.22 µm sterilizing filtration; pre/post filter integrity testing; environmental monitoring",
  },
  {
    id:"cqa-concentration", name:"Protein Concentration (Strength)", abbreviation:"Conc",
    category:"Strength", risk:"Critical", color:"#34D399",
    rationale:"Correct concentration directly determines clinical dose. OOS concentration risks under- or overdosing the patient. A280 spectrophotometry is the standard method using the protein's extinction coefficient.",
    spec:"Nominal ± 10% (e.g., 9.0–11.0 mg/mL for 10 mg/mL target)",
    testMethods:["am-a280"],
    linkedICH:["q6b"],
    ctdSection:"3.2.S.4",
    patientRisk:"Under-dose → therapeutic failure; over-dose → exaggerated pharmacology, toxicity",
    controlTier:"Release spec every lot; IPC during fill-finish (100% gravimetric check)",
    mitigation:"Precise UF/DF TMP control; A280 IPC during compounding; reference standard extinction coefficient verification",
  },
  {
    id:"cqa-cci", name:"Container Closure Integrity (CCI)", abbreviation:"CCI",
    category:"Safety", risk:"Critical", color:"#A78BFA",
    rationale:"CCI ensures the sterile barrier is maintained throughout shelf life. A breached container exposes the product to microbial contamination and O₂ ingress. USP <1207> provides the framework; deterministic methods (vacuum decay, HVLD) are preferred over probabilistic methods.",
    spec:"No leak detected; vacuum decay ≤10⁻⁶ mbar·L/sec or equivalent",
    testMethods:[],
    linkedICH:["q6b"],
    ctdSection:"3.2.P.3",
    patientRisk:"Microbial contamination (sterility breach); product degradation from O₂ ingress",
    controlTier:"Release (representative sample); Stability at each time point; Container closure system qualification",
    mitigation:"Container closure qualification; stopper/vial compatibility testing; validated inspection methods; O₂ headspace monitoring",
  },
];

// ─ Critical Process Parameters ────────────────────────────────
export const CPP_LIST = [
  // UPSTREAM
  {
    id:"cpp-do", name:"Dissolved Oxygen (DO) Setpoint", processStep:"Upstream — Bioreactor", stepColor:"#22D3EE",
    normalRange:"20–60% air saturation", criticalLow:"<15%", criticalHigh:">80%",
    mechanismOfEffect:"DO regulates oxidative glycosylation pathways. Low DO → reduced UDP-glucose transfer → altered glycoform distribution (↑ high-mannose). High DO → oxidative stress → Met/Trp oxidation (charge variants, potency impact). Cascade: DO deviation → glycosylation CQA and charge variant CQA.",
    linkedCQAs:["cqa-glycosylation","cqa-charge-variants","cqa-aggregation"],
    linkedICH:["q8r2","q11"],
    monitoringStrategy:"Inline DO probe (polarographic or optical) with PID closed-loop control via sparging. Alarms at <20% and >70% air saturation. Deviations require comparability testing.",
    controlMethod:"PID on O₂/air sparger mix; redundant probes at scale; DO deviation recorded in batch record",
    riskLevel:"High",
  },
  {
    id:"cpp-ph-bioreactor", name:"Bioreactor pH Setpoint", processStep:"Upstream — Bioreactor", stepColor:"#22D3EE",
    normalRange:"pH 6.95–7.10 (setpoint 7.02)", criticalLow:"<6.80", criticalHigh:">7.30",
    mechanismOfEffect:"pH directly affects glycosyltransferase enzyme activity (optimal pH 6.0–7.0) and cellular protein secretion. Low pH → increased acidic glycoforms; affects product deamidation rate. CO₂ accumulation at large scale lowers pH — active control critical.",
    linkedCQAs:["cqa-glycosylation","cqa-charge-variants","cqa-aggregation"],
    linkedICH:["q8r2","q11"],
    monitoringStrategy:"Inline pH probe (calibrated daily); CO₂ sparging + NaHCO₃/CO₂ overlay for adjustment. Scale-specific CO₂ management strategy.",
    controlMethod:"Closed-loop pH control; base addition (NaHCO₃) for pH up; CO₂ sparging for pH down; mass spec headspace for dCO₂",
    riskLevel:"High",
  },
  {
    id:"cpp-temp-bioreactor", name:"Bioreactor Temperature", processStep:"Upstream — Bioreactor", stepColor:"#22D3EE",
    normalRange:"37°C growth → 33–35°C production phase (temperature shift)", criticalLow:"<36°C (growth phase)", criticalHigh:">37.5°C",
    mechanismOfEffect:"Temperature shift is the most common upstream process strategy. Lower production temp: reduces high-mannose glycoforms, decreases aggregation by slowing folding kinetics, extends run duration, increases productivity. Deviations → altered glycosylation, aggregation, potency.",
    linkedCQAs:["cqa-glycosylation","cqa-aggregation","cqa-potency"],
    linkedICH:["q8r2","q11"],
    monitoringStrategy:"Inline temperature probe ±0.1°C; water jacket PID control; alarm at ±0.5°C from setpoint; temperature shift timing in batch record",
    controlMethod:"PID water jacket; redundant sensors; temperature shift protocol with timing triggers; deviation investigation for >0.5°C excursion",
    riskLevel:"High",
  },
  {
    id:"cpp-glucose-feed", name:"Glucose/Galactose Feed Strategy", processStep:"Upstream — Fed-Batch Feeding", stepColor:"#22D3EE",
    normalRange:"Glucose 2–8 mM; Galactose feed timed per PD protocol", criticalLow:"Glucose <1 mM", criticalHigh:"Glucose >20 mM (hyperosmolality)",
    mechanismOfEffect:"Galactose supplementation specifically increases G1F and G2F galactosylation. G2F glycoforms important for FcRn binding and complement. Nutrient depletion → cell stress → altered glycosylation, increased HCP secretion.",
    linkedCQAs:["cqa-glycosylation","cqa-hcp","cqa-potency"],
    linkedICH:["q8r2","q11"],
    monitoringStrategy:"Daily metabolite sampling (BioProfile Flex); automated glucose measurement; cell culture feed algorithm based on glucose consumption rate",
    controlMethod:"Automated fed-batch controller; glucose bolus or continuous feed; galactose supplement timing per batch record; validated by DoE",
    riskLevel:"Medium-High",
  },
  {
    id:"cpp-harvest-vcd", name:"Viable Cell Density (VCD) at Harvest", processStep:"Upstream — Harvest", stepColor:"#22D3EE",
    normalRange:"10–30 × 10⁶ cells/mL; viability ≥80%", criticalHigh:"Viability <75% or culture day >14",
    mechanismOfEffect:"High VCD + apoptosis at end of culture increases HCP release. Very high density causes nutrient depletion, lactate/ammonium accumulation, and product quality changes. Harvest timing balances yield vs. quality.",
    linkedCQAs:["cqa-hcp","cqa-aggregation"],
    linkedICH:["q11"],
    monitoringStrategy:"Daily ViCELL automated cell counter; viability ≥80% required for harvest; metabolic stress markers (lactate <3.5 mM, NH₄⁺ <10 mM)",
    controlMethod:"Defined harvest window (VCD range + viability + culture day); harvest decision algorithm in batch record",
    riskLevel:"Medium",
  },
  // DOWNSTREAM
  {
    id:"cpp-pra-load", name:"Protein A Load Density", processStep:"Downstream — Protein A Capture (Step 1)", stepColor:"#34D399",
    normalRange:"≤30 g protein/L resin (dynamic binding capacity, DBC)", criticalHigh:">40 g/L (breakthrough)",
    mechanismOfEffect:"Overloading above DBC leads to product breakthrough — yield loss and HCP carryover. DBC determined in process validation (10% breakthrough curve). Load density also affects HCP clearance and resin lifetime.",
    linkedCQAs:["cqa-hcp","cqa-aggregation"],
    linkedICH:["q11"],
    monitoringStrategy:"UV280 load and flow-through monitoring; IPC: batch load calculation per batch record; UV breakthrough alarm",
    controlMethod:"Load density calculated (titer × harvest volume / resin volume); alarm on UV280 breakthrough; validated column qualification",
    riskLevel:"High",
  },
  {
    id:"cpp-low-ph-hold", name:"Low pH Viral Inactivation (pH, Temp, Hold Time)", processStep:"Downstream — Viral Inactivation (Step 2)", stepColor:"#34D399",
    normalRange:"pH 3.50 ± 0.05; ≥37°C; ≥60 min hold", criticalLow:"pH >3.70 = insufficient; hold <55 min",
    mechanismOfEffect:"Low pH denatures enveloped virus capsids by disrupting lipid bilayer. Must achieve ≥4-log LRV for retroviruses. pH <3.4 risks mAb aggregation. All three parameters are critical: pH ≤3.7, time ≥60 min, temperature ≥15°C (per ICH Q5A framework).",
    linkedCQAs:["cqa-aggregation","cqa-potency","cqa-sterility"],
    linkedICH:["q5a","q11"],
    monitoringStrategy:"In-process pH measurement before/during hold; validated timer; post-inactivation SEC IPC",
    controlMethod:"Validated acidification procedure; batch record timers; post-hold neutralization; SEC IPC to confirm product quality",
    riskLevel:"Critical (viral safety — not a quality attribute but process safety control)",
  },
  {
    id:"cpp-cex-gradient", name:"CEX Chromatography pH and Salt Gradient", processStep:"Downstream — CEX Polishing (Step 3)", stepColor:"#34D399",
    normalRange:"Load pH 5.0; elution 0–500 mM NaCl gradient over 20 CV; collection by UV + IPC",
    criticalLow:"Load pH >5.3 (poor binding); gradient <15 CV (poor resolution)",
    mechanismOfEffect:"CEX separates charge variants by isoelectric point. Gradient slope controls charge variant profile of the elution pool (acidic species removal vs. main peak recovery). Also clears HCP, DNA, and leached Protein A.",
    linkedCQAs:["cqa-charge-variants","cqa-hcp","cqa-aggregation"],
    linkedICH:["q8r2","q11"],
    monitoringStrategy:"UV280 absorbance; online conductivity/pH; pool collection by UV fraction; IPC: icIEF main peak ≥85% before proceeding",
    controlMethod:"Validated gradient protocol; IPC specification on main peak % and HCP on pool; CEX resin lifetime validation (≥200 cycles)",
    riskLevel:"High",
  },
  {
    id:"cpp-ufdf-tmp", name:"UF/DF Transmembrane Pressure (TMP)", processStep:"Downstream — UF/DF (Final Step)", stepColor:"#34D399",
    normalRange:"TMP ≤2.0 bar; flux ≤30 LMH", criticalHigh:"TMP >3.0 bar",
    mechanismOfEffect:"Excessive TMP causes protein fouling of the TFF membrane, flux decline, and — critically — surface-induced aggregation. High-concentration mAbs (>50 mg/mL) especially susceptible. Final concentration set by UF/DF volume target.",
    linkedCQAs:["cqa-aggregation","cqa-particulates","cqa-concentration"],
    linkedICH:["q8r2","q11"],
    monitoringStrategy:"Online TMP sensors; daily permeate protein monitoring; IPC: concentration by A280 and SEC after UF/DF",
    controlMethod:"TMP feedback control; defined flux rate; pre-use TFF membrane integrity testing; IPC spec on aggregation post-UF/DF",
    riskLevel:"High",
  },
  // DRUG PRODUCT
  {
    id:"cpp-formulation-ph", name:"Formulation pH", processStep:"Drug Product — Formulation", stepColor:"#A78BFA",
    normalRange:"pH 5.5 ± 0.2 (histidine buffer)", criticalLow:"<5.0 (acid hydrolysis)", criticalHigh:">6.5 (deamidation acceleration)",
    mechanismOfEffect:"Formulation pH is the single most impactful parameter on chemical degradation rate. Deamidation (Asn→Asp) is fastest at neutral/alkaline pH; slowest at pH 4–5. Also affects electrostatic repulsion and aggregation propensity (physical stability). pH 5.5 optimal for most mAbs.",
    linkedCQAs:["cqa-aggregation","cqa-charge-variants","cqa-potency"],
    linkedICH:["q8r2","q5c"],
    monitoringStrategy:"pH meter IPC after buffer addition; in-line pH sensor in formulation vessel; IPC spec pH ± 0.3 of nominal",
    controlMethod:"Histidine buffer at controlled pH; batch record pH specification; calibrated electrode measurement; buffer confirmed pre-use",
    riskLevel:"Critical",
  },
];

// ─ FMEA Risk Assessment Table ──────────────────────────────────
// Severity 1-10 (patient risk), Occurrence 1-10 (probability), Detectability 1-10 (10 = hard to detect)
// RPN = Severity × Occurrence × Detectability
export const FMEA_TABLE = [
  {
    cqaId:"cqa-aggregation", cqaName:"Aggregation (HMW)",
    failureMode:"HMW species exceed release specification (>2% SEC)",
    potentialCauses:["TMP exceedance during UF/DF","Low pH hold too aggressive (pH <3.4)","Formulation pH drift","Excessive freeze-thaw cycles","Shear stress during fill-finish"],
    severity:9, occurrence:4, detectability:2, rpn:72,
    mitigations:["TMP control with alarms and IPC","pH IPC at each downstream step","SEC IPC post UF/DF","Validated PS-80 concentration","Minimize freeze-thaw cycles in cold chain"],
    residualRpn:24, linkedCPPs:["cpp-ufdf-tmp","cpp-low-ph-hold","cpp-formulation-ph"],
  },
  {
    cqaId:"cqa-potency", cqaName:"Potency (Biological Activity)",
    failureMode:"Potency fails release specification (<70% or >130%)",
    potentialCauses:["Reference standard degradation or incorrect assignment","Cell line drift in bioassay (passage number)","Protein structural changes (CDR oxidation/deamidation)","Incorrect concentration measurement (A280 error)"],
    severity:10, occurrence:3, detectability:3, rpn:90,
    mitigations:["Reference standard lifecycle management (3 lots, stability qualification)","Assay suitability controls and parallelism criteria","Stability-indicating correlation to structure (SEC, icIEF)","Cell passage number limits in bioassay SOP"],
    residualRpn:20, linkedCPPs:["cpp-formulation-ph","cpp-do","cpp-temp-bioreactor"],
  },
  {
    cqaId:"cqa-glycosylation", cqaName:"Glycosylation Profile",
    failureMode:"Afucosylation % OOS or major glycoform distribution shift",
    potentialCauses:["Bioreactor DO excursion","Bioreactor pH drift","Temperature deviation","Media galactose depletion","Cell line instability"],
    severity:8, occurrence:5, detectability:3, rpn:120,
    mitigations:["DO closed-loop control with alarms","Daily metabolite monitoring (BioProfile)","Temperature alarm system with automatic correction","Media nutrient feed algorithm","Cell bank characterization and stability testing"],
    residualRpn:32, linkedCPPs:["cpp-do","cpp-ph-bioreactor","cpp-temp-bioreactor","cpp-glucose-feed"],
  },
  {
    cqaId:"cqa-hcp", cqaName:"Host Cell Proteins (HCP)",
    failureMode:"HCP level exceeds specification (>100 ppm at release)",
    potentialCauses:["Protein A column overloading (DBC exceeded)","Aberrant cell culture conditions (high cell death)","Column lifetime exceeded (resin fouling)","Failed CEX or AEX polishing step"],
    severity:8, occurrence:3, detectability:4, rpn:96,
    mitigations:["Load density IPC for Protein A","Column lifetime validation (200 cycles)","HCP ELISA in-process on polishing pool","Resin qualification criteria; end-of-life testing"],
    residualRpn:24, linkedCPPs:["cpp-pra-load","cpp-cex-gradient"],
  },
  {
    cqaId:"cqa-charge-variants", cqaName:"Charge Variants (icIEF)",
    failureMode:"icIEF main peak fails spec or CDR deamidation detected at stability",
    potentialCauses:["Bioreactor pH excursion","Elevated temperature accelerating deamidation","Oxidative stress (dissolved O₂, metal ions)","Extended hold times at neutral pH","Insufficient CEX separation"],
    severity:7, occurrence:4, detectability:3, rpn:84,
    mitigations:["pH IPC at each manufacturing step","Cold chain management (2–8°C)","Antioxidant in formulation (Met 1 mM)","CEX gradient optimization to resolve charge variants","Forced degradation studies to characterize CDR site risk"],
    residualRpn:21, linkedCPPs:["cpp-ph-bioreactor","cpp-formulation-ph","cpp-cex-gradient"],
  },
  {
    cqaId:"cqa-endotoxin", cqaName:"Endotoxin",
    failureMode:"Endotoxin exceeds specification (>0.5 EU/mg) at release",
    potentialCauses:["Contaminated WFI or buffer preparation","Non-sterile media components","Gram-negative contamination in bioreactor","Environmental contamination in hold vessel"],
    severity:10, occurrence:2, detectability:2, rpn:40,
    mitigations:["Daily WFI endotoxin and TOC monitoring","Depyrogenation of vessels (250°C dry heat)","Environmental monitoring program","Release test every lot (KCA-LAL)"],
    residualRpn:10, linkedCPPs:["cpp-harvest-vcd"],
  },
  {
    cqaId:"cqa-particulates", cqaName:"Sub-visible Particulates",
    failureMode:"MFI particle count exceeds USP <788> limits",
    potentialCauses:["Protein aggregation (see HMW)","Silicone oil droplets from stopper","Glass delamination","PS-80 oxidative degradation products"],
    severity:8, occurrence:4, detectability:3, rpn:96,
    mitigations:["Optimized PS-80 concentration and peroxide control","Container closure system qualification","MFI routine lot testing","Freeze-thaw cycle minimization"],
    residualRpn:24, linkedCPPs:["cpp-ufdf-tmp","cpp-formulation-ph"],
  },
  {
    cqaId:"cqa-sterility", cqaName:"Sterility",
    failureMode:"Positive sterility test (growth in USP <71>)",
    potentialCauses:["Breach of Grade A environment","Sterilizing filter failure or integrity test failure","Aseptic connection error","Personnel aseptic technique failure"],
    severity:10, occurrence:1, detectability:4, rpn:40,
    mitigations:["Media fills 3× per campaign (0 contaminated units)","Pre- and post-use filter integrity test","Environmental monitoring Grade A/B daily","Operator gowning qualification and re-qualification"],
    residualRpn:8, linkedCPPs:["cpp-formulation-ph"],
  },
];

// ─ DoE Study Examples ─────────────────────────────────────────
export const DOE_STUDIES = [
  {
    id:"doe-upstream-glycan",
    title:"Upstream Glycan Optimization DoE",
    objective:"Maximize afucosylation % (5–15% target) and G2F galactosylation index while maintaining titer ≥3 g/L and aggregation ≤2%",
    design:"Face-Centered Central Composite Design (FC-CCD)",
    factors:[
      { name:"Dissolved Oxygen (DO)", low:"10% air sat", center:"35%", high:"60%" },
      { name:"pH Setpoint", low:"6.85", center:"7.00", high:"7.15" },
      { name:"Galactose Supplement", low:"0 mM", center:"5 mM", high:"10 mM" },
    ],
    responses:["Afucosylation %","G0F %","G2F %","Titer (g/L)","HMW Aggregation % (SEC)"],
    runs:20, software:"JMP Pro v17",
    keyFindings:"DO and galactose were most significant for afucosylation. DO × pH interaction significant for G2F. Optimum: DO 25%, pH 7.0, Gal 7 mM → afucosylation 11.2% ± 0.8% (within spec). Titer 3.8 g/L. All CQA specs met at optimum.",
  },
  {
    id:"doe-formulation",
    title:"Liquid Formulation Stability Optimization DoE",
    objective:"Minimize aggregation at 5°C / 2 years and 25°C / 6 months while maintaining Tm ≥70°C",
    design:"I-Optimal Response Surface Design (3-factor, 17 runs)",
    factors:[
      { name:"pH", low:"5.0", center:"5.5", high:"6.0" },
      { name:"Sucrose (%)", low:"3%", center:"6%", high:"9%" },
      { name:"Polysorbate 80 (mg/mL)", low:"0.1", center:"0.3", high:"0.5" },
    ],
    responses:["HMW % after 1 month 40°C","HMW % 6 months 25°C","Tm by nanoDSF (°C)","Tagg (°C)","MFI particles ≥2 µm/mL"],
    runs:17, software:"JMP Pro v17",
    keyFindings:"pH most significant for HMW (lower pH → less HMW). Sucrose significantly improved Tm and Tagg. Optimal: pH 5.5, 7% sucrose, 0.3 mg/mL PS-80. All responses within target. Confirmed with 3-month real-time stability at 5°C.",
  },
  {
    id:"doe-cex",
    title:"CEX Chromatography Optimization DoE",
    objective:"Maximize main peak recovery (≥90%) while achieving acidic species ≤10% and minimizing HCP",
    design:"Full 2³ Factorial (Resolution V) with Centerpoints",
    factors:[
      { name:"Load pH", low:"4.8", center:"5.0", high:"5.2" },
      { name:"Elution Gradient (CV)", low:"15 CV", center:"20 CV", high:"25 CV" },
      { name:"Load Density (g/L resin)", low:"15", center:"25", high:"35" },
    ],
    responses:["Main peak recovery (%)","Acidic species in pool (%)","Basic species (%)","HCP in pool (ppm)"],
    runs:12, software:"Minitab v21",
    keyFindings:"Load pH 4.8 dramatically improved acidic species removal. 20 CV gradient optimal for recovery vs. resolution trade-off. Load density up to 35 g/L showed no breakthrough. Selected: pH 4.8, 20 CV, 25 g/L. Main recovery 94%, acidic 7% (passes spec).",
  },
];

// ─ Design Space ───────────────────────────────────────────────
export const DESIGN_SPACE = [
  {
    id:"ds-upstream",
    title:"Upstream Bioreactor Design Space",
    description:"Upstream design space defined from 3-factor FC-CCD DoE (20 runs) at 2L scale, qualified to 2000L via validated scale-down model. Working within this space does not require regulatory notification per ICH Q8.",
    parameters:[
      { name:"Dissolved Oxygen", par:"15–65% air sat", nor:"25–55% air sat", setpoint:"35%", linkedCQAs:["Glycosylation","Charge variants"] },
      { name:"pH", par:"6.85–7.20", nor:"6.95–7.10", setpoint:"7.02", linkedCQAs:["Glycosylation","Charge variants"] },
      { name:"Temperature (growth)", par:"36.0–37.5°C", nor:"36.5–37.2°C", setpoint:"37°C", linkedCQAs:["Aggregation","Glycosylation"] },
      { name:"Temperature (production)", par:"32.0–35.5°C", nor:"33.0–34.0°C", setpoint:"33°C", linkedCQAs:["Aggregation","Titer"] },
      { name:"Glucose (fed-batch)", par:"1–20 mM", nor:"2–8 mM", setpoint:"5 mM", linkedCQAs:["Glycosylation","HCP"] },
      { name:"Culture Duration", par:"10–14 days", nor:"11–13 days", setpoint:"12 days", linkedCQAs:["HCP","Aggregation"] },
    ],
    linkedCQAs:["cqa-glycosylation","cqa-aggregation","cqa-hcp"],
    linkedICH:["q8r2","q11"],
    regulatoryStatus:"Formally established per ICH Q8 §3. Included in BLA Module 3.2.S.2.2. Changes to design space boundaries require Type II variation (EMA) or PAS (FDA). Working within PAR is not a regulatory change.",
  },
  {
    id:"ds-cex",
    title:"CEX Chromatography Design Space",
    description:"CEX polishing design space established from 2³ factorial DoE + centerpoints at pilot scale. R² = 0.94 for main peak recovery, 0.89 for acidic species. Validated with 6 confirmation runs.",
    parameters:[
      { name:"Load pH", par:"4.7–5.3", nor:"4.85–5.15", setpoint:"4.95", linkedCQAs:["Charge variants"] },
      { name:"Gradient Length (CV)", par:"15–28 CV", nor:"17–23 CV", setpoint:"20 CV", linkedCQAs:["Charge variants","Recovery"] },
      { name:"Load Density (g/L)", par:"15–38 g/L", nor:"18–32 g/L", setpoint:"25 g/L", linkedCQAs:["HCP","Recovery"] },
      { name:"Linear Velocity (cm/h)", par:"100–200 cm/h", nor:"130–170 cm/h", setpoint:"150 cm/h", linkedCQAs:["Recovery"] },
    ],
    linkedCQAs:["cqa-charge-variants","cqa-hcp","cqa-aggregation"],
    linkedICH:["q8r2","q11"],
    regulatoryStatus:"Formally established per ICH Q8 §3; included in BLA Module 3.2.S.2.2.",
  },
];

// ─ Control Strategy (Multi-Tiered) ────────────────────────────
export const CONTROL_STRATEGY = {
  overview:"A comprehensive, multi-tiered control strategy per ICH Q10 §1.7 and Q8 §3. Aligns process understanding (DoE, scale-down models) with CQA risk assessment to ensure every batch meets quality specifications. Defense-in-depth: multiple orthogonal controls provide redundancy.",
  tiers:[
    {
      tier:1, name:"Specification Controls", color:"#F472B6",
      description:"Release and shelf-life specifications applied to every lot. Final quality gate before patient use. All methods validated per ICH Q2(R1).",
      elements:[
        { control:"SEC-HPLC (% HMW)", target:"≤2% release; ≤5% shelf-life", frequency:"Every lot (release) + every stability time point", linkedCQA:"cqa-aggregation" },
        { control:"CE-SDS NR (% main peak)", target:"≥95% at release", frequency:"Every lot (release)", linkedCQA:"cqa-fragmentation" },
        { control:"Cell-based potency", target:"70–130% vs. RS", frequency:"Every lot (release) + stability", linkedCQA:"cqa-potency" },
        { control:"icIEF (main/acidic/basic %)", target:"Main ≥75%; Acidic ≤15%", frequency:"Every lot (release) + stability", linkedCQA:"cqa-charge-variants" },
        { control:"Glycan HILIC-UPLC (afucosylation %)", target:"5–15%", frequency:"Every lot (release)", linkedCQA:"cqa-glycosylation" },
        { control:"A280 (protein concentration)", target:"Nominal ± 10%", frequency:"Every lot (release)", linkedCQA:"cqa-concentration" },
        { control:"HCP ELISA", target:"≤100 ppm", frequency:"Every lot (release)", linkedCQA:"cqa-hcp" },
        { control:"Endotoxin (LAL KCA)", target:"≤0.5 EU/mg", frequency:"Every lot (release)", linkedCQA:"cqa-endotoxin" },
        { control:"MFI particulates", target:"USP <788> limits", frequency:"Every lot (release)", linkedCQA:"cqa-particulates" },
        { control:"Sterility (USP <71>)", target:"No growth", frequency:"Every lot (release)", linkedCQA:"cqa-sterility" },
        { control:"Container Closure Integrity", target:"No leak detected", frequency:"Release sample + all stability", linkedCQA:"cqa-cci" },
      ],
    },
    {
      tier:2, name:"In-Process Controls (IPCs)", color:"#F59E0B",
      description:"Real-time monitoring during manufacturing steps. IPCs provide early warning before batch completion. Action limits are tighter than release specifications.",
      elements:[
        { control:"Bioreactor DO (inline)", target:"15–65% air sat (alarm at limits)", frequency:"Continuous", linkedCPP:"cpp-do" },
        { control:"Bioreactor pH (inline)", target:"6.85–7.20 (alarm at limits)", frequency:"Continuous", linkedCPP:"cpp-ph-bioreactor" },
        { control:"Harvest viability", target:"≥80%", frequency:"Daily during culture + at harvest", linkedCPP:"cpp-harvest-vcd" },
        { control:"Protein A step yield (A280)", target:"≥90% step yield", frequency:"Each Protein A run", linkedCPP:"cpp-pra-load" },
        { control:"SEC post-UF/DF (IPC limit)", target:"≤1.8% HMW (tighter than release)", frequency:"Each UF/DF cycle", linkedCPP:"cpp-ufdf-tmp" },
        { control:"pH post-viral inactivation", target:"pH 3.45–3.55 during hold", frequency:"Each VI step", linkedCPP:"cpp-low-ph-hold" },
        { control:"CEX icIEF pool IPC", target:"Main ≥85% before next step", frequency:"CEX pool", linkedCPP:"cpp-cex-gradient" },
        { control:"DP concentration IPC", target:"±5% of nominal", frequency:"After DP compounding", linkedCPP:"cpp-formulation-ph" },
      ],
    },
    {
      tier:3, name:"Process Parameter Controls (Design Space / PAR)", color:"#22D3EE",
      description:"Operating within proven acceptable ranges (PAR) and design space ensures quality without additional testing. Critical process parameters are controlled within defined ranges per validated batch records.",
      elements:[
        { control:"Upstream design space (all CPPs)", target:"All upstream CPPs within defined PAR/NOR", frequency:"Continuous monitoring + batch record review", linkedCPP:"cpp-do, cpp-ph-bioreactor, cpp-temp-bioreactor" },
        { control:"Downstream CPP monitoring", target:"Load densities, pH, TMP within validated ranges", frequency:"Per step in batch record", linkedCPP:"cpp-pra-load, cpp-low-ph-hold, cpp-ufdf-tmp" },
        { control:"DP formulation CPPs", target:"pH, excipient concentrations, fill temp within NOR", frequency:"Batch record verification", linkedCPP:"cpp-formulation-ph" },
      ],
    },
    {
      tier:4, name:"Raw Material Controls", color:"#A78BFA",
      description:"Control of critical raw materials (CRM) that directly impact product quality or safety. Enhanced testing or Certificate of Analysis (CoA) verification required.",
      elements:[
        { control:"Cell culture media components", target:"Vendor CoA + identity testing on each lot received", frequency:"Each lot received", linkedCPP:"Multiple CPPs" },
        { control:"Polysorbate 80 (peroxide level)", target:"≤3 mM peroxide (prevents Met/Trp oxidation)", frequency:"Each PS-80 lot received", linkedCPP:"Formulation" },
        { control:"Water for Injection (WFI)", target:"Endotoxin ≤0.25 EU/mL; conductivity ≤1.3 µS/cm", frequency:"Daily monitoring or each batch use", linkedCPP:"All steps" },
        { control:"Protein A resin qualification", target:"Capacity ≥30 g/L; lifetime validated (200 cycles)", frequency:"Each resin lot + lifetime validation", linkedCPP:"cpp-pra-load" },
        { control:"Container closure system (vial + stopper)", target:"Container closure qualification per USP <1207>; extractables/leachables per FDA guidance", frequency:"Component lot + program-level qualification", linkedCPP:"CCI" },
      ],
    },
  ],
};

// ─ Certificate of Analysis (COA) ──────────────────────────────
export const COA_ELEMENTS = {
  required:[
    "Product name and INN (International Non-proprietary Name)",
    "Lot/Batch number (unique alphanumeric identifier)",
    "Manufacturing date and expiry date (or retest date)",
    "Manufacturing site name, address, and GMP license number",
    "Storage conditions (e.g., Store at 2–8°C, protected from light)",
    "Specification reference document number and version",
    "Test result for each specification test with analytical method reference",
    "Acceptance criteria for each test (from approved specification)",
    "Pass/Fail determination for each individual test",
    "Overall Lot Disposition: RELEASED / REJECTED / QUARANTINED",
    "Authorized Quality Assurance (QA) signatory name, title, signature, and date",
    "Reference standard lot numbers and expiry dates used in testing",
    "Certificate of Analysis version number and superseded version(s)",
  ],
  regulatoryBasis:[
    "21 CFR 211.184 — FDA requires laboratory records including specifications and test results",
    "21 CFR 601.12 — BLA holder must submit COA data supporting each lot disposition",
    "ICH Q6B §3 — Specifications must include test procedures, acceptance criteria, and justified limits",
    "ICH Q10 §3.2.3 — Quality system requires documented release procedures and COA generation",
    "EU GMP Annex 16 — Qualified Person (QP) responsible for certifying batch for release in EU",
    "USP <1> Visual Inspection; USP <85> Bacterial Endotoxins; USP <71> Sterility",
  ],
  dsExample:{
    title:"Example Drug Substance COA — mAb [Product Name] DS, 10 mg/mL in histidine buffer, Lot ABC-2024-001",
    tests:[
      { test:"Appearance", method:"Visual inspection (Ph. Eur. 2.9.20)", spec:"Clear to slightly opalescent; colorless to pale yellow; essentially free of visible particles", result:"Clear, colorless, no visible particles — PASS" },
      { test:"Protein Concentration (A280)", method:"UV spectrophotometry (ε = 1.42 mL/mg·cm)", spec:"9.5–10.5 mg/mL", result:"10.1 mg/mL — PASS" },
      { test:"Identity (CE-SDS NR)", method:"CE-SDS non-reduced (Beckman PA 800)", spec:"HC+LC ≈ 148 kDa; band pattern consistent with reference", result:"148.2 kDa; consistent — PASS" },
      { test:"Purity — Monomer % (SEC-HPLC)", method:"SEC-HPLC (TSKgel G3000SWxL, PBS pH 7.4)", spec:"Monomer ≥97.0%", result:"98.4% monomer, 1.6% HMW — PASS" },
      { test:"Purity — CE-SDS NR Main Peak %", method:"CE-SDS non-reduced", spec:"Main peak ≥95.0%", result:"97.1% — PASS" },
      { test:"Charge Variant Profile (icIEF)", method:"icIEF (Protein Simple iCE3)", spec:"Main ≥75.0%; Acidic ≤15.0%; Basic ≤10.0%", result:"Main 82.1%, Acidic 11.3%, Basic 6.6% — PASS" },
      { test:"Potency (ADCC Reporter Gene Assay)", method:"FcγRIIIa ADCC RGA (validated per ICH Q2(R1))", spec:"70.0–130.0% relative activity vs. RS", result:"96.2% — PASS" },
      { test:"Glycosylation — Afucosylation %", method:"HILIC-UPLC RapiFluor-MS labeled", spec:"5.0–15.0% afucosylated glycoforms", result:"9.4% — PASS" },
      { test:"Host Cell Protein (HCP ELISA)", method:"Generic CHO HCP ELISA (Cygnus Technologies F550)", spec:"≤100 ppm (ng HCP/mg protein)", result:"18 ppm — PASS" },
      { test:"Residual Protein A (ELISA)", method:"Protein A sandwich ELISA (Cygnus)", spec:"≤2.0 ppm", result:"<0.1 ppm (below quantitation limit) — PASS" },
      { test:"Endotoxin (LAL KCA)", method:"KCA-LAL (Charles River Endosafe)", spec:"≤0.5 EU/mg protein", result:"<0.05 EU/mg — PASS" },
      { test:"Bioburden (pre-sterile filtration)", method:"Membrane filtration, USP <61>/<62>", spec:"≤10 CFU/100 mL", result:"<1 CFU/100 mL — PASS" },
    ],
    disposition:"RELEASED — All specifications met. Lot ABC-2024-001 is approved for use in clinical drug product manufacturing.",
  },
  dpExample:{
    title:"Example Drug Product COA — mAb [Product Name] DP, 10 mg/mL, 10 mL Vial, Lot DPL-2024-007",
    tests:[
      { test:"Appearance (100% visual inspection)", method:"Automated inspection line + manual AQL (USP <1>)", spec:"Clear, colorless solution, essentially free of visible particles", result:"All units pass — PASS" },
      { test:"Identity (CE-SDS NR)", method:"CE-SDS non-reduced pattern vs. reference", spec:"Band pattern consistent with reference standard", result:"Consistent — PASS" },
      { test:"Protein Concentration (A280)", method:"UV spectrophotometry", spec:"9.0–11.0 mg/mL", result:"10.3 mg/mL — PASS" },
      { test:"pH", method:"Calibrated pH meter", spec:"5.3–5.7", result:"5.5 — PASS" },
      { test:"Osmolality", method:"Vapor pressure osmometry (Wescor Vapro)", spec:"260–330 mOsm/kg", result:"295 mOsm/kg — PASS" },
      { test:"Purity — SEC-HPLC Monomer %", method:"SEC-HPLC", spec:"Monomer ≥97.0%", result:"98.1% — PASS" },
      { test:"Purity — CE-SDS NR Main Peak %", method:"CE-SDS non-reduced", spec:"Main peak ≥95.0%", result:"96.8% — PASS" },
      { test:"Potency (ADCC RGA)", method:"FcγRIIIa ADCC Reporter Gene Assay", spec:"70.0–130.0%", result:"103.4% — PASS" },
      { test:"Sub-visible Particulates (MFI)", method:"Micro-Flow Imaging MFI-5200", spec:"≤6,000/container ≥10 µm; ≤600/container ≥25 µm", result:"2,340 ≥10 µm; 185 ≥25 µm — PASS" },
      { test:"Endotoxin (LAL KCA)", method:"KCA-LAL kinetic chromogenic", spec:"≤0.2 EU/mL", result:"<0.05 EU/mL — PASS" },
      { test:"Sterility (USP <71>)", method:"Membrane filtration, 14-day incubation", spec:"No growth", result:"No growth at day 14 — PASS" },
      { test:"Fill Volume / Weight", method:"Gravimetric (100% IPC during filling)", spec:"9.7–10.3 mL (10.0 ± 0.3 mL)", result:"Mean 10.1 mL, CV 0.4% — PASS" },
      { test:"Container Closure Integrity (CCI)", method:"Vacuum decay (Uson), USP <1207>", spec:"No leak detected (≤10⁻⁶ mbar·L/sec)", result:"0/100 units leaking — PASS" },
    ],
    disposition:"RELEASED — All specifications met. Lot DPL-2024-007 is approved for patient administration.",
  },
};
