// src/stability-data.js — ICH Q1A(R2) stability data

export const STABILITY_CONDITIONS = [
  {
    id: "long-term",
    label: "Long-Term",
    temp: "25°C ± 2°C",
    rh: "60% ± 5% RH",
    zone: "I/II",
    container: "Primary packaging",
    duration: "Up to 60 months",
    color: "#34D399",
    icon: "🌡️",
    description: "Supports shelf-life claim at intended storage conditions for Zone I/II markets",
    purpose: "Defines shelf life for real-world storage",
    freq_notes: "0, 3, 6, 9, 12, 18, 24, 36, 48, 60 months",
  },
  {
    id: "intermediate",
    label: "Intermediate",
    temp: "30°C ± 2°C",
    rh: "65% ± 5% RH",
    zone: "I/II",
    container: "Primary packaging",
    duration: "12 months minimum",
    color: "#F59E0B",
    icon: "🌤️",
    description: "Required when significant change at accelerated; bridges long-term and accelerated data",
    purpose: "Triggered if accelerated fails; required for Zone I/II products",
    freq_notes: "0, 6, 12 months (minimum)",
  },
  {
    id: "accelerated",
    label: "Accelerated",
    temp: "40°C ± 2°C",
    rh: "75% ± 5% RH",
    zone: "I/II",
    container: "Primary packaging",
    duration: "6 months",
    color: "#F472B6",
    icon: "🔥",
    description: "Predicts shelf life; accelerates degradation chemistry using Arrhenius kinetics",
    purpose: "Early indication of stability; supports shipping/excursion risk assessment",
    freq_notes: "0, 3, 6 months",
  },
  {
    id: "refrigerated",
    label: "Refrigerated (Long-Term)",
    temp: "5°C ± 3°C",
    rh: "Ambient humidity",
    zone: "All",
    container: "Primary packaging",
    duration: "Up to 60 months",
    color: "#38BDF8",
    icon: "❄️",
    description: "For products labeled 2–8°C storage (most biologics, vaccines, injectables)",
    purpose: "Shelf-life definition for cold-chain products",
    freq_notes: "0, 3, 6, 9, 12, 18, 24, 36, 48, 60 months",
  },
  {
    id: "refrigerated-accel",
    label: "Refrigerated (Accelerated)",
    temp: "25°C ± 2°C",
    rh: "60% ± 5% RH",
    zone: "All",
    container: "Primary packaging",
    duration: "6 months",
    color: "#A78BFA",
    icon: "⬆️",
    description: "Accelerated condition for refrigerated products; assesses temperature excursion impact",
    purpose: "Shipping & excursion assessment; early shelf-life prediction",
    freq_notes: "0, 3, 6 months",
  },
  {
    id: "frozen",
    label: "Frozen",
    temp: "-20°C ± 5°C",
    rh: "N/A",
    zone: "All",
    container: "Primary packaging",
    duration: "Up to 60 months",
    color: "#60A5FA",
    icon: "🧊",
    description: "For frozen drug substances (bulk mAb DS) and some frozen DP",
    purpose: "DS shelf-life, freeze-thaw stress assessment",
    freq_notes: "0, 3, 6, 12, 18, 24 months minimum",
  },
  {
    id: "stress-thermal",
    label: "Stress — Thermal",
    temp: "50°C–60°C",
    rh: "Variable",
    zone: "N/A",
    container: "Open container",
    duration: "2–4 weeks",
    color: "#FB923C",
    icon: "🌡️",
    description: "Forces oxidation, deamidation, aggregation; identifies thermal degradation routes",
    purpose: "Forced degradation for degradant identification and method specificity",
    freq_notes: "1, 2, 4 weeks",
  },
  {
    id: "stress-uv",
    label: "Stress — Photolytic",
    temp: "25°C",
    rh: "Ambient",
    zone: "N/A",
    container: "Open container",
    duration: "ICH Q1B exposure",
    color: "#FBBF24",
    icon: "☀️",
    description: "ICH Q1B: ≥1.2 million lux·h visible + ≥200 W·h/m² UV. Tests photosensitivity",
    purpose: "Photostability qualification per ICH Q1B; justifies packaging light protection",
    freq_notes: "Full ICH Q1B exposure achieved",
  },
  {
    id: "stress-acid",
    label: "Stress — Acid/Base",
    temp: "25°C",
    rh: "N/A",
    zone: "N/A",
    container: "Solution",
    duration: "Days to weeks",
    color: "#F87171",
    icon: "🧪",
    description: "HCl/NaOH pH extremes (pH 1–2, pH 12–13); identifies hydrolysis products",
    purpose: "Forced degradation for method specificity; regulatory requirement",
    freq_notes: "1, 3, 5, 7 days typical",
  },
  {
    id: "stress-oxidative",
    label: "Stress — Oxidative",
    temp: "25°C",
    rh: "N/A",
    zone: "N/A",
    container: "Solution",
    duration: "Days",
    color: "#C084FC",
    icon: "⚗️",
    description: "H₂O₂ (0.1–1%), t-BHP, or metal-catalyzed (Cu/Fe); identifies Met/Trp oxidation",
    purpose: "Identifies oxidation-prone residues; supports antioxidant/chelator choice",
    freq_notes: "2h, 6h, 24h typical",
  },
];

export const ICH_Q1_ZONES = [
  {
    zone: "I",
    label: "Temperate",
    countries: "UK, North Europe, Canada",
    mkt: "25°C/60% RH",
    color: "#34D399",
    description: "Annual mean kinetic temperature <15°C, mean kinetic humidity ≤45%"
  },
  {
    zone: "II",
    label: "Mediterranean/Subtropical",
    countries: "USA, Japan, EU (South), Australia",
    mkt: "25°C/60% RH",
    color: "#60A5FA",
    description: "Annual mean kinetic temperature 15–22°C; conditions support use of 25°C/60%"
  },
  {
    zone: "III",
    label: "Hot/Dry",
    countries: "Iran, Iraq, Sudan",
    mkt: "30°C/35% RH",
    color: "#F59E0B",
    description: "Annual mean kinetic temperature >22°C, humidity ≤35%"
  },
  {
    zone: "IVA",
    label: "Hot/Humid",
    countries: "Brazil, China, India (WHO)",
    mkt: "30°C/65% RH",
    color: "#F472B6",
    description: "WHO approach for tropical regions — 30°C/65% RH for long-term"
  },
  {
    zone: "IVB",
    label: "Hot/Very Humid",
    countries: "India (CDSCO), SE Asia, Africa",
    mkt: "30°C/75% RH",
    color: "#FB923C",
    description: "CDSCO requirement; most stringent zone — 30°C/75% RH for long-term"
  },
];

export const STABILITY_TESTS = [
  {
    id: "small-mol-oral",
    label: "Small Molecule — Oral Solid",
    icon: "💊",
    color: "#34D399",
    tests: [
      { test: "Assay (potency)", method: "HPLC/UV", spec: "98.0–102.0% label claim", ich: "ICH Q6A", usp: "USP <621>" },
      { test: "Related Substances", method: "HPLC gradient", spec: "Each impurity NMT 0.1–0.2%; total NMT 1%", ich: "ICH Q3B/Q6A", usp: "USP <621>" },
      { test: "Dissolution", method: "Paddle or basket (USP App II/I)", spec: "NLT 80% in 30 min (Q=75%)", ich: "ICH Q6A", usp: "USP <711>" },
      { test: "Disintegration", method: "USP App I/II basket", spec: "NMT 15 min (uncoated)", ich: "—", usp: "USP <701>" },
      { test: "Water Content", method: "KF titration", spec: "NMT X% (product-specific)", ich: "ICH Q6A", usp: "USP <921>" },
      { test: "Appearance", method: "Visual inspection", spec: "Conforms to reference standard", ich: "—", usp: "—" },
      { test: "Hardness/Friability", method: "Hardness tester / tumbling drum", spec: "Product-specific", ich: "—", usp: "USP <1217>" },
    ]
  },
  {
    id: "small-mol-inject",
    label: "Small Molecule — Injectable",
    icon: "💉",
    color: "#38BDF8",
    tests: [
      { test: "Assay (potency)", method: "HPLC/UV", spec: "95.0–105.0% label claim", ich: "ICH Q6A", usp: "USP <621>" },
      { test: "Related Substances", method: "HPLC gradient", spec: "ICH Q3B thresholds apply", ich: "ICH Q3B", usp: "USP <621>" },
      { test: "Particulate Matter", method: "Light obscuration / visual", spec: "USP <788>: ≤6000 @ ≥10µm, ≤600 @ ≥25µm per container", ich: "—", usp: "USP <788>" },
      { test: "pH", method: "Potentiometry", spec: "Product-specific range (e.g., 6.5–7.5)", ich: "—", usp: "USP <791>" },
      { test: "Osmolality", method: "Freezing point depression", spec: "270–330 mOsm/kg (isotonic)", ich: "—", usp: "USP <785>" },
      { test: "Sterility", method: "Membrane filtration / direct inoculation", spec: "No growth in 14 days", ich: "ICH Q2B", usp: "USP <71>" },
      { test: "Bacterial Endotoxins", method: "LAL kinetic chromogenic", spec: "< product-specific EU/mL limit", ich: "—", usp: "USP <85>" },
    ]
  },
  {
    id: "mab",
    label: "Monoclonal Antibody (Liquid)",
    icon: "🧬",
    color: "#A78BFA",
    tests: [
      { test: "Purity — SE-HPLC", method: "SEC-UV", spec: "NLT 95% monomer (product-specific)", ich: "ICH Q6B", usp: "USP <621>" },
      { test: "Purity — CE-SDS (NR)", method: "Capillary electrophoresis", spec: "NLT 95% intact IgG", ich: "ICH Q6B", usp: "—" },
      { test: "Charge Variants", method: "cIEF or CEX-HPLC", spec: "% main peak within ±X% of reference", ich: "ICH Q6B", usp: "—" },
      { test: "Potency (bioassay)", method: "Cell-based reporter assay", spec: "50–200% of reference standard", ich: "ICH Q6B", usp: "USP <1032>" },
      { test: "Protein Concentration", method: "A280 spectrophotometry", spec: "Target ± 10%", ich: "—", usp: "USP <1119>" },
      { test: "Subvisible Particles", method: "MFI / light obscuration", spec: "USP <787>: ≤6000 @ ≥10µm; ≤600 @ ≥25µm per container", ich: "—", usp: "USP <787>" },
      { test: "pH", method: "Potentiometry", spec: "Target ± 0.3 pH units", ich: "—", usp: "USP <791>" },
      { test: "Osmolality", method: "Freezing point depression", spec: "Target ± 10%", ich: "—", usp: "USP <785>" },
      { test: "Color/Clarity", method: "Visual + spectrophotometry", spec: "Compares to reference standard", ich: "—", usp: "USP <631>" },
      { test: "Sterility", method: "Membrane filtration", spec: "No growth in 14 days", ich: "ICH Q6B", usp: "USP <71>" },
      { test: "Endotoxin", method: "LAL kinetic chromogenic", spec: "< 0.5 EU/mL (typical IV product)", ich: "—", usp: "USP <85>" },
    ]
  },
  {
    id: "peptide",
    label: "Therapeutic Peptide",
    icon: "🔗",
    color: "#F472B6",
    tests: [
      { test: "Assay (purity)", method: "RP-HPLC", spec: "NLT 95–98% (product-specific)", ich: "ICH Q6A", usp: "USP <621>" },
      { test: "Related Peptides", method: "RP-HPLC gradient", spec: "Each impurity NMT 0.1%; total NMT 2%", ich: "ICH Q3B", usp: "USP <621>" },
      { test: "Oxidized Species", method: "RP-HPLC", spec: "NMT 1% (typical)", ich: "ICH Q6A", usp: "—" },
      { test: "Enantiomers / Racemization", method: "Chiral HPLC or peptide mapping", spec: "NMT 0.5% D-forms", ich: "—", usp: "—" },
      { test: "Water Content", method: "KF or LOD", spec: "NMT 8% (lyophilized)", ich: "—", usp: "USP <921>" },
      { test: "Residual Solvents", method: "GC headspace", spec: "ICH Q3C class limits", ich: "ICH Q3C", usp: "USP <467>" },
    ]
  },
];

export const STABILITY_TIMEPOINTS = {
  "long-term": [0, 3, 6, 9, 12, 18, 24, 36, 48, 60],
  "intermediate": [0, 6, 12],
  "accelerated": [0, 3, 6],
  "refrigerated": [0, 3, 6, 9, 12, 18, 24, 36, 48, 60],
  "refrigerated-accel": [0, 3, 6],
  "frozen": [0, 3, 6, 12, 18, 24],
  "stress-thermal": [0, 0.25, 0.5, 1, 2, 4],
  "stress-uv": ["Initial", "Post-exposure"],
  "stress-acid": [0, 1, 3, 7],
  "stress-oxidative": [0, 0.083, 0.25, 1],
};

export const SHELF_LIFE_STATS = [
  { product: "Small molecule oral", typical: "24–36 months", with_data: "Up to 60 months", storage: "25°C/60% RH" },
  { product: "Injectable solution", typical: "18–24 months", with_data: "Up to 36 months", storage: "2–8°C or 25°C" },
  { product: "Lyophilized biologic", typical: "24–36 months", with_data: "Up to 48 months", storage: "2–8°C" },
  { product: "Liquid mAb (vial)", typical: "18–24 months", with_data: "Up to 30 months", storage: "2–8°C" },
  { product: "Frozen DS (bulk mAb)", typical: "24–48 months", with_data: "Up to 60 months", storage: "-20°C to -80°C" },
  { product: "Vaccine (adjuvanted)", typical: "12–24 months", with_data: "Up to 36 months", storage: "2–8°C" },
];
