import type { ModuleContent } from '../../types/content';

export const module0: ModuleContent = {
  id: 'structure-m0',
  sectionId: 'structure',
  moduleNumber: 0,
  eyebrow: 'STRUCTURE 01',
  title: 'Overview & EU Numbering',
  lead: 'The molecular architecture of IgG antibodies and the EU index system that defines every critical residue in the constant regions.',
  tags: [
    { label: 'EU Index', color: 'amber' },
    { label: 'IgG Architecture', color: 'blue' },
    { label: 'Residue Mapping', color: 'teal' },
  ],
  stats: [
    { label: 'Molecular Weight', value: '~150 kDa' },
    { label: 'Domains', value: '12 total' },
    { label: 'Disulfide Bonds', value: '16 (IgG1)' },
    { label: 'Glycosylation Sites', value: '2 \u00d7 Asn297' },
  ],
  sections: [
    {
      type: 'card',
      title: 'IgG Architecture',
      color: 'blue',
      content:
        'IgG antibodies are ~150 kDa heterotetrameric glycoproteins composed of two identical heavy chains (~50 kDa each) and two identical light chains (~25 kDa each), linked by inter-chain disulfide bonds and non-covalent interactions. Each heavy chain contains four domains arranged linearly: VH (variable heavy) \u2192 CH1 (constant heavy 1) \u2192 hinge \u2192 CH2 \u2192 CH3. Each light chain contains two domains: VL (variable light) \u2192 CL (constant light, either \u03ba or \u03bb isotype). The molecule adopts a Y-shaped quaternary structure with two Fab arms (antigen binding) connected via a flexible hinge region to the Fc stem (effector functions). Papain cleaves above the hinge to generate two Fab fragments and one Fc fragment; pepsin cleaves below to yield F(ab\u2032)\u2082 + pFc\u2032 fragments. The 12 total immunoglobulin domains (2\u00d7VH, 2\u00d7VL, 2\u00d7CH1, 2\u00d7CL, 2\u00d7CH2, 2\u00d7CH3) each adopt the characteristic \u03b2-sandwich immunoglobulin fold of ~110 residues stabilised by a single intra-domain disulfide bond.',
    },
    {
      type: 'card',
      title: 'EU Numbering System',
      color: 'amber',
      content:
        'The EU numbering system is based on the amino acid sequence of the human IgG1 myeloma protein "Eu" characterised by Gerald Edelman and colleagues in 1969 (Edelman et al., Proc. Natl. Acad. Sci. USA 63:78-85, 1969). EU numbering assigns a fixed position number to each residue in the constant regions (CH1, hinge, CH2, CH3) based on alignment to this reference protein. Because the EU protein was fully sequenced and structurally characterised early, it became the de facto standard for describing all Fc mutations in therapeutic antibody engineering. Key features: (1) Position numbers are consistent across all IgG subclasses despite sequence differences; (2) Gaps are inserted where necessary to maintain alignment; (3) The system extends from approximately position 118 (start of CH1) through position 447 (C-terminus of CH3 in IgG1); (4) All major Fc engineering mutations in published literature and patent filings use EU numbering exclusively.',
    },
    {
      type: 'code',
      title: 'EU Position Reference \u2014 Critical Fc Residues',
      language: 'text',
      code: [
        '\u2550\u2550\u2550 HINGE REGION \u2550\u2550\u2550',
        'C226, C229          Inter-heavy chain disulfides (IgG1)',
        'S228               IgG4 Fab-arm exchange site (\u2192P228 stabilisation)',
        '',
        '\u2550\u2550\u2550 CH2 DOMAIN \u2014 Fc\u03b3R CONTACT FACE \u2550\u2550\u2550',
        'L234, L235          Lower hinge \u2014 primary Fc\u03b3R contact (LALA target)',
        'G236                Fc\u03b3RIIIa contact (GASDALIE target)',
        'P238                Fc\u03b3RIIb selectivity',
        'S239                ADCC enhancement (DE: S239D)',
        'D265                Fc\u03b3R binding; aglycosylation phenocopy when mutated',
        'N297                Conserved N-linked glycosylation site (NxT sequon)',
        'A330                GASDALIE target (A330L)',
        'I332                ADCC enhancement (DE: I332E; GASDALIE: I332E)',
        'P329                C1q proline sandwich (LALA-PG: P329G)',
        'P331                C1q contact face',
        '',
        '\u2550\u2550\u2550 CH2/CH3 \u2014 FcRn BINDING \u2550\u2550\u2550',
        'M252                FcRn contact (YTE: M252Y)',
        'I253                FcRn contact \u2014 pH sensor region',
        'S254                FcRn contact (YTE: S254T)',
        'T256                FcRn contact (YTE: T256E)',
        'H310                FcRn pH sensor \u2014 His protonation at pH 6.0',
        '',
        '\u2550\u2550\u2550 CH3 DOMAIN \u2550\u2550\u2550',
        'T366                KiH knob (T366W) or hole (T366S)',
        'L368                KiH hole (L368A)',
        'K370                CH3-CH3 dimer interface',
        'T394                KiH hole variant',
        'Y407                KiH hole (Y407V/A)',
        'K409                Strand-exchange in IgG4',
        'M428                FcRn contact (LS: M428L)',
        'H433                Protein A & FcRn binding',
        'N434                FcRn contact (LS: N434S)',
        'H435                FcRn pH sensor & Protein A (R435 in IgG3 \u2192 weak ProA)',
        'Y436                FcRn & Protein A contact',
      ].join('\n'),
    },
    {
      type: 'table',
      title: 'IgG Subclass Comparison',
      headers: [
        'Property',
        'IgG1',
        'IgG2',
        'IgG3',
        'IgG4',
      ],
      rows: [
        ['Molecular weight (kDa)', '~146', '~146', '~170', '~146'],
        ['Hinge length (residues)', '15', '12', '62 (extended)', '12'],
        ['Inter-HC disulfides', '2', '4', '11', '2'],
        ['Total disulfides', '16', '18', '27', '16'],
        ['Serum half-life (days)', '21', '21', '7-21', '21'],
        ['Serum abundance (%)', '60-70', '20-25', '5-8', '1-4'],
        ['Fc\u03b3RI binding', '+++', '\u2212', '++++', '++'],
        ['Fc\u03b3RIIa binding', '++', '+', '++', '+'],
        ['Fc\u03b3RIIIa binding', '++', '\u2212', '++', '+/\u2212'],
        ['C1q / CDC', '++', '+', '+++', '\u2212'],
        ['ADCC activity', '++', '\u2212/+', '++', '+/\u2212'],
        ['Protein A binding', 'Strong', 'Strong', 'Weak (R435)', 'Strong'],
        ['Fab-arm exchange', 'No', 'No', 'No', 'Yes (S228)'],
        ['Clinical examples', 'Trastuzumab, Rituximab', 'Panitumumab, Denosumab', 'Rare (clearance)', 'Nivolumab, Pembrolizumab'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'Relationship Between Numbering Schemes',
      color: 'teal',
      content:
        'Three major numbering systems coexist in antibody science, each serving a specific domain of use. (1) EU numbering (Edelman 1969): Standard for constant regions (CH1/hinge/CH2/CH3). Every Fc engineering mutation in the field is described in EU numbers. Example: N297 (glycosylation site), L234A/L235A (LALA mutations), M252Y/S254T/T256E (YTE half-life extension). (2) Kabat numbering (Wu & Kabat 1970, updated 1991): Standard for variable regions (VH, VL). Based on sequence variability analysis across thousands of antibody sequences. Defines CDR boundaries: HCDR1 H31-H35B, HCDR2 H50-H65, HCDR3 H95-H102, LCDR1 L24-L34, LCDR2 L50-L56, LCDR3 L89-L97. Uses letter suffixes for insertions (e.g., H52A, H52B). (3) IMGT numbering (Lefranc 1997): Standardised across the entire immunoglobulin superfamily. Fixed 128 positions per domain with gaps at defined positions. Primary use in germline gene databases and V-gene assignment. These systems are NOT interchangeable \u2014 the same physical residue has different position numbers in each scheme.',
    },
    {
      type: 'callout',
      title: 'Industry Practice \u2014 Numbering Convention',
      variant: 'info',
      content:
        'In industry practice, ALL Fc mutations are described using EU numbering. Variable region positions use Kabat numbering. Never mix these in CMC documentation. When writing regulatory submissions (e.g., CTD Module 3.2.S.1.2 Structure), always state explicitly: "Residue positions in the constant region are designated according to EU index numbering (Edelman et al., 1969). Variable region positions follow the Kabat numbering convention (Kabat et al., 1991)." Failure to specify the numbering scheme creates ambiguity that regulatory reviewers will flag as a deficiency.',
    },
    {
      type: 'bullets',
      title: 'CMC Implications of IgG Architecture',
      items: [
        'Domain stability hierarchy (CH2 < Fab < CH3) directly determines which domain unfolds first under thermal stress and drives aggregation nucleation \u2014 critical for formulation development and accelerated stability study design.',
        'The hinge region is the most protease-susceptible segment of the molecule. IgG1 hinge clipping by host cell proteases (e.g., matrix metalloproteinases, cathepsins) during cell culture is a major fragmentation pathway monitored by non-reducing CE-SDS.',
        'The Asn297 glycosylation site in CH2 is essential for Fc\u03b3R binding and structural integrity of the CH2 domain. Aglycosylation (e.g., by tunicamycin treatment or Asn297 mutation) reduces CH2 Tm by 5-10\u00b0C and abolishes effector functions.',
        'Inter-chain disulfide bond heterogeneity (particularly incomplete disulfide formation in the hinge) generates size variants visible by non-reducing CE-SDS. IgG2 disulfide isoforms (A, B, A/B) are a well-characterised source of structural heterogeneity.',
        'VH-VL and CH1-CL domain pairing interfaces are non-covalent in the intact IgG but stabilised by an inter-chain disulfide (HC C220 \u2013 LC C214 in IgG1). Loss of this disulfide generates free light chain species.',
        'Protein A binds at the CH2-CH3 interface (involving H433, H435, Y436), which is the basis for platform purification (Protein A chromatography). IgG3 has R435 instead of H435, resulting in weak Protein A binding and requiring alternative capture strategies.',
      ],
    },
    {
      type: 'table',
      title: 'Key EU Positions by Functional Category',
      headers: ['Function', 'EU Positions', 'Engineering Examples'],
      rows: [
        ['Fc\u03b3R binding (effector)', 'L234, L235, G236, P238, S239, D265, A330, I332', 'LALA (L234A/L235A), DE (S239D/I332E), GASDALIE (G236A/S239D/A330L/I332E)'],
        ['C1q / CDC', 'K322, P329, P331, D270', 'LALA-PG (L234A/L235A/P329G), K322A'],
        ['FcRn / half-life', 'M252, I253, S254, T256, H310, M428, N434, H435', 'YTE (M252Y/S254T/T256E), LS (M428L/N434S), YD (M252Y/T256D)'],
        ['Protein A binding', 'H433, H435, Y436', 'H435R abolishes binding (natural in IgG3)'],
        ['Glycosylation', 'N297 (NxT sequon at 297-299)', 'N297A/Q (aglycosylation), T299A (sequon disruption)'],
        ['Heterodimerisation', 'T366, L368, Y407, K409, D399, K392', 'KiH (T366W + T366S/L368A/Y407V), DD-KK charge pairs'],
        ['Hinge disulfides', 'C226, C229 (IgG1); C222 (IgG4)', 'S228P (IgG4 stabilisation)'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'The Fab Fragment \u2014 Structural Organisation',
      color: 'purple',
      content:
        'Each Fab arm (~50 kDa) consists of four immunoglobulin domains: VH-CH1 from the heavy chain paired with VL-CL from the light chain. The VH-VL pair forms the Fv (variable fragment) responsible for antigen recognition, while CH1-CL provides structural support and contains the inter-chain disulfide bond (HC C220 to LC C214 in IgG1). The elbow angle between Fv and CH1-CL varies from ~115\u00b0 to ~180\u00b0 and can influence antigen accessibility and Fab crystallisation. Within the Fv, the six CDR loops (3 from VH, 3 from VL) are arranged at the tips of the \u03b2-sandwich domains, forming the antigen-binding paratope. The VH domain contributes HCDR1 (H31-H35B, Kabat), HCDR2 (H50-H65), and HCDR3 (H95-H102) \u2014 with HCDR3 being the most structurally diverse loop, encoded by V-D-J recombination. The framework regions (FR1-FR4 in each variable domain) provide the structural scaffold for CDR loop display.',
    },
    {
      type: 'card',
      title: 'The Fc Region \u2014 Effector Platform',
      color: 'green',
      content:
        'The Fc region (~50 kDa homodimer) comprises the hinge, CH2, and CH3 domains of both heavy chains. Unlike the Fab, the Fc has no variable sequences \u2014 its function is determined entirely by the constant region subclass and post-translational modifications. CH2 domains do not make direct protein-protein contacts with each other; instead, they are held apart by the N297 glycans, which fill the inter-CH2 space and stabilise the open conformation required for Fc\u03b3R engagement. The CH3 domains form a tight homodimeric interface (~2000 \u00c5\u00b2 buried surface area) that is the most thermally stable part of the molecule (Tm ~82-85\u00b0C). The CH2-CH3 junction contains the FcRn binding site (M252, I253, S254, T256, H310, H433, N434, H435) and the Protein A binding site (overlapping at H433, H435, Y436). Fc effector functions include: ADCC (via Fc\u03b3RIIIa binding at lower hinge/CH2), CDC (via C1q binding at CH2), ADCP (via Fc\u03b3RIIa), and recycling/half-life (via FcRn at CH2-CH3 interface).',
    },
    {
      type: 'callout',
      title: 'Disulfide Bond Inventory \u2014 IgG1',
      variant: 'info',
      content:
        'A complete IgG1 molecule contains 16 disulfide bonds: 12 intra-domain (one per Ig domain \u00d7 12 domains, stabilising each \u03b2-sandwich fold), 2 inter-chain HC-LC bonds (C220-C214), and 2 inter-HC hinge bonds (C226-C226\u2032, C229-C229\u2032). During bioprocessing, incomplete disulfide bond formation in the hinge region is a common source of structural micro-heterogeneity. Non-reducing CE-SDS resolves these as partial species (e.g., H2L, H2, HL). Disulfide bond shuffling under mildly reducing conditions (e.g., in the presence of free thiols from cell lysis) can generate disulfide-linked aggregates. Monitoring disulfide bond integrity is part of the primary structure characterisation required in CTD Module 3.2.S.3.1.',
    },
    {
      type: 'bullets',
      title: 'Analytical Methods for Architecture Characterisation',
      items: [
        'Intact mass analysis by ESI-TOF or Orbitrap MS: Confirms total molecular weight, detects major glycoforms (G0F, G1F, G2F), resolves C-terminal Lys clipping variants.',
        'Reduced/deglycosylated mass: Separates heavy chain (~50 kDa) and light chain (~25 kDa) for individual chain mass confirmation.',
        'Non-reducing CE-SDS: Resolves intact IgG (~150 kDa), fragments (Fab ~50 kDa, Fc ~50 kDa, half-antibody ~75 kDa, HC ~50 kDa, LC ~25 kDa).',
        'Peptide mapping by RP-HPLC-MS/MS: Complete sequence coverage (>95%) with identification of all PTMs, disulfide bond assignments, and N/C-terminal processing.',
        'Size-exclusion chromatography (SEC): Quantifies monomer, dimer, higher-molecular-weight species (HMWS), and fragments. Industry specification typically \u226595% monomer.',
        'Differential scanning calorimetry (DSC) or nanoDSF: Domain Tm values identify CH2 (~60-65\u00b0C), Fab (~65-80\u00b0C), CH3 (~82-85\u00b0C) transitions.',
      ],
    },
  ],
  mentorQuestions: [
    'Why is EU numbering the industry standard for Fc engineering, and what would go wrong if we used Kabat numbering for Fc positions?',
    'How does the domain architecture of IgG influence the order of thermal unfolding events you see in a DSC thermogram?',
    'If you were reviewing a biosimilar\'s analytical comparability package, which structural features would you prioritise for head-to-head comparison?',
  ],
};
