import type { ModuleContent } from '../../types/content';

export const module5: ModuleContent = {
  id: 'structure-m5',
  sectionId: 'structure',
  moduleNumber: 5,
  eyebrow: 'STRUCTURE 06',
  title: 'VH-VL Interface',
  lead: 'The non-covalent packing between VH and VL domains \u2014 the structural determinant of Fv stability, antigen binding geometry, and humanisation success.',
  tags: [
    { label: 'Fv Stability', color: 'blue' },
    { label: 'Humanisation', color: 'purple' },
    { label: 'Vernier Zone', color: 'amber' },
  ],
  stats: [
    { label: 'Interface Area', value: '~700 \u00c5\u00b2' },
    { label: 'Key Packing Residues', value: '~10 per domain' },
    { label: 'VH-VL Angle Range', value: '\u00b150\u00b0' },
    { label: 'Vernier Residues', value: '~20' },
  ],
  sections: [
    {
      type: 'card',
      title: 'VH-VL Interface Architecture',
      color: 'blue',
      content:
        'The VH-VL interface is a non-covalent domain-domain interaction that stabilises the Fv (variable fragment) and positions the six CDR loops for antigen recognition. Unlike the CH1-CL interface, which is reinforced by an inter-chain disulfide bond (C220-C214 in IgG1), the VH-VL interaction relies entirely on hydrophobic packing and hydrogen bonds. The interface buries approximately 700 \u00c5\u00b2 of solvent-accessible surface area per domain (~1400 \u00c5\u00b2 total), which is relatively modest for a protein-protein interaction. This buried surface area consists primarily of hydrophobic residues from the inner faces of each \u03b2-sandwich, supplemented by 2-4 hydrogen bonds at the periphery. The interface is formed by residues from framework regions FR2 and FR4 of both VH and VL, plus contributions from the base of certain CDR loops (particularly HCDR3 and LCDR3). The modest size of this interface is functionally significant: it provides sufficient stability for antigen binding while allowing the conformational flexibility needed for induced-fit binding. However, it also means the VH-VL association is the weakest domain-domain interaction in the intact IgG, making it the primary vulnerability in engineered formats (scFv, diabody) that lack the CH1-CL stabilising scaffold.',
    },
    {
      type: 'table',
      title: 'Key VH Packing Residues at the Interface',
      headers: ['Position (Kabat)', 'Consensus Residue', 'Role', 'Conservation (%)'],
      rows: [
        ['VH L37', 'Leu (sometimes Val)', 'Hydrophobic core packing against VL', '>90% hydrophobic'],
        ['VH Q39', 'Gln', 'H-bond to VL Q38; critical interface contact', '>85% Gln'],
        ['VH V44', 'Val (sometimes Gly/Leu)', 'Core hydrophobic packing at interface centre', '>90% small hydrophobic'],
        ['VH G45', 'Gly', 'Allows close VH-VL approach; no side chain clash', '>95% Gly'],
        ['VH L47', 'Leu (sometimes Trp)', 'Deep hydrophobic contact; mutation here destabilises Fv by 5-15\u00b0C', '>85% Leu/Trp'],
        ['VH Y91', 'Tyr', 'Edge of interface; H-bond potential', '>70% Tyr/Phe'],
        ['VH W103', 'Trp', 'Highly conserved anchor at base of HCDR3; packs against VL', '>98% Trp'],
        ['VH F/Y100+', 'Phe/Tyr (in HCDR3 base)', 'CDR3 base stabilisation; context-dependent', 'Variable'],
      ],
      sortable: true,
    },
    {
      type: 'table',
      title: 'Key VL Packing Residues at the Interface',
      headers: ['Position (Kabat)', 'Consensus Residue', 'Role', 'Conservation (%)'],
      rows: [
        ['VL Y36', 'Tyr', 'Aromatic packing against VH hydrophobic residues', '>80% Tyr/Phe'],
        ['VL Q38', 'Gln', 'H-bond to VH Q39; symmetric interface contact', '>85% Gln'],
        ['VL V44', 'Val (sometimes Pro)', 'Core packing at interface centre', '>70% Val/Pro'],
        ['VL L46', 'Leu', 'Hydrophobic core contact against VH L47 region', '>85% Leu'],
        ['VL P44', 'Pro (in some \u03ba chains)', 'cis-Pro conformation at interface; alters VH-VL angle', 'Variable (\u03ba vs \u03bb)'],
        ['VL F87', 'Phe (VL-\u03ba) or Tyr (VL-\u03bb)', 'Interface edge; aromatic-aromatic stacking', '>75% Phe/Tyr'],
        ['VL F98', 'Phe', 'Base of LCDR3; packs against VH W103', '>80% Phe/Trp'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'VH-VL Packing Angle',
      color: 'teal',
      content:
        'The relative orientation of VH and VL domains \u2014 the VH-VL packing angle \u2014 varies by approximately 100\u00b0 across the known structural database of antibodies. This angle is defined by the relative rotation of the two \u03b2-sheet planes and profoundly influences the shape and electrostatic landscape of the antigen-binding site. A "closed" packing angle brings CDR-H3 and CDR-L3 closer together, creating a narrow and deep binding groove (typical for peptide-binding antibodies). An "open" angle creates a flatter binding surface (common for protein-binding antibodies). The packing angle is primarily determined by: (1) the identity of key framework residues at the interface (particularly VH positions 39, 44, 45, 47 and VL positions 38, 44, 46, 87); (2) the VH and VL germline gene family combination (e.g., VH1 family tends to pair with V\u03baI/III; VH3 is the most versatile pairer); (3) CDR loop conformations, particularly HCDR3 and LCDR3 base residues. Computational measurement of the packing angle is performed using the ABangle server (Dunbar et al., 2013) or the older ball-and-socket model (Abhinandan & Martin, 2010). In humanisation, a significant mismatch between the donor VH-VL angle and the acceptor framework VH-VL angle is a red flag for loss of binding affinity.',
    },
    {
      type: 'card',
      title: 'The Vernier Zone \u2014 CDR-Supporting Framework Residues',
      color: 'amber',
      content:
        'The Vernier zone was defined by Foote and Winter (J. Mol. Biol. 1992) as the set of framework residues that support CDR loop conformations without directly contacting antigen. These residues form the "platform" on which the CDR loops are displayed and are named by analogy with the vernier scale on a caliper \u2014 they make fine adjustments to CDR loop positioning. Vernier zone residues in VH (Kabat numbering): 2, 4, 27, 28, 29, 30, 36, 47, 48, 49, 67, 69, 71, 73, 78, 93, 94. Vernier zone residues in VL (Kabat numbering): 2, 4, 35, 36, 46, 47, 48, 49, 64, 66, 68, 69, 71, 98. During CDR grafting (humanisation), if the human acceptor framework has different residues at Vernier positions compared to the donor (mouse, rabbit, etc.), the CDR loops may adopt incorrect conformations, leading to loss of binding affinity. The standard rescue strategy is to "back-mutate" critical Vernier residues from the human acceptor sequence to the parental donor sequence. This is the single most important step in humanisation troubleshooting and accounts for 60-80% of successful humanisation rescues.',
    },
    {
      type: 'code',
      title: 'Vernier Zone Residue Map',
      language: 'text',
      code: [
        'VH VERNIER ZONE (Kabat numbering)',
        '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550',
        'FR1:  2, 4                      N-terminal packing',
        'FR1:  27, 28, 29, 30            HCDR1 base support',
        'FR2:  36                        Core Trp neighbour',
        'FR2:  47, 48, 49                VH-VL interface / HCDR2 base',
        'FR3:  67, 69                    HCDR2 support (\u201cH69 switch\u201d)',
        'FR3:  71, 73                    HCDR1/2 support',
        'FR3:  78                        HCDR1 support (VH1/VH3 differ)',
        'FR3:  93, 94                    HCDR3 base support',
        '',
        'VL VERNIER ZONE (Kabat numbering)',
        '\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550',
        'FR1:  2, 4                      N-terminal packing',
        'FR2:  35, 36                    LCDR1 support / core packing',
        'FR2:  46, 47, 48, 49            VH-VL interface / LCDR2 support',
        'FR3:  64, 66, 68, 69            LCDR2 support',
        'FR3:  71                        LCDR1/3 platform',
        'FR3:  98                        LCDR3 base (packs against VH W103)',
        '',
        'CRITICAL: Positions VH 47, 48, 69, 71, 78 are the most',
        'frequently back-mutated during humanisation.',
      ].join('\n'),
    },
    {
      type: 'card',
      title: 'Humanisation \u2014 VH-VL Interface Considerations',
      color: 'purple',
      content:
        'CDR grafting humanisation transfers the 6 CDR loops from a non-human donor antibody onto human germline-derived framework regions. Success depends critically on preserving the VH-VL interface geometry. The humanisation workflow involves: (1) Select human acceptor frameworks with highest FR sequence identity to the donor (typically using IgBLAST or IMGT/V-QUEST against human germline); (2) Graft CDR loops (typically Kabat-defined) onto the human FR scaffold; (3) Build homology model of the grafted construct; (4) Identify Vernier zone residues where the human and donor sequences differ; (5) Assess the predicted impact of each difference on CDR loop conformation and VH-VL packing; (6) Create a panel of back-mutation variants, from minimal (only the most critical Vernier positions) to maximal (all differing Vernier positions). The risk of humanisation failure is highest when: (a) the donor VH-VL angle differs significantly from the acceptor; (b) the donor uses an unusual germline combination not represented in common human germline families; (c) HCDR3 is unusually long (>20 residues) and requires extensive framework support. Modern approaches (humanness scoring by T20, Hu-mAb framework library screening) aim to reduce back-mutations to the minimum needed, as each non-human residue is a potential immunogenicity risk.',
    },
    {
      type: 'callout',
      title: 'Interface Stability \u2014 Critical for Developability',
      variant: 'warning',
      content:
        'During humanisation, always check VH-VL interface residues for conservation. A single mutation at a packing position (e.g., VH L47 \u2192 F47) can reduce Fv thermal stability by 5-15\u00b0C and increase aggregation propensity. The VH position 47 is particularly notorious: Leu47 (common in many mouse VH genes) provides optimal packing against VL, while some human VH3 frameworks have Trp47 at this position. The Leu\u2192Trp substitution is generally tolerated (sometimes stabilising), but Leu\u2192 smaller residues (Ala, Val) or charged residues (Arg, Lys) at position 47 can be devastating. Always measure Fv stability experimentally (by DSC or nanoDSF of Fab fragment) for each humanisation variant.',
    },
    {
      type: 'bullets',
      title: 'Developability Risks from Weak VH-VL Interface',
      items: [
        'scFv instability: In single-chain Fv (scFv) format, VH and VL are connected by a flexible linker (typically (G\u2084S)\u2083). Without the stabilising CH1-CL scaffold, the VH-VL interface is the sole source of domain association. Weak interfaces (Kd > 10 \u00b5M) lead to domain opening, linker-mediated aggregation, and loss of activity. scFv half-life in solution can be as short as hours for poorly pairing VH-VL combinations.',
        'Domain separation and aggregation: Under thermal or mechanical stress, VH-VL dissociation exposes hydrophobic interface residues (particularly VH W103 and surrounding hydrophobic core), nucleating aggregation. This is the primary aggregation pathway for Fab fragments and scFvs at temperatures below the domain Tm.',
        'Bispecific antibody challenges: Bispecific formats (BiTE, DVD-Ig, CrossMab) often place VH-VL pairs in non-native contexts (e.g., as scFv fusions to Fc). Weak VH-VL interfaces in one arm can compromise the stability of the entire bispecific construct.',
        'Measurement by DSC/nanoDSF: The Fv unfolding transition in a DSC thermogram of the intact IgG or Fab fragment reports on VH-VL + intra-domain stability. An unusually low Fab Tm (<60\u00b0C) suggests VH-VL interface weakness and should trigger engineering intervention.',
        'DLS kD measurement: The interaction parameter kD (from dynamic light scattering concentration series) can reveal self-association driven by exposed VH-VL interface hydrophobic patches. A negative kD (attractive self-interaction) is a red flag.',
      ],
    },
    {
      type: 'card',
      title: 'Engineered Disulfide Stabilisation of VH-VL',
      color: 'green',
      content:
        'For formats that lack the CH1-CL disulfide bond (scFv, Fv, diabody, BiTE), engineered disulfide bonds can dramatically stabilise the VH-VL interface. The most widely validated positions for an inter-domain disulfide are VH C44 \u2013 VL C100 (Kabat numbering; also described as VH44C-VL100C), first described by Reiter et al. (1996). This disulfide increases Fv Tm by 10-20\u00b0C, improves serum stability, and reduces aggregation during manufacturing. Alternative positions include VH C105 \u2013 VL C43 and VH C106 \u2013 VL C57, though these are less commonly used. The engineering protocol involves: (1) Introduce Cys mutations at the target positions; (2) Express and purify the construct; (3) Confirm disulfide formation by non-reducing SDS-PAGE and mass spectrometry; (4) Assess stability improvement by DSC, SEC (monomer retention at 40\u00b0C), and binding assay. Approximately 80-90% of scFvs show improved stability with the VH44C-VL100C disulfide, though in rare cases the mutation perturbs CDR3 conformation and reduces binding. The engineered disulfide is now standard practice for scFv-based components of bispecific antibodies (e.g., in BiTE and tandem scFv-Fc formats).',
    },
    {
      type: 'table',
      title: 'VH-VL Interface \u2014 Comparison Across Antibody Formats',
      headers: ['Format', 'VH-VL Interface', 'Stabilising Elements', 'Interface Risk'],
      rows: [
        ['Intact IgG (H\u2082L\u2082)', 'VH-VL + CH1-CL', 'CH1-CL disulfide (C220-C214), elbow angle constraints', 'Low \u2014 fully supported'],
        ['Fab', 'VH-VL + CH1-CL', 'CH1-CL disulfide, domain-domain contacts', 'Low \u2014 well stabilised'],
        ['scFv', 'VH-VL only', '(G\u2084S)\u2083 linker; no disulfide unless engineered', 'High \u2014 prone to aggregation'],
        ['Diabody', 'VH-VL cross-chain', 'Short linker (5-residue) forces inter-chain pairing', 'Moderate \u2014 kinetic trap'],
        ['VHH / Nanobody', 'No VL \u2014 single domain', 'Extended FR2 hydrophobic patch mutated to hydrophilic', 'N/A \u2014 no interface'],
        ['scFv-Fc', 'VH-VL + Fc scaffold', 'scFv stability determines overall molecular stability', 'Moderate \u2014 scFv is weak link'],
        ['BiTE (tandem scFv)', 'Two VH-VL pairs in series', 'No interdomain support between the two scFvs', 'High \u2014 both scFvs must be stable'],
        ['DVD-Ig', 'Outer VH-VL + inner VH-VL', 'Inner Fv stabilised by IgG scaffold; outer Fv less supported', 'Moderate \u2014 outer Fv at risk'],
      ],
    },
    {
      type: 'callout',
      title: 'VHH/Nanobody \u2014 The Exception That Proves the Rule',
      variant: 'info',
      content:
        'Camelid VHH domains (nanobodies) naturally lack a VL partner. They achieve stability without the VH-VL interface by mutating the hydrophobic residues that normally form the interface (VH positions 37, 44, 45, 47) to hydrophilic residues (e.g., Phe37\u2192Tyr, Gly44\u2192Glu, Leu45\u2192Arg, Trp47\u2192Gly). These "hallmark" VHH substitutions prevent aggregation of the exposed former interface. Additionally, VHH domains often have an extended CDR3 that folds back over the former VL-facing surface, providing additional solvent protection. For CMC scientists, VHH-based therapeutics (e.g., caplacizumab) present a different developability profile: no VH-VL interface concerns, but higher susceptibility to renal clearance due to small size (~15 kDa) and potential aggregation via CDR-mediated self-association.',
    },
    {
      type: 'table',
      title: 'Key VH Positions Frequently Back-Mutated in Humanisation',
      headers: ['VH Position (Kabat)', 'Structural Role', 'Common Issue', 'Back-Mutation Frequency'],
      rows: [
        ['H47 (Leu/Trp)', 'Core VH-VL packing', 'Mouse Leu \u2192 human Trp; usually tolerated but check', '~25%'],
        ['H48 (Ile/Met/Val)', 'HCDR2 base support', 'Size difference impacts HCDR2 positioning', '~15%'],
        ['H67 (Val/Ile/Phe)', 'HCDR2 backbone support', 'Affects HCDR2 conformation via packing', '~20%'],
        ['H69 (Leu/Ile/Met)', 'HCDR2 support (\u201cH69 switch\u201d)', 'Key determinant of HCDR2 canonical structure', '~40%'],
        ['H71 (Val/Arg/Lys)', 'HCDR1 and HCDR2 platform', 'Arg/Lys vs Val has major impact on CDR1 conformation', '~35%'],
        ['H73 (Asp/Asn/Thr)', 'HCDR1 support', 'H-bond network with CDR1 base', '~20%'],
        ['H78 (Ala/Val/Leu)', 'HCDR1 support', 'Size difference affects CDR1 loop packing', '~15%'],
        ['H93 (Ala/Val)', 'HCDR3 base anchor', 'Directly supports HCDR3 N-terminal stem', '~30%'],
        ['H94 (Arg/Lys/Ser)', 'HCDR3 base anchor', 'H-bond or charge interaction with HCDR3', '~25%'],
      ],
      sortable: true,
    },
  ],
  mentorQuestions: [
    'Why is VH position 47 considered critical for humanisation success?',
    'How would you assess VH-VL interface stability during developability assessment of a new candidate?',
    'What analytical methods would reveal a weakened VH-VL interface in a therapeutic mAb?',
  ],
};
