import type { ModuleContent } from '../../types/content';

export const module3: ModuleContent = {
  id: 'structure-m3',
  sectionId: 'structure',
  moduleNumber: 3,
  eyebrow: 'STRUCTURE 04',
  title: 'CDR Loops & Chemical Liabilities',
  lead: 'The six complementarity-determining regions that define antigen specificity \u2014 and the chemical degradation hotspots that challenge CMC development.',
  tags: [
    { label: 'Kabat Numbering', color: 'blue' },
    { label: 'PTM Hotspots', color: 'red' },
    { label: 'Developability', color: 'amber' },
  ],
  stats: [
    { label: 'CDR Loops', value: '6 total' },
    { label: 'HCDR3 Range', value: '3-30+ residues' },
    { label: 'Common Liability', value: 'Asn deamidation' },
    { label: 'Key Standard', value: 'Kabat 1991' },
  ],
  sections: [
    {
      type: 'table',
      title: 'CDR Loop Definitions (Kabat Numbering)',
      headers: ['CDR', 'Kabat Positions', 'Typical Length', 'Structural Role', 'Diversity Source'],
      rows: [
        ['LCDR1', 'L24\u2013L34', '10-17 residues', 'Antigen contact; canonical structures', 'V\u03ba/V\u03bb germline'],
        ['LCDR2', 'L50\u2013L56', '7 residues', 'Minor antigen contact; framework-supported', 'V\u03ba/V\u03bb germline'],
        ['LCDR3', 'L89\u2013L97', '7-11 residues', 'Antigen contact; shaped by V-J recombination', 'V-J junction'],
        ['HCDR1', 'H31\u2013H35B', '5-7 residues', 'Antigen contact; canonical structures', 'VH germline'],
        ['HCDR2', 'H50\u2013H65', '16-19 residues', 'Antigen contact; includes hotspot positions', 'VH germline + SHM'],
        ['HCDR3', 'H95\u2013H102', '3-30+ residues', 'Primary antigen contact; most diverse loop', 'V-D-J junction + SHM'],
      ],
      sortable: true,
    },
    {
      type: 'card',
      title: 'HCDR3 \u2014 The Most Diverse Antibody Loop',
      color: 'blue',
      content:
        'HCDR3 is the most structurally and sequentially diverse loop in the antibody repertoire, ranging from 3 to over 30 residues in length. This extraordinary diversity arises from the combinatorial and junctional mechanisms of V-D-J recombination: (1) ~27 D gene segments contribute the core of HCDR3; (2) D segments can be read in all three reading frames and from both strands; (3) P-nucleotide addition (palindromic fill-in) adds 1-2 bases at coding ends; (4) N-nucleotide addition by terminal deoxynucleotidyl transferase (TdT) inserts 0-15 random bases at V-D and D-J junctions; (5) Exonuclease trimming removes bases from the coding ends. The result is a loop that is essentially unrestricted in both sequence and length. Unlike CDR1 and CDR2 loops (which adopt a limited repertoire of canonical structures defined by key residues at specific positions), HCDR3 has no canonical structures \u2014 it is too diverse for classification. In therapeutic antibodies, HCDR3 is typically 10-15 residues and often dominates the antigen-binding interface, contributing 40-70% of the total binding energy. During humanisation, HCDR3 is always transferred intact from the parental antibody, as even single mutations can abolish binding.',
    },
    {
      type: 'card',
      title: 'Canonical Structures \u2014 Chothia Classification',
      color: 'teal',
      content:
        'Chothia and Lesk (1987) discovered that CDR loops CDR-L1, CDR-L2, CDR-L3, CDR-H1, and CDR-H2 adopt a limited number of backbone conformations (canonical structures) determined by the identity of key residues at specific positions. For example, CDR-L1 has ~7 canonical classes, determined by loop length and residues at positions L2, L25, L29, L30, L33, L71 (Chothia numbering). CDR-H1 has ~4 canonical classes determined by loop length and residues at H26, H27, H29, H34. CDR-H2 has ~4 canonical classes. This classification enables structure prediction from sequence alone for 5 of the 6 CDR loops with high accuracy (backbone RMSD < 1.5 \u00c5 for canonical members). Computational tools such as SCALOP (Canonical Loop Prediction), ABodyBuilder, and RosettaAntibody use canonical structure assignment as the first step in antibody homology modelling. For CMC scientists, canonical structure knowledge is important because the loop conformation determines the solvent accessibility of chemical liability motifs \u2014 a buried NG motif deamidates much more slowly than a solvent-exposed one.',
    },
    {
      type: 'table',
      title: 'Chemical Liability Hotspots by CDR Loop',
      headers: ['CDR', 'Position (Kabat)', 'Motif', 'Modification', 'Typical Risk Level'],
      rows: [
        ['HCDR1', 'H34 (some germlines)', 'Met', 'Oxidation \u2192 Met(O)', 'Medium \u2014 if solvent-exposed'],
        ['HCDR2', 'H54-H55', 'Asn-Gly (NG)', 'Deamidation \u2192 Asp/isoAsp + succinimide', 'Very High \u2014 fastest deamidation rate'],
        ['HCDR2', 'H55-H56', 'Asp-Gly (DG)', 'Isomerisation \u2192 isoAsp', 'High'],
        ['HCDR2', 'H54-H55', 'Asn-Ser (NS)', 'Deamidation \u2192 Asp/isoAsp', 'High'],
        ['HCDR3', 'Variable', 'Asp-Gly (DG)', 'Isomerisation \u2192 isoAsp', 'High \u2014 at CDR tip'],
        ['HCDR3', 'Variable', 'Trp', 'Oxidation \u2192 kynurenine/hydroxytryptophan', 'Medium-High'],
        ['HCDR3', 'Variable', 'Asn-Gly (NG)', 'Deamidation', 'Very High if present'],
        ['LCDR1', 'L30-L31', 'Asn-Ser (NS)', 'Deamidation', 'High'],
        ['LCDR1', 'L32', 'Asp', 'Isomerisation (if followed by small residue)', 'Medium'],
        ['LCDR2', '\u2014', '\u2014', 'Generally fewer liabilities (short loop)', 'Low'],
        ['LCDR3', 'Variable', 'Asn-Gly/Asn-Ser', 'Deamidation if present', 'High if present'],
        ['LCDR3', 'Variable', 'Asp-Gly', 'Isomerisation', 'Medium'],
      ],
      sortable: true,
    },
    {
      type: 'table',
      title: 'Deamidation & Isomerisation Rate Hierarchy',
      headers: ['Motif', 'Modification Type', 't\u00bd at Neutral pH, 37\u00b0C', 'Relative Rate', 'Key Dependencies'],
      rows: [
        ['Asn-Gly (NG)', 'Deamidation', '1\u201314 days', 'Fastest', 'Solvent exposure, backbone flexibility, pH'],
        ['Asn-Ser (NS)', 'Deamidation', '7\u201330 days', 'Fast', 'Conformation, pH, temperature'],
        ['Asn-Thr (NT)', 'Deamidation', 'Weeks to months', 'Moderate', 'Side-chain branching slows reaction'],
        ['Asn-His (NH)', 'Deamidation', 'Weeks', 'Moderate', 'His protonation state affects rate'],
        ['Asp-Gly (DG)', 'Isomerisation', 'Weeks', 'Fast (for isom.)', 'pH-dependent (acid-catalysed)'],
        ['Asp-Ser (DS)', 'Isomerisation', 'Months', 'Slow', 'Ser side chain impedes cyclisation'],
        ['Asp-Pro (DP)', 'Backbone clipping', 'Variable', 'pH-dependent', 'Acid pH accelerates hydrolysis dramatically'],
      ],
    },
    {
      type: 'callout',
      title: 'High-Risk CDR Liability \u2014 NG at HCDR2',
      variant: 'danger',
      content:
        'An Asn-Gly (NG) motif in HCDR2 at position 54-55 is one of the highest-risk CDR liabilities in CMC development. Deamidation at this site can reduce binding affinity by 10-100\u00d7 and generates charge heterogeneity detectable by CEX/iCIEF. The mechanism proceeds via a cyclic succinimide intermediate: Asn side chain attacks the backbone carbonyl of the n+1 residue (Gly), forming a five-membered succinimide ring with loss of ammonia. The succinimide hydrolyses to yield a mixture of Asp (~15-30%) and isoAsp (~70-85%). Both products insert a negative charge, shifting the isoelectric point. The succinimide intermediate itself is detectable by reversed-phase HPLC and has a half-life of hours at physiological pH. Critically, the rate of succinimide formation depends on both primary sequence (n+1 residue size) and local three-dimensional conformation (backbone torsion angles and solvent accessibility). A buried NG motif in a rigid \u03b2-strand may be completely stable, while the same motif in a flexible, solvent-exposed CDR loop deamidates in days.',
    },
    {
      type: 'card',
      title: 'Forced Degradation Study Design for CDR Liabilities',
      color: 'amber',
      content:
        'A comprehensive forced degradation study systematically stresses the molecule to accelerate each degradation pathway and characterise liability sites. The standard panel includes: (1) Thermal stress: 40\u00b0C for 1-4 weeks (accelerated deamidation and isomerisation) and 25\u00b0C for 3-6 months (supportive); (2) pH stress: pH 3.5 (acid; Asp-Pro clipping, isomerisation), pH 5.0 (formulation-relevant), pH 8.0 (basic; accelerated deamidation); (3) Oxidative stress: 0.1-1.0% H\u2082O\u2082, 18-24 hours (Met/Trp oxidation); 2,2\u2032-azobis(2-amidinopropane) dihydrochloride (AAPH) for free radical oxidation; (4) Light stress: ICH Q1B Option 2 (1.2 million lux\u00b7hours visible light + 200 Wh/m\u00b2 UV); (5) Mechanical stress: agitation, freeze-thaw cycles. Each stressed sample is characterised by: intact and reduced mass (ESI-MS), peptide mapping with quantitative PTM analysis (LC-MS/MS), CEX/iCIEF (charge variants), SE-HPLC (aggregation/fragmentation), non-reducing CE-SDS (size variants), and potency assay (cell-based or binding). The goal is to map every modification site, determine its rate, and assess whether it impacts potency.',
    },
    {
      type: 'card',
      title: 'CMC Risk Assessment \u2014 CDR vs Framework Liabilities',
      color: 'purple',
      content:
        'Not all post-translational modifications have equal CMC impact. CDR modifications are generally higher risk than framework modifications because: (1) CDR residues form the antigen-binding paratope; modifications that alter charge, shape, or flexibility can directly reduce potency. Published studies show that deamidation at CDR positions can reduce Kd by 2-100\u00d7, while the same modification at a framework position may have no measurable effect on binding. (2) CDR modifications generate charge heterogeneity that shifts the CEX/iCIEF profile and may require wider specifications. (3) Regulatory agencies expect a thorough understanding of CDR liabilities and their impact on potency, pharmacokinetics, and immunogenicity. Framework modifications (e.g., Asn deamidation in FR1, Met oxidation in FR3) are typically of lower concern for potency but may affect structural stability, aggregation, or immunogenicity. However, Vernier zone framework positions (those supporting CDR loop conformation) represent an intermediate risk category \u2014 modifications at these positions can indirectly perturb CDR geometry and reduce binding.',
    },
    {
      type: 'code',
      title: 'CDR Liability Scanning \u2014 Motif Summary',
      language: 'text',
      code: [
        'DEAMIDATION MOTIFS (Asn \u2192 Asp/isoAsp via succinimide)',
        '\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
        '  NG (Asn-Gly)     CRITICAL    t\u00bd 1-14 days',
        '  NS (Asn-Ser)     HIGH        t\u00bd 7-30 days',
        '  NH (Asn-His)     MODERATE    t\u00bd weeks',
        '  NT (Asn-Thr)     MODERATE    t\u00bd weeks-months',
        '  NN (Asn-Asn)     LOW-MOD     t\u00bd months',
        '',
        'ISOMERISATION MOTIFS (Asp \u2192 isoAsp via succinimide)',
        '\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
        '  DG (Asp-Gly)     HIGH        t\u00bd weeks',
        '  DS (Asp-Ser)     MODERATE    t\u00bd months',
        '  DT (Asp-Thr)     LOW         t\u00bd months+',
        '  DD (Asp-Asp)     LOW         t\u00bd months+',
        '',
        'CLIPPING MOTIFS',
        '\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
        '  DP (Asp-Pro)     MODERATE    Acid-catalysed hydrolysis',
        '',
        'OXIDATION TARGETS',
        '\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
        '  Met (CDR)        HIGH        If surface-exposed; Met(O) formation',
        '  Trp (CDR)        MEDIUM-HIGH Kynurenine, hydroxytryptophan products',
        '  His              LOW         Rare; 2-oxo-histidine under harsh oxidation',
        '',
        'N-TERMINAL MODIFICATIONS',
        '\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
        '  N-term Gln       LOW         PyroGlu (cyclisation); cosmetic charge shift',
        '  N-term Glu       LOW         PyroGlu; slower than Gln cyclisation',
      ].join('\n'),
    },
    {
      type: 'bullets',
      title: 'Analytical Detection Methods for CDR Modifications',
      items: [
        'CEX-HPLC (cation exchange): Separates acidic variants (deamidated, sialylated), main peak, and basic variants (C-term Lys, succinimide, incomplete pyroGlu). The most widely used charge variant method for release and stability testing.',
        'Imaged capillary isoelectric focusing (iCIEF/icIEF): Higher resolution than CEX for overall charge profile. Reports pI, acidic%, main%, basic%. Used in biosimilar comparability studies as a primary charge variant comparator.',
        'Peptide mapping by RP-HPLC-MS/MS: Site-specific quantification of each modification. Tryptic or Lys-C digestion generates CDR-containing peptides. Extracted ion chromatograms (XICs) for modified vs unmodified peptides yield % modification at each site. Gold standard for comprehensive PTM characterisation.',
        'Native or denaturing intact mass spectrometry: Detects mass shifts corresponding to deamidation (+1 Da), oxidation (+16 Da), glycation (+162 Da). Limited resolution for single deamidation events unless using high-resolution Orbitrap or FT-ICR instruments.',
        'Peptide mapping with electron transfer dissociation (ETD): Distinguishes Asp from isoAsp isomers by diagnostic c+57 and z\u221257 fragment ions. Critical for confirming isomerisation at specific Asp residues.',
        'Potency assay (cell-based or SPR binding): Essential to link observed modifications to functional impact. A modification at a CDR position is a CQA only if it measurably affects potency or pharmacokinetics.',
      ],
    },
    {
      type: 'callout',
      title: 'Specification Setting for CDR Modifications',
      variant: 'info',
      content:
        'Specifications for CDR modifications are set based on: (1) the observed rate of accumulation during real-time stability at the intended storage condition; (2) the relationship between modification level and potency (dose-response curve); (3) clinical experience (the range of modification levels present in clinical lots). ICH Q6B provides the framework: specifications should be set based on the range observed in lots used in clinical studies, with consideration of the analytical method variability (\u00b12-3% for peptide mapping). For a deamidation site that accumulates at 1% per month at 5\u00b0C and has no potency impact below 20%, a specification of NMT 15% at release (with a 24-month shelf life target of <30%) would be typical. For sites where potency is impacted at >5% modification, tighter specifications are required.',
    },
    {
      type: 'card',
      title: 'When to Mutate vs Accept a CDR Liability',
      color: 'green',
      content:
        'The decision to engineer out a CDR liability (by point mutation) vs accept it (with appropriate specifications and controls) is one of the most consequential CMC decisions in early development. Arguments for mutation: (1) The liability is in a critical contact residue and modification severely impacts potency (>5\u00d7 Kd shift); (2) The degradation rate is too fast for practical shelf life (e.g., NG deamidation reaching >30% at 24 months, 5\u00b0C); (3) The modification generates immunogenic neo-epitopes (isoAsp has been shown to trigger T-cell responses in some contexts). Arguments against mutation: (1) Any CDR mutation risks reducing potency \u2014 even conservative substitutions (e.g., N\u2192Q, D\u2192E) can alter CDR loop conformation; (2) Mutation requires full re-characterisation and potentially new toxicology; (3) If the liability rate is manageable within the target shelf life, formulation optimisation (pH, excipient selection, storage temperature) may be sufficient. Best practice: generate the mutant early (during lead optimisation), characterise its binding/potency head-to-head with the parent, and make the go/no-go decision before cell line development.',
    },
    {
      type: 'table',
      title: 'Common Conservative CDR Mutations to Remove Liabilities',
      headers: ['Liability', 'Parent Motif', 'Mutation', 'Rationale', 'Risk'],
      rows: [
        ['Deamidation', 'NG', 'N\u2192Q (iso-steric)', 'Removes Asn; Gln cannot form succinimide', 'CDR conformation change; potency loss 0-50%'],
        ['Deamidation', 'NG', 'G\u2192A (n+1 position)', 'Steric hindrance slows succinimide formation', 'Less disruptive; rate reduction 5-20\u00d7'],
        ['Deamidation', 'NS', 'N\u2192Q or S\u2192A', 'Remove Asn or enlarge n+1 residue', 'Variable; must test empirically'],
        ['Isomerisation', 'DG', 'D\u2192E (iso-steric)', 'Glu cannot form succinimide', 'Charge preserved; conformation may shift'],
        ['Isomerisation', 'DG', 'G\u2192A', 'Slows cyclisation', 'Less disruptive than D\u2192E'],
        ['Oxidation', 'Met', 'M\u2192L or M\u2192I', 'Removes oxidisable sulphur', 'Conservative; generally well-tolerated'],
        ['Oxidation', 'Trp', 'W\u2192F or W\u2192Y', 'Removes indole ring oxidation site', 'Higher risk \u2014 Trp often critical for binding'],
      ],
    },
  ],
  mentorQuestions: [
    'You receive a new molecule with an NG motif at HCDR2 position 54-55. What experiments would you design to assess the CMC risk?',
    'How does CDR loop conformation influence deamidation rate, and why is this important for accelerated stability predictions?',
    'When would you recommend a CDR mutation to remove a chemical liability, vs accepting it with a wider specification?',
  ],
};
